-- Generated by scripts/generate_topik_83_sql.mjs
BEGIN;

INSERT INTO mock_test_bank (
  title, exam_type, test_number, description, total_questions, duration, listening_questions, reading_questions
)
SELECT
  'TOPIK I 83-р шалгалт',
  'TOPIK_I',
  83,
  '83-р албан ёсны TOPIK I шалгалт',
  70,
  100,
  30,
  40
WHERE NOT EXISTS (
  SELECT 1 FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83
);

UPDATE mock_test_bank
SET
  title = 'TOPIK I 83-р шалгалт',
  description = '83-р албан ёсны TOPIK I шалгалт',
  total_questions = 70,
  duration = 100,
  listening_questions = 30,
  reading_questions = 40,
  updated_at = NOW()
WHERE id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1);

DELETE FROM mock_test_questions WHERE mock_test_id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1);

INSERT INTO mock_test_questions (
  mock_test_id,
  section,
  question_number,
  question_text,
  question_image_url,
  audio_url,
  option_image_urls,
  options,
  question_score,
  correct_answer_text,
  explanation
) VALUES
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 1, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

남자: 학생이에요?
여자: 네. 학생이에요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["네. 학생이에요.","네. 학생이 없어요.","아니요. 학생이 와요.","아니요. 학생이 많아요."]'::jsonb, 4, '네. 학생이에요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 2, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

여자: 책을 읽어요?
남자: 아니요. 책을 안 읽어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["네. 책을 싫어해요.","네. 책이 아니에요.","아니요. 책이 있어요.","아니요. 책을 안 읽어요."]'::jsonb, 4, '아니요. 책을 안 읽어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 3, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

남자: 우리 어디에서 이야기해요?
여자: 카페에서 해요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["지금 해요.","우리가 해요.","카페에서 해요.","동생하고 해요."]'::jsonb, 3, '카페에서 해요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 4, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

여자: 공항에 어떻게 갔어요?
남자: 지하철로 갔어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["어제 갔어요.","자주 갔어요.","친구가 갔어요.","지하철로 갔어요."]'::jsonb, 3, '지하철로 갔어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 5, '다음을 듣고 〈보기〉와 같이 이어지는 말을 고르십시오.

남자: 미안해요.
여자: 아니에요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["축하해요.","아니에요.","고마워요.","반가워요."]'::jsonb, 4, '아니에요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 6, '다음을 듣고 〈보기〉와 같이 이어지는 말을 고르십시오.

여자: 잠깐만 기다리세요.
남자: 네. 알겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["잘 먹겠습니다.","잘 지냈습니다.","네. 알겠습니다.","네. 그렇습니다."]'::jsonb, 3, '네. 알겠습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 7, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 어서 오세요. 뭘 드릴까요?
여자: 오렌지 열 개 주세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["꽃집","극장","학교","시장"]'::jsonb, 3, '시장', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 8, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 여기는 비빔밥이 맛있어요.
남자: 그럼, 우리 비빔밥을 먹어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["은행","식당","도서관","문구점"]'::jsonb, 3, '식당', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 9, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 이 구두를 신어 보고 싶어요.
여자: 네. 이쪽으로 오세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["백화점","여행사","우체국","박물관"]'::jsonb, 3, '백화점', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 10, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 식사 후에 이 약을 드세요.
남자: 감사합니다. 얼마예요?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["서점","약국","미용실","사진관"]'::jsonb, 4, '약국', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 11, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 수미 씨, 오빠가 있어요?
여자: 아니요. 언니가 있어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["나라","가족","이름","주말"]'::jsonb, 3, '가족', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 12, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 내일 시험이 몇 시예요?
남자: 두 시예요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["취미","날씨","시간","음식"]'::jsonb, 3, '시간', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 13, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 저는 농구를 좋아해요. 수미 씨는요?
여자: 저는 테니스를 좋아해요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["직업","운동","날짜","고향"]'::jsonb, 4, '운동', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 14, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 그 가방 좋네요. 비싼 거예요?
남자: 아니요. 비싸지 않아요. 이만 원이에요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["값","맛","위치","계절"]'::jsonb, 3, '값', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 15, '다음을 듣고 가장 알맞은 그림을 고르십시오.

남자: 저, 우산은 어디에 있어요?
여자: 저기 창문 밑에 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/listening/q15_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/listening/q15_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/listening/q15_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/listening/q15_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 4, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 16, '다음을 듣고 가장 알맞은 그림을 고르십시오.

여자: 우리 15번 버스를 타지요?
남자: 네. 이 정류장에서 탈 수 있네요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/listening/q16_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/listening/q16_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/listening/q16_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/listening/q16_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 4, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 17, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

여자: 민수 씨, 주말에 뭐 했어요?
남자: 드라마도 보고 집에서 쉬었어요. 수미 씨는요?
여자: 저는 일요일에 친구하고 수영장에 갔어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 주말에 드라마를 봤습니다.","남자는 일요일에 친구를 만났습니다.","여자는 일요일에 집에서 쉬었습니다.","여자는 주말에 이 남자와 수영장에 갔습니다."]'::jsonb, 3, '남자는 주말에 드라마를 봤습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 18, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

남자: 와, 김치찌개 맛있네요.
여자: 그래요? 우리 어머니한테 배웠는데 괜찮아요?
남자: 네. 맛있어요. 저는 요리 잘 못하는데
여자: 저도 아직 잘 못해서 어머니한테 가끔 배워요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 요리를 아주 잘합니다.","남자는 지금 김치찌개를 만듭니다.","여자는 어머니에게서 요리를 배웁니다.","여자는 어머니와 요리를 하고 있습니다."]'::jsonb, 3, '여자는 어머니에게서 요리를 배웁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 19, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

남자: 우리 이따가 수업 끝나고 영화 보러 갈래요?
여자: 음.... 날씨도 좋은데 한강공원은 어때요?
남자: 좋아요. 거기 가요. 수업 끝나고 가면 시원하고 좋을 것 같아요.
여자: 그래요. 다음에는 영화 보러 가요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 극장에서 남자를 만났습니다.","남자는 이따가 한강공원에 갈 겁니다.","남자는 오늘 수업이 모두 끝났습니다.","여자는 지금 영화를 보고 싶어 합니다."]'::jsonb, 3, '남자는 이따가 한강공원에 갈 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 20, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

여자: 민수 씨, 인터넷으로 안 쓰는 물건 팔아 봤어요?
남자: 네. 많이 팔아 봤어요. 왜요? 뭐 팔고 싶은 거 있어요?
여자: 작은 책상이 하나 있는데 팔고 싶어서요.
남자: 그런 물건을 팔 수 있는 인터넷 사이트가 많아요. 제가 알려 드릴게요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 책상을 사고 싶어 합니다.","남자는 여자에게 책상을 팔 겁니다.","남자는 인터넷으로 물건을 팔아 봤습니다.","여자는 인터넷 사이트에서 책상을 팔았습니다."]'::jsonb, 3, '남자는 인터넷으로 물건을 팔아 봤습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 21, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

남자: 여보세요. 거기 사랑병원이지요? 수요일 오후에 예약하고 싶은데요.
여자: 수요일요? 잠시만요. 몇 시쯤 오시겠어요?
남자: 세 시쯤 가도 될까요?
여자: 네. 됩니다. 이름과 전화번호를 말씀해 주세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 병원에서 일합니다.","여자는 오전에 예약을 했습니다.","여자는 남자와 같이 병원에 갑니다.","남자는 수요일에 병원에 갈 겁니다."]'::jsonb, 3, '남자는 수요일에 병원에 갈 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 22, '다음을 듣고 여자의 중심 생각을 고르십시오.

여자: 마이클 씨, 한국어 말하기 연습 많이 해요?
남자: 네. 선생님. 우리 반 친구들하고 자주 만나서 연습해요.
여자: 한국 사람하고도 이야기를 많이 해 보세요. 도움이 될 거예요.
남자: 네. 저도 한국 사람하고 이야기 많이 하고 싶어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["마이클 씨처럼 친구가 많았으면 좋겠습니다.","마이클 씨하고 외국어 공부를 하고 싶습니다.","마이클 씨에게 한국어를 더 가르쳐 주고 싶습니다.","마이클 씨가 말하기 연습을 많이 하면 좋겠습니다."]'::jsonb, 3, '마이클 씨가 말하기 연습을 많이 하면 좋겠습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 23, '다음을 듣고 여자의 중심 생각을 고르십시오.

여자: 시계가 고장 났는데 고칠 수 있을까요?
남자: 한번 볼게요. 꽤 오래된 시계네요.
여자: 이거 제가 정말 좋아하는 시계예요. 계속 쓰고 싶어요.
남자: 네. 그럼 고쳐 보고 연락드리겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["새 시계를 구경해 보고 싶습니다.","시계를 오늘 바로 고쳐야 합니다.","시계를 고쳐서 오래 쓰고 싶습니다.","좋은 시계로 바꾸어 주면 좋겠습니다."]'::jsonb, 3, '시계를 고쳐서 오래 쓰고 싶습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 24, '다음을 듣고 여자의 중심 생각을 고르십시오.

남자: 와, 케이팝 가수들은 노래도 잘하고 춤도 잘 추네요.
여자: 맞아요. 그런데 저는 춤을 추는 게 특히 멋있어 보여요.
남자: 그래요? 노래를 잘하는 게 더 멋있지 않아요?
여자: 아니에요. 공연장에 한번 가 보세요. 춤이 정말 최고예요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["가수들의 공연이 많아져서 좋습니다.","춤도 잘 추고 노래도 잘하는 가수가 좋습니다.","K-POP 가수들의 공연장에 가 보고 싶습니다.","K-POP 가수들은 춤을 출 때가 특히 멋있습니다."]'::jsonb, 3, 'K-POP 가수들은 춤을 출 때가 특히 멋있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 25, '여자가 왜 이 이야기를 하고 있는지 고르십시오.

여자: (딩동댕) 잠시 안내 말씀드립니다. 우리 회사에서는 ''사랑의 아침밥'' 행사를 엽니다. 식사를 못 하고 출근하시는 분들을 위해 내일부터 한 달 동안 아침 식사를 무료로 드립니다. 건강에 좋고 맛있는 식사가 준비됩니다. 1층 식당에 오셔서 아침을 드시고 즐거운 하루를 시작하시기 바랍니다. 감사합니다. (댕동딩)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["식당 위치를 설명하려고","행사 신청 기간을 안내하려고","회사에서 하는 행사를 알리려고","회사 직원에게 감사 인사를 하려고"]'::jsonb, 3, '회사에서 하는 행사를 알리려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 26, '들은 내용과 같은 것을 고르십시오.

여자: (딩동댕) 잠시 안내 말씀드립니다. 우리 회사에서는 ''사랑의 아침밥'' 행사를 엽니다. 식사를 못 하고 출근하시는 분들을 위해 내일부터 한 달 동안 아침 식사를 무료로 드립니다. 건강에 좋고 맛있는 식사가 준비됩니다. 1층 식당에 오셔서 아침을 드시고 즐거운 하루를 시작하시기 바랍니다. 감사합니다. (댕동딩)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["건강에 좋은 아침 식사가 준비됩니다.","오늘은 무료로 식사를 할 수 있습니다.","행사 기간 동안에 식당 문을 닫습니다.","한 달 전부터 이 행사를 하고 있습니다."]'::jsonb, 4, '건강에 좋은 아침 식사가 준비됩니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 27, '두 사람이 무엇에 대해 이야기를 하고 있는지 고르십시오.

남자: 수미 씨, 꽃이 예쁘네요. 선물 받은 거예요?
여자: 아니요. 제가 산 거예요.
남자: 아, 왜요? 누구 생일이에요?
여자: 그냥 제 책상 위에 놓으려고요. 예쁜 꽃을 보면 기분이 좋아져서 자주 사요.
남자: 아, 그렇군요. 저는 선물하려고 가끔 사는데 그게 아니면 잘 안 사요.
여자: 보통 그래요. 특별한 날에 많이 사지요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["자주 사는 꽃","꽃을 사는 이유","꽃을 선물할 사람","특별한 날에 사는 꽃"]'::jsonb, 3, '꽃을 사는 이유', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 28, '들은 내용과 같은 것을 고르십시오.

남자: 수미 씨, 꽃이 예쁘네요. 선물 받은 거예요?
여자: 아니요. 제가 산 거예요.
남자: 아, 왜요? 누구 생일이에요?
여자: 그냥 제 책상 위에 놓으려고요. 예쁜 꽃을 보면 기분이 좋아져서 자주 사요.
남자: 아, 그렇군요. 저는 선물하려고 가끔 사는데 그게 아니면 잘 안 사요.
여자: 보통 그래요. 특별한 날에 많이 사지요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 꽃을 자주 사지 않습니다.","여자는 생일 선물로 꽃을 받았습니다.","여자는 꽃을 별로 좋아하지 않습니다.","남자는 여자에게 주려고 꽃을 샀습니다."]'::jsonb, 4, '남자는 꽃을 자주 사지 않습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 29, '남자가 이 책을 쓴 이유를 고르십시오.

여자: 김민수 경찰관님, 이번에 책을 쓰셨지요? 어떤 책입니까?
남자: 제가 경찰이 된 지 8년이 됐는데요. 그 동안 경험한 일을 쓴 겁니다.
여자: 네. 특별히 이 책을 쓰신 이유가 있으세요?
남자: 사람들의 생각처럼 경찰관은 힘든 일을 많이 합니다. 하지만 기쁘고 행복한 일도 많아요. 이런 일들을 알려 주려고 작년부터 글을 쓰기 시작했습니다.
여자: 아, 행복한 일들요. 어떤 일들이지요?
남자: 몇 달 전에 제가 어떤 아이의 가방을 찾아 줬어요. 그런데 그 아이가 일을 잘했다고 저에게 상을 주는 거예요. 아이가 직접 만든 상과 편지를 받았는데, 칭찬을 받은 것 같아서 행복했어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["글을 쓰는 재미를 알리고 싶어서","힘들고 어려운 아이들에게 도움이 되고 싶어서","경찰이 되는 여러 가지 방법을 알려 주고 싶어서","경찰이 되어서 경험한 행복한 일을 소개하고 싶어서"]'::jsonb, 3, '경찰이 되어서 경험한 행복한 일을 소개하고 싶어서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 30, '들은 내용과 같은 것을 고르십시오.

여자: 김민수 경찰관님, 이번에 책을 쓰셨지요? 어떤 책입니까?
남자: 제가 경찰이 된 지 8년이 됐는데요. 그 동안 경험한 일을 쓴 겁니다.
여자: 네. 특별히 이 책을 쓰신 이유가 있으세요?
남자: 사람들의 생각처럼 경찰관은 힘든 일을 많이 합니다. 하지만 기쁘고 행복한 일도 많아요. 이런 일들을 알려 주려고 작년부터 글을 쓰기 시작했습니다.
여자: 아, 행복한 일들요. 어떤 일들이지요?
남자: 몇 달 전에 제가 어떤 아이의 가방을 찾아 줬어요. 그런데 그 아이가 일을 잘했다고 저에게 상을 주는 거예요. 아이가 직접 만든 상과 편지를 받았는데, 칭찬을 받은 것 같아서 행복했어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/audio/83-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 작년에 경찰이 되었습니다.","남자는 8년 동안 책을 쓰고 있습니다.","남자는 아이의 가방을 찾아 준 적이 있습니다.","남자는 아이에게 편지와 상을 줘서 행복했습니다."]'::jsonb, 4, '남자는 아이의 가방을 찾아 준 적이 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 1, '무엇에 대한 내용입니까?

사과가 맛있습니다. 바나나도 맛있습니다.', NULL, NULL, NULL, '["① 날씨","② 과일","③ 직업","④ 나이"]'::jsonb, 2, '② 과일', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 2, '무엇에 대한 내용입니까?

가게에 갑니다. 모자를 삽니다.', NULL, NULL, NULL, '["① 쇼핑","② 공부","③ 이름","④ 음식"]'::jsonb, 2, '① 쇼핑', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 3, '무엇에 대한 내용입니까?

7월에는 수업이 없습니다. 학교에 안 갑니다.', NULL, NULL, NULL, '["① 계절","② 방학","③ 여행","④ 위치"]'::jsonb, 2, '② 방학', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 4, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

영화를 ( ). 정말 재미있습니다.', NULL, NULL, NULL, '["① 봅니다","② 잡니다","③ 보냅니다","④ 마십니다"]'::jsonb, 2, '① 봅니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 5, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

한국 가수를 좋아합니다. 매일 한국 ( )를 듣습니다.', NULL, NULL, NULL, '["① 편지","② 노래","③ 전화","④ 시계"]'::jsonb, 2, '② 노래', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 6, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

저는 선생님입니다. 학교에서 학생들을 ( ).', NULL, NULL, NULL, '["① 읽습니다","② 입습니다","③ 가르칩니다","④ 물어봅니다"]'::jsonb, 2, '③ 가르칩니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 7, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

저는 요즘 ( ). 시간이 없습니다.', NULL, NULL, NULL, '["① 작습니다","② 바쁩니다","③ 무겁습니다","④ 조용합니다"]'::jsonb, 3, '② 바쁩니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 8, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

저는 김민수 씨를 모릅니다. 내일 ( ) 만납니다.', NULL, NULL, NULL, '["① 처음","② 보통","③ 제일","④ 항상"]'::jsonb, 3, '① 처음', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 9, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

저는 볼펜이 없습니다. 연필( ) 있습니다.', NULL, NULL, NULL, '["① 을","② 만","③ 도","④ 로"]'::jsonb, 2, '② 만', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 10, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/reading/q10.png', NULL, NULL, '["① 우유입니다.","② 천 원입니다.","③ 딸기 맛입니다.","④ 팔월까지 팝니다."]'::jsonb, 3, '④ 팔월까지 팝니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 11, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/reading/q11.png', NULL, NULL, '["① 방이 많습니다.","② 부엌이 큽니다.","③ 화장실이 있습니다.","④ 대학교에서 가깝습니다."]'::jsonb, 3, '① 방이 많습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 12, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/reading/q12.png', NULL, NULL, '["① 수미 씨는 공항에 왔습니다.","② 수미 씨는 제주도에 있습니다.","③ 지금 제주도는 날씨가 좋습니다.","④ 민희 씨는 수미 씨와 같이 있습니다."]'::jsonb, 3, '④ 민희 씨는 수미 씨와 같이 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 13, '다음을 읽고 내용이 같은 것을 고르십시오.

저는 요리를 잘 못합니다. 그래서 음식을 보통 사 먹습니다. 오늘 저녁은 집 근처 식당에서 불고기를 먹을 겁니다.', NULL, NULL, NULL, '["① 저는 요리를 자주 합니다.","② 집 근처에 식당이 없습니다.","③ 저는 오늘 불고기를 먹을 겁니다.","④ 저는 오늘 집에서 저녁을 먹습니다."]'::jsonb, 3, '③ 저는 오늘 불고기를 먹을 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 14, '다음을 읽고 내용이 같은 것을 고르십시오.

어제 친구가 한국에 왔습니다. 오늘 우리 집에 놀러올 겁니다. 저는 집을 깨끗하게 청소했습니다.', NULL, NULL, NULL, '["① 저는 친구 집에 갈 겁니다.","② 저는 오늘 친구를 만납니다.","③ 친구가 오늘 한국에 왔습니다.","④ 친구하고 집을 청소할 겁니다."]'::jsonb, 2, '② 저는 오늘 친구를 만납니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 15, '다음을 읽고 내용이 같은 것을 고르십시오.

명동에서 약속이 있었습니다. 저는 집에서 일찍 나왔지만 차가 많아서 길이 막혔습니다. 그래서 약속 장소에 늦게 도착했습니다.', NULL, NULL, NULL, '["① 저는 명동에 못 갔습니다.","② 길에 차가 많지 않았습니다.","③ 저는 약속 시간에 늦었습니다.","④ 저는 집에서 늦게 출발했습니다."]'::jsonb, 3, '③ 저는 약속 시간에 늦었습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 16, '다음을 읽고 중심 내용을 고르십시오.

제 동생은 빵을 잘 만듭니다. 동생이 만든 빵은 아주 맛있습니다. 저도 빵 만드는 방법을 배우고 싶습니다.', NULL, NULL, NULL, '["① 저는 빵집에서 일하고 싶습니다.","② 저는 맛있는 빵을 사고 싶습니다.","③ 저는 동생에게 빵을 주고 싶습니다.","④ 저는 맛있는 빵을 만들고 싶습니다."]'::jsonb, 3, '④ 저는 맛있는 빵을 만들고 싶습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 17, '다음을 읽고 중심 내용을 고르십시오.

저는 바다에서 수영하는 것을 좋아합니다. 여름에는 수영을 하러 바다에 자주 갑니다. 빨리 여름이 오면 좋겠습니다.', NULL, NULL, NULL, '["① 저는 여름을 제일 좋아합니다.","② 저는 수영을 잘하면 좋겠습니다.","③ 저는 여름 바다에 가 보고 싶습니다.","④ 저는 빨리 바다에서 수영하고 싶습니다."]'::jsonb, 3, '④ 저는 빨리 바다에서 수영하고 싶습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 18, '다음을 읽고 중심 내용을 고르십시오.

옷장에 옷이 너무 많습니다. 그래서 옷장에서 옷을 찾기가 힘듭니다. 내일은 옷장을 정리할 겁니다.', NULL, NULL, NULL, '["① 저는 옷장이 더 필요합니다.","② 저는 옷을 많이 찾을 겁니다.","③ 저는 옷을 정리하려고 합니다.","④ 저는 내일 옷을 사려고 합니다."]'::jsonb, 2, '③ 저는 옷을 정리하려고 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 19, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

저는 유치원 선생님입니다. 저는 아이들을 좋아해서 유치원 선생님이 되었습니다. 우리 유치원에는 아이들이 많아서 일이 조금 힘듭니다. 또 집에 늦게 가는 날도 많습니다. ( ) 아이들이 정말 귀엽고 예뻐서 저는 제 일을 좋아합니다.', NULL, NULL, NULL, '["① 그러면","② 하지만","③ 그래서","④ 그리고"]'::jsonb, 2, '② 하지만', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 20, '윗글의 내용과 같은 것을 고르십시오.

저는 유치원 선생님입니다. 저는 아이들을 좋아해서 유치원 선생님이 되었습니다. 우리 유치원에는 아이들이 많아서 일이 조금 힘듭니다. 또 집에 늦게 가는 날도 많습니다. ( ) 아이들이 정말 귀엽고 예뻐서 저는 제 일을 좋아합니다.', NULL, NULL, NULL, '["① 저는 아이들이 좋습니다.","② 저는 보통 일찍 집에 갑니다.","③ 유치원 일은 힘들지 않습니다.","④ 유치원에는 아이들이 많지 않습니다."]'::jsonb, 2, '① 저는 아이들이 좋습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 21, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

인주시에서는 매년 5월 ''인주 꽃 축제''를 엽니다. 이 축제에서는 세계 여러 나라의 꽃을 볼 수 있습니다. 특히 올해 축제에서는 많은 사람이 모여서 꽃으로 세계 지도 만들기를 합니다. 또 평일 오전에 가면 무료로 꽃다발을 ( ) 꽃 그림 그리기를 할 수 있습니다.', NULL, NULL, NULL, '["① 만드는데","② 만드니까","③ 만들거나","④ 만들려고"]'::jsonb, 3, '③ 만들거나', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 22, '무엇에 대한 내용인지 맞는 것을 고르십시오.

인주시에서는 매년 5월 ''인주 꽃 축제''를 엽니다. 이 축제에서는 세계 여러 나라의 꽃을 볼 수 있습니다. 특히 올해 축제에서는 많은 사람이 모여서 꽃으로 세계 지도 만들기를 합니다. 또 평일 오전에 가면 무료로 꽃다발을 ( ) 꽃 그림 그리기를 할 수 있습니다.', NULL, NULL, NULL, '["① 꽃 축제를 여는 이유","② 꽃 축제가 열리는 장소","③ 꽃 축제에 들어가는 방법","④ 꽃 축제에서 할 수 있는 일"]'::jsonb, 2, '④ 꽃 축제에서 할 수 있는 일', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 23, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

저는 감기에 걸려서 오늘 학교에 못 갔습니다. 병원에 가고 싶었지만 한국어를 잘 못해서 그냥 기숙사에 있었습니다. 그때 친구가 기숙사에 와서 저를 데리고 병원에 갔습니다. 기숙사로 ( ) 친구가 밥도 사 주었습니다. 정말 고마웠습니다.', NULL, NULL, NULL, '["① 돌아오지만","② 돌아오려면","③ 돌아오지 말고","④ 돌아오기 전에"]'::jsonb, 2, '④ 돌아오기 전에', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 24, '윗글의 내용과 같은 것을 고르십시오.

저는 감기에 걸려서 오늘 학교에 못 갔습니다. 병원에 가고 싶었지만 한국어를 잘 못해서 그냥 기숙사에 있었습니다. 그때 친구가 기숙사에 와서 저를 데리고 병원에 갔습니다. 기숙사로 ( ) 친구가 밥도 사 주었습니다. 정말 고마웠습니다.', NULL, NULL, NULL, '["① 저는 오늘 밥을 못 먹었습니다.","② 저는 오늘 친구하고 병원에 갔습니다.","③ 저는 오늘 친구의 기숙사 방에 갔습니다.","④ 저는 오늘 학교에 가서 친구를 만났습니다."]'::jsonb, 3, '② 저는 오늘 친구하고 병원에 갔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 25, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

얼마 전 만화 박물관이 문을 열었습니다. 이 박물관에는 1960년부터 지금까지 나온 여러 가지 만화책이 많이 있습니다. 유명한 만화 영화도 즐길 수 있어서 특히 아이들이 좋아합니다. 그리고 이 만화 박물관에는 ( ) 만화책을 오랜만에 다시 읽으러 오는 어른들도 많습니다.', NULL, NULL, NULL, '["① 요즘에 나온","② 어릴 때 읽은","③ 아이들이 만든","④ 박물관에서 빌려온"]'::jsonb, 2, '② 어릴 때 읽은', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 26, '윗글의 내용과 같은 것을 고르십시오.

얼마 전 만화 박물관이 문을 열었습니다. 이 박물관에는 1960년부터 지금까지 나온 여러 가지 만화책이 많이 있습니다. 유명한 만화 영화도 즐길 수 있어서 특히 아이들이 좋아합니다. 그리고 이 만화 박물관에는 ( ) 만화책을 오랜만에 다시 읽으러 오는 어른들도 많습니다.', NULL, NULL, NULL, '["① 이 박물관에는 어른들도 많이 옵니다.","② 이 박물관에는 만화 영화가 없습니다.","③ 이 박물관은 1960년에 문을 열었습니다.","④ 이 박물관은 어린이 만화 박물관입니다."]'::jsonb, 3, '① 이 박물관에는 어른들도 많이 옵니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 27, '다음을 순서에 맞게 배열한 것을 고르십시오.

(가) 채소가 싸고 좋아서 많이 샀습니다.
(나) 지난 주말에 채소를 사러 시장에 갔습니다.
(다) 아주머니가 주신 토마토 때문에 기분이 좋았습니다.
(라) 채소 가게 아주머니가 토마토를 하나 더 주셨습니다.', NULL, NULL, NULL, '["①(가)-(나)-(라)-(다)","②(가)-(다)-(나)-(라)","③(나)-(가)-(라)-(다)","④(나)-(다)-(라)-(가)"]'::jsonb, 3, '③(나)-(가)-(라)-(다)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 28, '다음을 순서에 맞게 배열한 것을 고르십시오.

(가) 남극에는 펭귄 우체국이 있습니다.
(나) 또 우체국에서는 여러 가지 펭귄 기념품도 팝니다.
(다) 여기에서는 관광객들이 쓴 편지를 전 세계로 보내 줍니다.
(라) 펭귄 우체국에서 이렇게 번 돈은 남극의 펭귄을 위해서 사용합니다.', NULL, NULL, NULL, '["①(가)-(다)-(나)-(라)","②(가)-(라)-(나)-(다)","③(라)-(나)-(가)-(다)","④(라)-(다)-(나)-(가)"]'::jsonb, 2, '①(가)-(다)-(나)-(라)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 29, '다음 문장이 들어갈 곳으로 가장 알맞은 것을 고르십시오.

주어진 문장: 그래서 지하철을 탈 때보다 집에서 일찍 나와야 합니다.

저는 요즘 자전거를 타고 학교에 갑니다. ( ① ) 전에는 지하철을 타고 다녔습니다. ( ② ) 그때는 학교까지 삼십 분이 걸렸지만 지금은 한 시간쯤 걸립니다. ( ③ ) 아침에 일찍 일어나는 것은 싫지만 운동을 할 수 있어서 좋습니다. ( ④ )', NULL, NULL, NULL, '["① 저는 운동하는 것을 싫어합니다.","② 저는 요즘 아침에 늦게 일어납니다.","③ 저는 자전거를 타고 학교에 다닙니다.","④ 저는 매일 한 시간 동안 지하철을 탑니다."]'::jsonb, 2, '③ 저는 자전거를 타고 학교에 다닙니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 30, '윗글의 내용과 같은 것을 고르십시오.

저는 요즘 자전거를 타고 학교에 갑니다. ( ① ) 전에는 지하철을 타고 다녔습니다. ( ② ) 그때는 학교까지 삼십 분이 걸렸지만 지금은 한 시간쯤 걸립니다. ( ③ ) 아침에 일찍 일어나는 것은 싫지만 운동을 할 수 있어서 좋습니다. ( ④ )', NULL, NULL, NULL, '["① 저는 운동하는 것을 싫어합니다.","② 저는 요즘 아침에 늦게 일어납니다.","③ 저는 자전거를 타고 학교에 다닙니다.","④ 저는 매일 한 시간 동안 지하철을 탑니다."]'::jsonb, 3, '③ 저는 자전거를 타고 학교에 다닙니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 31, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

저는 오랫동안 다닌 회사를 그만두었습니다. 내년부터는 다른 회사에서 일할 겁니다. 그때까지 시간이 생겨서 지금은 해외여행을 하고 있습니다. 자유롭게 여행하고 싶어서 ( ) 여기저기 가고 싶은 곳을 다니고 있습니다. 저에게는 지금 이 시간이 정말 소중하고 행복합니다.', NULL, NULL, NULL, '["① 회사에서 일하고","② 장소를 못 바꾸고","③ 약속 시간을 지키고","④ 계획을 세우지 않고"]'::jsonb, 2, '④ 계획을 세우지 않고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 32, '윗글의 내용과 같은 것을 고르십시오.

저는 오랫동안 다닌 회사를 그만두었습니다. 내년부터는 다른 회사에서 일할 겁니다. 그때까지 시간이 생겨서 지금은 해외여행을 하고 있습니다. 자유롭게 여행하고 싶어서 ( ) 여기저기 가고 싶은 곳을 다니고 있습니다. 저에게는 지금 이 시간이 정말 소중하고 행복합니다.', NULL, NULL, NULL, '["① 저는 여행사에서 일합니다.","② 저는 내년부터 여행을 다닐 겁니다.","③ 저는 지금 새 회사에 다니고 있습니다.","④ 저는 요즘 행복한 시간을 보내고 있습니다."]'::jsonb, 3, '④ 저는 요즘 행복한 시간을 보내고 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 33, '왜 윗글을 썼는지 맞는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/reading/q33.png', NULL, NULL, '["① 수업 시간을 바꾸려고","② 수업 신청을 받으려고","③ 수업 방법을 설명하려고","④ 수업 장소를 안내하려고"]'::jsonb, 2, '② 수업 신청을 받으려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 34, '윗글의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-83/reading/q33.png', NULL, NULL, '["① 칠월에 수업을 시작합니다.","② 영어 수업은 매일 있습니다.","③ 영어 수업은 한 달 동안 합니다.","④ 수업을 들을 때 돈을 내야 합니다."]'::jsonb, 3, '③ 영어 수업은 한 달 동안 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 35, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

초콜릿은 달아서 사람의 기분을 좋게 합니다. 그래서 사람들이 초콜릿을 자주 먹습니다. 그런데 말을 많이 할 때나 발표를 해야 할 때는 초콜릿을 먹지 않는 것이 좋습니다. 초콜릿을 먹으면 목이 마르게 되어서 목소리가 잘 안 ( ). 그래서 가수들도 공연 전에는 초콜릿을 먹지 않습니다.', NULL, NULL, NULL, '["① 나와도 됩니다","② 나와야 합니다","③ 나오기로 합니다","④ 나오기 때문입니다"]'::jsonb, 2, '④ 나오기 때문입니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 36, '윗글의 내용과 같은 것을 고르십시오.

초콜릿은 달아서 사람의 기분을 좋게 합니다. 그래서 사람들이 초콜릿을 자주 먹습니다. 그런데 말을 많이 할 때나 발표를 해야 할 때는 초콜릿을 먹지 않는 것이 좋습니다. 초콜릿을 먹으면 목이 마르게 되어서 목소리가 잘 안 ( ). 그래서 가수들도 공연 전에는 초콜릿을 먹지 않습니다.', NULL, NULL, NULL, '["① 초콜릿을 먹으면 기분이 좋아집니다.","② 목이 마를 때 초콜릿을 먹는 것이 좋습니다.","③ 가수들은 보통 공연 전에 초콜릿을 먹습니다.","④ 말을 많이 해야 할 때 초콜릿을 먹으면 좋습니다."]'::jsonb, 3, '① 초콜릿을 먹으면 기분이 좋아집니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 37, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

봄에는 몸에 힘이 없고 자주 피곤해집니다. 그것은 낮과 밤의 ( ) 생기는 일입니다. 봄에는 낮 기온은 높지만 아침과 밤 기온은 낮습니다. 사람의 몸은 이 온도 차이를 잘 따라가지 못해서 쉽게 피곤해집니다. 이럴 때는 햇빛을 보면서 산책을 하면 좋습니다. 물을 많이 마시는 것도 도움이 됩니다.', NULL, NULL, NULL, '["① 물이 뜨거워져서","② 햇빛이 아주 강해서","③ 기온이 크게 달라서","④ 온도 차이가 적어져서"]'::jsonb, 3, '③ 기온이 크게 달라서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 38, '윗글의 내용과 같은 것을 고르십시오.

봄에는 몸에 힘이 없고 자주 피곤해집니다. 그것은 낮과 밤의 ( ) 생기는 일입니다. 봄에는 낮 기온은 높지만 아침과 밤 기온은 낮습니다. 사람의 몸은 이 온도 차이를 잘 따라가지 못해서 쉽게 피곤해집니다. 이럴 때는 햇빛을 보면서 산책을 하면 좋습니다. 물을 많이 마시는 것도 도움이 됩니다.', NULL, NULL, NULL, '["① 봄에는 몸이 쉽게 피곤해집니다.","② 봄에는 아침과 낮의 기온이 비슷합니다.","③ 봄에는 물을 많이 마시면 건강에 나쁩니다.","④ 봄에는 밤에 산책을 하는 것이 도움이 됩니다."]'::jsonb, 3, '① 봄에는 몸이 쉽게 피곤해집니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 39, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

제가 초등학생이었을 때의 일입니다. 그날은 아버지의 생일이었고 저는 아버지를 기쁘게 해 드리고 싶었습니다. 그래서 제가 아기 때부터 매일 안고 잔 고양이 인형을 선물로 드리기로 했습니다. 저는 아버지가 기뻐할 것 같았습니다. 그런데 ( ) 아버지는 아무 말도 하지 않았습니다. 잠시 후 아버지는 웃으면서 저를 꼭 안아 주셨습니다. 시간이 흘러 저는 결혼을 하고 딸을 낳았습니다. 제 딸의 첫 번째 생일에 아버지는 예쁘게 포장한 그 고양이 인형을 제 딸에게 주셨습니다.', NULL, NULL, NULL, '["① 선물을 본","② 인형을 준","③ 인형을 산","④ 선물을 포장한"]'::jsonb, 3, '① 선물을 본', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 40, '윗글의 내용으로 알 수 있는 것을 고르십시오.

제가 초등학생이었을 때의 일입니다. 그날은 아버지의 생일이었고 저는 아버지를 기쁘게 해 드리고 싶었습니다. 그래서 제가 아기 때부터 매일 안고 잔 고양이 인형을 선물로 드리기로 했습니다. 저는 아버지가 기뻐할 것 같았습니다. 그런데 ( ) 아버지는 아무 말도 하지 않았습니다. 잠시 후 아버지는 웃으면서 저를 꼭 안아 주셨습니다. 시간이 흘러 저는 결혼을 하고 딸을 낳았습니다. 제 딸의 첫 번째 생일에 아버지는 예쁘게 포장한 그 고양이 인형을 제 딸에게 주셨습니다.', NULL, NULL, NULL, '["① 아버지는 제 선물을 받고 슬퍼하셨습니다.","② 제 딸은 새로 산 인형을 선물로 받았습니다.","③ 저는 아버지의 생일에 선물을 사 드렸습니다.","④ 아버지는 오랫동안 제 선물을 가지고 계셨습니다."]'::jsonb, 3, '④ 아버지는 오랫동안 제 선물을 가지고 계셨습니다.', NULL);

COMMIT;
