-- Generated by scripts/generate_topik_i_36_sql.py
BEGIN;

INSERT INTO mock_test_bank (
  title, exam_type, test_number, description, total_questions, duration, listening_questions, reading_questions
)
SELECT
  'TOPIK I 36-р шалгалт',
  'TOPIK_I',
  36,
  '36-р албан ёсны TOPIK I шалгалт',
  70,
  100,
  30,
  40
WHERE NOT EXISTS (
  SELECT 1 FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36
);

UPDATE mock_test_bank SET title = 'TOPIK I 36-р шалгалт', description = '36-р албан ёсны TOPIK I шалгалт', total_questions = 70, duration = 100, listening_questions = 30, reading_questions = 40, updated_at = NOW() WHERE id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1);

DELETE FROM mock_test_questions WHERE mock_test_id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1);

INSERT INTO mock_test_questions (
  mock_test_id,
  section,
  question_number,
  question_text,
  question_image_url,
  audio_url,
  option_image_urls,
  options,
  question_score,
  correct_answer_text,
  explanation
) VALUES
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 1, '여자 :공책이에요?
남자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["네,공책이에요.", "네,공책이 없어요.", "아니요,공책이 싸요.", "아니요,공책이 커요."]'::jsonb, 4, '네,공책이에요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 2, '남자 :숙제가 많아요?
여자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["네,숙제예요.", "네,숙제를 알아요.", "아니요,숙제가 없어요.", "아니요,숙제를 좋아해요."]'::jsonb, 4, '아니요,숙제가 없어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 3, '남자 :뭐 살 거예요?
여자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["두 개 살 거예요.", "지갑을 살 거예요.", "주말에 살 거예요.", "시장에서 살 거예요."]'::jsonb, 3, '지갑을 살 거예요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 4, '남자 :이 회사에서 얼마나 일했어요?
여자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["혼자 일했어요.", "3년 일했어요.", "오후에 일했어요.", "집에서 일했어요."]'::jsonb, 3, '3년 일했어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 5, '여자 :처음 뵙겠습니다.
남자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["미안합니다.", "감사합니다.", "안녕히 가십시오.", "만나서 반갑습니다."]'::jsonb, 4, '만나서 반갑습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 6, '남자 :저 주말에 부산으로 여행 가요.
여자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["괜찮아요.", "죄송해요.", "잘 다녀오세요.", "잘 부탁드려요."]'::jsonb, 3, '잘 다녀오세요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 7, '남자 :어서 오세요,손님.뭐 찾으세요?
여자 :운동화 있어요?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["교실", "식당", "가게", "공원"]'::jsonb, 3, '가게', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 8, '여자 :다섯 시 영화 표,두 장 주세요.
남자 :죄송합니다.다섯 시 표는 없습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["극장", "은행", "공항", "약국"]'::jsonb, 3, '극장', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 9, '남자 :지금 편지를 보내면 내일까지 도착할 수 있을까요?
여자 :네,내일까지는 도착합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["여행사", "도서관", "우체국", "미술관"]'::jsonb, 3, '우체국', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 10, '여자 :이 집은 딸기 케이크가 유명해요.
남자 :그래요?그럼,우리도 그거 한번 먹어 볼까요?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["빵집", "회사", "미용실", "박물관"]'::jsonb, 4, '빵집', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 11, '남자 :치마가 정말 예뻐요.
여자 :감사합니다.어제 백화점에서 샀어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["옷", "값", "생일", "날짜"]'::jsonb, 3, '옷', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 12, '여자 :저는 스물 세 살이에요.
남자 :그래요?저도 스물 세 살이에요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["시간", "나이", "음식", "기분"]'::jsonb, 3, '나이', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 13, '남자 :이거 언제 찍은 거예요?
여자 :작년에 제주도에서 찍은 거예요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["휴일", "달력", "사진", "그림"]'::jsonb, 4, '사진', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 14, '여자 :책상,의자,옷장…….방에 필요한 것은 거의 다 있네요.
남자 :네.침대만 사면 될 거예요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["가구", "주소", "계절", "선물"]'::jsonb, 3, '가구', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 15, '남자 :무거우시죠?제가 도와 드릴까요?
여자 :감사합니다.문 좀 열어 주시겠어요?
알맞은 그림을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/listening/q15_option_1.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/listening/q15_option_2.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/listening/q15_option_3.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/listening/q15_option_4.png"]'::jsonb, '["①", "②", "③", "④"]'::jsonb, 4, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 16, '남자 :잠깐만요,손님.여기 전화기 놓고 가셨어요.
여자 :(놀란 듯이)어머,그래요?
알맞은 그림을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/listening/q16_option_1.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/listening/q16_option_2.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/listening/q16_option_3.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/listening/q16_option_4.png"]'::jsonb, '["①", "②", "③", "④"]'::jsonb, 4, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 17, '여자 :가을이 되니까 많이 시원해졌네요.
남자 :네.근데 아침,저녁에는 좀 추워요.저는 밤에 옷을 얇게 입어서
감기에 걸렸어요.
여자 :그래서 저는 밖에 나올 때 긴팔 옷을 한 벌 가지고 와요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["남자는 감기에 걸렸습니다.", "여자는 지금 많이 춥습니다.", "여자는 밤에 옷을 얇게 입습니다.", "남자는 날씨가 시원해서 좋습니다."]'::jsonb, 3, '남자는 감기에 걸렸습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 18, '남자 :수미 씨,어제 이메일 보냈는데 받았어요?
여자 :아,그래요?바빠서 아직 못 봤어요.무슨 일 있어요?
남자 :이번 주 모임 날짜가 금요일로 바뀌었는데 시간 괜찮아요?
여자 :저는 금요일에 약속이 있는데 어떡하죠?다음에는 꼭 갈게요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["여자는 요즘 시간이 많습니다.", "여자는 어제 이메일을 읽었습니다.", "여자는 금요일 약속을 취소했습니다.", "여자는 이번 모임에 나갈 수 없습니다."]'::jsonb, 3, '여자는 이번 모임에 나갈 수 없습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 19, '여자 :안녕하세요?수영을 좀 배우려고 하는데요.
남자 :아,네.그러시면 여기 신청서부터 먼저 써 주세요.
여자 :아침에 회사 가기 전에 운동하고 싶은데 몇 시에 문 열어요?
남자 :저희는 매일 아침 여섯 시에 시작하니까 아침 일찍 오셔도 됩니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["여자는 신청서를 썼습니다.", "여자는 수영장에서 일합니다.", "여자는 아침에 수영을 배울 겁니다.", "여자는 회사에서 운동을 하려고 합니다."]'::jsonb, 3, '여자는 아침에 수영을 배울 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 20, '남자 :다음 주가 아버지 생신인데 뭐 특별한 선물 없을까요?
여자 :전에 저는 부모님이랑 음악회 갔는데 정말 좋아하셨어요.
남자 :아!우리 부모님도 음악 좋아하시니까 같이 음악회에 가야겠어요.
여자 :그래요.요즘 좋은 공연이 많으니까 인터넷으로 한번 알아보세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["여자는 다음 주에 음악회에 갑니다.", "남자는 아버지의 선물을 준비했습니다.", "남자는 부모님과 음악회에 가고 싶어합니다.", "여자는 인터넷으로 공연을 찾아보려고 합니다."]'::jsonb, 3, '남자는 부모님과 음악회에 가고 싶어합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 21, '남자 :팀장님,행사 때 필요한 물건들을 사러 가려고 하는데요.
여자 :필요한 것들을 아까 메모해 놓았는데,민수 씨 책상 위에 있을 거예요.
남자 :네,알겠습니다.그런데 물건들은 바로 행사장으로 가지고 갈까요?
여자 :아니요.행사장 준비가 아직 안 끝났으니까 우선 사무실로 가지고
오는 게 좋을 것 같아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["남자는 지금 행사장에 있습니다.", "남자는 물건을 사서 사무실로 오면 됩니다.", "남자는 여자에게 필요한 물건을 써 주었습니다.", "남자는 행사 때 쓸 물건을 책상 위에 놓았습니다."]'::jsonb, 3, '남자는 물건을 사서 사무실로 오면 됩니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 22, '남자 :여기는 공원 안에 호수가 있네요.
여자 :네.그래서 저녁에 산책하러 오는 사람들이 많아요.
남자 :공원에 있는 길을 따라서 걸으면 운동도 되겠는데요.우리 집 근처
에도 이런 곳이 있으면 좋겠어요.
여자 :그럼,산책하고 싶을 때 놀러 와요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["걷는 것은 좋은 운동이 됩니다.", "산책은 저녁에 하는 것이 좋습니다.", "공원 안에 호수를 만들어야 합니다.", "집 근처에 공원이 생기면 좋겠습니다."]'::jsonb, 3, '집 근처에 공원이 생기면 좋겠습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 23, '여자 :오늘 영화 정말 재미있었지요?
남자 :네.근데 너무 앞자리라서 목이 좀 아팠어요.영화관도 불편한 자리는
값을 좀 깎아 줘야 되는 거 아니에요?
여자 :맞아요.앞자리나 뒷자리는 영화 볼 때 좀 불편하죠.
남자 :사실 연극이나 뮤지컬은 자리마다 값이 좀 다르잖아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["불편한 자리는 가격을 싸게 해야 합니다.", "연극도 영화처럼 값이 싸면 좋겠습니다.", "영화는 앞자리에서 보면 더 재미있습니다.", "영화관은 모든 자리를 편하게 해야 합니다."]'::jsonb, 3, '불편한 자리는 가격을 싸게 해야 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 24, '여자 :민수 씨,왜 이쪽 길로 가세요?저쪽 길이 더 빠른데…….
남자 :오늘 마라톤 대회가 있어서 저 길로는 못 가요.
여자 :지금 시간에 마라톤을 해요?평일 아침이라 차도 많은데 길이 많이
막히겠네요.
남자 :길이 좀 복잡하기는 하겠지만 어쩔 수 없죠.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["마라톤 대회를 일찍 끝내야 합니다.", "마라톤을 하면 길이 막혀서 싫습니다.", "마라톤은 아침 시간에 하는 것이 좋습니다.", "마라톤 때문에 길이 좀 막혀도 참아야 합니다."]'::jsonb, 3, '마라톤 때문에 길이 좀 막혀도 참아야 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 25, '여자 :요즘 집안에 실내 정원을 만들고 싶어하는 분들 많으시죠?하지만 꽃을 심고 정원을 가꾸는 게 보통 일은 아닙니다.이럴 때 도움을 받을 수 있는 책이 한 권 있는데요.이 책에는 꽃을 키우는 방법들이 사진과 함께 있어 배우기가 아주 쉽습니다.또 봄,여름,가을,겨울에 키울 수 있는 꽃의 종류도 알 수 있고요.
어떤 이야기를 하고 있는지 고르십시오.(3점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["감사", "부탁", "신청", "소개"]'::jsonb, 3, '소개', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 26, '여자 :요즘 집안에 실내 정원을 만들고 싶어하는 분들 많으시죠?하지만 꽃을 심고 정원을 가꾸는 게 보통 일은 아닙니다.이럴 때 도움을 받을 수 있는 책이 한 권 있는데요.이 책에는 꽃을 키우는 방법들이 사진과 함께 있어 배우기가 아주 쉽습니다.또 봄,여름,가을,겨울에 키울 수 있는 꽃의 종류도 알 수 있고요.
들은 내용과 같은 것을 고르십시오.(4점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["실내 정원은 가꾸기가 어렵지 않습니다.", "이 책은 실내 정원을 만들 때 도움이 됩니다.", "이 책을 보면 정원의 종류를 알 수 있습니다.", "꽃을 키우는 방법은 책으로 배우기가 힘듭니다."]'::jsonb, 4, '이 책은 실내 정원을 만들 때 도움이 됩니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 27, '여자 :선생님,안녕하세요?다음 주부터 방학이라 인사드리러 왔어요.
남자 :어,어서 와요.(조금 쉬고)이번 방학에는 뭐 할 거예요?
여자 :방학을 좀 특별하게 보내고 싶어서 자전거 여행을 해 보려고요.
남자 :음,자전거 여행 좋죠.힘들기는 하겠지만 좋은 경험이 될 거예요.
여자 :네.그리고 기타도 한번 배워 보려고 해요.
남자 :새로운 걸 배워 보는 것도 좋겠네요.
두 사람이 무엇에 대해 이야기를 하고 있는지 고르십시오.(3점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["방학 때 하고 싶은 일", "방학 때 한 새로운 경험", "방학 때 간 특별한 여행", "방학 때 만나고 싶은 사람"]'::jsonb, 3, '방학 때 하고 싶은 일', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 28, '여자 :선생님,안녕하세요?다음 주부터 방학이라 인사드리러 왔어요.
남자 :어,어서 와요.(조금 쉬고)이번 방학에는 뭐 할 거예요?
여자 :방학을 좀 특별하게 보내고 싶어서 자전거 여행을 해 보려고요.
남자 :음,자전거 여행 좋죠.힘들기는 하겠지만 좋은 경험이 될 거예요.
여자 :네.그리고 기타도 한번 배워 보려고 해요.
남자 :새로운 걸 배워 보는 것도 좋겠네요.
들은 내용과 같은 것을 고르십시오.(4점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["여자는 요즘 기타를 배우고 있습니다.", "여자는 방학에 여행을 할 계획입니다.", "여자는 자전거 여행이 힘들어서 싫습니다.", "여자는 다음 주에 선생님을 찾아갈 겁니다."]'::jsonb, 4, '여자는 방학에 여행을 할 계획입니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 29, '여자 :아이 통장을 하나 만들려고 하는데요.
남자 :아,어린이 통장요?요즘 입학 때라 많이들 만드시네요.
여자 :네.우리 아이도 자기 통장을 갖고 싶어해서 선물하려고요.
남자 :좋은 생각이세요.자기 통장이 생기면 돈을 모으는 즐거움을 느낄 수 있을 거예요.참,아이 도장은 가져오셨죠?
여자 :도장이 필요해요?안 가져왔는데…….그냥 내일 다시 와야겠네요.
남자 :그럼 내일 아이도 데리고 오세요.은행에 와서 직접 통장을 만들면 더 좋아할 거예요.
여자는 왜 아이에게 통장을 만들어 줍니까?(3점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["아이가 돈을 모으고 싶어해서", "아이가 돈을 많이 가지고 있어서", "아이가 통장을 바꿀 때가 되어서", "아이가 자기 통장을 갖고 싶어해서"]'::jsonb, 3, '아이가 자기 통장을 갖고 싶어해서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'listening', 30, '여자 :아이 통장을 하나 만들려고 하는데요.
남자 :아,어린이 통장요?요즘 입학 때라 많이들 만드시네요.
여자 :네.우리 아이도 자기 통장을 갖고 싶어해서 선물하려고요.
남자 :좋은 생각이세요.자기 통장이 생기면 돈을 모으는 즐거움을 느낄 수 있을 거예요.참,아이 도장은 가져오셨죠?
여자 :도장이 필요해요?안 가져왔는데…….그냥 내일 다시 와야겠네요.
남자 :그럼 내일 아이도 데리고 오세요.은행에 와서 직접 통장을 만들면 더 좋아할 거예요.
들은 내용과 같은 것을 고르십시오.(4점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/audio/36th-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["여자는 지금 도장을 가지고 있습니다.", "여자는 내일 은행에 다시 오려고 합니다.", "여자는 아이에게 입학 선물을 주었습니다.", "여자는 오늘 어린이 통장을 만들었습니다."]'::jsonb, 4, '여자는 내일 은행에 다시 오려고 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 31, '오빠가 있습니다.언니도 있습니다.', NULL, NULL, NULL, '["이름", "가족", "생일", "친구"]'::jsonb, 2, '가족', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 32, '저는 회사원입니다.자동차 회사에 다닙니다.', NULL, NULL, NULL, '["취미", "장소", "주말", "직업"]'::jsonb, 2, '직업', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 33, '한국에는 봄,여름,가을,겨울이 있습니다.지금은 가을입니다.', NULL, NULL, NULL, '["계절", "나라", "시장", "휴일"]'::jsonb, 2, '계절', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 34, '서점에 갑니다.( )을 삽니다.', NULL, NULL, NULL, '["책", "물", "옷", "빵"]'::jsonb, 2, '책', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 35, '한국어가 어렵습니다.친구( )물어봅니다.', NULL, NULL, NULL, '["의", "를", "에게", "에서"]'::jsonb, 2, '에게', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 36, '학교가 ( ).그래서 걸어서 갑니다.', NULL, NULL, NULL, '["작습니다", "많습니다", "가깝습니다", "깨끗합니다"]'::jsonb, 2, '가깝습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 37, '영화가 끝났습니다.극장에서 ( ).', NULL, NULL, NULL, '["삽니다", "씁니다", "지냅니다", "나갑니다"]'::jsonb, 3, '나갑니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 38, '바다 여행이 재미있었습니다.다음에 ( )갈 겁니다.', NULL, NULL, NULL, '["다시", "서로", "아주", "제일"]'::jsonb, 3, '다시', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 39, '눈이 옵니다.그리고 바람도 ( ).', NULL, NULL, NULL, '["줍니다", "붑니다", "옵니다", "됩니다"]'::jsonb, 2, '붑니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 40, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/reading/q40.png', NULL, NULL, '["금요일에 민수 씨를 만납니다.", "주말에 미영 씨와 산에 갑니다.", "일주일에 두 번 수영을 합니다.", "시월 이십이 일에 쇼핑을 합니다."]'::jsonb, 3, '금요일에 민수 씨를 만납니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 41, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/reading/q41.png', NULL, NULL, '["민수 씨는 도서관에 있습니다.", "마이클 씨는 도서관에 올 겁니다.", "민수 씨는 10분 후에 전화할 겁니다.", "마이클 씨는 민수 씨에게 전화를 했습니다."]'::jsonb, 3, '마이클 씨는 도서관에 올 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 42, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/reading/q42.png', NULL, NULL, '["엄마는 만 원을 냅니다.", "커피와 주스도 같이 만듭니다.", "요리 교실은 토요일마다 있습니다.", "부모하고 아이가 불고기를 만듭니다."]'::jsonb, 3, '커피와 주스도 같이 만듭니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 43, '저는 그림을 배웁니다.주말마다 공원에 가서 그림을 그립니다.가끔
어머니와 미술관에 가서 구경을 합니다.', NULL, NULL, NULL, '["저는 어머니와 공원에 갑니다.", "어머니는 그림 공부를 합니다.", "저는 공원에서 그림을 그립니다.", "어머니는 혼자 미술관에 갑니다."]'::jsonb, 3, '저는 공원에서 그림을 그립니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 44, '오늘 저녁에 손님이 옵니다.그래서 아침에 꽃도 사고 집도 청소했습니다.
회사가 끝나면 집에 일찍 가서 음식을 준비할 겁니다.', NULL, NULL, NULL, '["저녁에 청소를 할 겁니다.", "손님과 저녁을 먹을 겁니다.", "음식을 벌써 준비했습니다.", "손님이 꽃을 사 올 겁니다."]'::jsonb, 2, '손님과 저녁을 먹을 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 45, '저는 마음이 아프고 힘들 때 친구를 만납니다.친구를 만나서 제 생각을
친구에게 이야기합니다.그러면 기분이 좋고 즐겁습니다.', NULL, NULL, NULL, '["저는 친구의 이야기를 잘 듣습니다.", "저는 친구를 만나면 마음이 아픕니다.", "저는 기분이 좋을 때 친구를 만납니다.", "저는 힘들 때 친구와 이야기를 합니다."]'::jsonb, 3, '저는 힘들 때 친구와 이야기를 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 46, '저는 아이들에게 가방을 만들어 줍니다.다른 사람에게도 자주 가방을
만들어서 선물합니다.가방 만들기는 어렵지만 재미있습니다.', NULL, NULL, NULL, '["저는 가방 만들기가 어렵습니다.", "저는 가방 만들기를 좋아합니다.", "저는 다른 사람과 가방을 만듭니다.", "저는 아이들에게 가방을 선물합니다."]'::jsonb, 3, '저는 가방 만들기를 좋아합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 47, '친구가 다리가 아파서 수업에 못 왔습니다.저는 오후에 친구에게 숙제를
말해 줄 겁니다.내일은 친구 집에 가서 함께 학교에 가려고 합니다.', NULL, NULL, NULL, '["저는 친구를 도와줄 겁니다.", "저는 친구와 살고 싶습니다.", "저는 친구 집에서 숙제를 할 겁니다.", "저는 보통 친구와 같이 학교에 갑니다."]'::jsonb, 3, '저는 친구를 도와줄 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 48, '형은 어릴 때 조용하고 말이 없었습니다.그리고 혼자 있는 것을 좋아
했습니다.그런데 지금은 재미있는 말도 많이 하고 사람들도 자주 만납니다.', NULL, NULL, NULL, '["형은 옛날과 많이 다릅니다.", "형은 요즘 말을 잘 안 합니다.", "형은 재미있는 이야기를 못 합니다.", "형은 옛날에 사람들을 자주 만났습니다."]'::jsonb, 2, '형은 옛날과 많이 다릅니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 49, '㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["손님이 별로 없습니다", "친절한 직원이 있습니다", "일하는 사람이 없습니다", "주인이 차를 직접 만듭니다"]'::jsonb, 2, '일하는 사람이 없습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 50, '이 글의 내용과 같은 것을 고르십시오.', NULL, NULL, NULL, '["이 카페는 오래되었습니다.", "카페의 차 값은 싸지 않습니다.", "손님은 차를 주문하고 기다립니다.", "이 카페는 편안해서 사람들이 좋아합니다."]'::jsonb, 2, '이 카페는 편안해서 사람들이 좋아합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 51, '㉠에 들어갈 알맞은 말을 고르십시오.(3점)', NULL, NULL, NULL, '["받을 수 있습니다", "예약할 수 있습니다", "빌릴 수 있습니다", "이용할 수 있습니다"]'::jsonb, 3, '이용할 수 있습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 52, '무엇에 대한 이야기인지 고르십시오.(2점)', NULL, NULL, NULL, '["120전화의 이용 시간", "택시와 기차의 예약 방법", "120전화의 서비스 내용", "한국에서 관광하기 좋은 장소"]'::jsonb, 2, '120전화의 서비스 내용', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 53, '㉠에 들어갈 알맞은 말을 고르십시오.(2점)', NULL, NULL, NULL, '["저를 봐서", "저를 보면", "저를 보거나", "저를 보니까"]'::jsonb, 2, '저를 보면', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 54, '이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["저와 여동생은 잘 웃지 않습니다.", "저와 여동생은 머리 색깔이 다릅니다.", "저와 여동생은 태어난 날이 같습니다.", "저와 여동생은 청바지를 잘 입지 않습니다."]'::jsonb, 3, '저와 여동생은 태어난 날이 같습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 55, '㉠에 들어갈 알맞은 말을 고르십시오.(2점)', NULL, NULL, NULL, '["그래서", "그리고", "하지만", "그런데"]'::jsonb, 2, '그래서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 56, '이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["떡볶이는 맛이 모두 같습니다.", "전통 떡볶이에는 소고기를 넣습니다.", "전통 떡볶이는 맵지만 건강에 좋습니다.", "전통 떡볶이는 외국인이 먹기 어렵습니다."]'::jsonb, 3, '전통 떡볶이에는 소고기를 넣습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 57, '(가)주말마다 서울 여기저기를 다닙니다.
(나)찰리 씨는 서울에 사는 외국인입니다.
(다)왜냐하면 지하철은 편리하기 때문입니다.
(라)서울 구경을 할 때는 주로 지하철을 탑니다.', NULL, NULL, NULL, '["(나)－(가)－(다)－(라)", "(나)－(가)－(라)－(다)", "(나)－(라)－(가)－(다)", "(나)－(라)－(다)－(가)"]'::jsonb, 3, '(나)－(가)－(라)－(다)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 58, '(가)그 남자는 지금 제 남자 친구입니다.
(나)저는 우산이 없어서 그냥 건물 앞에 서 있었습니다.
(다)그때 어떤 남자가 저에게 와서 우산을 주었습니다.
(라)어느 날 회사 일이 끝나고 집에 가는데 갑자기 비가 왔습니다.', NULL, NULL, NULL, '["(라)－(가)－(나)－(다)", "(라)－(가)－(다)－(나)", "(라)－(나)－(가)－(다)", "(라)－(나)－(다)－(가)"]'::jsonb, 2, '(라)－(나)－(다)－(가)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 59, '다음 문장이 들어갈 곳을 고르십시오.(2점)
사람들은 우리의 춤을 보고 박수를 치면서 소리를 지릅니다.', NULL, NULL, NULL, '["㉠", "㉡", "㉢", "㉣"]'::jsonb, 2, '㉢', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 60, '이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["저는 날마다 춤 연습을 합니다.", "저는 공연 보는 것을 좋아합니다.", "저는 요즘 춤에 관심이 생겼습니다.", "저는 혼자 공원에서 공연을 합니다."]'::jsonb, 3, '저는 날마다 춤 연습을 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 61, '㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["바꾸면", "바꿔도", "바꾸려고", "바꾸지만"]'::jsonb, 2, '바꾸려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 62, '이 글의 내용과 같은 것을 고르십시오.', NULL, NULL, NULL, '["평일에는 이 도로에 차가 다닐 수 없습니다.", "배가 고프면 이곳에서 음식을 직접 만듭니다.", "사람들이 많아지면서 거리가 더 복잡해졌습니다.", "이 도로는 젊은 사람들이 좋아하는 곳이 되었습니다."]'::jsonb, 2, '이 도로는 젊은 사람들이 좋아하는 곳이 되었습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 63, '김윤미 씨는 왜 이 글을 썼습니까?(2점)', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/reading/q63_64.png', NULL, NULL, '["그림책을 팔고 싶어서", "그림책을 바꾸고 싶어서", "그림책을 소개하고 싶어서", "그림책에 대해 물어보고 싶어서"]'::jsonb, 2, '그림책을 팔고 싶어서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 64, '이 글의 내용과 같은 것을 고르십시오.(3점)', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-36/reading/q63_64.png', NULL, NULL, '["이 그림책은 새 책입니다.", "여러 번 읽었지만 깨끗합니다.", "초등학교 가기 전에 읽는 책입니다.", "책값에 배달 비용도 들어 있습니다."]'::jsonb, 3, '책값에 배달 비용도 들어 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 65, '㉠에 들어갈 알맞은 말을 고르십시오.(2점)', NULL, NULL, NULL, '["준비해도 됩니다", "준비할 수 있습니다", "준비되어 있습니다", "준비된 적이 있습니다"]'::jsonb, 2, '준비되어 있습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 66, '이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["국제만화축제가 지금 열리고 있습니다.", "이 축제에서 옛날 만화책은 볼 수 없습니다.", "이 축제에서 다른 나라의 만화를 볼 수 있습니다.", "사람들에게 유명한 만화가의 얼굴을 그려 줍니다."]'::jsonb, 3, '이 축제에서 다른 나라의 만화를 볼 수 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 67, '㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["내야 합니다", "많이 법니다", "별로 없습니다", "받지 않습니다"]'::jsonb, 3, '받지 않습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 68, '이 글의 내용과 같은 것을 고르십시오.', NULL, NULL, NULL, '["김지호 씨는 바쁠 때 시골에 가지 못합니다.", "도시보다 시골의 작은 마을에 손님이 더 많습니다.", "마을 사람들은 김지호 씨의 이야기를 재미있게 듣습니다.", "김지호 씨는 시골 사람들과 함께 있는 시간을 좋아합니다."]'::jsonb, 3, '김지호 씨는 시골 사람들과 함께 있는 시간을 좋아합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 69, '㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["보고 싶을 겁니다", "보고 싶었습니다", "좋아지고 있습니다", "좋아지려고 합니다"]'::jsonb, 3, '보고 싶을 겁니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 36 ORDER BY created_at DESC LIMIT 1), 'reading', 70, '이 글의 내용으로 알 수 있는 것은 무엇입니까?', NULL, NULL, NULL, '["저는 이사를 가서 나무를 심을 겁니다.", "저는 나무와 헤어지게 되어서 슬픕니다.", "저는 나무 때문에 이사를 갈 수 없습니다.", "저는 나무가 보고 싶을 때 그 집에 갈 겁니다."]'::jsonb, 3, '저는 나무와 헤어지게 되어서 슬픕니다.', NULL);

COMMIT;
