-- Generated by scripts/generate_topik_i_52_sql.py
BEGIN;

INSERT INTO mock_test_bank (
  title, exam_type, test_number, description, total_questions, duration, listening_questions, reading_questions
)
SELECT
  'TOPIK I 52-р шалгалт',
  'TOPIK_I',
  52,
  '52-р албан ёсны TOPIK I шалгалт',
  70,
  100,
  30,
  40
WHERE NOT EXISTS (
  SELECT 1 FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52
);

UPDATE mock_test_bank SET title = 'TOPIK I 52-р шалгалт', description = '52-р албан ёсны TOPIK I шалгалт', total_questions = 70, duration = 100, listening_questions = 30, reading_questions = 40, updated_at = NOW() WHERE id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1);

DELETE FROM mock_test_questions WHERE mock_test_id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1);

INSERT INTO mock_test_questions (
  mock_test_id,
  section,
  question_number,
  question_text,
  question_image_url,
  audio_url,
  option_image_urls,
  options,
  question_score,
  correct_answer_text,
  explanation
) VALUES
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 1, '여자 :영화를 봐요?
남자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["네,영화를 해요.", "네,영화가 아니에요.", "아니요,영화를 안 봐요.", "아니요,영화가 재미있어요."]'::jsonb, 4, '아니요,영화를 안 봐요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 2, '남자 :사람이 많아요?
여자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["네,사람이 없어요.", "네,사람이 많아요.", "아니요,사람이에요.", "아니요,사람이 좋아요."]'::jsonb, 4, '네,사람이 많아요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 3, '여자 :모자를 언제 샀어요?
남자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["모자를 샀어요.", "동생이 샀어요.", "주말에 샀어요.", "백화점에서 샀어요."]'::jsonb, 3, '주말에 샀어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 4, '남자 :무슨 일을 해요?
여자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["매일 일해요.", "정말 멋있어요.", "일이 어려워요.", "학생을 가르쳐요."]'::jsonb, 3, '학생을 가르쳐요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 5, '여자 :안녕히 가세요.
남자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["반갑습니다.", "실례합니다.", "안녕히 계세요.", "여기 앉으세요."]'::jsonb, 4, '안녕히 계세요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 6, '남자 :여보세요,김수미 씨 좀 부탁합니다.
여자 :_____________________________', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["네,전데요.", "네,저도요.", "네,미안해요.", "네,괜찮아요."]'::jsonb, 3, '네,전데요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 7, '여자 :서울역으로 가 주세요.
남자 :네,알겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["택시", "기차", "비행기", "지하철"]'::jsonb, 3, '택시', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 8, '남자 :어떤 걸로 드릴까요?
여자 :저 딸기 케이크 주세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["은행", "빵집", "정류장", "세탁소"]'::jsonb, 3, '빵집', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 9, '여자 :이 소포 미국에 보내고 싶은데요.
남자 :안에 뭐가 들어 있어요?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["극장", "식당", "미술관", "우체국"]'::jsonb, 3, '우체국', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 10, '남자 :요리책은 어디에 있어요?
여자 :2층에 있습니다,손님.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["약국", "서점", "사진관", "운동장"]'::jsonb, 4, '서점', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 11, '남자 :몇 시에 학교에 가요?
여자 :열 시에 가요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["시간", "날짜", "나이", "주소"]'::jsonb, 3, '시간', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 12, '여자 :민수 씨,요즘도 수영해요?
남자 :네.그리고 테니스도 배우고 있어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["장소", "운동", "음식", "직업"]'::jsonb, 3, '운동', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 13, '남자 :마리 씨 고향은 지금 겨울이에요?
여자 :아니요.여름이에요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["요일", "나라", "여행", "계절"]'::jsonb, 4, '계절', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 14, '여자 :은행이 어디에 있어요?
남자 :저 커피숍 뒤에 있어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["취미", "약속", "위치", "교통"]'::jsonb, 3, '위치', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 15, '여자 :뭘 드릴까요?손님.
남자 :김밥 하나 주세요.
알맞은 그림을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/listening/q15_option_1.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/listening/q15_option_2.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/listening/q15_option_3.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/listening/q15_option_4.png"]'::jsonb, '["①", "②", "③", "④"]'::jsonb, 4, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 16, '여자 :비가 오네요.우산이 없는데…….
남자 :그래요?저하고 같이 써요.
알맞은 그림을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/listening/q16_option_1.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/listening/q16_option_2.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/listening/q16_option_3.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/listening/q16_option_4.png"]'::jsonb, '["①", "②", "③", "④"]'::jsonb, 4, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 17, '남자 :여자 친구한테 선물하고 싶은데,어떤 꽃이 좋을까요?
여자 :장미꽃이 좋을 것 같아요.
남자 :그럼 장미꽃으로 열 송이 주세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["남자는 장미꽃을 삽니다.", "여자는 선물을 받습니다.", "남자는 여자 친구가 없습니다.", "여자는 꽃 이름을 잘 모릅니다."]'::jsonb, 3, '남자는 장미꽃을 삽니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 18, '남자 :저는 방학에 아르바이트도 하고 여행도 했어요.수미 씨는 뭐 했어요?
여자 :(슬픈 목소리로)저는 도서관에서 시험공부만 했어요.
남자 :그래요?시험이 언제예요?
여자 :다음 주에 있어요.그래서 오늘도 도서관에 공부하러 갈 거예요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["여자는 도서관에 일하러 갑니다.", "남자는 다음 주에 시험을 볼 겁니다.", "여자는 방학에 시험 준비를 했습니다.", "남자는 일 때문에 여행을 못 갔습니다."]'::jsonb, 3, '여자는 방학에 시험 준비를 했습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 19, '남자 :(걱정하는 목소리로)미영 씨,왜 그래요?어디 안 좋아요?
여자 :아침부터 머리가 너무 아파요.지금은 열도 나고요.
남자 :그럼 일찍 가서 좀 쉬는 게 어때요?
여자 :감사합니다,과장님.이 일만 끝내고 가겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["남자는 쉬고 싶어 합니다.", "여자는 일을 다 끝냈습니다.", "남자는 집에 가려고 합니다.", "여자는 몸이 좋지 않습니다."]'::jsonb, 3, '여자는 몸이 좋지 않습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 20, '남자 :김현수 선수가 와서 농구를 가르쳐 주는 행사가 있어요.
여자 :그래요?제가 고등학생 때부터 좋아하는 선수인데…….
남자 :그럼 같이 신청할래요?이번 주까지 하면 돼요.
여자 :네,좋아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["여자는 농구 선수를 좋아합니다.", "남자는 행사에 관심이 없습니다.", "여자는 다음 주에 신청할 겁니다.", "남자는 농구를 가르치려고 합니다."]'::jsonb, 3, '여자는 농구 선수를 좋아합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 21, '여자 :(감탄하며)와,집에 만화책이 정말 많네요.
남자 :제가 만화책을 좋아해서 몇 년 전부터 모으고 있어요.
여자 :여기,외국 만화책도 있네요.이건 어떻게 샀어요?
남자 :외국에 사는 친구들한테 부탁해서 받은 거예요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["여자는 남자하고 만화책을 샀습니다.", "남자는 만화책을 많이 모았습니다.", "여자는 남자한테 만화책을 주었습니다.", "남자는 만화책을 사려고 외국에 갔습니다."]'::jsonb, 3, '남자는 만화책을 많이 모았습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 22, '남자 :아침밥을 못 먹고 와서 배가 고프네요.
여자 :이제 곧 수업 시작하는데…….그럼 이 우유 마실래요?
남자 :고마워요.저는 늦게 일어나서 아침을 못 먹을 때가 많아요.
여자 :아침밥을 먹는 게 건강에 좋아요.그리고 공부도 잘할 수 있고요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["아침밥을 먹는 게 좋습니다.", "아침에 일찍 일어나야 합니다.", "아침에 우유를 마시면 좋습니다.", "아침밥은 집에서 먹어야 합니다."]'::jsonb, 3, '아침밥을 먹는 게 좋습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 23, '남자 :회사에서 집까지 얼마나 걸려요?
여자 :우리 집은 회사에서 좀 멀어요.버스로 한 시간쯤 걸려요.
남자 :그럼 회사 근처로 이사 오지 그래요?아침에 힘들지 않아요?
여자 :집이 좀 멀지만 근처에 산도 있고 공원도 있어서 좋아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["지금 살고 있는 집이 좋습니다.", "집과 회사는 가까운 게 좋습니다.", "등산을 자주 하려면 이사해야 합니다.", "집에서 회사까지 걸어 다녀야 합니다."]'::jsonb, 3, '지금 살고 있는 집이 좋습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 24, '남자 :인터넷으로 구두를 샀는데 좀 크네요.바꾸는 게 좋겠지요?
여자 :네.저도 그런 적이 있어서 인터넷으로 신발을 잘 안 사요.
남자 :인터넷으로 신발을 사면 가게에 안 가서 편한데…….
여자 :하지만 이렇게 물건을 바꿔야 할 때는 다시 보내고 받아야 해서
시간이 걸리잖아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["신발은 좀 크게 신는 게 좋습니다.", "신발이 안 맞을 때는 빨리 바꿔야 합니다.", "인터넷으로 신발을 사면 바꾸기 쉽습니다.", "인터넷으로 신발을 사지 않는 게 좋습니다."]'::jsonb, 3, '인터넷으로 신발을 사지 않는 게 좋습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 25, '여자 :딩동댕 승객 여러분,안녕하십니까?이 버스는 시청에서 출발해서 중앙공원까지 가는 서울 투어 버스입니다.중간에 내려서 관광지를 구경할 수 있고,다음 버스를 탈 때는 표를 다시 사지 않아도 됩니다.버스는 삼십 분마다 서울 투어 버스 정류장에서 이용하실 수 있습니다.감사합니다.
여자가 왜 이 이야기를 하고 있는지 고르십시오.(3점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["버스 종류를 알려 주려고", "관광지 이름을 소개하려고", "관광지 위치를 설명하려고", "버스 이용 방법을 안내하려고"]'::jsonb, 3, '버스 이용 방법을 안내하려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 26, '여자 :딩동댕 승객 여러분,안녕하십니까?이 버스는 시청에서 출발해서 중앙공원까지 가는 서울 투어 버스입니다.중간에 내려서 관광지를 구경할 수 있고,다음 버스를 탈 때는 표를 다시 사지 않아도 됩니다.버스는 삼십 분마다 서울 투어 버스 정류장에서 이용하실 수 있습니다.감사합니다.
들은 내용과 같은 것을 고르십시오.(4점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["이 버스는 중앙공원에서 출발합니다.", "버스를 다시 탈 때는 표를 사야 합니다.", "사람들은 내려서 관광지를 구경할 수 있습니다.", "사람들은 한 시간 동안 버스를 기다려야 합니다."]'::jsonb, 4, '사람들은 내려서 관광지를 구경할 수 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 27, '여자 :네,인주 서비스 센터입니다.무엇을 도와 드릴까요?
남자 :새로 산 텔레비전이 갑자기 소리가 안 나와요.
여자 :그럼 텔레비전을 한번 꺼 보세요.그리고 잠시 후에 다시 켜 보세요.
남자 :그렇게 해 봤는데 안 돼요.(잠시 쉬고)오늘 고칠 수 있을까요?
여자 :오늘은 늦어서 어렵고요.내일 오전에 직원이 연락 드리고 고치러 갈 겁니다.
남자 :네,알겠습니다.
두 사람이 무엇에 대해 이야기를 하고 있는지 고르십시오.(3점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["고장 난 텔레비전", "사고 싶은 텔레비전", "서비스 센터 연락 방법", "서비스 센터 이용 시간"]'::jsonb, 3, '고장 난 텔레비전', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 28, '여자 :네,인주 서비스 센터입니다.무엇을 도와 드릴까요?
남자 :새로 산 텔레비전이 갑자기 소리가 안 나와요.
여자 :그럼 텔레비전을 한번 꺼 보세요.그리고 잠시 후에 다시 켜 보세요.
남자 :그렇게 해 봤는데 안 돼요.(잠시 쉬고)오늘 고칠 수 있을까요?
여자 :오늘은 늦어서 어렵고요.내일 오전에 직원이 연락 드리고 고치러 갈 겁니다.
남자 :네,알겠습니다.
들은 내용과 같은 것을 고르십시오.(4점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["남자는 텔레비전을 사러 왔습니다.", "남자는 내일 직원과 통화할 겁니다.", "여자는 남자의 집에 찾아갈 겁니다.", "여자는 남자의 텔레비전을 고쳤습니다."]'::jsonb, 4, '남자는 내일 직원과 통화할 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 29, '남자 :이번 한국어 말하기 대회에서 1등을 하셨는데요.기분이 어떠세요?
여자 :잘하는 학생들이 많았는데 제가 상을 받아서 정말 기뻐요.
남자 :그렇군요.실수도 하지 않고 자연스럽게 잘하셔서 정말 놀랐어요.
여자 :사실 제가 사람들 앞에서 긴장을 많이 해요.그래서 친구들 앞에서 매일 말하기 연습을 했어요.또 한국어 선생님께서 발음 연습을 도와주셨어요.그 덕분에 1등을 한 것 같아요.
남자 :네,그런데 이번 대회에는 어떻게 참가하게 되셨어요?
여자 :이번이 한국에서 공부하는 마지막 학기라서 그동안 해 보지 못한 경험을 하고 싶었어요.
여자가 대회에 참가한 이유를 고르십시오.(3점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["한국어 발음 연습을 할 수 있어서", "많은 외국인 학생을 만날 수 있어서", "한국에서 특별한 경험을 하고 싶어서", "사람들 앞에서 이야기하는 것을 좋아해서"]'::jsonb, 3, '한국에서 특별한 경험을 하고 싶어서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'listening', 30, '남자 :이번 한국어 말하기 대회에서 1등을 하셨는데요.기분이 어떠세요?
여자 :잘하는 학생들이 많았는데 제가 상을 받아서 정말 기뻐요.
남자 :그렇군요.실수도 하지 않고 자연스럽게 잘하셔서 정말 놀랐어요.
여자 :사실 제가 사람들 앞에서 긴장을 많이 해요.그래서 친구들 앞에서 매일 말하기 연습을 했어요.또 한국어 선생님께서 발음 연습을 도와주셨어요.그 덕분에 1등을 한 것 같아요.
남자 :네,그런데 이번 대회에는 어떻게 참가하게 되셨어요?
여자 :이번이 한국에서 공부하는 마지막 학기라서 그동안 해 보지 못한 경험을 하고 싶었어요.
들은 내용과 같은 것을 고르십시오.(4점)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/audio/52nd-TOPIK-I-Listening-Audio-File-64k-mono.mp3', NULL, '["여자는 한국에서 계속 공부하려고 합니다.", "여자는 긴장을 해서 실수를 많이 했습니다.", "여자는 사람들이 없는 곳에서 연습했습니다.", "여자는 한국어 선생님의 도움을 받았습니다."]'::jsonb, 4, '여자는 한국어 선생님의 도움을 받았습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 31, '형은 스물한 살입니다.누나는 스물세 살입니다.', NULL, NULL, NULL, '["나이", "날짜", "이름", "시간"]'::jsonb, 2, '나이', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 32, '비빔밥은 육천 원입니다.냉면은 오천 원입니다.', NULL, NULL, NULL, '["맛", "값", "옷", "일"]'::jsonb, 2, '값', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 33, '비가 옵니다.바람도 많이 붑니다.', NULL, NULL, NULL, '["날씨", "방학", "휴일", "계획"]'::jsonb, 2, '날씨', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 34, '저는 마이클입니다.미국( )왔습니다.', NULL, NULL, NULL, '["이", "의", "에서", "하고"]'::jsonb, 2, '에서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 35, '배가 고픕니다.( )에 갑니다.', NULL, NULL, NULL, '["은행", "식당", "우체국", "여행사"]'::jsonb, 2, '식당', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 36, '저는 사과 주스를 좋아합니다.그래서 ( )마십니다.', NULL, NULL, NULL, '["자주", "아마", "제일", "아까"]'::jsonb, 2, '자주', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 37, '도서관입니다.책이 아주 ( ).', NULL, NULL, NULL, '["넓습니다", "많습니다", "쉽습니다", "짧습니다"]'::jsonb, 3, '많습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 38, '길을 모릅니다.사람들에게 ( ).', NULL, NULL, NULL, '["줍니다", "팝니다", "노래합니다", "물어봅니다"]'::jsonb, 3, '물어봅니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 39, '동생의 결혼식입니다.가족들이 함께 사진을 ( ).', NULL, NULL, NULL, '["만납니다", "빌립니다", "찍습니다", "배웁니다"]'::jsonb, 2, '찍습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 40, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/reading/q40.png', NULL, NULL, '["부산으로 갑니다.", "표는 오만 구천 원입니다.", "아침 아홉 시에 출발합니다.", "오월 오일에 기차를 탑니다."]'::jsonb, 3, '부산으로 갑니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 41, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/reading/q41.png', NULL, NULL, '["수미 씨가 메모를 썼습니다.", "수미 씨는 친구를 만납니다.", "수미 씨의 친구가 회사에 왔습니다.", "수미 씨는 미영 씨와 점심을 먹을 겁니다."]'::jsonb, 3, '수미 씨는 미영 씨와 점심을 먹을 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 42, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/reading/q42.png', NULL, NULL, '["음악회는 주말에 합니다.", "음악회는 하늘공원에서 합니다.", "음악회는 저녁 여덟 시에 끝납니다.", "음악회에서 이소영 씨가 노래를 부릅니다."]'::jsonb, 3, '음악회에서 이소영 씨가 노래를 부릅니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 43, '내일은 친구의 생일입니다.저는 친구에게 주려고 과자를 만들었습니다.
내일 친구에게 선물할 겁니다.', NULL, NULL, NULL, '["저는 과자를 살 겁니다.", "친구가 과자를 만들었습니다.", "친구가 생일 선물을 주었습니다.", "저는 내일 친구에게 과자를 줄 겁니다."]'::jsonb, 3, '저는 내일 친구에게 과자를 줄 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 44, '오늘 수미 씨와 영화를 보러 갔습니다.우리는 영화관까지 함께 버스를
타고 갔습니다.영화를 보고 우리 집에서 같이 저녁을 먹었습니다.', NULL, NULL, NULL, '["저는 수미 씨와 영화를 봤습니다.", "저는 영화관까지 걸어서 갔습니다.", "저는 식당에서 저녁 식사를 했습니다.", "저는 영화관에서 수미 씨를 만났습니다."]'::jsonb, 2, '저는 수미 씨와 영화를 봤습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 45, '저는 보통 자전거를 타고 출근합니다.자전거를 타면 운동도 할 수 있어서
좋습니다.그런데 오늘은 다리가 아파서 택시를 타고 출근했습니다.', NULL, NULL, NULL, '["오늘은 회사에 가지 않았습니다.", "저는 회사에 가서 운동을 합니다.", "저는 보통 택시를 타고 회사에 갑니다.", "오늘은 다리가 아파서 자전거를 못 탔습니다."]'::jsonb, 3, '오늘은 다리가 아파서 자전거를 못 탔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 46, '제 친구 마리 씨가 오늘 고향으로 돌아갔습니다.우리는 공항에서 인사를
했습니다.저는 마리 씨와 헤어져서 눈물이 났습니다.', NULL, NULL, NULL, '["저는 고향에 가려고 했습니다.", "저는 마리 씨가 떠나서 슬펐습니다.", "저는 마리 씨의 고향에 가고 싶었습니다.", "저는 공항에서 친구를 만나고 싶었습니다."]'::jsonb, 3, '저는 마리 씨가 떠나서 슬펐습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 47, '아버지의 가방은 오래되었습니다.저는 아버지의 가방을 바꿔 드리고
싶습니다.그래서 요즘 아르바이트를 하고 있습니다.', NULL, NULL, NULL, '["저는 아버지의 가방이 좋습니다.", "저는 아르바이트를 찾으려고 합니다.", "저는 아버지께 가방을 사 드리려고 합니다.", "저는 가방 만드는 회사에서 일하고 싶습니다."]'::jsonb, 3, '저는 아버지께 가방을 사 드리려고 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 48, '저는 주말에 항상 민수 씨와 테니스를 칩니다.그런데 민수 씨가 일
때문에 외국에 갔습니다.저는 민수 씨가 빨리 오면 좋겠습니다.', NULL, NULL, NULL, '["저는 테니스를 배우려고 합니다.", "저는 외국에서 일을 하려고 합니다.", "저는 민수 씨와 테니스를 치고 싶습니다.", "저는 민수 씨와 같이 외국에 가고 싶습니다."]'::jsonb, 2, '저는 민수 씨와 테니스를 치고 싶습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 49, '㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["좋으면", "좋지만", "좋아도", "좋은데"]'::jsonb, 2, '좋으면', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 50, '이 글의 내용과 같은 것을 고르십시오.', NULL, NULL, NULL, '["저는 여행할 때 직접 운전을 합니다.", "저는 여러 사람과 함께 여행을 합니다.", "저는 여행 기간을 정한 후에 여행합니다.", "저는 여행할 때마다 유명한 관광지에 갑니다."]'::jsonb, 2, '저는 여행할 때 직접 운전을 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 51, '㉠에 들어갈 알맞은 말을 고르십시오.(3점)', NULL, NULL, NULL, '["그래서", "그러면", "그리고", "그러나"]'::jsonb, 3, '그리고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 52, '무엇에 대한 이야기인지 맞는 것을 고르십시오.(2점)', NULL, NULL, NULL, '["밀가루로 할 수 있는 일", "밀가루로 그릇을 닦는 순서", "밀가루로 과일을 씻는 방법", "밀가루로 만들 수 있는 음식"]'::jsonb, 2, '밀가루로 할 수 있는 일', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 53, '㉠에 들어갈 알맞은 말을 고르십시오.(2점)', NULL, NULL, NULL, '["금방 골랐습니다", "다시 보냈습니다", "계속 기다렸습니다", "직접 만들었습니다"]'::jsonb, 2, '직접 만들었습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 54, '이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["저는 비누를 만드는 것이 어렵습니다.", "저는 인터넷으로 쌀이나 과일을 삽니다.", "제 아이는 비누 만드는 방법을 배웁니다.", "제가 만든 비누는 아이의 피부에 좋습니다."]'::jsonb, 3, '제가 만든 비누는 아이의 피부에 좋습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 55, '㉠에 들어갈 알맞은 말을 고르십시오.(2점)', NULL, NULL, NULL, '["돌아가면 안 됩니다", "돌아갔기 때문입니다", "돌아가고 싶었습니다", "돌아간 적이 있습니다"]'::jsonb, 2, '돌아가고 싶었습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 56, '이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["제 아내는 도시 생활을 좋아합니다.", "제 아내는 회사에 다니지 않았습니다.", "저는 시골에 가서 꽃을 키우려고 합니다.", "저는 어렸을 때부터 서울에서 살았습니다."]'::jsonb, 3, '저는 시골에 가서 꽃을 키우려고 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 57, '(가)저는 오른손으로 글씨를 썼습니다.
(나)그때부터 왼손으로 글씨를 쓰기 시작했습니다.
(다)처음에는 불편했지만 지금은 왼손으로 쓰는 것이 익숙합니다.
(라)그런데 운동을 할 때 다쳐서 오른손으로 글씨를 쓸 수 없었습니다.', NULL, NULL, NULL, '["(가)－(다)－(라)－(나)", "(가)－(라)－(나)－(다)", "(다)－(라)－(나)－(가)", "(다)－(나)－(가)－(라)"]'::jsonb, 3, '(가)－(라)－(나)－(다)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 58, '(가)그렇지만 물 위에 있으면 오래된 달걀입니다.
(나)소금물이 있는 그릇에 달걀을 넣어 보면 됩니다.
(다)오래된 달걀과 신선한 달걀을 알 수 있는 방법이 있습니다.
(라)소금물에 넣었을 때 달걀이 그릇 바닥에 있으면 신선한 것입니다.', NULL, NULL, NULL, '["(나)－(라)－(다)－(가)", "(나)－(다)－(가)－(라)", "(다)－(가)－(나)－(라)", "(다)－(나)－(라)－(가)"]'::jsonb, 2, '(다)－(나)－(라)－(가)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 59, '다음 문장이 들어갈 곳을 고르십시오.(2점)
며칠 후에 다시 가 보면 우리가 놓고 온 것이 하나도 없습니다.', NULL, NULL, NULL, '["㉠", "㉡", "㉢", "㉣"]'::jsonb, 2, '㉢', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 60, '이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["우리 동네 산에는 토끼가 살지 않습니다.", "동물들은 우리가 산에 놓고 온 것을 먹습니다.", "저는 힘들어서 산에 올라가는 것을 싫어합니다.", "동물들은 먹을 것을 찾으려고 산에서 내려옵니다."]'::jsonb, 3, '동물들은 우리가 산에 놓고 온 것을 먹습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 61, '㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["고쳐 주거나", "고쳐 보려고", "고치고 싶지만", "고친 것 같아서"]'::jsonb, 2, '고쳐 주거나', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 62, '이 글의 내용과 같은 것을 고르십시오.', NULL, NULL, NULL, '["공항에서 여권을 만들 수 없습니다.", "공항에서 가방을 빌려주기도 합니다.", "공항에 편리한 서비스가 별로 없습니다.", "공항에 옷을 바꿔 주는 서비스가 있습니다."]'::jsonb, 2, '공항에서 가방을 빌려주기도 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 63, '왜 이 글을 썼는지 맞는 것을 고르십시오.(2점)', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/reading/q63_64.png', NULL, NULL, '["축제 날짜를 확인하려고", "축제 내용을 알려 주려고", "축제에 필요한 돈을 모으려고", "축제를 함께 준비할 사람을 찾으려고"]'::jsonb, 2, '축제 내용을 알려 주려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 64, '이 글의 내용과 같은 것을 고르십시오.(3점)', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-52/reading/q63_64.png', NULL, NULL, '["축제는 오후 열 시까지 합니다.", "축제는 올해 처음으로 시작됐습니다.", "축제에 참가하려면 돈을 내야 합니다.", "축제에 참가하려면 엽서를 보내야 합니다."]'::jsonb, 3, '축제에 참가하려면 돈을 내야 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 65, '㉠에 들어갈 알맞은 말을 고르십시오.(2점)', NULL, NULL, NULL, '["가족 모임에서 말했습니다", "피아노를 사려고 했습니다", "피아노를 함께 연주했습니다", "학원에 등록을 해 드렸습니다"]'::jsonb, 2, '학원에 등록을 해 드렸습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 66, '이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["어머니는 즐겁게 피아노를 배우십니다.", "우리 동네에는 피아노 학원이 없습니다.", "저는 어머니께 피아노를 가르쳐 드립니다.", "어머니는 가족들 앞에서 피아노를 안 치십니다."]'::jsonb, 3, '어머니는 즐겁게 피아노를 배우십니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 67, '㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["그림을 배우고 있습니다", "이곳을 찾아오고 있습니다", "물건을 전시하고 있습니다", "글씨를 예쁘게 쓰고 있습니다"]'::jsonb, 3, '이곳을 찾아오고 있습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 68, '이 글의 내용과 같은 것을 고르십시오.', NULL, NULL, NULL, '["인주시장은 최근에 새로 생겼습니다.", "인주시장에서만 살 수 있는 물건이 있습니다.", "인주시장에 오는 사람들이 그림을 전시했습니다.", "가게 주인들은 시장에 오는 사람들에게 이름을 써 줍니다."]'::jsonb, 3, '인주시장에서만 살 수 있는 물건이 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 69, '㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["배우를 만났습니다", "금방 유명해졌습니다", "다른 일을 찾았습니다", "더 열심히 노력했습니다"]'::jsonb, 3, '다른 일을 찾았습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 52 ORDER BY created_at DESC LIMIT 1), 'reading', 70, '이 글의 내용으로 알 수 있는 것을 고르십시오.', NULL, NULL, NULL, '["제 직업은 영화배우입니다.", "저는 직업을 바꾸고 싶습니다.", "아이들은 영화를 보면서 크게 웃습니다.", "제가 책을 읽어 주면 아이들은 좋아합니다."]'::jsonb, 3, '제가 책을 읽어 주면 아이들은 좋아합니다.', NULL);

COMMIT;
