-- Generated by scripts/generate_topik_i_35_sql.py
BEGIN;

INSERT INTO mock_test_bank (
  title, exam_type, test_number, description, total_questions, duration, listening_questions, reading_questions
)
SELECT
  'TOPIK I 35-р шалгалт',
  'TOPIK_I',
  35,
  '35-р албан ёсны TOPIK I шалгалт',
  70,
  100,
  30,
  40
WHERE NOT EXISTS (
  SELECT 1 FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35
);

UPDATE mock_test_bank SET title = 'TOPIK I 35-р шалгалт', description = '35-р албан ёсны TOPIK I шалгалт', total_questions = 70, duration = 100, listening_questions = 30, reading_questions = 40, updated_at = NOW() WHERE id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1);

ALTER TABLE mock_test_questions ADD COLUMN IF NOT EXISTS question_image_url TEXT;
ALTER TABLE mock_test_questions ADD COLUMN IF NOT EXISTS option_image_urls JSONB;
ALTER TABLE mock_test_questions ADD COLUMN IF NOT EXISTS question_score INTEGER NOT NULL DEFAULT 1;

DELETE FROM mock_test_questions WHERE mock_test_id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1);

INSERT INTO mock_test_questions (
  mock_test_id,
  section,
  question_number,
  question_text,
  question_image_url,
  audio_url,
  option_image_urls,
  options,
  question_score,
  correct_answer_text,
  explanation
) VALUES
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 1, '여자 :우산이 있어요?
남자 :_____________________________', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["네,우산이에요.", "아니요,우산을 써요.", "네,우산이 있어요.", "아니요,우산이 아니에요."]'::jsonb, 4, '네,우산이 있어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 2, '남자 :오늘 회사에 가요?
여자 :_____________________________', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["네,회사에 없어요.", "아니요,회사에 안 가요.", "네,회사가 아니에요.", "아니요,회사에서 일해요."]'::jsonb, 4, '아니요,회사에 안 가요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 3, '여자 :누구하고 커피를 마셨어요?
남자 :_____________________________', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["친구와 마셨어요.", "한 잔 마셨어요.", "커피숍에서 마셨어요.", "오늘 아침에 마셨어요."]'::jsonb, 3, '친구와 마셨어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 4, '여자 :이 파란색 바지 어때요?
남자 :_____________________________', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["어제 샀어요.", "아주 예뻐요.", "제 바지예요.", "오늘 입었어요."]'::jsonb, 3, '아주 예뻐요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 5, '여자 :민수 씨,저 먼저 갈게요.
남자 :_____________________________', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["잘 가요.", "고마워요.", "반가워요.", "안녕하세요."]'::jsonb, 4, '잘 가요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 6, '남자 :실례합니다.김 영수 씨 있어요?잠깐 만나러 왔는데요.
여자 :_____________________________', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["네,부탁합니다.", "네,들어오세요.", "네,그렇습니다.", "네,안녕히 가세요."]'::jsonb, 3, '네,들어오세요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 7, '남자 :뭘 드릴까요?
여자 :아침부터 머리가 아파요.약 좀 주세요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["꽃집", "약국", "문구점", "커피숍"]'::jsonb, 3, '약국', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 8, '여자 :오늘 수업은 여기까지입니다.
남자 :저,질문이 있습니다.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["공항", "시장", "빵집", "교실"]'::jsonb, 3, '교실', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 9, '남자 :실례합니다.책은 몇 권까지 빌릴 수 있어요?
여자 :다섯 권요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["미용실", "사진관", "도서관", "우체국"]'::jsonb, 3, '도서관', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 10, '여자 :우리 여기서 배드민턴 칠까요?
남자 :여기는 축구를 하는 학생들이 있으니까 저쪽으로 가요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["서점", "식당", "수영장", "운동장"]'::jsonb, 4, '운동장', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 11, '남자 :이거 비싸요?
여자 :아니요,안 비싸요.한 개에 천 원이에요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["값", "맛", "일", "집"]'::jsonb, 3, '값', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 12, '남자 :오늘 회의는 몇 시예요?
여자 :어제하고 같아요.세 시예요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["생일", "날짜", "나이", "시간"]'::jsonb, 3, '시간', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 13, '여자 :저는 요리하기를 좋아해요.민수 씨는요?
남자 :저는 시간이 있을 때마다 산에 가요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["선물", "계절", "취미", "사진"]'::jsonb, 4, '취미', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 14, '남자 :내일이 쉬는 날이에요?
여자 :네.내일은 한글날이라서 쉬어요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여행", "요일", "날씨", "휴일"]'::jsonb, 3, '휴일', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 15, '남자: 졸업 축하해요. 이 꽃 받으세요.
여자: 고마워요.
알맞은 그림을 고르십시오.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', '["__STORAGE_BASE_URL__/topik-i-35/listening/q15_option_1.png", "__STORAGE_BASE_URL__/topik-i-35/listening/q15_option_2.png", "__STORAGE_BASE_URL__/topik-i-35/listening/q15_option_3.png", "__STORAGE_BASE_URL__/topik-i-35/listening/q15_option_4.png"]'::jsonb, '["졸업식에서 남자가 여자에게 꽃을 선물합니다.", "집 앞에서 두 사람이 화분에 물을 줍니다.", "졸업식에서 사진을 찍고 있습니다.", "꽃가게에서 남자가 꽃을 사고 있습니다."]'::jsonb, 4, '졸업식에서 남자가 여자에게 꽃을 선물합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 16, '남자: (약간 멀리서) 유미 씨, 빨리 오세요.
여자: 잠깐만요. 오랜만에 자전거를 타니까 잘 못 타겠어요.
알맞은 그림을 고르십시오.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', '["__STORAGE_BASE_URL__/topik-i-35/listening/q16_option_1.png", "__STORAGE_BASE_URL__/topik-i-35/listening/q16_option_2.png", "__STORAGE_BASE_URL__/topik-i-35/listening/q16_option_3.png", "__STORAGE_BASE_URL__/topik-i-35/listening/q16_option_4.png"]'::jsonb, '["두 사람이 자전거 대신 뛰고 있습니다.", "두 사람이 한 대의 자전거를 함께 타고 있습니다.", "두 사람이 각자 자전거를 타고 있습니다.", "자전거를 수리하고 있습니다."]'::jsonb, 4, '두 사람이 각자 자전거를 타고 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 17, '여자 :돈을 찾으려고 하는데 근처에 은행이 있어요?
남자 :네.이쪽으로 쭉 가면 있어요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 돈을 찾았습니다.", "남자는 지금 은행에 있습니다.", "여자는 은행에 가려고 합니다.", "남자는 은행에 가는 길을 모릅니다."]'::jsonb, 3, '여자는 은행에 가려고 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 18, '남자 :손님,미술관으로 사진기를 가지고 들어오시면 안 됩니다.
여자 :어,몰랐어요.죄송해요.그럼 이 사진기는 어떻게 할까요?
남자 :입구에 사진기 맡기는 곳이 있습니다.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 미술관에서 일하고 있습니다.", "남자는 미술관 안을 구경하고 있습니다.", "남자는 여자에게 사진기를 빌리려고 합니다.", "여자는 사진기를 가지고 미술관에 들어갔습니다."]'::jsonb, 3, '여자는 사진기를 가지고 미술관에 들어갔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 19, '남자 :유미 씨는 요즘 주말에도 바쁜 것 같아요.
여자 :네,좀 바빠요.토요일마다 빵 만드는 걸 배우고 있어서요.
남자 :빵을 직접 만들어요?재미있겠네요.
여자 :정말 재미있어요.만드는 방법도 생각보다 어렵지 않고요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 토요일에 할 일이 없습니다.", "남자는 직접 빵을 만들어 먹습니다.", "여자는 빵 만드는 것을 좋아합니다.", "남자는 여자와 같이 빵을 만듭니다."]'::jsonb, 3, '여자는 빵 만드는 것을 좋아합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 20, '여자:(전화벨)여보세요.민우 씨,밤늦게 죄송한데요.회의 자료 좀 이메일로
보내 줄 수 있어요?
남자 :아,제가 지금 밖에 있는데요.집에 가서 바로 보내 드릴게요.
여자 :바쁘시면 다른 분께 부탁해 볼게요.
남자 :아니에요.지금 집에 가고 있어요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 지금 집에 있습니다.", "여자는 회의 자료가 필요합니다.", "여자는 다른 사람에게 연락을 했습니다.", "남자는 여자에게 회의 자료를 보냈습니다."]'::jsonb, 3, '여자는 회의 자료가 필요합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 21, '여자 :여권을 만들어야 하는데요.회사 일이 늦게 끝나서 갈 시간이 없어요.
남자 :요즘은 주말에도 여권을 신청할 수 있는 곳이 있어요.저도 주말에
거기 가서 여권을 만들었어요.
여자 :그래요?어디로 가면 돼요?
남자 :만들어 주는 데가 여러 곳 있어요.인터넷에서 찾아보고 가까운 곳
으로 가세요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 회사 일이 일찍 끝납니다.", "여자는 여권을 신청하고 싶어 합니다.", "남자는 여권을 신청하는 곳을 모릅니다.", "남자는 인터넷으로 여권을 신청합니다."]'::jsonb, 3, '여자는 여권을 신청하고 싶어 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 22, '여자 :저 다음 주부터 백화점 안에 있는 옷 가게에서 일하기로 했어요.
남자 :잘됐네요.그런데 매일 일해요?
여자 :아니요.월요일부터 금요일까지 하루에 세 시간씩만 하면 돼요.
남자 :공부와 일을 같이 하려면 힘들겠어요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["이 일은 주말에 합니다.", "이 일은 백화점에서 합니다.", "이 일은 오늘부터 시작합니다.", "이 일은 일주일에 세 시간 합니다."]'::jsonb, 3, '이 일은 백화점에서 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 23, '남자 :저 식당 음식이 정말 맛있나 봐요.
여자 :아,저기요.삼계탕만 파는 식당인데 항상 사람들이 많아요.
남자 :우리 회사 근처에 저런 유명한 식당이 있었네요.다음에 삼계탕 한번
먹으러 가야겠어요.
여자 :저 식당은 그날 준비한 걸 다 팔면 문을 닫아요.그러니까 늦게 가면
못 드실 수도 있어요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["이 식당은 메뉴가 하나입니다.", "이 식당은 회사 안에 있습니다.", "이 식당은 늦게 문을 닫습니다.", "이 식당은 손님이 별로 없습니다."]'::jsonb, 3, '이 식당은 메뉴가 하나입니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 24, '남자 :여행 가방 하나 사려고 하는데요.
여자 :(잠시 후)이 가방은 어떠세요?가볍고 튼튼해서 사람들이 많이 사요.
남자 :(잠시 후)주머니도 많아서 편하겠네요.근데 이거 말고 다른 색깔은
없어요?
여자 :있어요.여기 여러 가지 색깔이 있으니까 구경하세요.', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["이 가방은 인기가 있습니다.", "이 가방은 주머니가 없습니다.", "이 가방은 색깔이 한 가지입니다.", "이 가방은 튼튼하지만 무겁습니다."]'::jsonb, 3, '이 가방은 인기가 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 25, '여자: 자, 여러분. 호텔에 도착했습니다. 많이 피곤하시죠? 먼저 방에 가 계시면 짐들을 가져다 드리겠습니다. 식사는 지하 1층 식당에서 하시면 됩니다. 호텔에 있는 수영장은 무료로 이용하실 수 있습니다. 그리고 필요한 것이 있으면 저에게 전화해 주십시오. 제 방은 301호입니다. 그럼 편히 쉬십시오.
어떤 이야기를 하고 있는지 고르십시오.(3점)', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["부탁", "질문", "초대", "안내"]'::jsonb, 3, '안내', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 26, '여자: 자, 여러분. 호텔에 도착했습니다. 많이 피곤하시죠? 먼저 방에 가 계시면 짐들을 가져다 드리겠습니다. 식사는 지하 1층 식당에서 하시면 됩니다. 호텔에 있는 수영장은 무료로 이용하실 수 있습니다. 그리고 필요한 것이 있으면 저에게 전화해 주십시오. 제 방은 301호입니다. 그럼 편히 쉬십시오.
들은 내용과 같은 것을 고르십시오.(4점)', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["사람들은 지금 호텔 방에 있습니다.", "사람들은 짐을 직접 가지고 가야 합니다.", "수영장을 이용하려면 돈을 내야 합니다.", "도움이 필요하면 301호로 연락하면 됩니다."]'::jsonb, 4, '도움이 필요하면 301호로 연락하면 됩니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 27, '여자: 부산에 소포를 보내려고 하는데 지금 보내면 언제 도착해요?
남자: 지금 보내시면 모레 도착할 거예요.
여자: 오늘 저녁까지 도착할 수는 없을까요? 제가 좀 급해서요.
남자: 오전에 보내셨으면 오늘 안에 도착하는데 지금은 너무 늦었어요. 지금은 특급으로 보내도 내일 오전에 도착해요.
여자: 아, 그래요? 내일 오전까지 들어갈 수 있으면 그걸로 해 주세요.
두 사람이 무엇에 대해 이야기를 하고 있는지 고르십시오.(3점)', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["소포를 빨리 보내는 방법", "소포를 싸게 보내는 방법", "소포를 잘 포장하는 방법", "소포를 쉽게 보내는 방법"]'::jsonb, 3, '소포를 빨리 보내는 방법', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 28, '여자: 부산에 소포를 보내려고 하는데 지금 보내면 언제 도착해요?
남자: 지금 보내시면 모레 도착할 거예요.
여자: 오늘 저녁까지 도착할 수는 없을까요? 제가 좀 급해서요.
남자: 오전에 보내셨으면 오늘 안에 도착하는데 지금은 너무 늦었어요. 지금은 특급으로 보내도 내일 오전에 도착해요.
여자: 아, 그래요? 내일 오전까지 들어갈 수 있으면 그걸로 해 주세요.
들은 내용과 같은 것을 고르십시오.(4점)', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 부산에서 소포를 보냅니다.", "여자는 빨리 소포를 받고 싶어 합니다.", "여자는 소포를 특급으로 보낼 겁니다.", "여자는 내일 오전에 소포를 받을 겁니다."]'::jsonb, 4, '여자는 소포를 특급으로 보낼 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 29, '여자: 민수 씨, 이번 주말에 ‘사랑나누기’ 모임이 있는데 같이 가실래요?
남자: ‘사랑나누기’요? 그게 뭐예요?
여자: 혼자 사시는 할머니들을 도와 드리는 모임이에요.
남자: 아, 그래요? 근데 무슨 일을 도와 드려요?
여자: 청소를 하거나 음식을 만들어 드려요. 이번 주말엔 김치를 담가서 드릴 거예요.
남자: 좋은 일을 하시네요. 저도 이번 모임에 가 보고 싶어요. 김치를 담가 본 적은 없지만 열심히 해 볼게요.
두 사람은 왜 김치를 만듭니까?(3점)', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["할머니들께 드리고 싶어서", "할머니들과 같이 먹고 싶어서", "김치를 한번 담가 보고 싶어서", "김치를 혼자 담그기가 힘들어서"]'::jsonb, 3, '할머니들께 드리고 싶어서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'listening', 30, '여자: 민수 씨, 이번 주말에 ‘사랑나누기’ 모임이 있는데 같이 가실래요?
남자: ‘사랑나누기’요? 그게 뭐예요?
여자: 혼자 사시는 할머니들을 도와 드리는 모임이에요.
남자: 아, 그래요? 근데 무슨 일을 도와 드려요?
여자: 청소를 하거나 음식을 만들어 드려요. 이번 주말엔 김치를 담가서 드릴 거예요.
남자: 좋은 일을 하시네요. 저도 이번 모임에 가 보고 싶어요. 김치를 담가 본 적은 없지만 열심히 해 볼게요.
들은 내용과 같은 것을 고르십시오.(4점)', NULL, '__STORAGE_BASE_URL__/topik-i-35/audio/35-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 이 모임에 간 적이 있습니다.", "남자는 이번 주말에 모임에 갈 겁니다.", "이 모임에서는 할머니들이 음식을 만듭니다.", "이 모임에서는 이번 주말에 청소를 할 겁니다."]'::jsonb, 4, '남자는 이번 주말에 모임에 갈 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 31, '저는 김민수입니다.이 사람은 제임스입니다.', NULL, NULL, NULL, '["시간", "장소", "이름", "주말"]'::jsonb, 2, '이름', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 32, '불고기를 먹습니다.맛있습니다.', NULL, NULL, NULL, '["쇼핑", "사람", "노래", "음식"]'::jsonb, 2, '음식', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 33, '선생님을 만납니다.공부를 합니다.', NULL, NULL, NULL, '["학교", "요일", "취미", "날짜"]'::jsonb, 2, '학교', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 34, '몇 시( )옵니까?', NULL, NULL, NULL, '["가", "는", "를", "에"]'::jsonb, 2, '에', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 35, '( )에 갑니다.우유를 삽니다.', NULL, NULL, NULL, '["가게", "교실", "은행", "서점"]'::jsonb, 2, '가게', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 36, '저는 한국어 선생님입니다.한국어를 ( ).', NULL, NULL, NULL, '["줍니다", "모릅니다", "가르칩니다", "일어납니다"]'::jsonb, 2, '가르칩니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 37, '요즘 일이 ( ).바쁩니다.', NULL, NULL, NULL, '["비쌉니다", "작습니다", "많습니다", "나쁩니다"]'::jsonb, 3, '많습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 38, '산을 좋아합니다.그래서 등산을 ( )합니다.', NULL, NULL, NULL, '["자주", "제일", "아주", "아까"]'::jsonb, 3, '자주', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 39, '머리가 깁니다.그래서 ( )싶습니다.', NULL, NULL, NULL, '["자르고", "나오고", "가지고", "마시고"]'::jsonb, 2, '자르고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 40, '"1년 사용한 컴퓨터를 팔아요."
가격: 100,000원
연락처: study@Korea.co.kr
맞지 않는 것을 고르십시오.', '__STORAGE_BASE_URL__/topik-i-35/reading/q40.png', NULL, NULL, '["이 컴퓨터는 십만 원입니다.", "이 컴퓨터를 1년 동안 썼습니다.", "이 사람은 컴퓨터를 받고 싶습니다.", "컴퓨터를 사고 싶으면 이메일로 연락합니다."]'::jsonb, 3, '이 사람은 컴퓨터를 받고 싶습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 41, '민수 씨,
제 동생이 왔어요.
그래서 지금 회사 앞 커피숍에 있어요.
1시에 회사에 가겠습니다. ^^
지현 드림
맞지 않는 것을 고르십시오.', '__STORAGE_BASE_URL__/topik-i-35/reading/q41.png', NULL, NULL, '["지현 씨의 동생이 왔습니다.", "커피숍은 회사 안에 있습니다.", "지현 씨는 한 시에 회사에 갑니다.", "지현 씨는 민수 씨에게 메시지를 썼습니다."]'::jsonb, 3, '커피숍은 회사 안에 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 42, '행복음악회
음악회에 초대합니다.
기간: 2014년 8월 1일 ~ 8월 31일
일시: 매주 토요일 오후 8시
장소: 하늘공원
맞지 않는 것을 고르십시오.', '__STORAGE_BASE_URL__/topik-i-35/reading/q42.png', NULL, NULL, '["하늘공원에서 음악회를 합니다.", "토요일마다 음악회가 있습니다.", "이 음악회는 한 달 동안 합니다.", "이 음악회는 일곱 시에 시작합니다."]'::jsonb, 3, '이 음악회는 일곱 시에 시작합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 43, '저는 매일 아침 산책을 하고 학교에 갑니다.학생 식당에서 아침을 먹고
수업을 듣습니다.그리고 커피숍에서 아르바이트를 합니다.', NULL, NULL, NULL, '["저는 아침마다 산책을 합니다.", "저는 아침을 먹고 학교에 갑니다.", "저는 아르바이트를 하고 학교에 갑니다.", "저는 학생 식당에서 아르바이트를 합니다."]'::jsonb, 3, '저는 아침마다 산책을 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 44, '다음 주 월요일에 수학 시험이 있습니다.그 시험은 아주 어렵습니다.
그래서 날마다 도서관에 가서 공부합니다.', NULL, NULL, NULL, '["저는 수학을 좋아합니다.", "저는 요즘 열심히 공부합니다.", "이번 주에 수학 시험이 있습니다.", "저는 월요일마다 어려운 시험이 있습니다."]'::jsonb, 2, '저는 요즘 열심히 공부합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 45, '친구가 지난달에 고향으로 돌아갔습니다.친구는 저에게 냉장고를 주었
습니다.그 냉장고는 커서 좋습니다.', NULL, NULL, NULL, '["저는 냉장고를 샀습니다.", "저는 이 냉장고가 마음에 듭니다.", "저는 고향에 큰 냉장고가 있습니다.", "저는 친구에게 냉장고를 주었습니다."]'::jsonb, 3, '저는 이 냉장고가 마음에 듭니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 46, '저는 극장에 가지 않고 집에서 혼자 영화를 봅니다.집에서 영화를 보면
누워서 볼 수 있습니다.그리고 보고 싶은 시간에 볼 수 있습니다.', NULL, NULL, NULL, '["저는 극장에 자주 갑니다.", "저는 친구와 영화를 봅니다.", "저는 극장에서 영화를 봅니다.", "저는 집에서 영화 보는 것을 좋아합니다."]'::jsonb, 3, '저는 집에서 영화 보는 것을 좋아합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 47, '시간이 없어서 일을 다 하지 못했습니다.그래서 지현 씨가 저를 도와
주었습니다.저는 지현 씨에게 커피를 사 주었습니다.', NULL, NULL, NULL, '["저는 일을 많이 합니다.", "저는 커피를 좋아합니다.", "저는 지현 씨가 고마웠습니다.", "저는 지현 씨를 도와주었습니다."]'::jsonb, 3, '저는 지현 씨가 고마웠습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 48, '이번 주말에 제가 좋아하는 가수의 공연이 있습니다.저는 두 달 전에
표를 미리 샀습니다.공연을 빨리 보고 싶습니다.', NULL, NULL, NULL, '["저는 표를 사고 싶습니다.", "저는 가수가 되고 싶습니다.", "저는 공연을 기다리고 있습니다.", "저는 두 달 전에 공연을 봤습니다."]'::jsonb, 2, '저는 공연을 기다리고 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 49, '제 친구는 그림 그리는 것을 좋아합니다. 그래서 시간이 있을 때마다 종이컵에 그림을 그립니다. 그리고 친한 사람들에게 종이컵을 선물합니다. (㉠) 종이컵은 세상에 하나만 있습니다. 친구의 종이컵은 참 예쁩니다.
㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["친구가 산", "친구가 만든", "사람들이 선물한", "사람들이 버리는"]'::jsonb, 2, '친구가 만든', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 50, '제 친구는 그림 그리는 것을 좋아합니다. 그래서 시간이 있을 때마다 종이컵에 그림을 그립니다. 그리고 친한 사람들에게 종이컵을 선물합니다. (㉠) 종이컵은 세상에 하나만 있습니다. 친구의 종이컵은 참 예쁩니다.
이 글의 내용과 같은 것을 고르십시오.', NULL, NULL, NULL, '["친구는 종이로 컵을 만듭니다.", "친구는 예쁜 종이컵을 받았습니다.", "친구는 친한 사람들과 그림을 그립니다.", "친구는 종이컵에 예쁘게 그림을 그립니다."]'::jsonb, 3, '친구는 종이컵에 예쁘게 그림을 그립니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 51, '몇 십 년 후에는 자동차가 하늘로 다닐 것입니다. 그러면 그 자동차를 만드는 사람이 필요합니다. 그리고 하늘에 자동차가 있으면 하늘에서 일하는 교통경찰도 있어야 합니다. 지금은 이런 사람들을 (㉠) 없습니다. 하지만 앞으로는 이런 사람들을 자주 볼 수 있을 것입니다.
㉠에 들어갈 알맞은 말을 고르십시오.(3점)', NULL, NULL, NULL, '["만날 수", "보낼 수", "가르칠 수", "기다릴 수"]'::jsonb, 3, '만날 수', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 52, '몇 십 년 후에는 자동차가 하늘로 다닐 것입니다. 그러면 그 자동차를 만드는 사람이 필요합니다. 그리고 하늘에 자동차가 있으면 하늘에서 일하는 교통경찰도 있어야 합니다. 지금은 이런 사람들을 (㉠) 없습니다. 하지만 앞으로는 이런 사람들을 자주 볼 수 있을 것입니다.
무엇에 대한 이야기인지 고르십시오.(2점)', NULL, NULL, NULL, '["미래의 집", "미래의 직업", "내가 만든 자동차", "내가 좋아하는 자동차"]'::jsonb, 2, '미래의 직업', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 53, '저는 아침에 일어나서 혼자 운동을 합니다. 운동을 하면 즐겁습니다. 그런데 아침에 (㉠) 일어나는 것이 힘들어서 가끔 운동을 못 합니다. 그래서 다음 주부터는 저녁에 친구와 같이 운동을 하기로 했습니다. 이제 매일 운동을 할 것 같습니다.
㉠에 들어갈 알맞은 말을 고르십시오.(2점)', NULL, NULL, NULL, '["많이", "잠깐", "늦게", "일찍"]'::jsonb, 2, '일찍', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 54, '저는 아침에 일어나서 혼자 운동을 합니다. 운동을 하면 즐겁습니다. 그런데 아침에 (㉠) 일어나는 것이 힘들어서 가끔 운동을 못 합니다. 그래서 다음 주부터는 저녁에 친구와 같이 운동을 하기로 했습니다. 이제 매일 운동을 할 것 같습니다.
이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["이 사람은 저녁에 운동을 했습니다.", "이 사람은 아침마다 친구를 만납니다.", "이 사람은 친구와 운동을 할 것입니다.", "이 사람은 친구와 약속을 하려고 합니다."]'::jsonb, 3, '이 사람은 친구와 운동을 할 것입니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 55, '저는 안경이 여러 개 있습니다. 그래서 그때그때 다른 안경을 씁니다. 사람을 처음 만날 때는 부드러운 느낌의 안경을 씁니다. 운동을 할 때는 가벼운 안경을 씁니다. (㉠) 멋있게 보이고 싶을 때는 유행하는 안경을 씁니다. 이렇게 안경을 바꿔서 쓰면 기분이 좋아집니다.
㉠에 들어갈 알맞은 말을 고르십시오.(2점)', NULL, NULL, NULL, '["그러면", "그래서", "그리고", "그러니까"]'::jsonb, 2, '그리고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 56, '저는 안경이 여러 개 있습니다. 그래서 그때그때 다른 안경을 씁니다. 사람을 처음 만날 때는 부드러운 느낌의 안경을 씁니다. 운동을 할 때는 가벼운 안경을 씁니다. (㉠) 멋있게 보이고 싶을 때는 유행하는 안경을 씁니다. 이렇게 안경을 바꿔서 쓰면 기분이 좋아집니다.
이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["저는 안경이 한 개 있습니다.", "저는 유행하는 안경이 있습니다.", "저는 운동을 할 때 안경을 안 씁니다.", "저는 사람을 만날 때 안경을 벗습니다."]'::jsonb, 3, '저는 유행하는 안경이 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 57, '(가)모든 동물은 잠을 잡니다.
(나)하지만 개나 고양이는 열 시간쯤 잡니다.
(다)말은 하루에 세 시간만 자도 괜찮습니다.
(라)그런데 잠을 자는 시간은 동물마다 다릅니다.', NULL, NULL, NULL, '["(가)－(나)－(다)－(라)", "(가)－(다)－(나)－(라)", "(가)－(라)－(나)－(다)", "(가)－(라)－(다)－(나)"]'::jsonb, 2, '(가)－(라)－(다)－(나)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 58, '(가)우리 고향에는 딸기가 많이 납니다.
(나)그래서 딸기가 많은 4월에 축제를 합니다.
(다)그리고 맛있는 딸기를 시장보다 싸게 살 수 있습니다.
(라)이 축제에서는 딸기로 여러 가지 음식을 만들어 볼 수 있습니다.', NULL, NULL, NULL, '["(가)－(나)－(다)－(라)", "(가)－(나)－(라)－(다)", "(가)－(다)－(나)－(라)", "(가)－(라)－(나)－(다)"]'::jsonb, 3, '(가)－(나)－(라)－(다)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 59, '라면은 맛있지만 소금이 많이 들어 있어서 건강에 나쁩니다. (㉠) 라면의 소금은 보통 국물을 만드는 스프에 있습니다. (㉡) 그래도 국물을 먹고 싶으면 스프를 조금만 넣습니다. (㉢) 그리고 라면을 끓일 때 스프를 늦게 넣는 것도 소금을 덜 먹는 또 하나의 방법입니다. (㉣)
다음 문장이 들어갈 곳을 고르십시오.(2점)
그래서 소금을 적게 먹으려면 라면 국물을 먹지 않는 게 좋습니다.', NULL, NULL, NULL, '["㉠", "㉡", "㉢", "㉣"]'::jsonb, 2, '㉡', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 60, '라면은 맛있지만 소금이 많이 들어 있어서 건강에 나쁩니다. (㉠) 라면의 소금은 보통 국물을 만드는 스프에 있습니다. (㉡) 그래도 국물을 먹고 싶으면 스프를 조금만 넣습니다. (㉢) 그리고 라면을 끓일 때 스프를 늦게 넣는 것도 소금을 덜 먹는 또 하나의 방법입니다. (㉣)
이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["라면은 건강에 좋은 음식입니다.", "스프를 많이 넣으면 건강에 좋습니다.", "스프를 먼저 넣으면 소금을 많이 먹게 됩니다.", "라면의 소금을 적게 먹는 방법은 한 가지입니다."]'::jsonb, 3, '스프를 먼저 넣으면 소금을 많이 먹게 됩니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 61, '지금은 동전과 지폐를 모두 사용합니다. 하지만 전에는 동전만 사용했습니다. 종이로 만든 지폐는 쉽게 찢어지고 더러워져서 (㉠) 못합니다. 그리고 가짜 돈을 만들기도 쉽습니다. 그래서 동전보다 지폐를 늦게 사용한 것입니다.
㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["오래 쓰지", "가끔 내지", "자주 만들지", "계속 나오지"]'::jsonb, 2, '오래 쓰지', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 62, '지금은 동전과 지폐를 모두 사용합니다. 하지만 전에는 동전만 사용했습니다. 종이로 만든 지폐는 쉽게 찢어지고 더러워져서 (㉠) 못합니다. 그리고 가짜 돈을 만들기도 쉽습니다. 그래서 동전보다 지폐를 늦게 사용한 것입니다.
이 글의 내용과 같은 것을 고르십시오.', NULL, NULL, NULL, '["지폐는 잘 더러워집니다.", "옛날에도 지폐를 사용했습니다.", "지폐가 동전보다 먼저 나왔습니다.", "동전은 가짜 돈을 만들기 쉽습니다."]'::jsonb, 3, '지폐는 잘 더러워집니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 63, '받는사람: sarang@parang.com; koreal@empan.com; minsu@bola.com; ok1213@maver.com; tree@maver.com
제목: 유학생 농구 대회
보낸사람: yumi@parang.com

농구 대회에 참가 신청을 해 주셔서 감사합니다.
이번 주 토요일 오전 10시에 운동장에서 대회가 시작됩니다.
경기에 참가하는 선수들은 9시까지 와 주시기 바랍니다.
비가 오면 학생회관 옆에 있는 체육관에서 경기를 하겠습니다.
그럼, 토요일에 뵙겠습니다.
학생회장 김유미 올림
유미 씨는 왜 이 글을 썼습니까?', '__STORAGE_BASE_URL__/topik-i-35/reading/q63_64.png', NULL, NULL, '["대회 날짜를 바꾸려고", "대회 참가 신청을 받으려고", "대회 참가 신청을 취소하려고", "대회 시간과 장소를 알려 주려고"]'::jsonb, 2, '대회 시간과 장소를 알려 주려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 64, '받는사람: sarang@parang.com; koreal@empan.com; minsu@bola.com; ok1213@maver.com; tree@maver.com
제목: 유학생 농구 대회
보낸사람: yumi@parang.com

농구 대회에 참가 신청을 해 주셔서 감사합니다.
이번 주 토요일 오전 10시에 운동장에서 대회가 시작됩니다.
경기에 참가하는 선수들은 9시까지 와 주시기 바랍니다.
비가 오면 학생회관 옆에 있는 체육관에서 경기를 하겠습니다.
그럼, 토요일에 뵙겠습니다.
학생회장 김유미 올림
이 글의 내용과 같은 것을 고르십시오.', '__STORAGE_BASE_URL__/topik-i-35/reading/q63_64.png', NULL, NULL, '["체육관은 운동장 옆에 있습니다.", "비가 오면 농구 대회를 하지 않습니다.", "농구 대회 참가자는 10시까지 와야 합니다.", "날씨가 좋으면 운동장에서 농구 대회를 할 겁니다."]'::jsonb, 3, '날씨가 좋으면 운동장에서 농구 대회를 할 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 65, '식혜는 한국의 전통 음료수입니다. 보통 모임이나 잔치에서 (㉠) 식혜를 마십니다. 이것은 식혜가 소화를 도와주기 때문입니다. 식혜는 달고 맛있어서 많은 사람들이 좋아합니다. 시원하게 마시면 더 좋습니다. 저는 식혜를 만드는 방법이 간단해서 자주 만들어 먹습니다. 하지만 만드는 데 시간이 오래 걸립니다.
㉠에 들어갈 알맞은 말을 고르십시오.(2점)', NULL, NULL, NULL, '["운동을 한 후에", "음식을 먹은 후에", "모임에 가기 전에", "음료수를 마시기 전에"]'::jsonb, 2, '음식을 먹은 후에', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 66, '식혜는 한국의 전통 음료수입니다. 보통 모임이나 잔치에서 (㉠) 식혜를 마십니다. 이것은 식혜가 소화를 도와주기 때문입니다. 식혜는 달고 맛있어서 많은 사람들이 좋아합니다. 시원하게 마시면 더 좋습니다. 저는 식혜를 만드는 방법이 간단해서 자주 만들어 먹습니다. 하지만 만드는 데 시간이 오래 걸립니다.
이 글의 내용과 같은 것을 고르십시오.(3점)', NULL, NULL, NULL, '["식혜는 빨리 만들 수 있습니다.", "식혜는 달아서 사람들이 싫어합니다.", "식혜는 차갑게 마시면 더 맛있습니다.", "모임이나 잔치에 가면 식혜를 만듭니다."]'::jsonb, 3, '식혜는 차갑게 마시면 더 맛있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 67, '문제를 풀기 어려울 때는 책상 앞에만 앉아 있지 마십시오. 계속 앉아 있으면 좋은 생각이 (㉠) 않습니다. 그럴 때는 일어나서 걷는 것이 좋습니다. 걸으려고 꼭 밖으로 (㉡). 집 안도 좋고 사무실 안도 괜찮습니다.
㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["나지", "많지", "없어지지", "달라지지"]'::jsonb, 2, '나지', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 68, '문제를 풀기 어려울 때는 책상 앞에만 앉아 있지 마십시오. 계속 앉아 있으면 좋은 생각이 (㉠) 않습니다. 그럴 때는 일어나서 걷는 것이 좋습니다. 걸으려고 꼭 밖으로 (㉡). 집 안도 좋고 사무실 안도 괜찮습니다.
㉡에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["나가려고 합니다", "나갈 수 있습니다", "나가지 않아도 됩니다", "나가지 않기로 합니다"]'::jsonb, 2, '나가지 않아도 됩니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 69, '우리 가족은 (㉠) 적이 없습니다. 그래서 저는 그동안 할머니께서 노래를 좋아하는 것을 몰랐습니다. 그런데 어젯밤에 할머니께서 공연 초대장을 주셨습니다. 그 공연에서 할머니가 노래를 하실 것입니다. 우리 가족은 공연에 가려고 합니다. 거기에서 할머니의 노래를 처음 듣게 될 것입니다.
㉠에 들어갈 알맞은 말을 고르십시오.', NULL, NULL, NULL, '["할머니와 공연을 한", "할머니와 공연을 본", "할머니와 노래를 배운", "할머니의 노래를 들은"]'::jsonb, 3, '할머니의 노래를 들은', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 35 ORDER BY created_at DESC LIMIT 1), 'reading', 70, '우리 가족은 (㉠) 적이 없습니다. 그래서 저는 그동안 할머니께서 노래를 좋아하는 것을 몰랐습니다. 그런데 어젯밤에 할머니께서 공연 초대장을 주셨습니다. 그 공연에서 할머니가 노래를 하실 것입니다. 우리 가족은 공연에 가려고 합니다. 거기에서 할머니의 노래를 처음 듣게 될 것입니다.
이 글의 내용으로 알 수 있는 것은 무엇입니까?', NULL, NULL, NULL, '["할머니는 노래 부르기를 좋아하십니다.", "우리 가족은 함께 노래 연습을 했습니다.", "할머니는 가끔 우리를 공연에 초대하십니다.", "우리 가족은 할머니의 공연을 보러 갔습니다."]'::jsonb, 3, '할머니는 노래 부르기를 좋아하십니다.', NULL);

COMMIT;
