-- Generated by scripts/generate_topik_64_sql.mjs
BEGIN;

INSERT INTO mock_test_bank (
  title, exam_type, test_number, description, total_questions, duration, listening_questions, reading_questions
)
SELECT
  'TOPIK I 64-р шалгалт',
  'TOPIK_I',
  64,
  '64-р албан ёсны TOPIK I шалгалт',
  70,
  100,
  30,
  40
WHERE NOT EXISTS (
  SELECT 1 FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64
);

UPDATE mock_test_bank
SET
  title = 'TOPIK I 64-р шалгалт',
  description = '64-р албан ёсны TOPIK I шалгалт',
  total_questions = 70,
  duration = 100,
  listening_questions = 30,
  reading_questions = 40,
  updated_at = NOW()
WHERE id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1);

DELETE FROM mock_test_questions WHERE mock_test_id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1);

INSERT INTO mock_test_questions (
  mock_test_id,
  section,
  question_number,
  question_text,
  question_image_url,
  audio_url,
  option_image_urls,
  options,
  question_score,
  correct_answer_text,
  explanation
) VALUES
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 1, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

남자: 책을 읽어요?
여자: 네, 책을 읽어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["네, 책이 없어요.","네, 책을 읽어요.","아니요, 책이 많아요.","아니요, 책을 좋아해요."]'::jsonb, 4, '네, 책을 읽어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 2, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

여자: 구두가 커요?
남자: 아니요, 구두가 있어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["네, 구두예요.","네, 구두가 예뻐요.","아니요, 구두가 작아요.","아니요, 구두가 있어요."]'::jsonb, 4, '아니요, 구두가 작아요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 3, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

남자: 지금 뭐 먹어요?
여자: 김밥을 먹어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["자주 먹어요.","집에서 먹어요.","김밥을 먹어요.","언니하고 먹어요."]'::jsonb, 3, '김밥을 먹어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 4, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

여자: 친구를 몇 시에 만나요?
남자: 두 시에 만나요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["세 명이에요.","친구 집에 가요.","같이 숙제해요.","두 시에 만나요."]'::jsonb, 3, '두 시에 만나요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 5, '다음을 듣고 〈보기〉와 같이 이어지는 말을 고르십시오.

남자: 수미 씨, 연필 좀 주세요.
여자: 여기 있어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["괜찮아요.","반가워요.","여기 있어요.","잘 지냈어요."]'::jsonb, 4, '여기 있어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 6, '다음을 듣고 〈보기〉와 같이 이어지는 말을 고르십시오.

여자: 오늘 도와줘서 고마웠어요.
남자: 아니에요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["미안해요.","아니에요.","부탁해요.","좋겠어요."]'::jsonb, 3, '아니에요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 7, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 뭘 드릴까요?
남자: 장미가 예쁘네요. 장미 주세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["꽃집","식당","교실","약국"]'::jsonb, 3, '꽃집', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 8, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 어서 오세요, 손님. 어디까지 가세요?
여자: 한국대학교로 가 주세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["공항","택시","우체국","백화점"]'::jsonb, 3, '택시', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 9, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 방은 5층이고요, 501호입니다.
남자: 네. 아침 식사 시간은 언제예요?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["호텔","회사","극장","빵집"]'::jsonb, 3, '호텔', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 10, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 저 여기 산책하러 자주 오는데 참 좋지요?
여자: 네. 나무도 많고 넓어서 좋네요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["서점","공원","사진관","미용실"]'::jsonb, 4, '공원', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 11, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 아주머니, 이 음식 매워요?
여자: 네, 조금 매워요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["일","맛","시간","이름"]'::jsonb, 3, '맛', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 12, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 민수 씨, 야구를 좋아해요?
남자: 아니요. 저는 축구가 좋아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["나라","장소","날짜","운동"]'::jsonb, 3, '운동', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 13, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 저는 방학 때 제주도에 갈 거예요. 수미 씨는요?
여자: 저는 고향에 갈 거예요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["계획","날씨","주말","취미"]'::jsonb, 4, '계획', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 14, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 저, 행복마트가 어디에 있어요?
남자: 저기 은행 있지요? 은행 뒤로 가세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["약속","교통","위치","소개"]'::jsonb, 3, '위치', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 15, '다음을 듣고 가장 알맞은 그림을 고르십시오.

여자: 어디가 아파서 오셨어요?
남자: 어제부터 계속 배가 아파서요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/listening/q15_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/listening/q15_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/listening/q15_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/listening/q15_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 4, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 16, '다음을 듣고 가장 알맞은 그림을 고르십시오.

남자: 식탁이 무거운데 같이 좀 들어 줄래요?
여자: 네. 제가 여기를 들게요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/listening/q16_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/listening/q16_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/listening/q16_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/listening/q16_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 4, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 17, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

남자: 수미 씨, 내일 출장 가지요? 잘 다녀오세요.
여자: 아침에는 회사에 올 거예요. 저녁에 출발해요.
남자: 아, 그래요? 그럼 내일 봐요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 출장을 갑니다.","여자는 아침에 출발합니다.","여자는 내일 회사에 안 갑니다.","남자는 내일 여자를 만날 겁니다."]'::jsonb, 3, '남자는 내일 여자를 만날 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 18, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

여자: 저, 식빵은 없어요?
남자: 네. 다 팔려서 지금 다시 만들고 있습니다.
여자: 그럼 언제쯤 오면 돼요?
남자: 세 시쯤 오시면 됩니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 식빵을 못 샀습니다.","남자는 여자에게 빵을 줬습니다.","여자는 이 곳에 세 시에 왔습니다.","남자는 지금 빵집에 다녀올 겁니다."]'::jsonb, 3, '여자는 식빵을 못 샀습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 19, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

남자: 수미 씨, 미영 씨 결혼식이 일곱 시지요? 이제 가야겠어요.
여자: 네. 그런데 우리 어떻게 갈까요? 차를 가지고 갈까요?
남자: 거기 너무 복잡하니까 지하철로 가는 게 어때요?
여자: 그래요. 길이 막힐 수도 있으니까 지하철로 가요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 혼자 결혼식에 갈 겁니다.","여자는 일곱 시에 남자를 만날 겁니다.","여자는 지하철로 결혼식장에 갈 겁니다.","남자는 결혼식에 차를 가지고 갈 겁니다."]'::jsonb, 3, '여자는 지하철로 결혼식장에 갈 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 20, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

여자: 손님, 식사 맛있게 하셨어요?
남자: 네, 맛있었어요. 얼마예요?
여자: 이만 원입니다. 인터넷으로 예약을 하셔서 오천 원 할인되었습니다.
남자: 네, 이 카드로 계산해 주세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 지금 카드가 없습니다.","남자는 인터넷으로 예약했습니다.","여자는 이 식당에 처음 왔습니다.","여자는 남자와 같이 식사를 했습니다."]'::jsonb, 3, '남자는 인터넷으로 예약했습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 21, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

여자: 민수 씨, 아르바이트할 곳을 찾았어요?
남자: 아니요. 아직 못 찾았어요.
여자: 제가 일하는 박물관에서 아르바이트할 사람을 찾고 있는데, 생각 있어요?
남자: 박물관 아르바이트는 안 해 봤는데 한번 해 보고 싶네요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 남자와 같은 일을 합니다.","여자는 박물관에서 일하고 있습니다.","남자는 박물관에서 일을 해 봤습니다.","남자는 아르바이트를 안 하려고 합니다."]'::jsonb, 3, '여자는 박물관에서 일하고 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 22, '다음을 듣고 여자의 중심 생각을 고르십시오.

여자: 민수 씨, 이 영화 봤어요? 정말 재미있어요. 꼭 보세요.
남자: 아, 이 영화요? 저는 나중에 집에서 보려고요.
여자: 이 영화는 영화관에서 크게 봐야 돼요. 안 그러면 재미없어요.
남자: 그래요? 그럼 저도 가서 봐야겠어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["재미있는 영화를 보고 싶습니다.","영화는 여러 번 봐도 재미있습니다.","이 영화는 많은 사람이 봐야 합니다.","이 영화는 영화관에서 보는 게 좋습니다."]'::jsonb, 3, '이 영화는 영화관에서 보는 게 좋습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 23, '다음을 듣고 여자의 중심 생각을 고르십시오.

남자: 무엇을 도와 드릴까요?
여자: 제가 지금 영어 수업을 들었는데 혹시 다른 반은 없어요?
남자: 왜 그러세요? 무슨 문제가 있으세요?
여자: 네. 좀 어려워서요. 다른 수업을 들었으면 좋겠어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["반이 더 많아져야 합니다.","쉬운 수업을 듣고 싶습니다.","수업을 더 듣는 것이 좋습니다.","영어 수업이 많이 도움이 됩니다."]'::jsonb, 3, '쉬운 수업을 듣고 싶습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 24, '다음을 듣고 여자의 중심 생각을 고르십시오.

남자: 수미 씨, 이거 주스 병 아니에요?
여자: 네. 주스 병을 버리지 않고 꽃병으로 쓰고 있어요.
남자: 전 이런 생각 못 했는데 이렇게 하면 쓰레기도 안 생기고 좋겠네요.
여자: 맞아요. 생각해 보면 버리지 않고 다시 쓸 수 있는 게 많아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["쓰레기를 모아서 버려야 합니다.","물건을 많이 살 필요가 없습니다.","쓰레기를 버리는 곳이 많이 필요합니다.","물건을 안 버리고 다시 쓰는 게 좋습니다."]'::jsonb, 3, '물건을 안 버리고 다시 쓰는 게 좋습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 25, '여자가 왜 이 이야기를 하고 있는지 고르십시오.

여자: (딩동댕) 잠시 안내 말씀 드립니다. 다음 달에 열리는 ''회사 사랑 걷기 대회''의 참가 신청이 이번 주 금요일까지입니다. 그런데 아직 신청을 하신 분이 많지 않습니다. 올해는 특히 많은 선물이 준비되어 있으니 많이 참가해 주시기 바랍니다. 자세한 내용은 홈페이지를 확인해 주세요. (댕동딩)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["신청을 더 받으려고","신청 방법이 바뀌어서","대회 내용을 설명하려고","대회 날짜를 알려 주려고"]'::jsonb, 3, '신청을 더 받으려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 26, '들은 내용과 같은 것을 고르십시오.

여자: (딩동댕) 잠시 안내 말씀 드립니다. 다음 달에 열리는 ''회사 사랑 걷기 대회''의 참가 신청이 이번 주 금요일까지입니다. 그런데 아직 신청을 하신 분이 많지 않습니다. 올해는 특히 많은 선물이 준비되어 있으니 많이 참가해 주시기 바랍니다. 자세한 내용은 홈페이지를 확인해 주세요. (댕동딩)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["이 대회는 이번 달에 합니다.","홈페이지에 대회 내용이 없습니다.","금요일까지 참가 신청을 할 수 있습니다.","이 대회에 참가 신청을 한 사람이 많습니다."]'::jsonb, 4, '금요일까지 참가 신청을 할 수 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 27, '두 사람이 무엇에 대해 이야기를 하고 있는지 고르십시오.

여자: 민수 씨, 어제 드라마 ''첫사랑'' 봤어요? 거기에서 두 사람이 어떤 섬에 갔는데 정말 아름다웠어요.
남자: 아, 저도 그거 봤어요. 거기 제가 작년 여름휴가 때 간 곳이에요.
여자: 정말요? 그 섬이 어디예요?
남자: 여수에 있는 섬인데, 경치가 아름다워서 드라마에 자주 나와요.
여자: 아, 그래요? 저도 다음에 한번 가 보고 싶어요.
남자: 가기 전에 궁금한 거 있으면 물어보세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["인기 있는 드라마","기억에 남는 여행","원하는 휴가 기간","드라마에 나온 장소"]'::jsonb, 3, '드라마에 나온 장소', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 28, '들은 내용과 같은 것을 고르십시오.

여자: 민수 씨, 어제 드라마 ''첫사랑'' 봤어요? 거기에서 두 사람이 어떤 섬에 갔는데 정말 아름다웠어요.
남자: 아, 저도 그거 봤어요. 거기 제가 작년 여름휴가 때 간 곳이에요.
여자: 정말요? 그 섬이 어디예요?
남자: 여수에 있는 섬인데, 경치가 아름다워서 드라마에 자주 나와요.
여자: 아, 그래요? 저도 다음에 한번 가 보고 싶어요.
남자: 가기 전에 궁금한 거 있으면 물어보세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 작년 여름에 섬에 갔습니다.","여자는 어제 드라마를 못 봤습니다.","남자는 여수에 가 본 적이 없습니다.","여자는 여수에서 휴가를 보냈습니다."]'::jsonb, 4, '남자는 작년 여름에 섬에 갔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 29, '남자가 그림을 배우게 된 이유를 고르십시오.

여자: 영화배우 김민수 씨, 요즘은 그림도 그리고 계시는데요. 언제부터 그림을 그리셨어요?
남자: 3년 전에 영화에서 화가 역할을 한 적이 있어요. 직접 그림을 그려야 해서 배우게 됐는데, 지금까지 취미로 그리고 있어요.
여자: 그렇군요. 주로 어떤 그림을 그리세요?
남자: 처음엔 산을 많이 그렸는데 요즘은 사람들의 얼굴을 그리고 있어요.
여자: 곧 첫 번째 전시회를 하신다고요?
남자: 네. 같이 그림 그리는 친구들과 전시회를 하기로 했어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["새로운 취미를 갖고 싶어서","그림을 보면 기분이 좋아져서","좋아하는 사람을 그리고 싶어서","영화에서 화가 역할을 하게 되어서"]'::jsonb, 3, '영화에서 화가 역할을 하게 되어서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 30, '들은 내용과 같은 것을 고르십시오.

여자: 영화배우 김민수 씨, 요즘은 그림도 그리고 계시는데요. 언제부터 그림을 그리셨어요?
남자: 3년 전에 영화에서 화가 역할을 한 적이 있어요. 직접 그림을 그려야 해서 배우게 됐는데, 지금까지 취미로 그리고 있어요.
여자: 그렇군요. 주로 어떤 그림을 그리세요?
남자: 처음엔 산을 많이 그렸는데 요즘은 사람들의 얼굴을 그리고 있어요.
여자: 곧 첫 번째 전시회를 하신다고요?
남자: 네. 같이 그림 그리는 친구들과 전시회를 하기로 했어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/audio/64-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 요즘 주로 산을 그립니다.","남자는 어릴 때부터 그림을 배웠습니다.","남자는 그림 전시회를 한 적이 있습니다.","남자는 다른 사람과 함께 전시회를 합니다."]'::jsonb, 4, '남자는 다른 사람과 함께 전시회를 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 1, '무엇에 대한 이야기입까?

지금은 아침입니다. 여덟 시입니다.', NULL, NULL, NULL, '["① 사람","② 나이","③ 계절","④ 시간"]'::jsonb, 2, '④ 시간', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 2, '무엇에 대한 이야기입니까?

오늘은 집에 있습니다. 쉽니다.', NULL, NULL, NULL, '["① 나라","② 휴일","③ 쇼핑","④ 직업"]'::jsonb, 2, '② 휴일', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 3, '무엇에 대한 이야기입니까?

저는 바지를 좋아합니다. 치마는 안 입습니다.', NULL, NULL, NULL, '["① 옷","② 값","③ 일","④ 집"]'::jsonb, 2, '① 옷', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 4, '( )에 들어갈 가장 알맞은 것을 고르십시오.

저는 ( )에 갑니다. 공부를 합니다.', NULL, NULL, NULL, '["① 약국","② 학교","③ 여행사","④ 편의점"]'::jsonb, 2, '② 학교', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 5, '( )에 들어갈 가장 알맞은 것을 고르십시오.

전화를 합니다. 친구와 ( ).', NULL, NULL, NULL, '["① 씁니다","② 줍니다","③ 읽습니다","④ 이야기합니다"]'::jsonb, 2, '④ 이야기합니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 6, '( )에 들어갈 가장 알맞은 것을 고르십시오.

집에서 은행이 ( ). 집 앞에 있습니다.', NULL, NULL, NULL, '["① 넓습니다","② 가깝습니다","③ 깨끗합니다","④ 시원합니다"]'::jsonb, 2, '② 가깝습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 7, '( )에 들어갈 가장 알맞은 것을 고르십시오.

저는 보통 버스를 탑니다. ( ) 지하철을 탑니다.', NULL, NULL, NULL, '["① 가끔","② 빨리","③ 아주","④ 항상"]'::jsonb, 3, '① 가끔', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 8, '( )에 들어갈 가장 알맞은 것을 고르십시오.

오늘은 수미의 생일입니다. 저는 수미( ) 선물을 했습니다.', NULL, NULL, NULL, '["① 도","② 를","③ 에서","④ 에게"]'::jsonb, 3, '④ 에게', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 9, '( )에 들어갈 가장 알맞은 것을 고르십시오.

형이 아직 안 왔습니다. 형을 ( ).', NULL, NULL, NULL, '["① 압니다","② 보냅니다","③ 기다립니다","④ 가르칩니다"]'::jsonb, 2, '③ 기다립니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 10, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/reading/q10.png', NULL, NULL, '["① 금요일에 합니다.","② 같이 축구를 합니다.","③ 모임은 오전에 있습니다.","④ 학교 운동장에서 만납니다."]'::jsonb, 3, '③ 모임은 오전에 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 11, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/reading/q11.png', NULL, NULL, '["① 삼분 후에 먹습니다.","② 가격은 이천 원입니다.","③ 이 라면은 김치 맛입니다.","④ 이 라면에 계란이 있습니다."]'::jsonb, 3, '② 가격은 이천 원입니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 12, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/reading/q12.png', NULL, NULL, '["① 마이클 씨가 문자 메시지를 받습니다.","② 마이클 씨는 지금 미영 씨와 있습니다.","③ 미영 씨는 오늘 친구들을 만날 겁니다.","④ 미영 씨는 오늘 집에서 영화를 볼 겁니다."]'::jsonb, 3, '② 마이클 씨는 지금 미영 씨와 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 13, '다음의 내용과 같은 것을 고르십시오.

우리 집에서는 제가 요리를 합니다. 한국 음식도 잘하고 다른 나라의 음식도 잘 만듭니다. 매일 음식을 해서 가족들과 같이 먹습니다.', NULL, NULL, NULL, '["① 가족들은 매일 요리를 합니다.","② 저는 한국 음식을 잘 만듭니다.","③ 가족들은 한국 음식을 안 먹습니다.","④ 저는 다른 나라 음식을 잘 못 만듭니다."]'::jsonb, 3, '② 저는 한국 음식을 잘 만듭니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 14, '다음의 내용과 같은 것을 고르십시오.

오늘도 인주시에 비가 많이 오겠습니다. 오후부터 비가 오고 밤에는 비가 오지 않겠습니다. 내일은 날씨가 맑겠습니다.', NULL, NULL, NULL, '["① 내일은 비가 내리지 않을 겁니다.","② 오늘 밤에 비가 많이 올 겁니다.","③ 오늘 오후에 비가 오지 않을 겁니다.","④ 인주시에 오랜만에 비가 내릴 겁니다."]'::jsonb, 2, '① 내일은 비가 내리지 않을 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 15, '다음의 내용과 같은 것을 고르십시오.

제 취미는 가구 만들기입니다. 주말에만 만들어서 하나를 만들 때 시간이 많이 걸립니다. 지금까지 책장 하나와 의자 두 개를 만들었습니다.', NULL, NULL, NULL, '["① 저는 가구를 빨리 만듭니다.","② 저는 주말에 가구를 만듭니다.","③ 저는 책장을 많이 만들었습니다.","④ 저는 의자를 한 개 만들었습니다."]'::jsonb, 3, '② 저는 주말에 가구를 만듭니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 16, '다음을 읽고 중심 생각을 고르십시오.

오늘 자동차 박물관에 갔습니다. 박물관이 작고 자동차도 많지 않았습니다. 재미가 없어서 일찍 나왔습니다.', NULL, NULL, NULL, '["① 박물관에 다시 가겠습니다.","② 박물관이 더 컸으면 좋겠습니다.","③ 박물관이 마음에 들지 않았습니다.","④ 박물관에 자동차가 너무 적었습니다."]'::jsonb, 3, '③ 박물관이 마음에 들지 않았습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 17, '다음을 읽고 중심 생각을 고르십시오.

저는 한복을 한번 입어 보고 싶었습니다. 그래서 이번 방학에 한국에 가면 한복을 입어 볼 겁니다. 한복을 입고 사진도 찍을 겁니다.', NULL, NULL, NULL, '["① 방학에 한국에 가고 싶습니다.","② 한복을 자주 입으면 좋겠습니다.","③ 여러 한복 사진을 찍고 싶습니다.","④ 한국에서 한복을 입어 보려고 합니다."]'::jsonb, 3, '④ 한국에서 한복을 입어 보려고 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 18, '다음을 읽고 중심 생각을 고르십시오.

저는 게임 회사에 다니고 있습니다. 일도 재미있고 회사 사람들도 좋습니다. 저는 이 회사에 오래 다니고 싶습니다.', NULL, NULL, NULL, '["① 저는 게임을 하는 것이 좋습니다.","② 저는 이 회사의 게임을 좋아합니다.","③ 저는 이 회사에서 계속 일하면 좋겠습니다.","④ 저는 회사에서 같이 일하는 사람들이 좋습니다."]'::jsonb, 2, '③ 저는 이 회사에서 계속 일하면 좋겠습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 19, '( )에 들어갈 알맞은 말을 고르십시오.

저는 음악 공연 보는 것을 좋아합니다. 하지만 요즘에는 바빠서 공연을 거의 보지 못했습니다. 오늘은 일이 빨리 끝나서 오랜만에 친구와 같이 공연을 ( ). 공연은 정말 신나고 좋았습니다. 공연을 보고 나올 때 행복했습니다.', NULL, NULL, NULL, '["① 보러 갔습니다","② 봐야 했습니다","③ 보지 않았습니다","④ 볼 수 없었습니다"]'::jsonb, 2, '① 보러 갔습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 20, '이 글의 내용과 같은 것을 고르십시오.

저는 음악 공연 보는 것을 좋아합니다. 하지만 요즘에는 바빠서 공연을 거의 보지 못했습니다. 오늘은 일이 빨리 끝나서 오랜만에 친구와 같이 공연을 ( ). 공연은 정말 신나고 좋았습니다. 공연을 보고 나올 때 행복했습니다.', NULL, NULL, NULL, '["① 저는 요즘 시간이 많습니다.","② 저는 오늘 일을 쉬었습니다.","③ 저는 친구와 공연을 자주 봅니다.","④ 저는 공연을 봐서 기분이 좋았습니다."]'::jsonb, 2, '④ 저는 공연을 봐서 기분이 좋았습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 21, '( )에 들어갈 알맞은 말을 고르십시오.

전에는 문을 열 때 항상 열쇠를 사용했습니다. 그런데 요즘은 꼭 열쇠가 필요한 것은 아닙니다. 자기만 아는 번호를 사용할 수도 있고 카드로 문을 열 수도 있습니다. ( ) 사람마다 모두 다른 목소리나 얼굴 모양을 이용하는 방법도 있습니다. 요즘은 이렇게 다양한 방법을 씁니다.', NULL, NULL, NULL, '["① 그리고","② 그래서","③ 그러면","④ 그렇지만"]'::jsonb, 3, '① 그리고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 22, '무엇에 대한 이야기인지 맞는 것을 고르십시오.

전에는 문을 열 때 항상 열쇠를 사용했습니다. 그런데 요즘은 꼭 열쇠가 필요한 것은 아닙니다. 자기만 아는 번호를 사용할 수도 있고 카드로 문을 열 수도 있습니다. ( ) 사람마다 모두 다른 목소리나 얼굴 모양을 이용하는 방법도 있습니다. 요즘은 이렇게 다양한 방법을 씁니다.', NULL, NULL, NULL, '["① 열쇠가 사용되는 곳","② 열쇠로 할 수 있는 일","③ 문을 여는 여러 가지 방법","④ 문을 열 때 카드를 쓰는 이유"]'::jsonb, 2, '③ 문을 여는 여러 가지 방법', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 23, '( )에 들어갈 알맞은 말을 고르십시오.

저는 초등학교 때 친하게 지낸 친구가 한 명 있었습니다. 항상 같이 다닌 좋은 친구였습니다. 그런데 초등학교를 ( ) 그 친구는 부산으로 이사를 갔습니다. 서로 멀리 떨어져서 만나지 못했고 이제는 연락이 안 됩니다. 그 친구를 찾을 수 있으면 좋겠습니다.', NULL, NULL, NULL, '["① 졸업해도","② 졸업하거나","③ 졸업하고 나서","④ 졸업하게 되면"]'::jsonb, 2, '③ 졸업하고 나서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 24, '이 글의 내용과 같은 것을 고르십시오.

저는 초등학교 때 친하게 지낸 친구가 한 명 있었습니다. 항상 같이 다닌 좋은 친구였습니다. 그런데 초등학교를 ( ) 그 친구는 부산으로 이사를 갔습니다. 서로 멀리 떨어져서 만나지 못했고 이제는 연락이 안 됩니다. 그 친구를 찾을 수 있으면 좋겠습니다.', NULL, NULL, NULL, '["① 저는 그 친구와 연락을 할 수 없습니다.","② 저는 초등학교 때부터 부산에 살았습니다.","③ 저는 초등학교에 다닐 때 이사를 갔습니다.","④ 저는 그 친구를 이제 만나고 싶지 않습니다."]'::jsonb, 3, '① 저는 그 친구와 연락을 할 수 없습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 25, '( )에 들어갈 알맞은 말을 고르십시오.

동문시장은 작고 조용한 시장이었습니다. 이곳에는 70년이 된 작은 국수 가게가 하나 있습니다. 얼마 전 이 국수 가게가 방송에 소개되었습니다. 그 후 동문시장의 분위기는 크게 달라졌습니다. 방송에 나온 후 이 국수 가게에 ( ) 동문시장도 함께 유명해졌기 때문입니다.', NULL, NULL, NULL, '["① 일할 자리가 나서","② 바뀐 것이 없어서","③ 없는 물건이 없어서","④ 오는 사람이 많아져서"]'::jsonb, 2, '④ 오는 사람이 많아져서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 26, '이 글의 내용과 같은 것을 고르십시오.

동문시장은 작고 조용한 시장이었습니다. 이곳에는 70년이 된 작은 국수 가게가 하나 있습니다. 얼마 전 이 국수 가게가 방송에 소개되었습니다. 그 후 동문시장의 분위기는 크게 달라졌습니다. 방송에 나온 후 이 국수 가게에 ( ) 동문시장도 함께 유명해졌기 때문입니다.', NULL, NULL, NULL, '["① 이 시장은 전과 달라진 것이 없습니다.","② 이 시장은 요즘에 사람이 거의 없습니다.","③ 이 가게는 생긴 지 칠십 년이 되었습니다.","④ 이 가게는 방송에 소개된 후 문을 닫았습니다."]'::jsonb, 3, '③ 이 가게는 생긴 지 칠십 년이 되었습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 27, '다음을 순서대로 맞게 나열한 것을 고르십시오.

(가) 저는 종이컵을 많이 썼습니다.
(나) 이제부터 그 컵을 쓰려고 합니다.
(다) 그래서 가지고 다닐 컵을 샀습니다.
(라) 그런데 종이컵은 바로 쓰레기가 됩니다.', NULL, NULL, NULL, '["①(가)-(다)-(나)-(라)","②(가)-(라)-(다)-(나)","③(나)-(다)-(라)-(가)","④(나)-(라)-(가)-(다)"]'::jsonb, 3, '②(가)-(라)-(다)-(나)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 28, '다음을 순서대로 맞게 나열한 것을 고르십시오.

(가) 회사원들의 이런 생활은 목에 좋지 않습니다.
(나) 그래서 잠깐씩 일어나서 목 운동을 해야 합니다.
(다) 또 목 주위를 따뜻하게 해 주는 것도 도움이 됩니다.
(라) 회사원들은 오랜 시간 앉아서 컴퓨터를 보고 일합니다.', NULL, NULL, NULL, '["①(가)-(나)-(라)-(다)","②(가)-(다)-(나)-(라)","③(라)-(가)-(나)-(다)","④(라)-(다)-(나)-(가)"]'::jsonb, 2, '③(라)-(가)-(나)-(다)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 29, '다음 문장이 들어갈 곳을 고르십시오.

주어진 문장: 처음에는 피아노를 전혀 치지 못했습니다.

저는 피아노 학원에 다닌 지 3년이 되었습니다.( ① ) 그렇지만 지금은 여러 노래들을 잘 칠 수 있게 되었습니다. ( ② ) 피아노를 치면서 좋아하는 가수의 노래를 부르면 정말 즐거워집니다. ( ③ ) 피아노를 배우는 것이 정말 좋습니다. ( ④ )', NULL, NULL, NULL, '["① 저는 피아노를 배우러 다닙니다.","② 저는 피아노 학원을 그만두고 싶습니다.","③ 저는 가수가 되기 위해서 피아노를 배웁니다.","④ 저는 삼 년 전부터 학원에서 일하고 있습니다."]'::jsonb, 2, '① 저는 피아노를 배우러 다닙니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 30, '이 글의 내용과 같은 것을 고르십시오.

저는 피아노 학원에 다닌 지 3년이 되었습니다.( ① ) 그렇지만 지금은 여러 노래들을 잘 칠 수 있게 되었습니다. ( ② ) 피아노를 치면서 좋아하는 가수의 노래를 부르면 정말 즐거워집니다. ( ③ ) 피아노를 배우는 것이 정말 좋습니다. ( ④ )', NULL, NULL, NULL, '["① 저는 피아노를 배우러 다닙니다.","② 저는 피아노 학원을 그만두고 싶습니다.","③ 저는 가수가 되기 위해서 피아노를 배웁니다.","④ 저는 삼 년 전부터 학원에서 일하고 있습니다."]'::jsonb, 3, '① 저는 피아노를 배우러 다닙니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 31, '( )에 들어갈 알맞은 말을 고르십시오.

저는 조금 전에 텔레비전을 보고 깜짝 놀랐습니다. 텔레비전에 제 동생이 크게 나왔기 때문입니다. 동생은 테니스 경기장에서 경기를 보고 있었는데 박수를 치면서 웃고 있었습니다. 동생의 모습을 텔레비전에서 본 것은 처음 이었습니다. 매일 보는 동생이지만 동생의 얼굴을 텔레비전에서 보니까 ( ) 새로운 기분이 들었습니다.', NULL, NULL, NULL, '["① 편하고","② 반갑고","③ 복잡하고","④ 비슷하고"]'::jsonb, 2, '② 반갑고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 32, '이 글의 내용과 같은 것을 고르십시오.

저는 조금 전에 텔레비전을 보고 깜짝 놀랐습니다. 텔레비전에 제 동생이 크게 나왔기 때문입니다. 동생은 테니스 경기장에서 경기를 보고 있었는데 박수를 치면서 웃고 있었습니다. 동생의 모습을 텔레비전에서 본 것은 처음 이었습니다. 매일 보는 동생이지만 동생의 얼굴을 텔레비전에서 보니까 ( ) 새로운 기분이 들었습니다.', NULL, NULL, NULL, '["① 동생은 테니스를 보러 경기장에 갔습니다.","② 저는 박수를 치면서 동생의 모습을 보았습니다.","③ 전에도 텔레비전에서 동생의 얼굴을 보았습니다.","④ 저는 오늘 테니스 경기장에서 동생을 만났습니다."]'::jsonb, 2, '① 동생은 테니스를 보러 경기장에 갔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 33, '왜 이 글을 썼는지 맞는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/reading/q33.png', NULL, NULL, '["① 청소 장소를 바꾸려고","② 청소 계획을 물어보려고","③ 청소 이유를 설명하려고","④ 청소 날짜와 시간을 알리려고"]'::jsonb, 2, '④ 청소 날짜와 시간을 알리려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 34, '이 글의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-64/reading/q33.png', NULL, NULL, '["① 이틀 동안 주차장 청소를 할 겁니다.","② 주차장 청소는 화요일에 시작할 겁니다.","③ 지하 주차장 물청소는 아홉 시까지 합니다.","④ 7월 22일까지 다른 주차장을 이용해야 합니다."]'::jsonb, 3, '① 이틀 동안 주차장 청소를 할 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 35, '( )에 들어갈 알맞은 말을 고르십시오.

얼음 음료는 여름철 인기 메뉴입니다. 그런데 얼음이 녹아서 물이 되면 음료의 맛이 없어집니다. 그래서 얼음 음료를 만들 때는 천천히 녹는 얼음을 넣으면 좋습니다. 큰 얼음은 작은 얼음보다 천천히 녹고, 오래 얼린 얼음도 잠깐 얼린 얼음보다 천천히 녹습니다. 이런 얼음을 넣으면 ( ) 처음 음료의 맛을 오래 즐길 수 있습니다.', NULL, NULL, NULL, '["① 마시지만","② 마시려고","③ 마시기 때문에","④ 마시는 동안에"]'::jsonb, 2, '④ 마시는 동안에', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 36, '이 글의 내용과 같은 것을 고르십시오.

얼음 음료는 여름철 인기 메뉴입니다. 그런데 얼음이 녹아서 물이 되면 음료의 맛이 없어집니다. 그래서 얼음 음료를 만들 때는 천천히 녹는 얼음을 넣으면 좋습니다. 큰 얼음은 작은 얼음보다 천천히 녹고, 오래 얼린 얼음도 잠깐 얼린 얼음보다 천천히 녹습니다. 이런 얼음을 넣으면 ( ) 처음 음료의 맛을 오래 즐길 수 있습니다.', NULL, NULL, NULL, '["① 오래 얼린 얼음이 더 빨리 녹습니다.","② 작은 얼음은 큰 얼음보다 빨리 녹습니다.","③ 큰 얼음을 음료에 넣으면 맛이 금방 달라집니다.","④ 음료 맛은 작은 얼음을 넣을 때 천천히 변합니다."]'::jsonb, 3, '② 작은 얼음은 큰 얼음보다 빨리 녹습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 37, '( )에 들어갈 알맞은 말을 고르십시오.

태풍은 보통 7월부터 9월까지 많이 생깁니다. 이런 태풍들도 이름이 있는데 그 중에는 한국어로 된 이름도 있습니다. 태풍의 이름은 태풍이 지나가는 곳에 있는 열네 개 나라에서 만들고 있습니다. 한국도 2000년부터 태풍의 이름을 ( ). 한국어로 이름을 만들 때는 다른 나라 사람들도 발음하기 쉬운 단어를 고릅니다.', NULL, NULL, NULL, '["① 부르려고 합니다","② 바꾸기로 했습니다","③ 원하고 있습니다","④ 만들기 시작했습니다"]'::jsonb, 3, '④ 만들기 시작했습니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 38, '이 글의 내용과 같은 것을 고르십시오.

태풍은 보통 7월부터 9월까지 많이 생깁니다. 이런 태풍들도 이름이 있는데 그 중에는 한국어로 된 이름도 있습니다. 태풍의 이름은 태풍이 지나가는 곳에 있는 열네 개 나라에서 만들고 있습니다. 한국도 2000년부터 태풍의 이름을 ( ). 한국어로 이름을 만들 때는 다른 나라 사람들도 발음하기 쉬운 단어를 고릅니다.', NULL, NULL, NULL, '["① 태풍은 보통 겨울과 봄에 생깁니다.","② 한국에는 태풍이 거의 불지 않습니다.","③ 태풍의 이름은 열네 개 나라에서 만듭니다.","④ 태풍의 한국어 이름은 발음이 쉽지 않습니다."]'::jsonb, 3, '③ 태풍의 이름은 열네 개 나라에서 만듭니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 39, '( )에 들어갈 알맞은 말을 고르십시오.

몇 달 전, 우리 집 앞에서 떨고 있는 작고 마른 강아지를 보았습니다. 저는 그 강아지가 너무 불쌍해 보였습니다. 저는 강아지를 집으로 데려와 먹을 것을 주고 잠도 재워 주었습니다. 그때부터 주인을 찾고 있는데 아직도 주인이 나타나지 않습니다. 그 강아지는 이제 ( ) 저의 좋은 친구가 되었습니다. 강아지와 헤어지기 싫습니다.', NULL, NULL, NULL, '["① 잠이 많아져서","② 주인을 찾아서","③ 크고 건강해져서","④ 계속 떨고 있어서"]'::jsonb, 3, '③ 크고 건강해져서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 40, '이 글의 내용으로 알 수 있는 것을 고르십시오.

몇 달 전, 우리 집 앞에서 떨고 있는 작고 마른 강아지를 보았습니다. 저는 그 강아지가 너무 불쌍해 보였습니다. 저는 강아지를 집으로 데려와 먹을 것을 주고 잠도 재워 주었습니다. 그때부터 주인을 찾고 있는데 아직도 주인이 나타나지 않습니다. 그 강아지는 이제 ( ) 저의 좋은 친구가 되었습니다. 강아지와 헤어지기 싫습니다.', NULL, NULL, NULL, '["① 저는 강아지의 주인을 만났습니다.","② 저는 이 강아지를 잃어버렸습니다.","③ 저는 이 강아지를 키우는 것이 싫습니다.","④ 저는 길에서 데려온 강아지를 키우고 있습니다."]'::jsonb, 3, '④ 저는 길에서 데려온 강아지를 키우고 있습니다.', NULL);

COMMIT;
