-- Generated by scripts/generate_topik_83_sql.mjs
BEGIN;

INSERT INTO mock_test_bank (
  title, exam_type, test_number, description, total_questions, duration, listening_questions, reading_questions
)
SELECT
  'TOPIK II 83-р шалгалт',
  'TOPIK_II',
  83,
  '83-р албан ёсны TOPIK II шалгалт',
  100,
  130,
  50,
  50
WHERE NOT EXISTS (
  SELECT 1 FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83
);

UPDATE mock_test_bank
SET
  title = 'TOPIK II 83-р шалгалт',
  description = '83-р албан ёсны TOPIK II шалгалт',
  total_questions = 100,
  duration = 130,
  listening_questions = 50,
  reading_questions = 50,
  updated_at = NOW()
WHERE id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1);

DELETE FROM mock_test_questions WHERE mock_test_id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1);

INSERT INTO mock_test_questions (
  mock_test_id,
  section,
  question_number,
  question_text,
  question_image_url,
  audio_url,
  option_image_urls,
  options,
  question_score,
  correct_answer_text,
  explanation
) VALUES
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 1, '다음을 듣고 가장 알맞은 그림 또는 그래프를 고르십시오.

여자 : 지금 전시장에 들어갈 수 있어요?
남자: 잠시만 기다려 주세요. 곧 입장 시작합니다.
여자 : 네. 알겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q1_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q1_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q1_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q1_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 2, '다음을 듣고 가장 알맞은 그림 또는 그래프를 고르십시오.

남자: 아, 무거워. 이 화분은 어디에 놓을까?
여자: 여기 창문 앞은 어때?
남자: 그래. 거기가 좋겠다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q2_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q2_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q2_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q2_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 3, '다음을 듣고 가장 알맞은 그림 또는 그래프를 고르십시오.

남자: 외국인 관광객들이 한국을 방문하는 목적은 ''휴가''가 가장 많았습니다.
다음으로 ''사업''과 ''친척 방문''이 뒤를 이었는데요. 그렇다면 외국인
관광객들은 누구와 함께 한국에 올까요? ''가족이나 친구''가 54%로
가장 많았고, ''혼자''가 33%, ''동료''가 10%로 나타났습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q3_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q3_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q3_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/listening/q3_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 4, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.

여자 : 민수야, 내가 빌려 준 책 읽고 있어? 재미있지?
남자: 응. 재미있어. 근데 언제까지 돌려주면 돼?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["어제 다 읽었어.","천천히 읽고 돌려줘.","책 읽을 시간이 없었어.","재미있는 책 좀 추천해 줘."]'::jsonb, 2, '천천히 읽고 돌려줘.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 5, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.

남자: 아직도 아르바이트를 못 구했어요.
여자 : 학교 앞 식당에서 일할 사람을 찾던데요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["그래요? 한번 가 봐야겠어요.","그럼요. 내일부터 일하기로 했어요.","정말요? 힘들면 언제든지 그만두세요.","맞아요. 좋은 곳을 구해서 기분이 좋아요."]'::jsonb, 2, '그래요? 한번 가 봐야겠어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 6, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.

여자: 나는 이 운동화로 할래. 너는 뭐 살 거야?
남자: 난 파란색하고 하얀색 둘 다 마음에 드는데, 뭐가 더 괜찮아?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["그럼 하얀색으로 바꾸러 가자.","나는 다른 운동화도 신어 볼래.","새로 산 운동화가 마음에 들어.","파란색이 너한테 더 잘 어울려."]'::jsonb, 2, '파란색이 너한테 더 잘 어울려.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 7, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.

여자 : 뉴스에서 봤는데 주말부터 장마가 시작된대요.
남자: 그래요? 올해도 작년만큼 비가 많이 올까요?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["비가 곧 그칠 거래요.","일기 예보를 볼 걸 그랬어요.","장마가 끝나니까 진짜 더워요.","작년하고 거의 비슷할 거래요."]'::jsonb, 2, '작년하고 거의 비슷할 거래요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 8, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.

남자: 고객 센터죠? 일주일 전에 의자를 주문했는데 아직 안 와서요.
여자 : 죄송합니다. 주문량이 많아서 배송이 늦어지고 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["곧 배송된다니 다행이에요.","제품에 문제가 있는 것 같아요.","언제쯤 배송될지 확인해 주시겠어요?","고객 센터 전화번호 좀 알려 주실래요?"]'::jsonb, 2, '언제쯤 배송될지 확인해 주시겠어요?', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 9, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.

여자: 사과는 다 씻었고. 이제 자르면 되겠다.
남자: 자르는 건 내가 할 테니까 거기 있는 냄비 좀 줄래?
여자: 여기 있어. 근데 잼 만들려면 설탕이 더 필요하겠네. 내가 찾아올까?
남자: 응. 좀 갖다 줘.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["사과를 씻는다.","과일을 자른다.","설탕을 가져온다.","냄비를 찾아온다."]'::jsonb, 2, '설탕을 가져온다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 10, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.

남자: 손님, 놀이 기구 타실 거죠? 그러면 가방은 여기에 보관하시겠어요?
여자 : 네. 여기요. 모자는 쓰고 타도 돼요?
남자: 그것도 날아갈 수 있으니까 같이 보관해 드릴게요.
여자: 알겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["모자를 벗는다.","놀이 기구에 탄다.","떨어진 물건을 줍는다.","남자에게 가방을 받는다."]'::jsonb, 2, '모자를 벗는다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 11, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.

여자 : 빨래방은 처음인데 먼저 코스 선택하고 세탁물 넣으면 되나?
남자: 여기 안내문 있다. 세탁물 넣은 후에 코스 선택하고, 동전 넣으래.
여자: 나 동전은 없는데. 아, 저기 동전 교환기 있네. 바꿔 올게.
남자: 응. 난 또 뭘 해야 되는지 읽어 볼게.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["세탁물을 넣는다.","안내문을 읽는다.","동전을 바꾸러 간다.","세탁 코스를 선택한다."]'::jsonb, 2, '동전을 바꾸러 간다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 12, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.

여자: 감독님, 촬영 준비 끝났습니다. 물건들도 제자리에 놓았고요.
남자: 그럼 카메라 화면에서 어떻게 보이는지 확인해 봅시다. 음, 저 거울이
꼭 필요할까요?
여자: 거울이 커서 그런지 사무실처럼 보이지가 않네요. 치울까요?
남자 : 네. 그렇게 해 주세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["거울을 치운다.","카메라를 설치한다.","카메라 화면을 본다.","촬영할 물건을 가져온다."]'::jsonb, 2, '거울을 치운다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 13, '다음을 듣고 들은 내용과 같은 것을 고르십시오.

여자: 이 사진 좀 볼래? 이게 모형이래. 실제 배하고 똑같지?
남자: 와, 정말 잘 만들었다. 근데 뭐로 만든 거야? 나무인가?
여자: 아니. 가죽으로 만든 거래.
남자: 신기하다. 가죽을 이용해서 배 모형을 만들다니. 직접 한번 보고 싶다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["두 사람은 모형 배를 만드는 중이다.","이 모형 배는 가죽으로 만들어졌다.","여자는 남자가 준 사진을 보고 있다.","남자는 이 모형 배를 직접 본 적이 있다."]'::jsonb, 2, '이 모형 배는 가죽으로 만들어졌다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 14, '다음을 듣고 들은 내용과 같은 것을 고르십시오.

여자: (딩동댕) 댄스 대회에 오신 여러분께 안내 드립니다. 잠시 후 두 시
부터 개회식이 열립니다. 대기실에 계신 참가자들은 대회장으로
오시기 바랍니다. 개회식이 끝나는 대로 예선 경기가 시작되오니
그 자리에서 기다려 주십시오. 대회 중에는 촬영을 할 수 없으니
협조 부탁드립니다. (댕동딩)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["개회식은 대회장에서 열린다.","대회의 장면을 찍을 수 있다.","예선 경기는 두 시에 시작된다.","개회식 후에 대기실로 가야 한다."]'::jsonb, 2, '개회식은 대회장에서 열린다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 15, '다음을 듣고 들은 내용과 같은 것을 고르십시오.

남자: 어젯밤 열시, 인주산에서 길은 잃은 등산객 네 명이 구조됐습니다.
등산객의 구조 요청을 받은 구조대원들은 곧바로 수색 작업을 시작해
두 시간 만에 등산객 모두를 발견했습니다. 등산객들은 산 정상에서
내려오던 중 날이 어두워져 길을 잃은 것으로 확인됐습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 사고는 오전에 발생했다.","등산객들은 모두 구조되었다.","사고 발생 원인을 조사할 예정이다.","산 정상에 오르다가 사고가 발생했다."]'::jsonb, 2, '등산객들은 모두 구조되었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 16, '다음을 듣고 들은 내용과 같은 것을 고르십시오.

남자: 작가님의 그림이 인기를 얻고 있는 이유는 뭐라고 생각하십니까?
여자 : 우리 주변의 흔하고 평범한 소재를 따뜻하게 그리기 때문이 아닐까요?
저는 행복했던 어린 시절을 기억하고 싶어서 70세가 넘어서야 그림을
그리기 시작했어요. 물론 배운 적도 없고요. 꾸미지 않은 그런 느낌을
사람들이 좋아해 주는 것 같아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["여자는 전문적으로 그림을 배웠다.","여자의 그림은 화려한 느낌을 준다.","여자는 화가가 된 지 70년이 넘었다.","여자는 평범한 것을 그림의 소재로 삼는다."]'::jsonb, 2, '여자는 평범한 것을 그림의 소재로 삼는다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 17, '다음을 듣고 남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

남자: 수미야, 내가 보낸 메일 못 받았어?
여자: 아니. 받았어. 어떻게 쓸까 생각하느라고 아직 답장을 못 보냈어.
남자: 난 메일이 안 갔나 걱정했어. 기다렸는데 받았다는 말이라도 해 주지.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["메일을 자주 확인해야 한다.","답장이 올 때까지 기다리는 게 낫다.","메일을 받은 사실을 알려 줘야 한다.","답장을 보내기 전에 확인하는 게 좋다."]'::jsonb, 2, '메일을 받은 사실을 알려 줘야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 18, '다음을 듣고 남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

남자: 요즘 새벽에 일어나서 공부하는데 집중이 잘되더라.
여자: 그래? 난 새벽에 일어나면 많이 피곤할 것 같은데.
남자: 처음엔 나도 좀 피곤했는데 이제는 공부가 잘돼서 좋아.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["공부는 매일 하는 것이 중요하다.","공부하는 장소를 바꿀 필요가 있다.","새벽에 일어나서 공부하는 게 좋다.","피곤할 때는 적당한 휴식도 필요하다."]'::jsonb, 2, '새벽에 일어나서 공부하는 게 좋다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 19, '다음을 듣고 남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

여자: 지난번에 갔던 직업인들과의 만남 프로그램, 진짜 좋았지?
남자 : 응. 다양한 직업을 가진 사람들의 이야기를 들으니까 참 좋았어.
여자: 맞아. 진로를 결정하는 데에도 꽤 도움이 됐어.
남자: 여러 분야의 사람들을 만나면 배울 것도 많은 것 같아.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["다양한 분야의 사람을 만나야 한다.","직업을 자주 바꾸는 것은 좋지 않다.","같이 일하는 사람과 잘 지내야 한다.","진로에 대해 충분히 고민할 필요가 있다."]'::jsonb, 2, '다양한 분야의 사람을 만나야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 20, '다음을 듣고 남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

여자 : 선생님, 마을 이름에 대한 책을 내신 특별한 계기가 있으신가요?
남자 : 네. 지명에는 지금은 안 쓰는 옛날 말이 많이 남아 있습니다. 특히
마을의 문화나 자연을 가리키는 말들 중에 무척 아름다운 표현들이
많은데요. 그런 표현들이 다시 우리의 일상으로 들어와 삶의 곳곳에서
사용됐으면 하는 마음으로 책을 쓰게 됐어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["오래된 지명을 새롭게 바꿀 필요가 있다.","지명은 많은 사람이 알기 쉽게 만들어야 한다.","지명에 쓰인 아름다운 옛말이 사용되면 좋겠다.","지명을 만들 때는 마을의 문화를 반영해야 한다."]'::jsonb, 2, '지명에 쓰인 아름다운 옛말이 사용되면 좋겠다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 21, '남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

여자: 교수님, 제 연구 계획서인데요. 한번 봐 주시겠어요?
남자: ''성격과 여행지''라, 성격이 여행지 결정에 미치는 영향을 알아보겠다는
거군요? 주제가 아주 새롭고 좋아요. 연구 방법으로는 설문 조사를
선택했는데 계획이 거의 없네요. 설문 조사는 조사하려는 내용이 분명
해야 하니까 조사 대상과 내용을 잘 계획할 필요가 있어요.
여자 : 네. 그런데 무엇부터 시작을 하면 좋을지 모르겠어요.
남자: 그럼 성격과 여행지의 유형을 나누는 것부터 시작해 보세요。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["설문 조사의 주제를 바꿔야 한다.","설문 조사는 결과 분석이 중요하다.","설문 조사의 계획을 잘 세워야 한다.","설문 조사는 응답자 수가 많을수록 좋다."]'::jsonb, 2, '설문 조사의 계획을 잘 세워야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 22, '들은 내용과 같은 것을 고르십시오.

여자: 교수님, 제 연구 계획서인데요. 한번 봐 주시겠어요?
남자: ''성격과 여행지''라, 성격이 여행지 결정에 미치는 영향을 알아보겠다는
거군요? 주제가 아주 새롭고 좋아요. 연구 방법으로는 설문 조사를
선택했는데 계획이 거의 없네요. 설문 조사는 조사하려는 내용이 분명
해야 하니까 조사 대상과 내용을 잘 계획할 필요가 있어요.
여자 : 네. 그런데 무엇부터 시작을 하면 좋을지 모르겠어요.
남자: 그럼 성격과 여행지의 유형을 나누는 것부터 시작해 보세요。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["남자는 연구 계획서를 작성하고 있다.","남자는 성격에 대한 연구를 하려고 한다.","남자는 연구 방법을 아직 결정하지 못했다.","남자는 여자의 연구 주제가 새롭다고 생각한다."]'::jsonb, 2, '남자는 여자의 연구 주제가 새롭다고 생각한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 23, '남자가 무엇을 하고 있는지 고르십시오.

남자: 안녕하십니까, 인주 상사입니다. 합격자 분들에게 건강 검진과
신입 사원 연수 일정을 문자로 보내 드렸는데 확인하셨나요?
여자 : 네. 확인했습니다. 그런데 건강 검진은 정해진 병원에서만 해야 하나요?
남자: 아닙니다. 집 근처 보건소나 병원에 가서 받으셔도 됩니다. 검진
결과는 연수 끝나고 출근 전까지 내시면 되고요. 신입 사원 연수
때는 문자로 안내 드린 증명서만 제출하시면 됩니다.
여자 : 감사합니다. 그럼 연수 때 뵙겠습니다。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["취업에 성공한 방법을 소개하고 있다.","신입 사원 연수 일정을 변경하고 있다.","신입 사원 채용 절차를 설명하고 있다.","입사 전에 해야 할 일을 안내하고 있다."]'::jsonb, 2, '입사 전에 해야 할 일을 안내하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 24, '들은 내용과 같은 것을 고르십시오.

남자: 안녕하십니까, 인주 상사입니다. 합격자 분들에게 건강 검진과
신입 사원 연수 일정을 문자로 보내 드렸는데 확인하셨나요?
여자 : 네. 확인했습니다. 그런데 건강 검진은 정해진 병원에서만 해야 하나요?
남자: 아닙니다. 집 근처 보건소나 병원에 가서 받으셔도 됩니다. 검진
결과는 연수 끝나고 출근 전까지 내시면 되고요. 신입 사원 연수
때는 문자로 안내 드린 증명서만 제출하시면 됩니다.
여자 : 감사합니다. 그럼 연수 때 뵙겠습니다。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 회사의 신입 사원 연수가 끝났다.","신입 사원 연수 일정을 문자로 공지했다.","건강 검진은 정해진 병원에서 받아야 한다.","건강 검진 결과는 출근 후에 제출하면 된다."]'::jsonb, 2, '신입 사원 연수 일정을 문자로 공지했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 25, '남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

여자: 이번에 설계하신 타이어의 판매를 곧 시작한다고 들었는데요. 기존의
타이어와는 어떤 점에서 다른 건가요?
남자: 저는 환경 보호를 위해서는 성능만 강조하는 기존의 타이어 설계에
변화가 필요하다고 생각했습니다. 타이어에서 생기는 작은 플라스틱들이
대기 오염의 가장 큰 원인이 되고 있거든요. 이걸 해결하기 위해 미세
플라스틱 조각이 공기 중으로 날아가지 않고 타이어 안쪽의 캡슐 장치에
모여 저장되도록 설계했습니다. 캡슐이 가득 차면 타이어 옆면의 색이
바뀌어서 운전자가 알 수 있게 했고요。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["타이어를 설계할 때는 환경을 생각해야 한다.","생산된 타이어의 저장 공간을 마련해야 한다.","운전자의 의견을 타이어 디자인에 반영해야 한다.","타이어의 재료로 쓸 새로운 소재를 연구해야 한다."]'::jsonb, 2, '타이어를 설계할 때는 환경을 생각해야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 26, '들은 내용과 같은 것을 고르십시오.

여자: 이번에 설계하신 타이어의 판매를 곧 시작한다고 들었는데요. 기존의
타이어와는 어떤 점에서 다른 건가요?
남자: 저는 환경 보호를 위해서는 성능만 강조하는 기존의 타이어 설계에
변화가 필요하다고 생각했습니다. 타이어에서 생기는 작은 플라스틱들이
대기 오염의 가장 큰 원인이 되고 있거든요. 이걸 해결하기 위해 미세
플라스틱 조각이 공기 중으로 날아가지 않고 타이어 안쪽의 캡슐 장치에
모여 저장되도록 설계했습니다. 캡슐이 가득 차면 타이어 옆면의 색이
바뀌어서 운전자가 알 수 있게 했고요。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 타이어는 많은 판매량을 기록했다.","이 타이어의 안쪽에는 특수한 장치가 있다.","이 타이어는 성능 향상에 중점을 두고 개발되었다.","이 타이어는 대기 오염의 정도를 색깔로 알려 준다."]'::jsonb, 2, '이 타이어의 안쪽에는 특수한 장치가 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 27, '남자가 말하는 의도로 알맞은 것을 고르십시오.

남자: 수미야, 너 그거 들었어? 학교에서 남는 공간을 창업 동아리에
무료로 대여해 준대. 우리도 한번 지원해 보자.
여자: 아, 그거 학교 안의 빈 공간을 빌려 주는 사업 맞지? 나도 들었어.
근데 지금 신청할 수 있대?
남자: 금요일까지 학교 홈페이지에 몇 가지 정보만 입력하면 신청할
수 있나 봐. 다른 서류는 다음 주까지 홈페이지에 올리면 되고.
여자: 그렇구나. 그런데 서류는 뭐가 필요한 거야?
남자 : 글쎄. 나도 그건 정확히 모르겠어. 사무실에 가서 한번 물어보자。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["공간 대여 사업의 결과를 알려 주려고","공간 대여에 필요한 서류를 문의하려고","공간 대여를 위한 신청서의 작성을 부탁하려고","공간 대여 사업에 함께 신청할 것을 제안하려고"]'::jsonb, 2, '공간 대여 사업에 함께 신청할 것을 제안하려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 28, '들은 내용과 같은 것을 고르십시오.

남자: 수미야, 너 그거 들었어? 학교에서 남는 공간을 창업 동아리에
무료로 대여해 준대. 우리도 한번 지원해 보자.
여자: 아, 그거 학교 안의 빈 공간을 빌려 주는 사업 맞지? 나도 들었어.
근데 지금 신청할 수 있대?
남자: 금요일까지 학교 홈페이지에 몇 가지 정보만 입력하면 신청할
수 있나 봐. 다른 서류는 다음 주까지 홈페이지에 올리면 되고.
여자: 그렇구나. 그런데 서류는 뭐가 필요한 거야?
남자 : 글쎄. 나도 그건 정확히 모르겠어. 사무실에 가서 한번 물어보자。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 사업은 다음 주까지 신청할 수 있다.","이 사업에서는 비어 있는 공간을 활용한다.","이 사업을 통해 적은 비용으로 공간을 빌릴 수 있다.","이 사업에 지원하려면 사무실에 서류를 제출해야 한다."]'::jsonb, 2, '이 사업에서는 비어 있는 공간을 활용한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 29, '남자가 누구인지 고르십시오.

여자: 팀장님께서는 게임을 출시하기 전에, 게임에서 발생하는 여러 문제점
들을 찾아내는 일을 맡고 계시다고 들었습니다.
남자 : 네. 개발팀이 완성한 게임을 일정 기간 동안 직접 해 보면서 기술적인
오류를 찾아내고 있습니다. 또 캐릭터의 디자인이나 음향 효과 등
사용자의 흥미와 관련된 것들의 문제점도 찾아내고요.
여자 : 게임의 완성도를 높이기 위해서는 이 일이 굉장히 중요하겠네요.
남자 : 네. 출시 후에 이런 문제가 발생하면 게임 판매에 부정적인 영향을
주게 되거든요. 그래서 저희는 출시 전까지 책임감을 갖고 일합니다。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["게임의 오류를 찾아내는 사람","새로운 게임을 기획하는 사람","게임에 음향 효과를 넣는 사람","새로 개발한 게임을 홍보하는 사람"]'::jsonb, 2, '게임의 오류를 찾아내는 사람', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 30, '들은 내용과 같은 것을 고르십시오.

여자: 팀장님께서는 게임을 출시하기 전에, 게임에서 발생하는 여러 문제점
들을 찾아내는 일을 맡고 계시다고 들었습니다.
남자 : 네. 개발팀이 완성한 게임을 일정 기간 동안 직접 해 보면서 기술적인
오류를 찾아내고 있습니다. 또 캐릭터의 디자인이나 음향 효과 등
사용자의 흥미와 관련된 것들의 문제점도 찾아내고요.
여자 : 게임의 완성도를 높이기 위해서는 이 일이 굉장히 중요하겠네요.
남자 : 네. 출시 후에 이런 문제가 발생하면 게임 판매에 부정적인 영향을
주게 되거든요. 그래서 저희는 출시 전까지 책임감을 갖고 일합니다。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 일은 개발팀에서 담당하고 있다.","이 일은 게임의 판매에 영향을 미친다.","남자는 게임 출시 후에 일을 시작한다.","남자는 게임 캐릭터도 직접 디자인한다."]'::jsonb, 2, '이 일은 게임의 판매에 영향을 미친다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 31, '남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

남자: 현재 검토 중인 업무 관리 프로그램요. 업무의 진행 상황과 자료를
실시간으로 공유할 수 있어서 일의 속도와 효율성을 향상시킬 것으로
보입니다.
여자: 새로운 프로그램에 직원들이 적응하는 게 쉽지는 않을 것 같은데요.
남자 : 초기에는 어려움이 있겠지만 장기적으로는 업무를 관리하는 데 큰
도움이 될 겁니다. 지속적으로 교육하면 직원들도 프로그램을 잘
활용할 수 있게 될 거고요。
여자 : 직원 교육 문제는 여전히 부담스럽긴 해요. 더 신중히 생각해 보죠。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["업무 관리 프로그램의 도입이 필요하다.","업무 방식의 개선을 신중히 결정해야 한다.","직원 교육을 통해 업무의 효율을 높여야 한다.","일의 속도를 강조하는 분위기를 바꿀 필요가 있다."]'::jsonb, 2, '업무 관리 프로그램의 도입이 필요하다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 32, '남자의 태도로 가장 알맞은 것을 고르십시오.

남자: 현재 검토 중인 업무 관리 프로그램요. 업무의 진행 상황과 자료를
실시간으로 공유할 수 있어서 일의 속도와 효율성을 향상시킬 것으로
보입니다.
여자: 새로운 프로그램에 직원들이 적응하는 게 쉽지는 않을 것 같은데요.
남자 : 초기에는 어려움이 있겠지만 장기적으로는 업무를 관리하는 데 큰
도움이 될 겁니다. 지속적으로 교육하면 직원들도 프로그램을 잘
활용할 수 있게 될 거고요。
여자 : 직원 교육 문제는 여전히 부담스럽긴 해요. 더 신중히 생각해 보죠。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["예상되는 문제점을 우려하고 있다.","문제의 해결 방안을 요구하고 있다.","자신의 의견을 일관되게 주장하고 있다.","상대방의 의견에 적극적으로 동의하고 있다."]'::jsonb, 2, '자신의 의견을 일관되게 주장하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 33, '무엇에 대한 내용인지 알맞은 것을 고르십시오.

여자: 이것은 옷이나 가방에서 볼 수 있는 지퍼가 처음 만들어졌을 때의
모습입니다. 지금과 달리 모양이 복잡했고 고장도 잦았죠. 그래서 처음
발명된 19세기 후반에는 시장의 주목을 받지 못했습니다. 그러다가
20세기 초에 오늘날과 같이 형태가 바뀌고 기능도 개선됐는데요.
지퍼를 단 지갑이 선원들에게 인기를 끌면서 지퍼가 알려지기 시작
했습니다. 흔들리는 배에서도 동전을 잘 보관할 수 있었기 때문이죠.
이후 지퍼 달린 장화가 깔끔한 디자인과 편리함을 앞세워 큰 성공을
거두면서 전 세계로 지퍼가 퍼지게 되었습니다。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["기능에 따른 지퍼의 형태","지퍼를 활용한 상품의 종류","초기의 지퍼가 가진 문제점","지퍼가 널리 쓰이게 된 과정"]'::jsonb, 2, '지퍼가 널리 쓰이게 된 과정', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 34, '들은 내용과 같은 것을 고르십시오.

여자: 이것은 옷이나 가방에서 볼 수 있는 지퍼가 처음 만들어졌을 때의
모습입니다. 지금과 달리 모양이 복잡했고 고장도 잦았죠. 그래서 처음
발명된 19세기 후반에는 시장의 주목을 받지 못했습니다. 그러다가
20세기 초에 오늘날과 같이 형태가 바뀌고 기능도 개선됐는데요.
지퍼를 단 지갑이 선원들에게 인기를 끌면서 지퍼가 알려지기 시작
했습니다. 흔들리는 배에서도 동전을 잘 보관할 수 있었기 때문이죠.
이후 지퍼 달린 장화가 깔끔한 디자인과 편리함을 앞세워 큰 성공을
거두면서 전 세계로 지퍼가 퍼지게 되었습니다。', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["지퍼는 20세기 초반에 발명되었다.","지퍼는 선원들을 통해 알려지기 시작했다.","지퍼는 신발 제작에 가장 먼저 활용되었다.","지퍼는 초기부터 깔끔한 모양으로 주목을 받았다."]'::jsonb, 2, '지퍼는 선원들을 통해 알려지기 시작했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 35, '남자가 무엇을 하고 있는지 고르십시오.

남자 : 오늘은 인주 극장이 시민과 연극인 곁으로 다시 돌아오게 된 뜻 깊은
날입니다. 몇 년 전 인주 극장의 폐관 소식을 듣고 우리 연극인들이
이곳을 지켜내지 못했구나 싶어 마음이 아팠습니다. 인주 극장은
주인이 수차례 바뀌는 와중에도 400여 편의 연극을 올리고 수많은
연극인을 배출하는 등 한국 연극사의 발전을 이끌어 왔습니다. 이번
재개관이 더욱 기쁜 것은 이런 역사를 이어 가자는 데에 공감한
연극인들이 마음을 모아 이뤄 낸 결과이기 때문입니다. 다시 문을 연
이곳이 시민과 연극인의 소중한 보금자리가 되어 주리라 생각합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["연극인들을 위한 극장 건축을 다짐하고 있다.","재개관한 극장의 모습과 시설을 소개하고 있다.","연극인들에 대한 관심과 지원을 부탁하고 있다.","극장 재개관에 따른 소감과 기대를 밝히고 있다."]'::jsonb, 2, '극장 재개관에 따른 소감과 기대를 밝히고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 36, '들은 내용과 같은 것을 고르십시오.

남자 : 오늘은 인주 극장이 시민과 연극인 곁으로 다시 돌아오게 된 뜻 깊은
날입니다. 몇 년 전 인주 극장의 폐관 소식을 듣고 우리 연극인들이
이곳을 지켜내지 못했구나 싶어 마음이 아팠습니다. 인주 극장은
주인이 수차례 바뀌는 와중에도 400여 편의 연극을 올리고 수많은
연극인을 배출하는 등 한국 연극사의 발전을 이끌어 왔습니다. 이번
재개관이 더욱 기쁜 것은 이런 역사를 이어 가자는 데에 공감한
연극인들이 마음을 모아 이뤄 낸 결과이기 때문입니다. 다시 문을 연
이곳이 시민과 연극인의 소중한 보금자리가 되어 주리라 생각합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 극장은 작년에 문을 닫았다.","이 극장은 주인이 여러 번 바뀌었다.","오늘 이 극장에서는 400번째 연극을 올린다.","일반 시민이 뜻을 모아 이 극장을 다시 열었다."]'::jsonb, 2, '이 극장은 주인이 여러 번 바뀌었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 37, '여자의 중심 생각으로 가장 알맞은 것을 고르십시오.

남자: 부모 세대가 사용했던 필름 카메라가 디지털에 익숙한 젊은 세대들의
마음을 사로잡고 있습니다.
여자 : 네. 필름 사진만이 갖는 독특한 감성 때문입니다. 필름을 현상하기 위해
약품 처리를 하는 과정에서 묘한 색감과 분위기가 나는데 그것이
아주 매력적이죠. 또 필름 카메라는 필름을 구하기도 어렵고 필름마다
찍을 수 있는 사진 수가 제한적이에요. 인화 과정을 거쳐야만 사진을
받아볼 수 있고요. 이런 번거로움이 오히려 젊은 세대들이 사진 한 장
한 장을 소중하고 특별하게 느끼는 이유가 됩니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["사진을 찍을 때는 정성을 들이는 게 중요하다.","필름 사진을 잘 찍으려면 많이 찍어 봐야 한다.","사진을 여러 장 인화하면 원본의 가치가 떨어진다.","필름 사진에는 감성을 자극하는 특별한 매력이 있다."]'::jsonb, 2, '필름 사진에는 감성을 자극하는 특별한 매력이 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 38, '들은 내용과 같은 것을 고르십시오.

남자: 부모 세대가 사용했던 필름 카메라가 디지털에 익숙한 젊은 세대들의
마음을 사로잡고 있습니다.
여자 : 네. 필름 사진만이 갖는 독특한 감성 때문입니다. 필름을 현상하기 위해
약품 처리를 하는 과정에서 묘한 색감과 분위기가 나는데 그것이
아주 매력적이죠. 또 필름 카메라는 필름을 구하기도 어렵고 필름마다
찍을 수 있는 사진 수가 제한적이에요. 인화 과정을 거쳐야만 사진을
받아볼 수 있고요. 이런 번거로움이 오히려 젊은 세대들이 사진 한 장
한 장을 소중하고 특별하게 느끼는 이유가 됩니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["필름 사진은 인화하기 전에 미리 볼 수 있다.","필름 사진을 얻을 때까지의 과정이 수월해졌다.","필름 사진의 색감은 약품 처리를 할 때 생긴다.","필름 카메라가 부모 세대들에게 재유행하고 있다."]'::jsonb, 2, '필름 사진의 색감은 약품 처리를 할 때 생긴다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 39, '이 대화 전의 내용으로 가장 알맞은 것을 고르십시오.

여자: 그렇다면 정부는 지난 10년간 해양 생태계 개선 사업이 성공적
이었다고 판단한 거군요.
남자 : 네. 최근에 해양 생태계의 환경이 개선되고 있다는 지표가 나오자
사업의 확대 시행까지 검토하고 있습니다. 이 사업에 대해 일부 어업
인의 반대가 있는 것도 사실입니다. 바다 생물의 서식 환경이 개선되면
소득이 증대할 것이라 기대했으나 어획량은 기대만큼 늘지 않았기
때문입니다. 그러나 해양 생태계를 건강하게 만드는 것은 장기적인
관점에서 어업인들의 소득 증대로 이어질 수 있습니다. 사업의 필요
성에 대한 공감대를 넓혀 나가는 노력을 해야 할 것입니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["바다 생태계 환경을 평가하는 지표가 개발됐다.","정부는 해양 생태계 개선 사업을 긍정적으로 평가했다.","어업인의 소득을 늘리기 위한 새로운 정책안이 발표됐다.","사업의 실효성에 대해 의문을 제기하는 언론 보도가 있었다."]'::jsonb, 2, '정부는 해양 생태계 개선 사업을 긍정적으로 평가했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 40, '들은 내용과 같은 것을 고르십시오.

여자: 그렇다면 정부는 지난 10년간 해양 생태계 개선 사업이 성공적
이었다고 판단한 거군요.
남자 : 네. 최근에 해양 생태계의 환경이 개선되고 있다는 지표가 나오자
사업의 확대 시행까지 검토하고 있습니다. 이 사업에 대해 일부 어업
인의 반대가 있는 것도 사실입니다. 바다 생물의 서식 환경이 개선되면
소득이 증대할 것이라 기대했으나 어획량은 기대만큼 늘지 않았기
때문입니다. 그러나 해양 생태계를 건강하게 만드는 것은 장기적인
관점에서 어업인들의 소득 증대로 이어질 수 있습니다. 사업의 필요
성에 대한 공감대를 넓혀 나가는 노력을 해야 할 것입니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["어업인들은 이 사업의 확대 시행을 주장하고 있다.","정부가 경제적인 이유로 사업 중단을 검토 중이다.","이 사업은 이번에 시작해 향후 10년 동안 진행된다.","어업인들은 이 사업을 통해 소득이 늘 것으로 기대했다."]'::jsonb, 2, '어업인들은 이 사업을 통해 소득이 늘 것으로 기대했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 41, '이 강연의 중심 내용으로 가장 알맞은 것을 고르십시오.

여자 : 자, 이것이 화성 탐사선입니다. 여기 바퀴를 자세히 보면 이렇게 접혀
있는 부분이 보이죠? 탐사선은 화성의 울퉁불퉁한 표면을 달려야
하는데요. 종이 접기 기술이 적용된 이 부분을 펼쳤다 접었다 하면
양쪽 바퀴의 크기를 유연하게 바꿀 수 있어 균형 잡기가 쉽습니다.
만약 바퀴를 변형하는 데 기계 장치를 활용했다면 나사나 이음매 등
많은 부품이 필요했을 테고 구동 방식도 굉장히 복잡했을 겁니다.
하지만 종이 접기 기술이 활용된 이 바퀴는 특별한 부품 없이 접는
선이 새겨진 얇은 판 한 장만으로 만들어졌습니다. 또 판을 접었다
펴는 단순한 작동 원리로 기능을 효과적으로 수행할 것입니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["탐사선의 기능에 따라 바퀴를 접는 방식이 달라진다.","화성 탐사선에 종이 접기 기술이 유용하게 활용된다.","지구 밖을 탐사하기 위한 인간의 노력이 이어지고 있다.","작은 부품이 기계를 구동하는 데에 결정적인 역할을 한다."]'::jsonb, 2, '화성 탐사선에 종이 접기 기술이 유용하게 활용된다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 42, '들은 내용과 같은 것을 고르십시오.

여자 : 자, 이것이 화성 탐사선입니다. 여기 바퀴를 자세히 보면 이렇게 접혀
있는 부분이 보이죠? 탐사선은 화성의 울퉁불퉁한 표면을 달려야
하는데요. 종이 접기 기술이 적용된 이 부분을 펼쳤다 접었다 하면
양쪽 바퀴의 크기를 유연하게 바꿀 수 있어 균형 잡기가 쉽습니다.
만약 바퀴를 변형하는 데 기계 장치를 활용했다면 나사나 이음매 등
많은 부품이 필요했을 테고 구동 방식도 굉장히 복잡했을 겁니다.
하지만 종이 접기 기술이 활용된 이 바퀴는 특별한 부품 없이 접는
선이 새겨진 얇은 판 한 장만으로 만들어졌습니다. 또 판을 접었다
펴는 단순한 작동 원리로 기능을 효과적으로 수행할 것입니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 바퀴에는 많은 부품이 들어간다.","이 바퀴는 평면의 얇은 판을 접어서 만든다.","이 바퀴가 접히는 부분에는 종이가 부착된다.","이 바퀴는 양쪽이 같은 크기로 고정되어 있다."]'::jsonb, 2, '이 바퀴는 평면의 얇은 판을 접어서 만든다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 43, '무엇에 대한 내용인지 알맞은 것을 고르십시오.

남자: 지금 흥미로운 실험이 진행 중이다. 참가자들은 1분 동안 수백 장의
사진을 본다. 꽃, 책상, 사슴 등의 사진이 빠르게 지나간다. 그 사이로
인상을 쓴 얼굴 사진 하나가 스쳐 간다. 순간, 참가자들의 뇌에서
편도체가 활성화된다. 실험이 끝난 뒤, 참가자들은 수많은 사진 중
인상 쓴 얼굴을 또렷이 기억했다. 편도체가 그것을 생존을 위협하는
요소로 인식해 재빨리 기억하도록 했기 때문이다. 특정 장면에 대한
공포는 생존을 위한 뇌의 학습 결과인 것이다. 동물도 마찬가지다.
쥐는 고양이를 만나면 공포를 느끼고 도망친다. 하지만 편도체가
손상된 쥐는 천적에 대한 기억이 없어 위험에 그대로 노출된다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["뇌에 의한 착각 현상","시간을 인식하는 뇌의 부위","생존을 위한 뇌의 작동 방식","손상된 뇌로 인한 특이 반응"]'::jsonb, 2, '생존을 위한 뇌의 작동 방식', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 44, '참가자들이 얼굴 사진을 기억한 이유로 맞는 것을 고르십시오.

남자: 지금 흥미로운 실험이 진행 중이다. 참가자들은 1분 동안 수백 장의
사진을 본다. 꽃, 책상, 사슴 등의 사진이 빠르게 지나간다. 그 사이로
인상을 쓴 얼굴 사진 하나가 스쳐 간다. 순간, 참가자들의 뇌에서
편도체가 활성화된다. 실험이 끝난 뒤, 참가자들은 수많은 사진 중
인상 쓴 얼굴을 또렷이 기억했다. 편도체가 그것을 생존을 위협하는
요소로 인식해 재빨리 기억하도록 했기 때문이다. 특정 장면에 대한
공포는 생존을 위한 뇌의 학습 결과인 것이다. 동물도 마찬가지다.
쥐는 고양이를 만나면 공포를 느끼고 도망친다. 하지만 편도체가
손상된 쥐는 천적에 대한 기억이 없어 위험에 그대로 노출된다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["익숙함을 느꼈기 때문에","반복적으로 노출되었기 때문에","위험한 요소로 받아들였기 때문에","다른 사진과 공통점을 발견했기 때문에"]'::jsonb, 2, '위험한 요소로 받아들였기 때문에', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 45, '들은 내용과 같은 것을 고르십시오.

여자 : 조선 시대, 왕실의 행사에는 늘 장악원의 음악인들이 있었습니다.
장악원은 조선의 국가 음악 기관으로서 궁중 음악에 관한 모든
일을 관장했는데요. 각종 행사에 맞는 다양한 연주 방법과 횟수는
물론, 천여 명에 달하는 소속 음악인들의 연습 일정까지 법으로 정해
놓을 만큼 철저하게 운영되었습니다. 또 내부 교육 기관을 두어 전문
음악인을 양성하고, 연주에 필요한 악기를 직접 제작하는 것도 장악원
에서 담당했습니다. 당시 장악원의 음악적 완성도는 상당한 수준이
었는데요. 그들의 음악은 궁중 의례에 경건함을 더하고 왕실에 권위를
부여해 주는 핵심 요소였습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["장악원의 운영 방식은 법으로 규정되어 있었다.","장악원은 소수의 전문 음악인들로 이루어졌다.","장악원에 소속된 음악인을 교육하는 외부 기관이 존재했다.","장악원의 음악은 행사에 관계없이 일정한 형식을 갖추었다."]'::jsonb, 2, '장악원의 운영 방식은 법으로 규정되어 있었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 46, '여자가 말하는 방식으로 알맞은 것을 고르십시오.

여자 : 조선 시대, 왕실의 행사에는 늘 장악원의 음악인들이 있었습니다.
장악원은 조선의 국가 음악 기관으로서 궁중 음악에 관한 모든
일을 관장했는데요. 각종 행사에 맞는 다양한 연주 방법과 횟수는
물론, 천여 명에 달하는 소속 음악인들의 연습 일정까지 법으로 정해
놓을 만큼 철저하게 운영되었습니다. 또 내부 교육 기관을 두어 전문
음악인을 양성하고, 연주에 필요한 악기를 직접 제작하는 것도 장악원
에서 담당했습니다. 당시 장악원의 음악적 완성도는 상당한 수준이
었는데요. 그들의 음악은 궁중 의례에 경건함을 더하고 왕실에 권위를
부여해 주는 핵심 요소였습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["장악원의 연주 장면을 묘사하고 있다.","장악원을 다른 기관과 비교하고 있다.","장악원의 변천 과정을 요약하고 있다.","장악원이 담당한 역할을 설명하고 있다."]'::jsonb, 2, '장악원이 담당한 역할을 설명하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 47, '들은 내용과 같은 것을 고르십시오.

여자 : 박사님, 과거에는 한 국가의 경쟁력을 평가할 때 돈과 같은 물질
자본이 주된 기준이었는데요. 최근 경제학에서는 사회적 자본이
더 중요한 지표로 언급되고 있습니다.
남자 : 네. 사회적 자본이 갖는 경제적 가치가 입증되었기 때문이죠. 사회적
자본은 구성원들 간의 신뢰를 측정한 값으로 정의되는데요. 사회적
자본이 확보되면 불신으로 인해 발생하는 불필요한 절차나 거래 비용이
줄어 일의 처리가 빨라집니다. 그럼 사회 전체의 효율성과 수익성이
높아지고 이는 곧 경제적 자본의 성장으로 이어지죠. 이처럼 사회적
자본은 경제 성장의 원동력이 된다는 점에서 매우 중요합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["경제학에서는 사회적 자본에 대한 연구가 미비하다.","경제학에서는 물질 자본을 더 중요한 지표로 삼는다.","사회적 자본은 구성원들의 신뢰 정도를 측정한 것이다.","사회적 자본은 높은 거래 비용을 요구하는 경우가 많다."]'::jsonb, 2, '사회적 자본은 구성원들의 신뢰 정도를 측정한 것이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 48, '남자의 태도로 알맞은 것을 고르십시오.

여자 : 박사님, 과거에는 한 국가의 경쟁력을 평가할 때 돈과 같은 물질
자본이 주된 기준이었는데요. 최근 경제학에서는 사회적 자본이
더 중요한 지표로 언급되고 있습니다.
남자 : 네. 사회적 자본이 갖는 경제적 가치가 입증되었기 때문이죠. 사회적
자본은 구성원들 간의 신뢰를 측정한 값으로 정의되는데요. 사회적
자본이 확보되면 불신으로 인해 발생하는 불필요한 절차나 거래 비용이
줄어 일의 처리가 빨라집니다. 그럼 사회 전체의 효율성과 수익성이
높아지고 이는 곧 경제적 자본의 성장으로 이어지죠. 이처럼 사회적
자본은 경제 성장의 원동력이 된다는 점에서 매우 중요합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["사회적 자본의 가치를 높이 평가하고 있다.","사회적 자본의 활용 방안을 검토하고 있다.","사회적 자본에 대한 맹신을 경계하고 있다.","사회적 자본이 미칠 영향을 우려하고 있다."]'::jsonb, 2, '사회적 자본의 가치를 높이 평가하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 49, '들은 내용과 같은 것을 고르십시오.

남자: 여러분은 사법 재판에서 가장 중요한 건 무엇이라고 생각하시나요?
아마도 공정함을 꼽을 것입니다. 많은 국가들이 이 공정함이라는 원칙을
수호하기 위해 심급 제도를 시행하고 있는데요. 이는 한 사건에 대해
서로 다른 급의 법원에서 재판을 받을 수 있도록 보장하는 제도입니다.
만약 하급심의 법관이 법을 잘못 해석했거나, 판결이 부당하다고 판단
하면 누구나 이 제도를 통해 상급 법원에 다시 재판을 청구할 수 있지요.
하지만 이 과정에는 많은 시간과 인적 자원이 소요되는 것이 사실입
니다. 그래서 일부에서는 재판의 신속성을 위해 제도를 간소화하자는
목소리도 있습니다. 그럼에도 불구하고 심급 제도는 법 앞의 공정함을
실현하도록 한다는 점에서 반드시 필요한 제도라 할 수 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 제도는 재판의 신속성을 목적으로 한다.","이 제도는 많은 국가에서 시행을 앞두고 있다.","이 제도는 특정 사건에 한해 제한적으로 적용된다.","이 제도는 상급 법원에 재판을 청구할 권리를 보장한다."]'::jsonb, 2, '이 제도는 상급 법원에 재판을 청구할 권리를 보장한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'listening', 50, '남자의 태도로 알맞은 것을 고르십시오.

남자: 여러분은 사법 재판에서 가장 중요한 건 무엇이라고 생각하시나요?
아마도 공정함을 꼽을 것입니다. 많은 국가들이 이 공정함이라는 원칙을
수호하기 위해 심급 제도를 시행하고 있는데요. 이는 한 사건에 대해
서로 다른 급의 법원에서 재판을 받을 수 있도록 보장하는 제도입니다.
만약 하급심의 법관이 법을 잘못 해석했거나, 판결이 부당하다고 판단
하면 누구나 이 제도를 통해 상급 법원에 다시 재판을 청구할 수 있지요.
하지만 이 과정에는 많은 시간과 인적 자원이 소요되는 것이 사실입
니다. 그래서 일부에서는 재판의 신속성을 위해 제도를 간소화하자는
목소리도 있습니다. 그럼에도 불구하고 심급 제도는 법 앞의 공정함을
실현하도록 한다는 점에서 반드시 필요한 제도라 할 수 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/audio/83-TOPIK-II-Listening-Audio-File.mp3', NULL, '["제도의 새로운 변화를 기대하고 있다.","제도의 필요성과 의의를 강조하고 있다.","제도의 개선 방향에 적극 동의하고 있다.","제도의 확대 적용을 강력하게 주장하고 있다."]'::jsonb, 2, '제도의 필요성과 의의를 강조하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 1, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오. (각 2점)

책을 많이( ........................ ) 지식을 쌓을 수 있다.', NULL, NULL, NULL, '["읽으면","읽든지","읽지만","읽거나"]'::jsonb, 2, '읽으면', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 2, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오. (각 2점)

꽃이 피기 시작하는 걸 보니 봄이( ........................ ).', NULL, NULL, NULL, '["오곤 한다","온 모양이다","오는 편이다","온 적이 있다"]'::jsonb, 2, '온 모양이다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 3, '밑줄 친 부분과 의미가 가장 비슷한 것을 고르십시오.

시험이 시작되자 교실은 숨소리가 <span class=''underline''>들릴 만큼</span> 조용해졌다.', NULL, NULL, NULL, '["들리다가","들리더라도","들릴 정도로","들릴 때까지"]'::jsonb, 2, '들릴 정도로', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 4, '밑줄 친 부분과 의미가 가장 비슷한 것을 고르십시오.

집의 분위기는 <span class=''underline''>꾸미기 나름이다</span>.', NULL, NULL, NULL, '["꾸밀 만하다","꾸미기가 쉽다","꾸밀 수도 있다","꾸미기에 달려 있다"]'::jsonb, 2, '꾸미기에 달려 있다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 5, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/reading/q5.png', NULL, NULL, '["안경","침대","운동화","노트북"]'::jsonb, 2, '운동화', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 6, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/reading/q6.png', NULL, NULL, '["공원","식당","꽃집","서점"]'::jsonb, 2, '식당', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 7, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/reading/q7.png', NULL, NULL, '["환경 보호","생활 예절","건강 관리","봉사 활동"]'::jsonb, 2, '생활 예절', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 8, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/reading/q8.png', NULL, NULL, '["안전 규칙","신청 방법","사용 순서","교환 안내"]'::jsonb, 2, '안전 규칙', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 9, '다음 글의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/reading/q9.png', NULL, NULL, '["이 행사는 한 달 동안 진행된다.","사진은 이메일로 제출해야 한다.","인주시에서 올해 찍은 사진을 내면 된다.","이 행사에 참여하면 인주시의 옛날 사진을 받는다."]'::jsonb, 2, '이 행사는 한 달 동안 진행된다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 10, '다음 글 또는 그래프의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-83/reading/q10.png', NULL, NULL, '["용돈 중 물건 구입비의 비율이 가장 낮았다.","학원비 사용은 교통비보다 두 배 이상 많았다.","대학생들은 용돈의 절반 이상을 식비로 지출했다.","대학생들은 문화생활비보다 교통비를 더 적게 사용했다."]'::jsonb, 2, '대학생들은 용돈의 절반 이상을 식비로 지출했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 11, '다음 글의 내용과 같은 것을 고르십시오.

그림책 작가 이수지 씨가 한국인 최초로 어린이책 노벨상이라는 안데르센 상을 받아 주목받고 있다. 이 상은 1956년에 만들어진 상으로 작가가 발표한 모든 작품을 대상으로 심사한다. 이 작가는 어린이들이 꿈꾸고 상상하는 세계를 그림으로 잘 표현해 낸다는 평을 받았다.', NULL, NULL, NULL, '["이 작가가 받은 상은 작년에 만들어졌다.","이 작가는 한국인 중 처음으로 이 상을 받았다.","이 작가는 자신이 직접 경험한 이야기를 그림으로 표현했다.","이 작가는 자신의 작품 중 한 편을 골라 심사 대상으로 제출했다."]'::jsonb, 2, '이 작가는 한국인 중 처음으로 이 상을 받았다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 12, '다음 글의 내용과 같은 것을 고르십시오.

17일 오전 6시 22분 인주시에서 규모 3.2의 지진이 발생했다. 이날 지진은 올해 인주시에서 발생한 지진 중 가장 큰 규모다. 119 상황실에는 지진을 느낀 시민들의 신고가 여러 건 접수됐다. 그러나 이번 지진으로 입은 큰 피해는 없는 것으로 조사됐다. 기상청은 이번 주 내로 규모 2.0 정도의 지진이 몇 번 더 발생할 것으로 보고 있다.', NULL, NULL, NULL, '["이번 지진은 늦은 밤에 일어났다.","시민들이 지진을 느껴 상황실에 신고를 했다.","이번 지진으로 큰 피해를 입은 사람들이 많다.","이번 주에는 더 이상 지진이 일어나지 않을 것이다."]'::jsonb, 2, '시민들이 지진을 느껴 상황실에 신고를 했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 13, '다음을 순서에 맞게 배열한 것을 고르십시오.

(가) 그러나 이를 닦을 때는 순서에 맞춰 닦는 것이 좋다.
(나) 사람들은 보통 이를 닦을 때 순서에 별로 신경 쓰지 않는다.
(다) 전문가들은 안쪽 구석에서부터 앞쪽 방향이 좋다고 조언한다.
(라) 안쪽 이가 상하기 쉬워서 더 꼼꼼하게 닦아야 하기 때문이다.', NULL, NULL, NULL, '["(나)-(가)-(다) - (라)","(나)-(라)-(가)-(다)","(다)-(가)-(라) - (나)","(다)-(나)-(라) - (가)"]'::jsonb, 2, '(나)-(가)-(다) - (라)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 14, '다음을 순서에 맞게 배열한 것을 고르십시오.

(가) 그 사업이 쉽지는 않겠지만 한번 시도해 보고 싶다.
(나) 친구들은 마지막까지 퇴사를 다시 고민해 보라고 했다.
(다) 내일은 내가 10년 동안 다니던 회사를 그만두는 날이다.
(라) 하지만 나는 오랫동안 생각해 온 사업을 시작해 보려고 한다.', NULL, NULL, NULL, '["(나)-(가)-(라) - (다)","(나)-(다)-(가) - (라)","(다)-(라)-(가)-(나)","(다)-(나)-(라) - (가)"]'::jsonb, 2, '(다)-(나)-(라) - (가)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 15, '다음을 순서에 맞게 배열한 것을 고르십시오.

(가) 모래시계는 모래를 이용해 일정 단위의 시간을 재는 기구이다.
(나) 또한 모래시계의 구멍 크기를 통해서도 시간 단위를 조절한다.
(다) 구멍 크기가 작을수록 큰 시간 단위의 모래시계를 만들 수 있다.
(라) 모래의 양을 조절하면 다양한 시간 단위의 모래시계를 만들 수 있다.', NULL, NULL, NULL, '["(가)-(다)-(나)-(라)","(가)-(라)-(나)-(다)","(라)-(다)-(나)-(가)","(라)-(가)-(다)-(나)"]'::jsonb, 2, '(가)-(라)-(나)-(다)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 16, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

필름형 스피커는 종이보다 얇고 투명해서( ........................ ) 사용할 수 있다. 이 스피커를 활용하면 컴퓨터 화면이나 액자뿐만 아니라 벽이나 천장에서도 소리가 나오게 할 수 있다. 또 소재가 부드러워서 옷이나 커튼에 달아도 불편함 없이 사용이 가능하다.', NULL, NULL, NULL, '["소리 크기를 높여","단독 형태로 분리해","다양한 물건에 붙여","특수한 영역을 제한해"]'::jsonb, 2, '다양한 물건에 붙여', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 17, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

여권은 국제 신분증으로 통할 뿐만 아니라 한 국가의 정체성과 문화를 드러내기도 한다. 그래서 많은 국가들은 여권의 ( ........................ ) 결정 한다. 여권 표지의 색깔을 국가의 상징색으로 표현하거나 국가를 상징하는 문양을 넣기도 한다. 또한 여권에 불빛이 비치면 주요 문화재가 화려하게 보이도록 한 것도 있다.', NULL, NULL, NULL, '["두께를 자율적으로","디자인을 신중하게","이용 범위를 확실히","발급 방식을 구체적으로"]'::jsonb, 2, '디자인을 신중하게', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 18, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

얼마 전 일본에서만 사는 텃새 두 마리가 한국의 작은 섬에서 발견됐다. 텃새는 자리를 옮기지 않고 한 지역에서만 살기 때문에 장거리 이동을 거의 하지 않는다. 따라서 전문가는 이번에 발견된 텃새가 태풍에 휩쓸려 한국에 온 것으로 추측된다며 이 섬에서( ........................ ) 것이 매우 보기 드문 사례라고 언급했다.', NULL, NULL, NULL, '["살던 텃새가 줄어든","한국의 텃새가 사라진","일본의 텃새가 관찰된","부상당한 텃새가 보호된"]'::jsonb, 2, '일본의 텃새가 관찰된', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 19, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

흥미와 재미 요소를 내세워 홍보하는 마케팅 전략이 주목받고 있다. 이런 마케팅은 소비자의 호기심을 자극해 구매로 이어지게 한다. 그러나 제품의 품질이 소비자의 기대에 미치지 못하는 경우( ........................ ) 브랜드 이미지까지 나빠지기도 한다. 실제로 한 햄버거 회사에서 ''주머니 버거'', ''눌러 먹는 버거''를 만들어 소비자의 관심을 끌었지만 품질이 기대에 못 미치자 회사의 다른 제품까지 판매가 감소한 경우가 있었다.', NULL, NULL, NULL, '["과연","비록","차라리","오히려"]'::jsonb, 2, '오히려', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 20, '윗글의 주제로 가장 알맞은 것을 고르십시오.

흥미와 재미 요소를 내세워 홍보하는 마케팅 전략이 주목받고 있다. 이런 마케팅은 소비자의 호기심을 자극해 구매로 이어지게 한다. 그러나 제품의 품질이 소비자의 기대에 미치지 못하는 경우( ........................ ) 브랜드 이미지까지 나빠지기도 한다. 실제로 한 햄버거 회사에서 ''주머니 버거'', ''눌러 먹는 버거''를 만들어 소비자의 관심을 끌었지만 품질이 기대에 못 미치자 회사의 다른 제품까지 판매가 감소한 경우가 있었다.', NULL, NULL, NULL, '["마케팅도 중요하지만 제품의 품질이 더 중요하다.","식품 기업은 먼저 소비자의 요구를 확인해야 한다.","제품에 재미 요소를 포함하는 마케팅 전략이 필요하다.","특이한 제품보다 소비자에게 익숙한 것이 홍보에 더 좋다."]'::jsonb, 2, '마케팅도 중요하지만 제품의 품질이 더 중요하다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 21, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

소방관은 재난 현장에서 끔찍한 상황을 자주 접하기 때문에 정신 건강에 위험이 따른다. 최근 이러한 문제가 심각해지자 인주시가 해결을 위해 ( ........................ ). 인주시는 빠른 시일 내에 정신 건강에 대해 조사를 실시하고 문제를 겪는 소방관이 있으면 전문 상담사를 보내 상담을 진행 하기로 했다. 이와 더불어 심리 안정 프로그램 개발과 진료비 지원을 위한 예산을 확보했다고 발표했다.', NULL, NULL, NULL, '["등 떠밀었다","눈을 맞췄다","발 벗고 나섰다","손에 땀을 쥐었다"]'::jsonb, 2, '발 벗고 나섰다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 22, '윗글의 내용과 같은 것을 고르십시오.

소방관은 재난 현장에서 끔찍한 상황을 자주 접하기 때문에 정신 건강에 위험이 따른다. 최근 이러한 문제가 심각해지자 인주시가 해결을 위해 ( ........................ ). 인주시는 빠른 시일 내에 정신 건강에 대해 조사를 실시하고 문제를 겪는 소방관이 있으면 전문 상담사를 보내 상담을 진행 하기로 했다. 이와 더불어 심리 안정 프로그램 개발과 진료비 지원을 위한 예산을 확보했다고 발표했다.', NULL, NULL, NULL, '["소방관의 심리적 어려움은 최근 많이 해소되었다.","인주시는 소방관의 정신 건강 조사를 모두 마쳤다.","인주시는 소방관 심리 안정 프로그램을 운영할 계획이다.","소방관이 정신 건강 상담을 받으려면 상담사를 찾아가야 한다."]'::jsonb, 2, '인주시는 소방관 심리 안정 프로그램을 운영할 계획이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 23, '밑줄 친 부분에 나타난 ''나''의 심정으로 가장 알맞은 것을 고르십시오.

며칠 전 창고 선반 위에 올려 둔 가방을 꺼내는데 공책 한 권이 툭 하고 떨어졌다. 나는 ''뭐지?'' 하고 별 생각 없이 안을 펼쳐 보고는 <span class=''underline''>눈물이 왈칵 나올 뻔했다</span>. 그것은 바로 어렸을 때 돌아가신 아버지의 일기장이었다. 아버지 물건이 아직도 집에 남아 있을 줄은 전혀 생각하지 못했다. 두근거리는 마음으로 거실로 나와 일기장을 펼쳤다. 30년 전 날짜가 적힌 일기장의 누렇게 변한 페이지마다 아버지의 하루하루가 적혀 있었다. 내가 초등학교에 입학한 날, 여행한 날, 혼났던 날....... 그때의 추억들이 펼쳐졌다. 아버지는 언제 어디서 무엇을 하셨는지 빼곡히 적어 두셨다. 일기장에 적혀 있는 곳을 인터넷으로 찾아보니 자주 가시던 빵집과 국숫집이 아직도 그대로 있었다. 그곳에 가면 아버지의 흔적을 느낄 수 있을까? 나는 이번 주말에 일기장에 적혀 있는 곳에 한번 찾아가 보려고 한다.', NULL, NULL, NULL, '["반갑고 감격스럽다","편하고 만족스럽다","아쉽고 걱정스럽다","기쁘고 자랑스럽다"]'::jsonb, 2, '반갑고 감격스럽다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 24, '윗글의 내용과 같은 것을 고르십시오.

며칠 전 창고 선반 위에 올려 둔 가방을 꺼내는데 공책 한 권이 툭 하고 떨어졌다. 나는 ''뭐지?'' 하고 별 생각 없이 안을 펼쳐 보고는 <span class=''underline''>눈물이 왈칵 나올 뻔했다</span>. 그것은 바로 어렸을 때 돌아가신 아버지의 일기장이었다. 아버지 물건이 아직도 집에 남아 있을 줄은 전혀 생각하지 못했다. 두근거리는 마음으로 거실로 나와 일기장을 펼쳤다. 30년 전 날짜가 적힌 일기장의 누렇게 변한 페이지마다 아버지의 하루하루가 적혀 있었다. 내가 초등학교에 입학한 날, 여행한 날, 혼났던 날....... 그때의 추억들이 펼쳐졌다. 아버지는 언제 어디서 무엇을 하셨는지 빼곡히 적어 두셨다. 일기장에 적혀 있는 곳을 인터넷으로 찾아보니 자주 가시던 빵집과 국숫집이 아직도 그대로 있었다. 그곳에 가면 아버지의 흔적을 느낄 수 있을까? 나는 이번 주말에 일기장에 적혀 있는 곳에 한번 찾아가 보려고 한다.', NULL, NULL, NULL, '["나는 아버지의 물건을 많이 가지고 있다.","나는 전에 아버지의 일기장을 자주 꺼내 읽었다.","나는 거실에 아버지의 일기장을 보관하고 있었다.","나는 아버지가 자주 가시던 빵집에 가 보려고 한다."]'::jsonb, 2, '나는 아버지가 자주 가시던 빵집에 가 보려고 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 25, '다음 신문 기사의 제목을 가장 잘 설명한 것을 고르십시오.

드라마 ''진실'' 인기 효과, 원작 베스트셀러 1위', NULL, NULL, NULL, '["드라마 ''진실''이 인기를 얻으면서 원작이 판매량 1위를 차지했다.","드라마 ''진실''이 시청률 1위가 되자 원작 작가에 대한 관심이 높아졌다.","드라마 ''진실''의 인기로 원작 작가의 모든 작품들의 판매율이 상승했다.","드라마 ''진실''이 원작의 인기 요소를 추가해 시청률 1위의 드라마가 됐다."]'::jsonb, 2, '드라마 ''진실''이 인기를 얻으면서 원작이 판매량 1위를 차지했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 26, '다음 신문 기사의 제목을 가장 잘 설명한 것을 고르십시오.

기습 폭우에 차량 ''엉금엉금'', 출근길 정체', NULL, NULL, NULL, '["폭우로 피해를 입은 차량들이 늘면서 사람들의 출근이 늦어졌다.","큰비에 차량 사고가 잇따르면서 출근하던 사람들이 곤란을 겪었다.","갑자기 많이 쏟아진 비로 차들이 천천히 운행하면서 출근길이 막혔다.","계속된 비에 대중교통 이용자가 한꺼번에 몰리면서 출근길이 혼잡해졌다."]'::jsonb, 2, '갑자기 많이 쏟아진 비로 차들이 천천히 운행하면서 출근길이 막혔다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 27, '다음 신문 기사의 제목을 가장 잘 설명한 것을 고르십시오.

온라인 거래 사기 급증, 정부 대책 마련은 미흡', NULL, NULL, NULL, '["온라인 거래 사기가 늘었지만 정부의 대책 마련은 충분하지 않다.","온라인 시장에서 거래 사기가 증가해 정부가 대책을 수립하고 있다.","온라인 거래 사기를 막기 위해 마련한 정부의 대책은 큰 효과가 없었다.","온라인 거래 사기 피해자들을 위해 정부가 대책을 마련하겠다고 발표했다."]'::jsonb, 2, '온라인 거래 사기가 늘었지만 정부의 대책 마련은 충분하지 않다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 28, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

최근 한국의 편의점 업체가 해외로 진출하면서 현지에서 큰 인기를 끌고 있다. 인테리어에서 판매 상품까지( ........................ ) 전략을 썼기 때문이다. 보통 마트가 해외에 진출할 때는 현지인의 취향에 맞추려고 하는데 이 편의점 업체는 이와 반대되는 방법을 써서 성공한 것이다.', NULL, NULL, NULL, '["빠뜨리지 않고 홍보하는","판매자의 기호에 맞추는","편의점의 특성을 최대한 감추는","한국 편의점을 그대로 재현하는"]'::jsonb, 2, '한국 편의점을 그대로 재현하는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 29, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

고대 이집트 피라미드를 건축할 때 거대한 바위를 모래 위에서 운반해야 했는데 이를 위해서는( ........................ ) 기술이 중요했다. 모래에 수분이 일정하게 유지되면 모랫길이 단단해져서 운반이 수월했기 때문이다. 실제로 고대 벽화에는 바위를 운반하는 길 위에 사람들이 물을 뿌리고 있는 장면이 묘사되어 있다.', NULL, NULL, NULL, '["적정량의 물을 뿌리는","모래를 부드럽게 만드는","바위의 무게를 계산하는","운반하는 사람들을 배치하는"]'::jsonb, 2, '적정량의 물을 뿌리는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 30, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

일부 프로 농구 리그에서는 반드시 주황색 공을 쓰게 하고 있다. 여러 이유가 있지만 그중 하나는 ( ........................ )데 있다. 바닥에 공을 많이 튕겨야 하는 농구의 특성상 공이 바닥의 색과 많이 다르면 선수나 관중 모두 부담을 느낄 수 있기 때문이다.', NULL, NULL, NULL, '["골을 잘 넣게 하려는","공이 잘 보이게 하려는","눈의 피로감을 줄이려는","선수들의 운동복과 구별하려는"]'::jsonb, 2, '공이 잘 보이게 하려는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 31, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

''가면 증후군''이란 사회적으로 인정을 받고 있지만 그것이 자신의 진짜 실력 때문이 아니라는 생각으로 괴로워하는 현상이다. 성과를 내고 있음에도 ( ........................ ) 언젠가 가면이 벗겨질지도 모른다는 생각에 불안해 하는 것이다. 이런 현상이 생긴 원인은 다양한데 양육 과정에서 부모의 인정을 받지 못했거나 겸손을 강조하는 분위기 속에서 자랐기 때문이다.', NULL, NULL, NULL, '["일을 계속 미루면서","타인의 평가를 원하면서","낮은 지위에 머무르면서","자신의 능력을 의심하면서"]'::jsonb, 2, '자신의 능력을 의심하면서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 32, '다음을 읽고 글의 내용과 같은 것을 고르십시오.

오케스트라는 연주하기 전에 악기들의 음을 서로 맞춰 보는 과정을 거친다. 그때 오케스트라의 한가운데에 자리 잡은 오보에가 기준 음을 낸다. 오보에는 다른 관악기와 달리 나무 떨림판인 ''리드''를 두 장 겹쳐 사용해서 소리가 더 정확하고 또렷하기 때문이다. 또 음을 안정적으로 길게 유지할 수 있어서 다른 악기들이 음을 쉽게 맞출 수 있도록 해 준다.', NULL, NULL, NULL, '["오보에는 다른 악기와 달리 리드 하나로 음을 낸다.","오보에의 첫 음과 함께 오케스트라 연주가 시작된다.","오보에는 소리가 작아서 오케스트라의 앞쪽에 위치한다.","오보에는 오케스트라에서 소리를 맞출 때 기준 역할을 한다."]'::jsonb, 2, '오보에는 오케스트라에서 소리를 맞출 때 기준 역할을 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 33, '다음을 읽고 글의 내용과 같은 것을 고르십시오.

애기장대는 각종 식물 실험에 빠지지 않고 등장하는 식물이다. 식물 중에서는 처음으로 유전체 해독이 완료되어 식물의 유전자 연구를 할 때 주로 이용된다. 전 세계에 고루 분포하고, 곤충의 도움 없이 씨앗을 맺을 수 있어서 재배도 쉽다. 또한 한 세대 기간이 6주 정도밖에 되지 않아 실험 결과를 빨리 확인할 수 있기 때문에 실험에 널리 이용되고 있다.', NULL, NULL, NULL, '["애기장대는 세계 곳곳에서 볼 수 있는 식물이다.","애기장대의 유전체 해독을 위한 연구가 진행 중이다.","애기장대가 씨앗을 만드는 데에 곤충의 역할이 필요하다.","애기장대는 성장 기간이 길어 유전자 연구에 효율적이다."]'::jsonb, 2, '애기장대는 세계 곳곳에서 볼 수 있는 식물이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 34, '다음을 읽고 글의 내용과 같은 것을 고르십시오.

아이가 ''엄마'' 다음으로 빨리 배우는 말 중에는 ''이것''과 같이 여러 물건을 가리키는 지시어가 있다. 지시어는 대화하는 상황을 타인과 공유해야 그 의미를 이해할 수 있다는 특성이 있다. 아기들은 이러한 지시어를 사용해 자연스럽게 부모의 관심을 끄는 것이다. 대부분의 아기들이 생후 12~18개월 무렵에 이런 지시어를 사용한다는 것은 이미 여러 언어 연구에서 밝혀진 바 있다.', NULL, NULL, NULL, '["아기는 혼잣말을 할 때 지시어를 자주 사용한다.","아기는 엄마라는 단어보다 지시어를 먼저 습득한다.","지시어를 습득하는 시기는 언어권마다 다르게 나타난다.","지시어는 상대방과 상황을 공유해야 의미를 전달할 수 있다."]'::jsonb, 2, '지시어는 상대방과 상황을 공유해야 의미를 전달할 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 35, '다음을 읽고 글의 주제로 가장 알맞은 것을 고르십시오.

대중을 대상으로 한 예술 입문서가 작품의 역사적 배경, 작가에 대한 일화 등 독자의 흥미를 끄는 이야기에 집중하는 경우를 많이 볼 수 있다. 작품에 관한 이런 지식은 작품 이해에 도움이 된다. 그러나 예술의 본질은 작품 그 자체에 있다. 작품 외적인 사실들보다 작품에 초점을 두고 작품의 구성 요소, 표현 방식 등을 충분히 설명하는 입문서가 늘어나기를 희망한다.', NULL, NULL, NULL, '["예술 입문서는 작품 외적인 사실들을 다양하게 다뤄야 한다.","작품 자체에 대해 충실히 소개하는 예술 입문서가 많아져야 한다.","대중이 예술 작품에 관해 궁금해 하는 것이 무엇인지 알아야 한다.","예술 입문서는 대중이 예술을 어려운 것이 아니라고 느끼게 해야 한다."]'::jsonb, 2, '작품 자체에 대해 충실히 소개하는 예술 입문서가 많아져야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 36, '다음을 읽고 글의 주제로 가장 알맞은 것을 고르십시오.

점자 표기의 위치, 방식 등이 제조사나 제품별로 달라 시각 장애인들이 불편과 혼란을 겪고 있다. 시각 장애인을 위한 점자 정보가 여러 제품에 표기되고는 있지만 아직 통일된 규정이 없기 때문이다. 현재는 의약품에 한해서만 표기 규정이 정해져 있다. 관계 기관은 더 많은 제품을 대상으로 점자 표기에 대한 규정을 정해야 한다.', NULL, NULL, NULL, '["의약품의 점자 표기 규정을 검토해야 한다.","점자 표기의 필요성에 대한 인식이 높아져야 한다.","제품에 잘못 표기된 점자 정보가 없는지 조사해야 한다.","다양한 제품에 적용할 점자 표기 규정이 마련되어야 한다."]'::jsonb, 2, '다양한 제품에 적용할 점자 표기 규정이 마련되어야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 37, '다음을 읽고 글의 주제로 가장 알맞은 것을 고르십시오.

''자기 길들이기''는 동물이 스스로 공격성을 억제하고 친화력을 높이는 방향으로 진화하는 현상을 말한다. 호모 사피엔스도 이것을 생존 전략으로 삼았다는 가설이 있다. 네안데르탈인은 호모 사피엔스보다 체격도 좋고 뇌의 용량도 컸지만 살아남지 못했다. 반면 호모 사피엔스는 서로를 포용하고 보호하는 친화력을 무기로 살아남았다. 높은 친화력으로 더 큰 집단을 형성 함으로써 외부의 공격과 환경 변화에 대응한 것이다.', NULL, NULL, NULL, '["자기 길들이기는 인간이 가진 고유한 특성이다.","자기 길들이기는 네안데르탈인의 생존 전략이었다.","호모 사피엔스는 신체 능력이 가장 뛰어난 종이었다.","호모 사피엔스는 높은 친화력 덕분에 생존할 수 있었다."]'::jsonb, 2, '호모 사피엔스는 높은 친화력 덕분에 생존할 수 있었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 38, '다음을 읽고 글의 주제로 가장 알맞은 것을 고르십시오.

뚜렷한 신념 없이 사안에 따라 의견을 바꾼다는 인식 때문에 중도층은 부정적 존재로 여겨진다. 그러나 이들에 대한 긍정적 평가도 있다. 주관 없이 흔들리는 것처럼 보이지만 쟁점에 대해 좀 더 유연하고 객관적으로 사고 한다고 보는 관점이다. 중도층의 의견이 정치적 양극화를 완화하고 합리적 으로 사회적 합의가 도출되도록 이끄는 토대가 될 수 있다는 것이다.', NULL, NULL, NULL, '["중도층은 사회적 쟁점에 대해 대체로 비판적인 태도를 취한다.","중도층은 사회가 균형을 이루며 발전하도록 돕는 역할을 할 수 있다.","정치적 신념을 적극적으로 표출하는 것은 사회의 발전에 도움이 된다.","정치적 사안에 대해 그때그때 의견을 바꾸는 것은 사회 발전을 저해한다."]'::jsonb, 2, '중도층은 사회가 균형을 이루며 발전하도록 돕는 역할을 할 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 39, '주어진 문장이 들어갈 곳으로 가장 알맞은 것을 고르십시오.

주어진 문장: 이 책은 크게 두 부분으로 구성되어 있는데 먼저 옛 다리들과 그에 얽힌 이야기를 다룬다.

이영천의 『다시, 오래된 다리를 거닐다』는 다리를 소재로 한국인의 삶을 돌아본 책이다.( ㉠ ) 여기에서는 수백 년 전에 놓인 징검다리, 왕을 위한 다리 등을 통해 우리 고유의 풍속과 역사를 만난다. ( ㉡ )이어서 근현대식 다리와 함께 기술의 발전이 다리와 우리 사회에 가져온 변화를 살펴본다.( ㉢ ) 이 책은 과거와 현재의 다리를 거닐며 우리가 지나온 길과 가야 할 길을 생각해 보게 한다. ( ㉣ )', NULL, NULL, NULL, '["㉠","㉡","㉢","㉣"]'::jsonb, 2, '㉠', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 40, '주어진 문장이 들어갈 곳으로 가장 알맞은 것을 고르십시오.

주어진 문장: 장 신경계는 주로 장 내의 근육 운동과 소화액을 조절하여 소화를 촉진하는 일을 한다.

뇌는 신경계를 통해 몸 전체의 움직임을 관장하는데 장의 경우에는 뇌의 명령 없이 자율적으로 작동하기도 한다.( ㉠ ) 생존에 필수적인 식사와 소화를 위해 장에 별도의 신경계를 두었기 때문이다.( ㉡ ) 한편 장 신경계가 오로지 장에만 관여하는 것은 아니다. ( ㉢ ) 과학자 들은 장 신경계와 뇌가 서로 소통하고 있어서 장의 문제가 심리적 변화에 영향을 줄 수 있다고 말한다. ( ㉣ )', NULL, NULL, NULL, '["㉠","㉡","㉢","㉣"]'::jsonb, 2, '㉡', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 41, '주어진 문장이 들어갈 곳으로 가장 알맞은 것을 고르십시오.

주어진 문장: 이처럼 정밀하면서도 실제와 같은 그림은 외부인이 궁궐에 침입할 목적 으로 사용할 수 있다.

동궐도는 창덕궁과 창경궁 전체를 그린 조선 시대의 그림이다. ( ㉠ ) 세로 2m, 가로 5m가 넘는 대작으로 건축물은 물론 주변의 산과 궁궐 안 연못, 나무까지 그대로 그려 넣었다. ( ㉡ ) 건물 배치와 건물 사이의 거리도 완벽하게 재현했다.( ㉢ ) 이러한 이유로 제작자와 제작 연도를 포함하여 그림에 관련된 정보 일체가 왕실 기밀이었을 것으로 추정된다. ( ㉣ )', NULL, NULL, NULL, '["㉠","㉡","㉢","㉣"]'::jsonb, 2, '㉢', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 42, '밑줄 친 부분에 나타난 ''부모님''의 심정으로 가장 알맞은 것을 고르십시오.

올해 서른두 살인 준은 어렸을 때부터 특출나게 뛰어난 재능이 없다는 점이 큰 불만이었다. 공부도 그럭저럭, 외모도 그럭저럭, 이었다. (중략) 특이한 재능이 있긴 했다. 준은 본능적으로 동서남북을 감지할 수 있었다. 어느 장소에 가든지 북쪽과 동쪽이 어디인지 본능적으로 느낄 수 있는 감각이었다. 이게 남들은 못하는 특이한 재능이란 걸 알게 된 건 가족들과 3박 4일 일정으로 포항에 놀러갔던 중학생 때였다. 부모님은 유명하다는 포항 바닷가의 해돋이를 꼭 보고 싶어했다. (중략)<br><br>"여보, 이쪽으로 걸어가면 되겠지? 동쪽이 저쪽인가?"<br>"아냐, 자기야 호텔 지배인이 선착장으로 가라고 했잖아. 그러니까 저기가 동쪽이지!"<br>"아냐, 엄마. 동쪽은 이쪽이잖아."(중략)<br>준은 후드 주머니에 꼼지락거리고 있던 손을 꺼내 반대편으로 가려는 부모를 잡았다. 준이 심드렁한 표정으로 반대쪽을 턱짓으로 가리키자 부모님은 고개를 갸웃했다.<br><br>"<span class=''underline''>네가 그걸 어떻게 알아?</span>"<br><br>"이 방향이 북쪽이잖아. 그러니까 동쪽은 이쪽이지." (중략) 처음에 부모님은 반신반의했지만, 준이 물어볼 때마다 오차 없이 정확히 맞추는 걸 확인하고는 자기들이 천재를 낳았다며 즐거워했다.', NULL, NULL, NULL, '["후회스럽다","의심스럽다","실망스럽다","짜증스럽다"]'::jsonb, 2, '의심스럽다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 43, '윗글의 내용으로 알 수 있는 것을 고르십시오.

올해 서른두 살인 준은 어렸을 때부터 특출나게 뛰어난 재능이 없다는 점이 큰 불만이었다. 공부도 그럭저럭, 외모도 그럭저럭, 이었다. (중략) 특이한 재능이 있긴 했다. 준은 본능적으로 동서남북을 감지할 수 있었다. 어느 장소에 가든지 북쪽과 동쪽이 어디인지 본능적으로 느낄 수 있는 감각이었다. 이게 남들은 못하는 특이한 재능이란 걸 알게 된 건 가족들과 3박 4일 일정으로 포항에 놀러갔던 중학생 때였다. 부모님은 유명하다는 포항 바닷가의 해돋이를 꼭 보고 싶어했다. (중략)<br><br>"여보, 이쪽으로 걸어가면 되겠지? 동쪽이 저쪽인가?"<br>"아냐, 자기야 호텔 지배인이 선착장으로 가라고 했잖아. 그러니까 저기가 동쪽이지!"<br>"아냐, 엄마. 동쪽은 이쪽이잖아."(중략)<br>준은 후드 주머니에 꼼지락거리고 있던 손을 꺼내 반대편으로 가려는 부모를 잡았다. 준이 심드렁한 표정으로 반대쪽을 턱짓으로 가리키자 부모님은 고개를 갸웃했다.<br><br>"<span class=''underline''>네가 그걸 어떻게 알아?</span>"<br><br>"이 방향이 북쪽이잖아. 그러니까 동쪽은 이쪽이지." (중략) 처음에 부모님은 반신반의했지만, 준이 물어볼 때마다 오차 없이 정확히 맞추는 걸 확인하고는 자기들이 천재를 낳았다며 즐거워했다.', NULL, NULL, NULL, '["준은 여행지에서 해 뜨는 방향을 한 번에 찾았다.","준의 부모님은 아들과 같은 능력을 가지고 있었다.","준은 공부를 잘해서 학교에서 모르는 사람이 없었다.","준의 부모님은 아들의 재능을 발견한 후 걱정하기 시작했다."]'::jsonb, 2, '준은 여행지에서 해 뜨는 방향을 한 번에 찾았다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 44, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

서양 역사에서는 15·16세기를 ''위대한 발견의 시대''라고 부른다. 콜럼버스 처럼 유럽의 많은 탐험가들이 금이나 향신료 등을 얻고자( ........................ ) 때문이다. 그러나 이 시대에 이루어진 발견의 진정한 의미는 대륙의 발견이 아니라 바다의 발견이었다. 탐험을 통해 지구상의 모든 바다가 하나로 이어져 있다는 인식이 생겼다는 것, 또 이러한 인식을 바탕으로 다양한 해상 항로를 발견한 것이 이 시대의 진정한 소산이라는 것이다. 실제로 탐험가들은 아프리카를 돌아 인도양, 더 나아가 극동까지 가는 바닷길을 열었고 콜럼버스도 대서양을 왕복할 수 있는 경로를 만들었다. 바닷길이 열리자 전 세계가 하나의 지구가 되었고 이로 인해 경제, 기술, 문화뿐만 아니라 생태계의 교환까지 이루어지는 계기가 마련되었다.', NULL, NULL, NULL, '["값비싼 물건을 매매했기","다양한 지도를 수집했기","미지의 땅을 찾아 떠났기","탐험에 대한 기록을 남겼기"]'::jsonb, 2, '미지의 땅을 찾아 떠났기', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 45, '윗글의 주제로 가장 알맞은 것을 고르십시오.

서양 역사에서는 15·16세기를 ''위대한 발견의 시대''라고 부른다. 콜럼버스 처럼 유럽의 많은 탐험가들이 금이나 향신료 등을 얻고자( ........................ ) 때문이다. 그러나 이 시대에 이루어진 발견의 진정한 의미는 대륙의 발견이 아니라 바다의 발견이었다. 탐험을 통해 지구상의 모든 바다가 하나로 이어져 있다는 인식이 생겼다는 것, 또 이러한 인식을 바탕으로 다양한 해상 항로를 발견한 것이 이 시대의 진정한 소산이라는 것이다. 실제로 탐험가들은 아프리카를 돌아 인도양, 더 나아가 극동까지 가는 바닷길을 열었고 콜럼버스도 대서양을 왕복할 수 있는 경로를 만들었다. 바닷길이 열리자 전 세계가 하나의 지구가 되었고 이로 인해 경제, 기술, 문화뿐만 아니라 생태계의 교환까지 이루어지는 계기가 마련되었다.', NULL, NULL, NULL, '["콜럼버스는 새로운 대륙을 개척하는 데 기여한 바가 크다.","신대륙 발견은 동방의 대륙 탐험을 시작하는 계기가 되었다.","신대륙 발견으로 대륙 간에 문물과 생물의 이동이 증가할 수 있었다.","유럽인들의 탐험은 항로를 만들어 세계를 연결시켰다는 데 의의가 있다."]'::jsonb, 2, '유럽인들의 탐험은 항로를 만들어 세계를 연결시켰다는 데 의의가 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 46, '윗글에 나타난 필자의 태도로 가장 알맞은 것을 고르십시오.

세계는 신에너지, 자동화, 우주여행 등이 주도하는 시대로 급속히 접어들고 있다. 세계 각국은 풍력, 태양광 등 재생 가능한 에너지를 개발하는 회사에 대한 정부 보조금을 늘리고 있고 그에 따라 대체 에너지의 사용 비율도 점차 증가하고 있다. 민간 우주 산업 육성을 위해 인공위성 주파수 사용과 우주선 발사 등에 대한 대대적인 규제 완화를 한 국가도 있다. 그 덕분에 한 민간 기업은 화성 여행이 가능한 호텔급 우주여행선을 제작할 수 있었다. 민간 기업이 과학 기술 개발을 주도하며 성장할 수 있게 된 것은 정부가 지원을 확대하면서도 간섭을 최소화했기 때문이다. 이처럼 과학 기술이 유의미하게 발전하기 위해서는 과학 전문가들이 정책 수립을 주도하고 전문 기업이 그 정책의 수행을 담당할 수 있게 해야 한다. 이때 정부는 모든 과정에 지원은 하되 과도하게 관여하는 일은 없어야 할 것이다.', NULL, NULL, NULL, '["과학 정책에 대한 정부의 지나친 개입을 경계하고 있다.","과학 기술 발전을 위해서는 연구가 중요함을 강조하고 있다.","과학 기술 발전이 경제 성장에 미치는 영향력에 감탄하고 있다.","과학 정책 수립 시 우주 과학이 소홀히 다루어질 것을 우려하고 있다."]'::jsonb, 2, '과학 정책에 대한 정부의 지나친 개입을 경계하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 47, '윗글의 내용과 같은 것을 고르십시오.

세계는 신에너지, 자동화, 우주여행 등이 주도하는 시대로 급속히 접어들고 있다. 세계 각국은 풍력, 태양광 등 재생 가능한 에너지를 개발하는 회사에 대한 정부 보조금을 늘리고 있고 그에 따라 대체 에너지의 사용 비율도 점차 증가하고 있다. 민간 우주 산업 육성을 위해 인공위성 주파수 사용과 우주선 발사 등에 대한 대대적인 규제 완화를 한 국가도 있다. 그 덕분에 한 민간 기업은 화성 여행이 가능한 호텔급 우주여행선을 제작할 수 있었다. 민간 기업이 과학 기술 개발을 주도하며 성장할 수 있게 된 것은 정부가 지원을 확대하면서도 간섭을 최소화했기 때문이다. 이처럼 과학 기술이 유의미하게 발전하기 위해서는 과학 전문가들이 정책 수립을 주도하고 전문 기업이 그 정책의 수행을 담당할 수 있게 해야 한다. 이때 정부는 모든 과정에 지원은 하되 과도하게 관여하는 일은 없어야 할 것이다.', NULL, NULL, NULL, '["많은 국가들이 신에너지 개발에 대한 투자를 줄이고 있다.","과학 정책이 빠르게 변해서 과학 기술이 발전할 수 있었다.","정부가 우주 산업에 대한 규제를 풀어 성장한 민간 기업이 있다.","우주 개발에 참여 중인 민간 기업이 화성에 호텔을 건설하고 있다."]'::jsonb, 2, '정부가 우주 산업에 대한 규제를 풀어 성장한 민간 기업이 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 48, '윗글을 쓴 목적으로 가장 알맞은 것을 고르십시오.

많은 사람들은 결혼, 수입 등의 객관적 조건이 행복을 결정하는 요인이라고 생각한다. 그러나 이런 요인들로는 행복의 이유를 10% 정도밖에 설명할 수 없다고 한다. 그렇다면 행복을 결정하는 요인은 무엇일까? 그것은 행복에 대해 가지는 믿음과 태도이다. 행복에 대한 태도는 행복의 유한성과 무한성 중 어느 한쪽을 선택함으로써 결정된다. 이 세상에 존재하는 행복의 ( ........................ ) 믿는 사람들은 항상 타인이 행복한 정도를 예의 주시 하는 특징이 관찰되었다. 남이 행복하면 내 행복이 줄어든다고 생각하는 사람에게는 타인의 행복이 자신의 행복에 위협적인 요소가 되기 때문이다. 반면 행복의 무한성을 믿는 사람들은 타인의 행복에 그다지 관심을 가지지 않는다. 따라서 행복하려면 행복이 무한한 것이라는 믿음을 가질 필요가 있다. 이러한 생각만으로도 행복감은 증대될 수 있으며 자신이 어떻게 할 때 행복해지는지에 집중할 수 있게 되기 때문이다.', NULL, NULL, NULL, '["행복의 사회적 특성을 파악하려고","행복을 측정하는 방법을 소개하려고","행복에 대한 관점의 변화를 유도하려고","행복이 인간에게 미치는 영향을 분석하려고"]'::jsonb, 2, '행복에 대한 관점의 변화를 유도하려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 49, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

많은 사람들은 결혼, 수입 등의 객관적 조건이 행복을 결정하는 요인이라고 생각한다. 그러나 이런 요인들로는 행복의 이유를 10% 정도밖에 설명할 수 없다고 한다. 그렇다면 행복을 결정하는 요인은 무엇일까? 그것은 행복에 대해 가지는 믿음과 태도이다. 행복에 대한 태도는 행복의 유한성과 무한성 중 어느 한쪽을 선택함으로써 결정된다. 이 세상에 존재하는 행복의 ( ........................ ) 믿는 사람들은 항상 타인이 행복한 정도를 예의 주시 하는 특징이 관찰되었다. 남이 행복하면 내 행복이 줄어든다고 생각하는 사람에게는 타인의 행복이 자신의 행복에 위협적인 요소가 되기 때문이다. 반면 행복의 무한성을 믿는 사람들은 타인의 행복에 그다지 관심을 가지지 않는다. 따라서 행복하려면 행복이 무한한 것이라는 믿음을 가질 필요가 있다. 이러한 생각만으로도 행복감은 증대될 수 있으며 자신이 어떻게 할 때 행복해지는지에 집중할 수 있게 되기 때문이다.', NULL, NULL, NULL, '["개인차가 크지 않다고","총량이 정해져 있다고","양상이 매우 다양하다고","크기가 계속 증가한다고"]'::jsonb, 2, '총량이 정해져 있다고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 83 ORDER BY created_at DESC LIMIT 1), 'reading', 50, '윗글의 내용과 같은 것을 고르십시오.

많은 사람들은 결혼, 수입 등의 객관적 조건이 행복을 결정하는 요인이라고 생각한다. 그러나 이런 요인들로는 행복의 이유를 10% 정도밖에 설명할 수 없다고 한다. 그렇다면 행복을 결정하는 요인은 무엇일까? 그것은 행복에 대해 가지는 믿음과 태도이다. 행복에 대한 태도는 행복의 유한성과 무한성 중 어느 한쪽을 선택함으로써 결정된다. 이 세상에 존재하는 행복의 ( ........................ ) 믿는 사람들은 항상 타인이 행복한 정도를 예의 주시 하는 특징이 관찰되었다. 남이 행복하면 내 행복이 줄어든다고 생각하는 사람에게는 타인의 행복이 자신의 행복에 위협적인 요소가 되기 때문이다. 반면 행복의 무한성을 믿는 사람들은 타인의 행복에 그다지 관심을 가지지 않는다. 따라서 행복하려면 행복이 무한한 것이라는 믿음을 가질 필요가 있다. 이러한 생각만으로도 행복감은 증대될 수 있으며 자신이 어떻게 할 때 행복해지는지에 집중할 수 있게 되기 때문이다.', NULL, NULL, NULL, '["행복에 대한 사람들의 태도는 대체로 유사하다.","행복은 결혼 여부나 수입 정도의 영향을 많이 받는다.","행복의 양이 유한하다고 믿는 사람들은 더 많이 행복할 수 있다.","행복이 무한하다고 믿는 사람들은 자신을 남과 잘 비교하지 않는다."]'::jsonb, 2, '행복이 무한하다고 믿는 사람들은 자신을 남과 잘 비교하지 않는다.', NULL);

COMMIT;
