-- Generated by scripts/generate_topik_102_sql.mjs
BEGIN;

INSERT INTO mock_test_bank (
  title, exam_type, test_number, description, total_questions, duration, listening_questions, reading_questions
)
SELECT
  'TOPIK I 102-р шалгалт',
  'TOPIK_I',
  102,
  '102-р албан ёсны TOPIK I шалгалт',
  70,
  100,
  30,
  40
WHERE NOT EXISTS (
  SELECT 1 FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102
);

UPDATE mock_test_bank
SET
  title = 'TOPIK I 102-р шалгалт',
  description = '102-р албан ёсны TOPIK I шалгалт',
  total_questions = 70,
  duration = 100,
  listening_questions = 30,
  reading_questions = 40,
  updated_at = NOW()
WHERE id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1);

DELETE FROM mock_test_questions WHERE mock_test_id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1);

INSERT INTO mock_test_questions (
  mock_test_id,
  section,
  question_number,
  question_text,
  question_image_url,
  audio_url,
  option_image_urls,
  options,
  question_score,
  correct_answer_text,
  explanation
) VALUES
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 1, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

남자: 우산이 있어요?
여자:', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["네, 우산이 있어요.","네, 우산이 아니에요.","아니요, 우산이에요.","아니요, 우산이 작아요."]'::jsonb, 4, '네, 우산이 있어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 2, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

여자: 신문을 봐요?
남자:', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["네, 신문이 없어요.","네, 신문을 싫어해요.","아니요, 신문을 안 봐요.","아니요, 신문이 재미있어요."]'::jsonb, 4, '아니요, 신문을 안 봐요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 3, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

남자: 어제 뭐 먹었어요?
여자:', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["혼자 먹었어요.","불고기를 먹었어요.","저녁에 먹었어요.","학교에서 먹었어요."]'::jsonb, 3, '불고기를 먹었어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 4, '다음을 듣고 〈보기〉와 같이 물음에 맞는 대답을 고르십시오.

여자: 오늘이 며칠이에요?
남자:', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["두 개예요.","네 시예요.","팔 일이에요.","수요일이에요."]'::jsonb, 3, '팔 일이에요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 5, '다음을 듣고 〈보기〉와 같이 이어지는 말을 고르십시오.

남자: 정말 고마워요.
여자:', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["미안해요.","반가워요.","실례해요.","아니에요."]'::jsonb, 4, '아니에요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 6, '다음을 듣고 〈보기〉와 같이 이어지는 말을 고르십시오.

여자: 잠깐만 기다리세요.
남자:', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["그렇습니다.","알겠습니다.","환영합니다.","오랜만입니다."]'::jsonb, 3, '알겠습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 7, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 손님, 이 바지 어떠세요?
여자: 좋아요. 이거 주세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["빵집","서점","옷 가게","신발 가게"]'::jsonb, 3, '옷 가게', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 8, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 민수 씨, 저기 버스 와요. 저 먼저 갈게요.
남자: 네. 내일 봐요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["꽃집","은행","정류장","지하철역"]'::jsonb, 3, '정류장', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 9, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 어제부터 목이 좀 아파서 왔어요.
여자: 그럼 이걸 식사 후에 드세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["식당","약국","미용실","도서관"]'::jsonb, 3, '약국', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 10, '여기는 어디입니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 자, 의자에 앉으시고 여기 카메라 보세요.
남자: 네. 잘 찍어 주세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["극장","시장","우체국","사진관"]'::jsonb, 4, '사진관', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 11, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 저는 일본에서 왔어요. 안나 씨는요?
여자: 저는 베트남에서 왔어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["가족","나라","시간","약속"]'::jsonb, 3, '나라', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 12, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 민수 씨는 무슨 일을 해요?
남자: 저는 회사에 다녀요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["직업","이름","날씨","휴일"]'::jsonb, 3, '직업', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 13, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

남자: 축구를 자주 해요?
여자: 네. 농구도 많이 해요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["건강","계획","방학","운동"]'::jsonb, 4, '운동', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 14, '다음은 무엇에 대해 말하고 있습니까? 〈보기〉와 같이 알맞은 것을 고르십시오.

여자: 이사하니까 어때요?
남자: 거실이 넓고 방이 밝아서 좋아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["값","집","가구","고향"]'::jsonb, 3, '집', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 15, '다음을 듣고 가장 알맞은 그림을 고르십시오.

남자: 우유는 어디에 있어요?
여자: 저쪽으로 가세요. 문 옆에 있어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/listening/q15_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/listening/q15_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/listening/q15_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/listening/q15_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 4, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 16, '다음을 듣고 가장 알맞은 그림을 고르십시오.

여자: 민수 씨, 어떤 가방을 가지고 갈까요?
남자: 짐이 많으니까 큰 가방이 좋겠어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/listening/q16_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/listening/q16_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/listening/q16_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/listening/q16_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 4, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 17, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

여자: 민수 씨, 방학 때 뭐 했어요?
남자: 오랜만에 고향에 가서 부모님을 만났어요. 수미 씨는요?
여자: 저는 여행도 하고 영어도 배우면서 재미있게 보냈어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 고향에 자주 갑니다.","남자는 방학에 가족을 못 만났습니다.","여자는 방학에 영어 공부를 했습니다.","여자는 이번 방학에 여행을 가지 못했습니다."]'::jsonb, 3, '여자는 방학에 영어 공부를 했습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 18, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

남자: 회사 앞에 새로 생긴 인주식당 가 봤어요?
여자: 네. 지난주에 가 봤어요. 메뉴가 많진 않은데 음식이 진짜 맛있었어요.
남자: 그래서 볼 때마다 사람이 많았군요. 저는 아직 못 가 봤어요.
여자: 거기는 미리 예약을 해야 돼요. 저도 예약하고 갔어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["인주식당은 메뉴가 많습니다.","인주식당은 예약을 받지 않습니다.","남자는 인주식당의 위치를 모릅니다.","여자는 지난주에 인주식당에 갔습니다."]'::jsonb, 3, '여자는 지난주에 인주식당에 갔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 19, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

여자: 운전 시작한 지 한 달 됐는데 아직 잘 못하겠어요.
남자: 처음엔 어렵죠. 저도 매일 집 근처에서 연습했어요.
여자: 그래서 내일부터는 회사에 갈 때 운전해서 가 보려고 해요.
남자: 그렇게 해 보세요. 지난번에 보니까 금방 잘할 것 같던데요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 운전에 익숙해졌습니다.","남자는 운전을 할 줄 모릅니다.","여자는 내일부터 회사에 운전해서 갈 겁니다.","남자는 여자가 운전하는 것을 본 적이 없습니다."]'::jsonb, 3, '여자는 내일부터 회사에 운전해서 갈 겁니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 20, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

남자: 수미 씨, 이 노래 누가 부른 거예요? 목소리가 좋네요.
여자: 김우진 씨요. 제가 좋아하는 가수인데 유명하지는 않아요.
남자: 아, 예전에 한강공원에서 공연하는 걸 한 번 본 적이 있어요.
여자: 그래요? 정말 부러워요. 저는 실제로는 못 봤는데.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["이 가수는 아주 유명합니다.","여자는 이 가수를 좋아하지 않습니다.","여자는 이 가수를 직접 본 적이 있습니다.","이 가수는 한강공원에서 공연을 했습니다."]'::jsonb, 3, '이 가수는 한강공원에서 공연을 했습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 21, '다음을 듣고 〈보기〉와 같이 대화 내용과 같은 것을 고르십시오.

여자: 여기 505호인데요. 호텔 수영장은 몇 시까지 이용할 수 있나요?
남자: 네, 손님. 새벽 여섯 시부터 밤 열 시까지 이용하실 수 있습니다.
여자: 그렇군요. 혹시 호텔에 수영복 살 수 있는 곳도 있나요?
남자: 네. 수영장 입구에 있습니다. 만 원을 내시면 빌려드리기도 하고요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["남자는 지금 505호에 있습니다.","오후에는 수영장에 못 들어갑니다.","호텔에서 수영복을 살 수 없습니다.","수영복을 빌리려면 돈을 내야 합니다."]'::jsonb, 3, '수영복을 빌리려면 돈을 내야 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 22, '다음을 듣고 여자의 중심 생각을 고르십시오.

남자: 수미 씨, 필통에 연필이 정말 많네요.
여자: 네. 저는 메모하거나 일기 쓸 때 연필을 자주 사용해요.
남자: 그래요? 특별히 연필을 많이 쓰는 이유가 있어요?
여자: 쓸 때 나는 소리가 좋아요. 틀리면 쉽게 지울 수도 있고요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["연필을 사용하는 것을 좋아합니다.","오래 기억하려면 메모를 해야 합니다.","여러 종류의 연필이 있으면 좋겠습니다.","일기를 자주 쓰는 습관을 가지고 싶습니다."]'::jsonb, 3, '연필을 사용하는 것을 좋아합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 23, '다음을 듣고 여자의 중심 생각을 고르십시오.

여자: 꽃집이죠? 어제 꽃다발 예약한 김수미인데요. 하나 더 주문하려고요.
남자: 네, 손님. 이번에는 어떤 꽃다발로 준비해 드릴까요?
여자: 음……………. 어제 예약한 거랑 같은 걸로 할게요.
남자: 알겠습니다. 그럼 내일 두 시에 찾으러 오세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["꽃다발을 빨리 찾으러 가고 싶습니다.","다양한 꽃으로 만든 꽃다발이 좋습니다.","꽃다발을 똑같이 만드는 것이 어렵습니다.","같은 꽃다발을 하나 더 주문하고 싶습니다."]'::jsonb, 3, '같은 꽃다발을 하나 더 주문하고 싶습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 24, '다음을 듣고 여자의 중심 생각을 고르십시오.

여자: 우리 이제, 침대만 사면 되지요? 침대는 주말에 직접 가서 사요.
남자: 어제 인터넷에서 본 거 주문하는 건 어때요? 괜찮아 보이던데요.
여자: 침대는 실제로 보고 사야죠. 오래 쓸 거니까 한번 누워도 보고요.
남자: 좋아요. 그럼 주말에 같이 보러 가요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["침대는 직접 보고 사야 합니다.","침대는 자주 바꿀 필요가 있습니다.","가구는 디자인이 예쁜 것이 좋습니다.","가구는 인터넷으로 사는 게 편합니다."]'::jsonb, 3, '침대는 직접 보고 사야 합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 25, '여자가 왜 이 이야기를 하고 있는지 고르십시오.

여자: (딩동댕) 직원 여러분께 안내드립니다. 다음 주 월요일인 6일, 지하 주차장을 청소합니다. 오전 아홉 시부터 오후 세 시까지는 지하 주차장 출입이 금지되니 회사 건너편에 있는 야외 주차장을 이용해 주십시오. 청소가 끝나는 세 시 이후에는 지하 주차장을 다시 이용할 수 있으니 참고하시기 바랍니다. (댕동딩)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["청소 일정을 안내하려고","청소 신청 방법을 알리려고","청소가 필요한 이유를 설명하려고","청소 날짜가 바뀐 것을 이야기하려고"]'::jsonb, 3, '청소 일정을 안내하려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 26, '들은 내용과 같은 것을 고르십시오.

여자: (딩동댕) 직원 여러분께 안내드립니다. 다음 주 월요일인 6일, 지하 주차장을 청소합니다. 오전 아홉 시부터 오후 세 시까지는 지하 주차장 출입이 금지되니 회사 건너편에 있는 야외 주차장을 이용해 주십시오. 청소가 끝나는 세 시 이후에는 지하 주차장을 다시 이용할 수 있으니 참고하시기 바랍니다. (댕동딩)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["주차장 청소는 오전에 끝납니다.","주차장 청소는 이번 주에 합니다.","회사 근처에 야외 주차장이 있습니다.","청소할 때 지하 주차장에 들어갈 수 있습니다."]'::jsonb, 4, '회사 근처에 야외 주차장이 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 27, '두 사람이 무엇에 대해 이야기를 하고 있는지 고르십시오.

남자: 수미 씨, 요즘 인주 바닷가에서 영화 축제 하는 거 알아요? 저 어제 다녀왔는데 파도 소리 들으면서 영화를 보니까 좋았어요.
여자: 아, 저도 가 보고 싶었는데. 영화 축제에 가려면 어떻게 해야 돼요?
남자: 홈페이지에서 표를 사면 돼요. 홈페이지에 영화 제목이랑 일정도 나와 있어요. 축제가 이번 주 금요일까지니까 한번 가 보세요.
여자: 그래야겠네요. 그런데 영화를 해변에 앉아서 보는 거예요?
남자: 네. 저는 그냥 모래 위에 앉아서 봤는데 거기서 의자도 빌려줘요.
여자: 그렇군요. 홈페이지에 한번 들어가 봐야겠어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["인주 해변에 가는 방법","인주 해변에서 찍은 영화","해변에서 하는 영화 축제","축제에 같이 가고 싶은 사람"]'::jsonb, 3, '해변에서 하는 영화 축제', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 28, '들은 내용과 같은 것을 고르십시오.

남자: 수미 씨, 요즘 인주 바닷가에서 영화 축제 하는 거 알아요? 저 어제 다녀왔는데 파도 소리 들으면서 영화를 보니까 좋았어요.
여자: 아, 저도 가 보고 싶었는데. 영화 축제에 가려면 어떻게 해야 돼요?
남자: 홈페이지에서 표를 사면 돼요. 홈페이지에 영화 제목이랑 일정도 나와 있어요. 축제가 이번 주 금요일까지니까 한번 가 보세요.
여자: 그래야겠네요. 그런데 영화를 해변에 앉아서 보는 거예요?
남자: 네. 저는 그냥 모래 위에 앉아서 봤는데 거기서 의자도 빌려줘요.
여자: 그렇군요. 홈페이지에 한번 들어가 봐야겠어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["축제는 다음 주까지 합니다.","여자는 어제 이 축제에 갔다 왔습니다.","영화를 볼 때 의자를 빌릴 수 없습니다.","일정은 홈페이지에서 확인할 수 있습니다."]'::jsonb, 4, '일정은 홈페이지에서 확인할 수 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 29, '여자가 탁구 선수가 된 이유를 고르십시오.

남자: 김수미 선수, 축하합니다. 열일곱 살의 나이에 전국 탁구 대회에서 일등을 하셨는데요. 기분이 어떠세요?
여자: 한국 최고의 대회에서 일등을 해서 기뻐요. 그동안 정말 열심히 했는데 올해 다른 대회에서는 계속 결과가 안 좋아서 힘들었거든요.
남자: 그랬겠네요. 그런데 언제부터 탁구 선수가 되고 싶으셨어요?
여자: 초등학생 때 아버지가 탁구를 가르쳐 주셨어요. 취미로만 치다가 대회장에서 탁구 경기를 보고, 그게 너무 멋있어서 선수가 되기로 했죠.
남자: 그렇군요. 앞으로 어떤 계획이 있으신가요?
여자: 먼저 친구들하고 좀 놀고 싶어요. 그리고 바로 내년 봄에 있는 세계 대회를 준비하려고 합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["어렸을 때부터 운동을 잘해서","직접 본 탁구 경기가 멋있어서","친구들과 같이 운동하고 싶어서","아버지를 기쁘게 해 드리고 싶어서"]'::jsonb, 3, '직접 본 탁구 경기가 멋있어서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'listening', 30, '들은 내용과 같은 것을 고르십시오.

남자: 김수미 선수, 축하합니다. 열일곱 살의 나이에 전국 탁구 대회에서 일등을 하셨는데요. 기분이 어떠세요?
여자: 한국 최고의 대회에서 일등을 해서 기뻐요. 그동안 정말 열심히 했는데 올해 다른 대회에서는 계속 결과가 안 좋아서 힘들었거든요.
남자: 그랬겠네요. 그런데 언제부터 탁구 선수가 되고 싶으셨어요?
여자: 초등학생 때 아버지가 탁구를 가르쳐 주셨어요. 취미로만 치다가 대회장에서 탁구 경기를 보고, 그게 너무 멋있어서 선수가 되기로 했죠.
남자: 그렇군요. 앞으로 어떤 계획이 있으신가요?
여자: 먼저 친구들하고 좀 놀고 싶어요. 그리고 바로 내년 봄에 있는 세계 대회를 준비하려고 합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/audio/102-TOPIK-I-Listening-Audio-File.mp3', NULL, '["여자는 아버지께 탁구를 배웠습니다.","여자는 다음 달에 세계 대회에 나갈 겁니다.","여자는 중학생 때 탁구를 치기 시작했습니다.","여자는 올해 여러 대회에서 일등을 했습니다."]'::jsonb, 4, '여자는 아버지께 탁구를 배웠습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 1, '무엇에 대한 내용입니까?

저는 누나가 있습니다. 동생도 있습니다.', NULL, NULL, NULL, '["나라","나이","운동","가족"]'::jsonb, 2, '가족', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 2, '무엇에 대한 내용입니까?

지금은 저녁입니다. 일곱 시입니다.', NULL, NULL, NULL, '["시간","직업","날짜","휴일"]'::jsonb, 2, '시간', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 3, '무엇에 대한 내용입니까?

저는 등산을 좋아합니다. 산에 자주 갑니다.', NULL, NULL, NULL, '["쇼핑","교통","계절","취미"]'::jsonb, 2, '취미', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 4, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

저는 의사입니다. ( )에서 일합니다.', NULL, NULL, NULL, '["병원","서점","미용실","우체국"]'::jsonb, 2, '병원', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 5, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

저는 일이 많습니다. 그래서 조금 ( ).', NULL, NULL, NULL, '["작습니다","비쌉니다","무겁습니다","피곤합니다"]'::jsonb, 2, '피곤합니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 6, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

친구를 만났습니다. 우리는 ( ) 공부를 했습니다.', NULL, NULL, NULL, '["가장","아직","별로","같이"]'::jsonb, 2, '같이', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 7, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

방이 덥습니다. 창문( ) 엽니다.', NULL, NULL, NULL, '["에","의","을","이"]'::jsonb, 3, '을', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 8, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

선물을 삽니다. 친구에게 ( ).', NULL, NULL, NULL, '["줍니다","듣습니다","다닙니다","가르칩니다"]'::jsonb, 3, '줍니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 9, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

민수 씨하고 약속이 있습니다. 저는 민수 씨를 ( ).', NULL, NULL, NULL, '["내립니다","넣습니다","구경합니다","기다립니다"]'::jsonb, 2, '기다립니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 10, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/reading/q10.png', NULL, NULL, '["일요일은 맑습니다.","오늘은 비가 옵니다.","내일은 토요일입니다.","인주시의 날씨입니다."]'::jsonb, 3, '오늘은 비가 옵니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 11, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/reading/q11.png', NULL, NULL, '["주말에 파티를 합니다.","유미의 생일 파티입니다.","파티는 오전에 시작합니다.","호텔 삼 층에서 파티를 합니다."]'::jsonb, 3, '파티는 오전에 시작합니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 12, '다음을 읽고 맞지 않는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/reading/q12.png', NULL, NULL, '["지영 씨는 지금 집에 있습니다.","마이클 씨는 모임에 안 갔습니다.","지영 씨는 내일 학교에 갈 겁니다.","마이클 씨는 오늘 지영 씨를 만났습니다."]'::jsonb, 3, '마이클 씨는 모임에 안 갔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 13, '다음을 읽고 내용이 같은 것을 고르십시오.

저는 은행에서 일합니다. 은행에 외국인 손님이 많이 옵니다. 저는 그 손님들하고 영어로 이야기합니다.', NULL, NULL, NULL, '["저는 영어를 할 수 없습니다.","저는 요즘 일을 하지 않습니다.","저는 은행에서 일을 하려고 합니다.","저는 은행에서 외국 사람을 많이 만납니다."]'::jsonb, 3, '저는 은행에서 외국 사람을 많이 만납니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 14, '다음을 읽고 내용이 같은 것을 고르십시오.

오늘 집에서 비누를 만들었습니다. 비누에 레몬을 넣었습니다. 이 비누로 손을 씻었는데 냄새가 좋았습니다.', NULL, NULL, NULL, '["이 비누에 레몬이 들어갔습니다.","이 비누는 냄새가 나지 않습니다.","저는 오늘 레몬 비누를 샀습니다.","저는 이 비누를 사용하지 않았습니다."]'::jsonb, 2, '이 비누에 레몬이 들어갔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 15, '다음을 읽고 내용이 같은 것을 고르십시오.

고향에 계신 부모님이 과자를 보내 주셨습니다. 제가 좋아하는 고향 과자가 많이 있었습니다. 방 친구와 같이 과자를 먹었습니다.', NULL, NULL, NULL, '["저는 부모님과 같이 삽니다.","저는 과자를 혼자 먹었습니다.","저는 부모님에게 과자를 받았습니다.","저는 고향의 과자를 좋아하지 않습니다."]'::jsonb, 3, '저는 부모님에게 과자를 받았습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 16, '다음을 읽고 중심 내용을 고르십시오.

요즘 춤을 배우고 있습니다. 춤을 추는 것이 아주 재미있습니다. 그래서 매일 춤 연습을 합니다.', NULL, NULL, NULL, '["저는 춤을 오래 배웠습니다.","저는 춤을 배우는 것이 즐겁습니다.","저는 요즘 춤을 출 시간이 없습니다.","저는 친구와 춤 연습을 하고 싶습니다."]'::jsonb, 3, '저는 춤을 배우는 것이 즐겁습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 17, '다음을 읽고 중심 내용을 고르십시오.

저는 주말마다 테니스를 칩니다. 지난주에는 비가 와서 테니스를 못 쳤습니다. 이번 주는 비가 안 오면 좋겠습니다.', NULL, NULL, NULL, '["저는 테니스를 배우려고 합니다.","저는 테니스 보는 것을 좋아합니다.","저는 테니스를 잘 치면 좋겠습니다.","저는 이번 주말에 테니스를 치고 싶습니다."]'::jsonb, 3, '저는 이번 주말에 테니스를 치고 싶습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 18, '다음을 읽고 중심 내용을 고르십시오.

얼마 전에 운동화를 샀습니다. 이 운동화는 가볍고 아주 편합니다. 저는 매일 이 운동화를 신고 다닙니다.', NULL, NULL, NULL, '["저는 운동화를 사려고 합니다.","저는 이 운동화를 선물할 겁니다.","저는 이 운동화가 마음에 듭니다.","저는 운동화가 많으면 좋겠습니다."]'::jsonb, 2, '저는 이 운동화가 마음에 듭니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 19, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

우리 가족은 오랫동안 외국에 살았습니다. 그곳의 미용실은 가격이 비쌌습니다. 그래서 우리 가족은 미용실에 가지 않았습니다. 남편과 아이의 머리는 제가 잘라 주었습니다. 처음에는 잘 못 ( ) 나중에는 잘 자르게 되었습니다. 지금 우리 가족은 한국에서 살고 있습니다. 저는 요즘도 가족들의 머리를 잘라 줍니다.', NULL, NULL, NULL, '["자르면","자르니까","잘랐거나","잘랐지만"]'::jsonb, 2, '잘랐지만', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 20, '윗글의 내용과 같은 것을 고르십시오.

우리 가족은 오랫동안 외국에 살았습니다. 그곳의 미용실은 가격이 비쌌습니다. 그래서 우리 가족은 미용실에 가지 않았습니다. 남편과 아이의 머리는 제가 잘라 주었습니다. 처음에는 잘 못 ( ) 나중에는 잘 자르게 되었습니다. 지금 우리 가족은 한국에서 살고 있습니다. 저는 요즘도 가족들의 머리를 잘라 줍니다.', NULL, NULL, NULL, '["우리 가족은 한국에 돌아왔습니다.","외국의 미용실은 가격이 쌌습니다.","요즘은 아이의 머리를 잘라 주지 않습니다.","우리 가족은 외국에서 미용실에 자주 갔습니다."]'::jsonb, 2, '우리 가족은 한국에 돌아왔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 21, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

인주시에서는 매년 가을에 떡볶이 축제를 합니다. 이 축제에서는 ''매운 떡볶이 먹기 대회''가 열리는데 축제에 온 사람은 누구나 이 대회에 참가할 수 있습니다. ( ) 이 축제에서 한국의 유명한 떡볶이를 모두 먹어 볼 수 있습니다. 떡볶이 재료를 싸게 살 수도 있고 공연도 볼 수 있어서 이 축제를 찾는 사람이 많습니다.', NULL, NULL, NULL, '["그리고","그래도","그렇지만","왜냐하면"]'::jsonb, 3, '그리고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 22, '무엇에 대한 내용인지 맞는 것을 고르십시오.

인주시에서는 매년 가을에 떡볶이 축제를 합니다. 이 축제에서는 ''매운 떡볶이 먹기 대회''가 열리는데 축제에 온 사람은 누구나 이 대회에 참가할 수 있습니다. ( ) 이 축제에서 한국의 유명한 떡볶이를 모두 먹어 볼 수 있습니다. 떡볶이 재료를 싸게 살 수도 있고 공연도 볼 수 있어서 이 축제를 찾는 사람이 많습니다.', NULL, NULL, NULL, '["이 축제를 하는 장소","이 축제를 하는 날짜","이 축제에서 할 수 있는 일","이 축제에서 볼 수 있는 공연"]'::jsonb, 2, '이 축제에서 할 수 있는 일', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 23, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

제 친구는 회사원인데 그림을 잘 그립니다. 오늘 친구가 첫 번째 전시회를 열었습니다. 저는 ( ) 그 친구의 전시회에 갔다 왔습니다. 전시회 에는 꽃 그림이 많았습니다. 저는 장미꽃 그림을 하나 샀습니다. 오늘 이 그림을 제 방에 걸었습니다.', NULL, NULL, NULL, '["퇴근하러","퇴근한 지","퇴근하려면","퇴근한 후에"]'::jsonb, 2, '퇴근한 후에', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 24, '윗글의 내용과 같은 것을 고르십시오.

제 친구는 회사원인데 그림을 잘 그립니다. 오늘 친구가 첫 번째 전시회를 열었습니다. 저는 ( ) 그 친구의 전시회에 갔다 왔습니다. 전시회 에는 꽃 그림이 많았습니다. 저는 장미꽃 그림을 하나 샀습니다. 오늘 이 그림을 제 방에 걸었습니다.', NULL, NULL, NULL, '["제 친구는 직업이 화가입니다.","저는 친구의 그림을 하나 샀습니다.","제 친구는 전시회를 여러 번 했습니다.","저는 장미꽃 그림을 회사에 가져갔습니다."]'::jsonb, 3, '저는 친구의 그림을 하나 샀습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 25, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

인주시에는 유명한 ''옷 거리''가 있습니다. 이곳은 가게마다 다른 종류의 옷을 팔아서 구경하는 재미가 있습니다. 여러 가게 중에서 인기가 많은 가게는 예전에 유행한 옷을 파는 가게와 특별한 디자인의 청바지를 파는 가게입니다. 다른 곳에서 팔지 않는 옷이 ( ). 그래서 자기만의 특별한 옷을 사고 싶어 하는 사람들이 많이 찾아옵니다.', NULL, NULL, NULL, '["많아도 됩니다","많아야 합니다","많기 때문입니다","많은 적이 있습니다"]'::jsonb, 2, '많기 때문입니다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 26, '윗글의 내용과 같은 것을 고르십시오.

인주시에는 유명한 ''옷 거리''가 있습니다. 이곳은 가게마다 다른 종류의 옷을 팔아서 구경하는 재미가 있습니다. 여러 가게 중에서 인기가 많은 가게는 예전에 유행한 옷을 파는 가게와 특별한 디자인의 청바지를 파는 가게입니다. 다른 곳에서 팔지 않는 옷이 ( ). 그래서 자기만의 특별한 옷을 사고 싶어 하는 사람들이 많이 찾아옵니다.', NULL, NULL, NULL, '["이 거리에 청바지 가게가 생기지 않았습니다.","이 거리에서 예전에 유행한 옷을 살 수 있습니다.","이 거리는 사람들에게 많이 알려지지 않았습니다.","이 거리에 같은 종류의 옷을 파는 가게들이 모여 있습니다."]'::jsonb, 3, '이 거리에서 예전에 유행한 옷을 살 수 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 27, '다음을 순서에 맞게 배열한 것을 고르십시오.

(가) 저는 친구들과 함께 방송국을 구경하러 갔습니다.
(나) 저는 뛰어가서 그 배우와 함께 사진을 찍었습니다.
(다) 그때 제가 좋아하는 배우가 저쪽으로 지나갔습니다.
(라) 우리는 방송국 일 층에서 안내 직원을 기다리고 있었습니다.', NULL, NULL, NULL, '["(가)-(나)-(다)-(라)","(가)-(라)-(다)-(나)","(라)-(가)-(나)-(다)","(라)-(나)-(다)-(가)"]'::jsonb, 3, '(가)-(라)-(다)-(나)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 28, '다음을 순서에 맞게 배열한 것을 고르십시오.

(가) 그것을 확인하는 방법은 아주 간단합니다.
(나) 그럴 때는 정말 배가 고파서 그런 것인지 확인하는 게 좋습니다.
(다) 싫어하는 음식을 생각해도 먹고 싶다면 정말 배가 고픈 것입니다.
(라) 식사를 했는데도 금방 음식을 먹고 싶은 생각이 들 때가 있습니다.', NULL, NULL, NULL, '["(가)-(다)-(나)-(라)","(다)-(나)-(가)-(라)","(라)-(나)-(가)-(다)","(라)-(다)-(가)-(나)"]'::jsonb, 2, '(라)-(나)-(가)-(다)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 29, '다음 문장이 들어갈 곳으로 가장 알맞은 것을 고르십시오.

주어진 문장: 반가운 마음에 저는 초등학교로 찾아갔습니다.

얼마 전에 제가 초등학교 때 쓴 일기장을 보았습니다. ( ① ) 거기에는 제가 선생님께 칭찬을 듣고 기뻐하는 이야기가 써 있었습니다. ( ② ) 일기를 보고 갑자기 선생님이 생각나서 학교로 전화를 해 봤습니다. 선생님은 아직 그 초등학교에 계셨습니다. ( ③ ) 선생님을 만나서 초등학교 때의 이야기를 나누었습니다. ( ④ )', NULL, NULL, NULL, '["①","②","③","④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 30, '윗글의 내용과 같은 것을 고르십시오.

얼마 전에 제가 초등학교 때 쓴 일기장을 보았습니다. ( ① ) 거기에는 제가 선생님께 칭찬을 듣고 기뻐하는 이야기가 써 있었습니다. ( ② ) 일기를 보고 갑자기 선생님이 생각나서 학교로 전화를 해 봤습니다. 선생님은 아직 그 초등학교에 계셨습니다. ( ③ ) 선생님을 만나서 초등학교 때의 이야기를 나누었습니다. ( ④ )', NULL, NULL, NULL, '["저는 선생님을 만나러 갔습니다.","선생님이 저에게 전화를 하셨습니다.","선생님은 지금 다른 학교에 계십니다.","저는 초등학교 때의 일기장을 잃어버렸습니다."]'::jsonb, 3, '저는 선생님을 만나러 갔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 31, '㉠에 들어갈 말로 가장 알맞은 것을 고르십시오.

저는 드라마를 만드는 사람과 함께 일을 합니다. 드라마에 잘 맞는 ( ㉠ ) 일입니다. 이번에 시작하는 드라마는 바닷가 시골 마을 사람들의 이야기 입니다. 그래서 부산과 제주도의 작은 바닷가 마을들을 여기저기 다녔습니다. 한 달이 걸려서 드라마에 딱 맞는 곳을 찾을 수 있었습니다. 이번 주말에 드라마 촬영이 시작됩니다. 이 드라마가 인기가 있으면 좋겠습니다.', NULL, NULL, NULL, '["장소를 찾는","배우를 찾는","옷을 만드는","음악을 만드는"]'::jsonb, 2, '장소를 찾는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 32, '윗글의 내용과 같은 것을 고르십시오.

저는 드라마를 만드는 사람과 함께 일을 합니다. 드라마에 잘 맞는 ( ㉠ ) 일입니다. 이번에 시작하는 드라마는 바닷가 시골 마을 사람들의 이야기 입니다. 그래서 부산과 제주도의 작은 바닷가 마을들을 여기저기 다녔습니다. 한 달이 걸려서 드라마에 딱 맞는 곳을 찾을 수 있었습니다. 이번 주말에 드라마 촬영이 시작됩니다. 이 드라마가 인기가 있으면 좋겠습니다.', NULL, NULL, NULL, '["이 드라마는 이번 주말에 끝납니다.","이번 일을 위해서 부산과 제주도에 갔습니다.","이번에 도시 사람들의 이야기를 드라마로 찍습니다.","이번 일 때문에 일주일 동안 여기저기를 다녔습니다."]'::jsonb, 2, '이번 일을 위해서 부산과 제주도에 갔습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 33, '왜 윗글을 썼는지 맞는 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/reading/q33.png', NULL, NULL, '["자전거 주차장의 요금을 바꾸려고","자전거 주차장의 위치를 확인하려고","자전거 주차장에서 일할 직원을 찾으려고","자전거 주차장이 생기는 것을 안내하려고"]'::jsonb, 2, '자전거 주차장이 생기는 것을 안내하려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 34, '윗글의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-i-102/reading/q33.png', NULL, NULL, '["새 주차장은 관리실 근처에 있습니다.","이 아파트에는 자전거 주차장이 없었습니다.","새 주차장은 십이월부터 이용할 수 있습니다.","아파트 입구에 있는 자전거는 옮기지 않아도 됩니다."]'::jsonb, 3, '새 주차장은 관리실 근처에 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 35, '㉠에 들어갈 말로 가장 알맞은 것을 고르십시오.

토끼는 혼자서 생활하는 동물입니다. 보통 산에 사는데 무서운 동물을 만날 때가 많습니다. 그럴 때 토끼가 ( ㉠ ) 방법에는 여러 가지가 있습니다. 토끼는 튼튼한 다리로 빠르고 멀리 뛸 수 있습니다. 또 먼 곳에 있는 동물도 냄새로 알 수 있습니다. 귀를 움직여서 소리가 나는 위치도 정확하게 찾습니다. 그래서 무서운 동물이 오는 것을 미리 알 수 있습니다.', NULL, NULL, NULL, '["잠을 자는","자기를 지키는","음식을 구하는","상처를 치료하는"]'::jsonb, 2, '자기를 지키는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 36, '윗글의 내용과 같은 것을 고르십시오.

토끼는 혼자서 생활하는 동물입니다. 보통 산에 사는데 무서운 동물을 만날 때가 많습니다. 그럴 때 토끼가 ( ㉠ ) 방법에는 여러 가지가 있습니다. 토끼는 튼튼한 다리로 빠르고 멀리 뛸 수 있습니다. 또 먼 곳에 있는 동물도 냄새로 알 수 있습니다. 귀를 움직여서 소리가 나는 위치도 정확하게 찾습니다. 그래서 무서운 동물이 오는 것을 미리 알 수 있습니다.', NULL, NULL, NULL, '["산에 사는 토끼는 모여서 생활합니다.","토끼는 냄새가 나는 것을 잘 못 느낍니다.","토끼는 소리가 나는 위치를 정확하게 압니다.","산에 사는 토끼는 빠른 속도로 뛸 수 없습니다."]'::jsonb, 3, '토끼는 소리가 나는 위치를 정확하게 압니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 37, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

인주도서관에는 ''독서 로봇''이 있습니다. 아이들에게 책을 읽어 주는 로봇 입니다. 아이들이 책을 펴서 한 장씩 보여 주면 로봇이 읽어 줍니다. 모양도 귀엽고 재미있는 목소리로 책을 읽어 줘서 한글을 모르는 아이들이 좋아 합니다. 도서관을 방문한 아이는 누구나 이용할 수 있고, 인터넷으로 미리 신청 하면 집에 빌려 갈 수도 있습니다. 이 로봇 덕분에 인주도서관에 ( ) 있습니다.', NULL, NULL, NULL, '["한글 책이 줄고","새 직원이 들어오고","아이들 손님이 늘고","높은 책장이 없어지고"]'::jsonb, 3, '아이들 손님이 늘고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 38, '윗글의 내용과 같은 것을 고르십시오.

인주도서관에는 ''독서 로봇''이 있습니다. 아이들에게 책을 읽어 주는 로봇 입니다. 아이들이 책을 펴서 한 장씩 보여 주면 로봇이 읽어 줍니다. 모양도 귀엽고 재미있는 목소리로 책을 읽어 줘서 한글을 모르는 아이들이 좋아 합니다. 도서관을 방문한 아이는 누구나 이용할 수 있고, 인터넷으로 미리 신청 하면 집에 빌려 갈 수도 있습니다. 이 로봇 덕분에 인주도서관에 ( ) 있습니다.', NULL, NULL, NULL, '["이 로봇은 아이들에게 책을 골라 줍니다.","이 로봇은 한글을 몰라도 이용할 수 있습니다.","이 로봇은 모양 때문에 아이들에게 인기가 없습니다.","이 로봇을 빌리려면 도서관에 가서 신청해야 합니다."]'::jsonb, 3, '이 로봇은 한글을 몰라도 이용할 수 있습니다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 39, '( )에 들어갈 말로 가장 알맞은 것을 고르십시오.

10년 넘게 키운 강아지가 하늘나라로 떠나서 이제 만날 수 없습니다. 저는 강아지와 함께한 시간을 기억하고 싶어서 휴대폰 게임을 만들었 습니다. 주인공과 강아지가 함께 ( ) 게임입니다. 저는 주인공이 되어 강아지와 높은 산도 오르고 파도가 심한 바다도 건닙니다. 나쁜 사람을 만나면 함께 싸우기도 합니다. 여행을 마치고 집으로 돌아오면 게임이 끝납니다. 저는 강아지가 보고 싶을 때마다 이 게임을 합니다.', NULL, NULL, NULL, '["집을 짓는","여행을 떠나는","가족을 만나는","사람들을 돕는"]'::jsonb, 3, '여행을 떠나는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_I' AND test_number = 102 ORDER BY created_at DESC LIMIT 1), 'reading', 40, '윗글의 내용으로 알 수 있는 것을 고르십시오.

10년 넘게 키운 강아지가 하늘나라로 떠나서 이제 만날 수 없습니다. 저는 강아지와 함께한 시간을 기억하고 싶어서 휴대폰 게임을 만들었 습니다. 주인공과 강아지가 함께 ( ) 게임입니다. 저는 주인공이 되어 강아지와 높은 산도 오르고 파도가 심한 바다도 건닙니다. 나쁜 사람을 만나면 함께 싸우기도 합니다. 여행을 마치고 집으로 돌아오면 게임이 끝납니다. 저는 강아지가 보고 싶을 때마다 이 게임을 합니다.', NULL, NULL, NULL, '["저는 강아지를 그리워하고 있습니다.","저는 강아지를 키우는 게임을 샀습니다.","저는 오랫동안 이 게임을 하지 못했습니다.","저는 강아지와 매일 놀아 주는 것이 힘들었습니다."]'::jsonb, 3, '저는 강아지를 그리워하고 있습니다.', NULL);

COMMIT;
