-- Generated by scripts/generate_topik_ii_91_sql.py
BEGIN;

INSERT INTO mock_test_bank (
  title, exam_type, test_number, description, total_questions, duration, listening_questions, reading_questions
)
SELECT
  'TOPIK II 91-р шалгалт',
  'TOPIK_II',
  91,
  '91-р албан ёсны TOPIK II шалгалт',
  100,
  130,
  50,
  50
WHERE NOT EXISTS (
  SELECT 1 FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91
);

UPDATE mock_test_bank SET title = 'TOPIK II 91-р шалгалт', description = '91-р албан ёсны TOPIK II шалгалт', total_questions = 100, duration = 130, listening_questions = 50, reading_questions = 50, updated_at = NOW() WHERE id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1);

DELETE FROM mock_test_questions WHERE mock_test_id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1);

INSERT INTO mock_test_questions (
  mock_test_id,
  section,
  question_number,
  question_text,
  question_image_url,
  audio_url,
  option_image_urls,
  options,
  question_score,
  correct_answer_text,
  explanation
) VALUES
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 1, '다음을 듣고 가장 알맞은 그림 또는 그래프를 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q1_option_1.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q1_option_2.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q1_option_3.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q1_option_4.png"]'::jsonb, '["①", "②", "③", "④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 2, '다음을 듣고 가장 알맞은 그림 또는 그래프를 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q2_option_1.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q2_option_2.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q2_option_3.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q2_option_4.png"]'::jsonb, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 3, '다음을 듣고 가장 알맞은 그림 또는 그래프를 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q3_option_1.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q3_option_2.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q3_option_3.png", "https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q3_option_4.png"]'::jsonb, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 4, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 2019 2020 2021 20225) ° 2019 2020 2021 2022(%5) ® 독서를 하지 않는 이유 이 독서를 하지 않는 이유 1위 일 때문에 시간이 없어서 1위 일 때문에 시간이 없어서 2위 책 대신 다른 매체를 이용해서 2위 책 읽는 습관이 안 들어서 3위 책 읽는 습관이 안 들어서 3위 책 대신 다른 매체를 이용해서", "다음을 SH 이어질 수 있는 말로 가장 알맞은 것을 고르십시오. (각 2점) 4.", "그래? 안 나와서 걱정했어. ® 무슨 학원에 다니고 있어?", "그래? 할머니 Foy 언제 가? ® 부모님과 함께 가기로 했거든."]'::jsonb, 2, '이 2019 2020 2021 20225) ° 2019 2020 2021 2022(%5) ® 독서를 하지 않는 이유 이 독서를 하지 않는 이유 1위 일 때문에 시간이 없어서 1위 일 때문에 시간이 없어서 2위 책 대신 다른 매체를 이용해서 2위 책 읽는 습관이 안 들어서 3위 책 읽는 습관이 안 들어서 3위 책 대신 다른 매체를 이용해서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 5, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 2019 2020 2021 20225) ° 2019 2020 2021 2022(%5) ® 독서를 하지 않는 이유 이 독서를 하지 않는 이유 1위 일 때문에 시간이 없어서 1위 일 때문에 시간이 없어서 2위 책 대신 다른 매체를 이용해서 2위 책 읽는 습관이 안 들어서 3위 책 읽는 습관이 안 들어서 3위 책 대신 다른 매체를 이용해서", "다음을 SH 이어질 수 있는 말로 가장 알맞은 것을 고르십시오. (각 2점) 5. 그럼 거기로 다시 가 볼까요?", "아직 한 곳밖에 안 가 봤는데요.", "그럼 이 소파를 사는 게 어때요? ® 집 근처에 있는 소파 가게에서 4hoig."]'::jsonb, 2, '이 2019 2020 2021 20225) ° 2019 2020 2021 2022(%5) ® 독서를 하지 않는 이유 이 독서를 하지 않는 이유 1위 일 때문에 시간이 없어서 1위 일 때문에 시간이 없어서 2위 책 대신 다른 매체를 이용해서 2위 책 읽는 습관이 안 들어서 3위 책 읽는 습관이 안 들어서 3위 책 대신 다른 매체를 이용해서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 6, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 7, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["맞아요. 이전 작품은 내용이 별로였어요.", "그래요? 이 드라마 다 보면 다른 작품도 봐야겠어요. (", "맞아요. 이 드라마는 몇 번을 다시 봐도 재미있네요.", "그래요? 이 작가가 처음으로 쓴 작품인 줄 몰랐어요."]'::jsonb, 2, '그래요? 이 드라마 다 보면 다른 작품도 봐야겠어요. (', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 8, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 9, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 10, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["고객 대기실로 간다. (", "남자에게 열쇠를 준다.", "AL] 상태를 확인한다.", "AS 수리하려고 예약한다."]'::jsonb, 2, '고객 대기실로 간다. (', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 11, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["물감을 찾아본다. <) 미술 연필을 고른다.", "직원에게 물어본다. ® 남자에게 제품 이름을 말한다. 12.", "촬영팀에게 연락한다.", "진행 순서를 설명한다. @ 공연 무대를 점검한다. ® 공연팀을 데리러 간다."]'::jsonb, 2, '촬영팀에게 연락한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 12, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 13, '다음을 듣고 들은 내용과 같은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 14, '다음을 듣고 들은 내용과 같은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 15, '다음을 듣고 들은 내용과 같은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 16, '다음을 듣고 들은 내용과 같은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 17, '', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["저녁 식사를 미리 준비해 두어야 한다.", "SAS 한꺼번에 많이 먹지 않는 것이 좋다.", "AGS 위해서 식사를 규칙적으로 해야 한다.", "피곤할 때는 저녁을 밖에서 사 먹는 것이 좋다."]'::jsonb, 2, '피곤할 때는 저녁을 밖에서 사 먹는 것이 좋다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 18, '친구가 힘들 때는 옆에 있어 줘야 한다.
@ 여러 사람과 잘 지내기 위해 노력할 필요가 있다.
@ 다른 사람과 함께 있을 때는 BS 조심해야 한다.
® 친구와 문제가 생겼을 때는 빨리 해결하는 것이 좋다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 19, '여행은 여유롭게 하는 것이 좋다.
@ 여행을 자주 가는 것은 좋지 않다.
(8) 여행에서 다양한 BBS 해 봐야 한다.
® 여행에 필요한 예산을 정해 놓을 필요가 있다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 20, '', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["광고를 짧게 만드는 것이 효과적이다.", "광고는 대중의 호기심을 자극해야 한다.", "광고는 ASS] 정보를 사실대로 전달해야 한다.", "광고는 보는 사람이 쉽게 이해할 수 있어야 한다."]'::jsonb, 2, '광고는 대중의 호기심을 자극해야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 21, '남자의 중심 생각으로 가장 알맞은 것을 고르십시오.
회의 내용을 빠짐없이 기록해야 한다.
<) 회의 때 낭비되는 SS 줄이는 것이 좋다.
8) 회의실을 지금보다 더 큰 장소로 바꿔야 한다.
@) 발표 자료는 알아보기 쉽게 만드는 것이 좋다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 22, '들은 내용과 같은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이번 회의는 발표 자료 없이 진행된다.", "여자는 회의에서 쓸 ALS 복사할 예정이다.", "VAS 회의 때 대형 화면을 사용한 적이 있다.", "여자는 참석자들에게 참고할 자료를 이미 이메일로 보내 놓았다."]'::jsonb, 2, 'VAS 회의 때 대형 화면을 사용한 적이 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 23, '남자가 무엇을 하고 있는지 고르심시오.
D 가게의 위치를 확인하고 있다.
® 가게 운영에 대해 조언을 구하고 있다.
@ 구매할 물건의 사용 방법을 물어보고 있다.
@® 원하는 조건의 물건이 있는지 알아보고 있다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 24, '들은 내용과 같은 것을 고르심시오.
0) 여자의 가게에는 크기가 큰 냉장고가 없다.
@ 남자는 카페에서 케이크를 팔지 않기로 했다.
@ 남자의 카페에는 유리문이 달린 냉장고가 있다.
® 여자의 가게에서는 새로 나온 제품만 판매한다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 25, '남자의 종심 생각으로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["마을 축제에 대한 주민들의 관심이 필요하다.", "마을의 SYS 활용한 것이 축제의 성공 비결이다.", "축제에서 판매할 기념품을 새로 제작하는 것이 좋다.", "축제를 기획할 때 성공 사례를 충분히 검토해야 한다."]'::jsonb, 2, '마을의 SYS 활용한 것이 축제의 성공 비결이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 26, '들은 내용과 같은 AS 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 마을을 아는 사람이 거의 없다. ® 이 마을에서 축제가 을해 처음으로 열렸다.", "이 마을의 해바라기 들판은 최근에 만들어졌다.", "이 마을의 특산품이 관광객에게 좋은 반응을 얻었다.", "다음을 듣고 물음에 답하십시오. (각 2점)"]'::jsonb, 2, '다음을 듣고 물음에 답하십시오. (각 2점)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 27, '남자가 말하는 의도로 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 과자의 맞이 달라진 것을 지적하려고", "이 과자를 생산하게 된 이유를 알려 주려고", "이 과자의 생산이 중단될 것이라는 소식을 전하려고", "이 과자를 구하기 어려운 것에 대한 불만을 말하려고"]'::jsonb, 2, '이 과자를 구하기 어려운 것에 대한 불만을 말하려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 28, '들은 내용과 같은 것을 고르십시오.
© 이 회사는 작업 시간을 늘렸다.
® 남자는 이 과자를 구입한 적이 있다.
© ©] 과자는 사람들의 관심을 끌지 못했다.
0 여자는 남자에게 이 과자에 대해 처음 들었다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 29, '남자가 누구인지 고르십시오.
@ ERS 정비하는 사람
@ 교통 상황을 촬영하는 사람
® 도로에 CCIVE 설치하는 사람
® 방송에서 교통 상황을 알려 주는 사람', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 30, '들은 내용과 같은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["WH 매일 오후에 근무를 시작한다.", "남자는 이 일을 할 때 긴장하지 않는다.", "남자는 CCTVS 분석하는 일을 하지 않는다.", "BAS] 일에는 시민들이 보낸 문자를 보는 것이 포함된다."]'::jsonb, 2, 'BAS] 일에는 시민들이 보낸 문자를 보는 것이 포함된다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 31, '남자의 중심 생각으로 가장 알맞은 것을 고르십시오.
0) 시설을 다른 지역으로 옮겨서 설치해야 한다.
(3) 시설의 설치 효과에 대한 명확한 검증이 필요하다.
@ 시설 AA 대한 반대는 SRS 통해 해결할 수 있다.
® 시설의 설치 사실을 주민들에게 바로 알리지 않는 것이 좋다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 32, '남자의 태도로 가장 알맞은 것을 고르십시오.
0) 앞으로 일어날 문제에 대해 걱정하고 있다.
(3) 자신의 의견대로 될 것임을 확신하고 있다.
@ 상대방에게 객관적인 BAS 요구하고 있다.
® 상황이 심각해진 것에 대한 책임을 묻고 있다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 33, '무엇에 대한 내용인지 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["음악을 감상하는 올바른 방법", "음악적 재능이 발달하는 결정적 시기", "HIS 대상으로 하는 연구에서 주의할 점", "음악 활동이 노인의 인지 기능에 미치는 영향"]'::jsonb, 2, '음악 활동이 노인의 인지 기능에 미치는 영향', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 34, '들은 내용과 같은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 APS 위한 ABS 1년 동안 진행됐다. ® 이 FB} 결과는 AHA] 예상과 같았다.", "이 실험에서 두 집단은 동일한 결과를 보였다.", "이 ABS 음악을 전공한 사람들을 대상으로 했다.", "CSS 듣고 물음에 답하십시오. (각 2점)"]'::jsonb, 2, '이 실험에서 두 집단은 동일한 결과를 보였다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 35, '남자가 무엇을 하고 있는지 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 편지가 가지는 가치와 의의를 알리고 있다.", "이 편지의 보존 상태에 대해 아쉬움을 표하고 있다.", "이 편지가 발견된 장소와 발굴 과정을 보고하고 있다.", "이 WAS 연구하는 데 도움을 준 사람들에게 감사하고 있다."]'::jsonb, 2, '이 편지가 가지는 가치와 의의를 알리고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 36, '들은 내용과 같은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 편지는 곧 박물관에 전시될 것이다.", "이 WAL 군인인 남편이 아내에게 쓴 것이다.", "이 편지가 어느 시대의 것인지 밝혀지지 않았다.", "이 WAS BS 지정하기 위한 논의가 진행 중이다."]'::jsonb, 2, '이 WAL 군인인 남편이 아내에게 쓴 것이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 37, '여자의 중심 생각으로 가장 알맞은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["SAS 수출하기 위한 경로를 확보해야 한다.", "산림 순환 경영을 통해 좋은 효과를 얻을 수 있다.", "좋은 목재를 얻을 수 있는 나무를 심는 것이 좋다.", "산림 순환 경영이 정착될 때까지 시간이 필요하다."]'::jsonb, 2, '산림 순환 경영을 통해 좋은 효과를 얻을 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 38, '들은 내용과 같은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["한국은 목재 수입 비중이 낮은 편이다.", "한국은 산림 순환 경영을 시행하고 있다.", "나무가 30년 이상 되면 탄소 흡수 능력이 떨어진다. ® 한국의 산에는 심은 지 얼마 안 된 어린나무가 많다.", "CSS 듣고 물음에 답하십시오. (각 2점)"]'::jsonb, 2, '나무가 30년 이상 되면 탄소 흡수 능력이 떨어진다. ® 한국의 산에는 심은 지 얼마 안 된 어린나무가 많다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 39, '이 대화 전의 내용으로 가장 알맞은 AS 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["인공위성을 관측하는 신기술이 개발되었다.", "대기권에서 인공위성이 폭발하는 사고가 있었다.", "우주 조약을 개정하기 위해 여러 나라 사람들이 모였다.", "우주 탐사를 위한 인력을 양성하는 것은 쉬운 일이 아니다."]'::jsonb, 2, '대기권에서 인공위성이 폭발하는 사고가 있었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 40, '들은 내용과 같은 것을 고르십시오.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["얼마 전에 국제 우주법이 제정되었다.", "우주 조약은 구체적인 내용으로 구성되어 있다. 0", "우주 조약은 강제적인 효력을 가지고 있지 않다.", "인공위성으로 인한 전파 방해 문제는 일어나지 않을 것이다."]'::jsonb, 2, '우주 조약은 강제적인 효력을 가지고 있지 않다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 41, '※ ([41~4', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["CSS 듣고 물음에 답하십시오. (각 2점) 41. 이 강연의 중심 내용으로 가장 알맞은 것을 고르십시오.", "제품의 FIL 부품의 Ao] 의해 결정된다.", "ALG 일자리 창출에 크게 기여하고 있다.", "제품에 대한 고객의 의견을 반영하는 것이 중요하다. 9 제조업은 사업 영역 WHS 통해 발전을 도모하고 있다."]'::jsonb, 2, '제품에 대한 고객의 의견을 반영하는 것이 중요하다. 9 제조업은 사업 영역 WHS 통해 발전을 도모하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 42, '※ ([41~4', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["CSS 듣고 물음에 답하십시오. (각 2점) 42. 들은 내용과 같은 것을 고르십시오.", "이 업체는 엔진 판매에 어려움을 Aw 있다.", "조선업이 경제적으로 힘든 상황에 놓여 있다.", "이 업체는 안정적인 수입을 얻지 못하고 있다. 9 이 업체는 실시간 엔진 점검 서비스 시스템을 마련했다."]'::jsonb, 2, '이 업체는 안정적인 수입을 얻지 못하고 있다. 9 이 업체는 실시간 엔진 점검 서비스 시스템을 마련했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 43, '※ ([41~4', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["CSS 듣고 물음에 답하십시오. (각 2점) 43. 무엇에 대한 내용인지 알맞은 것을 고르십시오. 0", "종묘 정전의 건축미", "종묘 정전의 건립 과정", "종묘 정전의 관리 방법 @ 종묘 정전의 현대적 기능"]'::jsonb, 2, 'CSS 듣고 물음에 답하십시오. (각 2점) 43. 무엇에 대한 내용인지 알맞은 것을 고르십시오. 0', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 44, '※ ([41~42] CSS 듣고 물음에 답하십시오. (각 2점)
44. 종묘 정전에 대한 설명으로 맞는 것을 고르십시오.
0 지붕이 곡선 형태로 휘어 있다.
® 기둥에 화려한 색이 사용되었다.
® 도심에서 멀리 떨어진 곳에 있다.
9 왕과 왕비의 제사를 지내는 공간이다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 45, '※ ([45~4', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["CSS 듣고 SS", "답하십시오. (각 2점) 45. 들은 내용과 같은 것을 고르십시오. ® 충수에는 염증이 잘 생기지 않는다.", "충수는 소화가 잘되도록 돕는 일을 한다. (", "충수에는 유익한 미생물이 서식하고 있다. <) 충수를 제거하는 수술이 최근에 가능해졌다."]'::jsonb, 2, '충수는 소화가 잘되도록 돕는 일을 한다. (', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 46, '※ ([45~4', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["CSS 듣고 SS", "답하십시오. (각 2점) 46. 여자가 말하는 방식으로 알맞은 것을 고르십시오.", "유사한 사례들을 묶어 비교 분석하고 있다. ® 대상이 가진 BA] 주요 원인을 유추하고 있다. (", "대상의 역할에 대해 밝혀진 사실을 설명하고 있다. © 다양한 연구를 바탕으로 자신만의 기준을 제시하고 있다."]'::jsonb, 2, '유사한 사례들을 묶어 비교 분석하고 있다. ® 대상이 가진 BA] 주요 원인을 유추하고 있다. (', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 47, '※ ([45~4', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["CSS 듣고 SS", "답하십시오. (각 2점) 47. 들은 내용과 같은 것을 고르십시오.", "인건비와 임대료는 고정 비용에 포함되지 않는다.", "소상공인의 AIO 일률적 방식으로 해결할 수 있다. @ 대출 의존도가 높은 경우 채무를 조정해 주면 안 된다. @) 영업 비용 때문에 빚을 지는 소상공인이 많아지고 있다."]'::jsonb, 2, '소상공인의 AIO 일률적 방식으로 해결할 수 있다. @ 대출 의존도가 높은 경우 채무를 조정해 주면 안 된다. @) 영업 비용 때문에 빚을 지는 소상공인이 많아지고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 48, '※ ([45~46] CSS 듣고 SSO] 답하십시오. (각 2점)
48. 남자의 태도로 알맞은 것을 고르십시오.
0) 소상공업계의 태도 변화를 기대하고 있다.
<) 경제 위기 극복을 위한 소상공인의 노력에 감탄하고 있다.
® 소상공인에 대한 실효성 있는 지원 방안을 제안하고 있다.
® 소상공업의 활성화가 가져올 경제적 효과를 낙관하고 있다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 49, '들은 내용과 같은 것을 고르십시오.
© 이 철학자는 도덕성에 대해 일반적인 AHS 따르고 있다.
® 이 철학자는 도덕성을 평가하는 기준에서 감정을 배제했다.
@ 이 철학자에 따르면 출근 시간을 지키는 것은 도덕적 의무가 아니다.
@ 이 철학자에 따르면 어떤 상황에서도 다른 사람을 돕는 것이 최우선이다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 50, '남자의 태도로 알맞은 것을 고르십시오.
© 도덕적 행위의 당위성을 강조하고 있다.
® 도덕적 행위의 가치를 과대평가하고 있다.
@ 도덕성에 대한 선부른 판단을 경계하고 있다.
@ 도덕성에 대한 연구의 필요성을 제기하고 있다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 51, '※ [~ ( )에 들어갈 말로 가장 알맞은 것을 고르십시오. (각 2점)
1. 나는 오래전에 설악산을 ( ).
© 등산하고 싶다 ® 등산해도 된다
@ 등산할 것 같다 @ 등산한 적이 있다', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 52, '※ [~ ( )에 들어갈 말로 가장 알맞은 것을 고르십시오. (각 2점)
2. 새집으로 ( ) 가구를 새로 Abc
© 이사한 지 ® 이사하거든
@) 이사하려면 ® 이사하고 나서
※ [3~4] 밑줄 친 부분과 의미가 가장 비슷한 것을 고르십시오. (각 2점)', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 53, '※ [~ ( )에 들어갈 말로 가장 알맞은 것을 고르십시오. (각 2점)
3. 어려운 LS 돕고자 매년 봉사 활동에 참여하고 있다.', NULL, NULL, NULL, '["돕기 위해서", "돕는 대신에", "돕기 무섭게", "돕는 바람에"]'::jsonb, 2, '돕기 위해서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 54, '※ [~ ( )에 들어갈 말로 가장 알맞은 것을 고르십시오. (각 2점)
4. 지난 3년 동안 영화를 한 편 봤으니 거의 안 본 셈이다.
<) 본 척했다 @ 보기 나름이다
@) 볼 수밖에 없었다 @ 본 거나 마찬가지이다', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 55, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q55.png', NULL, NULL, '["비누", "AS", "안경", "수건"]'::jsonb, 2, 'AS', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 56, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q56.png', NULL, NULL, '["은행", "서점", "유치원", "우체국"]'::jsonb, 2, '유치원', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 57, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q57.png', NULL, NULL, '["계단으로 다니기! 하루 30H 운동하기! 우리 몸을 위해 실천하세요.", "건강 관리 Osa _", "전화 예절 0", "절약 습관"]'::jsonb, 2, '계단으로 다니기! 하루 30H 운동하기! 우리 몸을 위해 실천하세요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 58, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q58.png', NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 59, '다음 글 또는 도표의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q59.png', NULL, NULL, '["ie 이용 요금: 성인 10,000원/학생 5,000원(7세이하 무료)", "예약 방법 : 출발 하루 전까지 홈페이지(//////.]4-10나.0000)0", "성인과 학생의 버스 유금이 같다. <) 이 HAE 별빛공원에서 출발한다. (", "매일 LA] 이 HAS 탈 수 있다. ® 이 HAS 타려면 미리 신청해야 한다."]'::jsonb, 2, '매일 LA] 이 HAS 탈 수 있다. ® 이 HAS 타려면 미리 신청해야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 60, '다음 글 또는 도표의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q60.png', NULL, NULL, '["를 2022 3", "조사 CHAE: 직 30 28 27 <조사 대상: 직장인 1,000명> 20 | 10 8 5", "ope 버스 지하철 걸어서 기타", "자가용으로 출퇴근한다고 응답한 직장인들의 비율이 줄었다. @) 걸어서 출퇴근하는 직장인은 2012년보다 2022년이 더 적었다. @ 2022년에는 지하철을 타고 출퇴근하는 직장인이 가장 많았다. ® 2012년에 직장인들은 출퇴근할 때 YAS 제일 많이 이용했다."]'::jsonb, 2, '조사 CHAE: 직 30 28 27 <조사 대상: 직장인 1,000명> 20 | 10 8 5', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 61, '| _ 인주시가 작년에 이어 올해도 10월 한 달간 ''찾아가는 자전거 수리 센터`를
운영한다. 평일에는 여러 ASS 직접 방문해 고쳐 주고 주말에는 인주공원
에서 수리 서비스를 제공한다. 전문 수리 기사가 자전거를 무료로 고쳐 주고
부품 교체가 필요한 경우에는 저렴한 가격으로 바꿔 준다. 시는 시민들의
자전거 타기 생활화를 위해 이 수리 센터를 운영하는 것이라고 밝혔다.
0) 이 서비스는 일 년 내내 운영된다.
© 올해 ALOR 이 센터가 운영되기 시작했다.
8) 주말에는 인주공원에서 수리를 받을 수 있다.
® 이 수리 센터에서는 무료로 부품을 교체해 준다.', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 62, '| 피자 가게를 운영하는 김민수 씨의 사연이 진잔한 WES 주고 있다. 최근
김 씨는 피자를 배달하러 가다가 오토바이가 빗길에 미끄러지는 사고를
당했다. 다행히 사람이 다치는 피해는 없었지만 피자가 망가져서 배달에
BADE 생겼다. 배달이 늦어지는 것에 대해 김 씨가 고객에게 연락히자 고객은
“천천히 오셔도 돼요. 몸은 괜찮나요?"라며 따뜻한 말부터 전했다고 한다.', NULL, NULL, NULL, '["고객은 주문한 피자를 취소하겠다고 말했다.", "사고가 생겨서 배달 중이던 피자가 망가졌다.", "오토바이가 빗길에 미끄러져서 김 씨가 다쳤다.", "김 씨는 피자를 시킨 고객에게 연락하다 사고가 났다."]'::jsonb, 2, '사고가 생겨서 배달 중이던 피자가 망가졌다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 63, '| (가) 짧게는 하루, 길게는 한 달 정도 반짝 운영하는 임시 매장이다.
(나) 사람이 붐비는 장소에서 짧은 기간 동안 운영하는 매장이 유행이다.
(다) 기업은 이 임시 매장을 이용해 주로 특정 ASS 팔거나 홍보를 한다.
ED) 또 기업 이미지를 친숙하게 만들기 위해 재미있는 행사를 열기도 한다.
® (가) - (다) - (라) - (4) (9) (나) - (가) - (다) - (라)
(8) (가) - (라) - (나) - () (4) (나) - (라) - (다) - (가)', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 64, '| (가) 그런데 전화를 끊고 뒤늦게 미안한 마음이 들었다.
(나) 친구는 나의 합격 소식을 듣고 자신의 일처럼 기뻐했다.
(다) 얼마 전 나는 회사 합격 ANS 듣고 친한 친구에게 전화했다.
(라) 아직 취업 못 한 APS 내가 배려하지 못했다는 생각 때문이었다.
0) (나) - (다) - (라) - (가) (9) (나) - (라) - (가) - (다)
(8) (다) - (나) - (가) - (라) (4) (다) - (나) - (라) - (가)', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 65, '| (가) 빵이나 고기를 구울 때 갈색으로 바뀌는 것이 그 예이다.
(나) 갈색으로 바뀌면서 빵이나 고기의 맛도 더 깊어지고 풍부해진다.
(다) 식품에 들어 있는 당과 단백질이 열을 만나면 색깔이 바뀌게 된다.
(라) 만약 열이 너무 가해져서 검게 타게 되면 그런 맛을 낼 수가 없다.
<) (가) - (나) - (라) - EH) (9) (다) - (가) - (나) - (라)
(8) (가) - (다) - (라) - (4) 8) (다) - (라) - (나) - (가)', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 66, '※ [16~18] ( )에 들어갈 말로 가장 알맞은 AS 고르십시오. (각 28)
16.| 타조는 멀리서 적이 IKE 머리를 모래에 HR 있다. 그래서 위험이나
위기를 모르는 척 피하는 사람을 타조에 비유하곤 한다. 그런데 사실 타조는
( ) 위해 이런 행동을 한다. 시각보다 청각이 발달한 타조는
망에서 울리는 발소리를 듣고 적이 오는지를 파악하려는 것이다.
0) 적의 움직임을 알기 <) 먹이를 빨리 구하기
08 머리를 깨끗이 371 0 다른 타조를 공격하기', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 67, '※ [16~18] ( )에 들어갈 말로 가장 알맞은 AS 고르십시오. (각 28)
17.| _ 섬유 유연제는 섬유에 막을 씩워 옷감을 부드럽게 하고 향기도 남긴다.
그래서 세탁할 때 유연제를 넣는 사람들이 많다. 그런데 수건처럼 물기를
빠르게 흡수해야 하는 소재에는 유연제를 넣는 것이 좋은 것만은 아니다.
유연제가 만든 막이 오히려 섬유의 ( ) 때문이다.
0) 향기를 없애기 <) 색깔을 변형시키기
8) Seas 떨어뜨리기 ® 촉감을 거칠게 만들기', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 68, '※ [16~18] ( )에 들어갈 말로 가장 알맞은 AS 고르십시오. (각 28)
18.| 디지털 기기에 대한 의존도가 높아지면서 사람들이 무언가 직접 기억해야
할 일은 줄었다. 그래서 이전보다 ( ) 생각할 수 있다.
그런데 뇌를 사용하는 방식이 이전과 달라졌을 뿐 사용량이 줄어든 것이
아니다. 과거에는 단순히 정보를 기억하는 데 뇌를 썼다면 이제는 과거보다
압도적으로 많아진 정보를 처리하는 데 사용하고 있는 것이다.
0) 뇌를 덜 사용한다고
® 기억력이 좋아졌다고
8) 저장해야 할 정보가 많다고
® 디지털 기기를 많이 쓴다고', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 69, '매서운 남극의 겨울, 황제팽권들은 겹겹이 붙어 서로의 체온으로 추위를
견딘다. 무리 전체가 돌면서 바깥쪽과 안쪽에 있는 팽권들이 계속 서로의
위치를 바꾼다. 안에서 BS 데운 GAs 밖으로 나기고 밖에서 추위에 떨던
평권은 안으로 들어오는 것이다. ( ) 그 움직임은 아주 느리지만
쉬지 않고 이루어져 한 마리의 팽권이 줄곧 찬바람을 맞고 서 있는 일이
없다. 그렇게 쉼 없이 둥글게 돌면서 Base 다 함께 살아남는다.
19. ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.', NULL, NULL, NULL, '["혹시", "또는", "비록", "만약"]'::jsonb, 2, '비록', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 70, '매서운 남극의 겨울, 황제팽권들은 겹겹이 붙어 서로의 체온으로 추위를
견딘다. 무리 전체가 돌면서 바깥쪽과 안쪽에 있는 팽권들이 계속 서로의
위치를 바꾼다. 안에서 BS 데운 GAs 밖으로 나기고 밖에서 추위에 떨던
평권은 안으로 들어오는 것이다. ( ) 그 움직임은 아주 느리지만
쉬지 않고 이루어져 한 마리의 팽권이 줄곧 찬바람을 맞고 서 있는 일이
없다. 그렇게 쉼 없이 둥글게 돌면서 Base 다 함께 살아남는다.
20. 윗글의 주제로 가장 알맞은 것을 고르십시오.', NULL, NULL, NULL, '["PAGAL 서로 도우면서 추위에 맞서 생존해 왔다.", "황제평권은 둥글게 돌면서 날씨에 대한 정보를 알린다.", "PAPAS 추위에서 살아남기 위해 움직임이 느려졌다.", "황제평권은 무리 생활을 통해 경쟁에서 이기는 BS 배운다."]'::jsonb, 2, 'PAGAL 서로 도우면서 추위에 맞서 생존해 왔다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 71, '최근 미술 전시회 수요가 증가하면서 돈벌이에 급급한 전시회가 늘고
있다. 일부 전시 관계자들이 전시 포스터 등 홍보 자료에 복제품 전시임을
밝히지 않고 입장료 수입만을 챙기는 것이다. 전시장을 찾아와서야 이런
사실을 알게 된 관람객들은 불만을 쏟아 내고 있다. 전문가들은 이런 전시
행태가 미술계 발전의 ( ) 수 있다고 우려한다. 전시회에
실망한 사람들이 미술에 대한 관심을 아예 끊을 수 있기 때문이다.
21. ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.', NULL, NULL, NULL, '["입맛에 맞을", "가슴을 울릴", "발목을 잡을", "손을 맞잡을"]'::jsonb, 2, '발목을 잡을', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 72, '최근 미술 전시회 수요가 증가하면서 돈벌이에 급급한 전시회가 늘고
있다. 일부 전시 관계자들이 전시 포스터 등 홍보 자료에 복제품 전시임을
밝히지 않고 입장료 수입만을 챙기는 것이다. 전시장을 찾아와서야 이런
사실을 알게 된 관람객들은 불만을 쏟아 내고 있다. 전문가들은 이런 전시
행태가 미술계 발전의 ( ) 수 있다고 우려한다. 전시회에
실망한 사람들이 미술에 대한 관심을 아예 끊을 수 있기 때문이다.
22. 윗글의 내용과 같은 것을 고르십시오.
0) 복제품 전시회는 입장료를 받지 않는다.
03) 최근 미술 전시회를 찾는 사람들이 많지 않다.
(8) 전시회에서 복제품을 전시하는 So] 점점 줄고 있다.
® 복제품 전시회인지 모르고 전시회를 방문한 관람객들이 있다.', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 73, 'BAS 지나다가 꽃말에 이끌려 금진화 꽃씨를 ale}. 화분에 심어 사무실의
내 책상 위에 두었더니 어느 PAO] ACh 때맞춰 물도 주며 나는 수시로
들여다보았다. 신기했다. 작고 여린 AL 눈에 띄게 쑥쑥 자랐다. 그런데
내가 상상한 모습이 아니었다. 도대체 여기서 어떻게 꽂이 핀다는 건지.
무순처럼 Asp 위로만 자라는 것이었다. 하루는 출근해 보니 금잔화가
쓰러져 있었다. 그럼 그렇지. 내가 무슨 식물을 키우나. 그날 나는 화분을
창가로 A 놓았다. 죽을 것 같은 BSS 눈앞에서 보고 싶지 않았다. 그런데
어느 날부턴가 점점 줄기가 굴어지더니 잊도 제법 풍성해지기 시작했다.
어느 날에는 꽃망울도 올라와 있었다. 금잔화는 창문으로 들어오는 풍성한
햇별 속에서 스스로 튼튼해졌다. 금잔화에게는 햇빛이 더 많이 필요했었나
보다. 사람도 식물도 사랑하려면 그 대상을 제대로 알아야 하는 건 똑같구나
싶었다. 씩씩하게 BIS 금잔화의 BHO ''반드시 을 행복''이다.
23. 밑줄 친 부분에 나타난 ''나"의 심정으로 가장 알맞은 것을 고르십시오.
© 의심스럽다
® 고통스럽다
0 조심스럽다
® 부담스럽다', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 74, 'BAS 지나다가 꽃말에 이끌려 금진화 꽃씨를 ale}. 화분에 심어 사무실의
내 책상 위에 두었더니 어느 PA', NULL, NULL, NULL, '["ACh 때맞춰 물도 주며 나는 수시로 들여다보았다. 신기했다. 작고 여린 AL 눈에 띄게 쑥쑥 자랐다. 그런데 내가 상상한 모습이 아니었다. 도대체 여기서 어떻게 꽂이 핀다는 건지. 무순처럼 Asp 위로만 자라는 것이었다. 하루는 출근해 보니 금잔화가 쓰러져 있었다. 그럼 그렇지. 내가 무슨 식물을 키우나. 그날 나는 화분을 창가로 A 놓았다. 죽을 것 같은 BSS 눈앞에서 보고 싶지 않았다. 그런데 어느 날부턴가 점점 줄기가 굴어지더니 잊도 제법 풍성해지기 시작했다. 어느 날에는 꽃망울도 올라와 있었다. 금잔화는 창문으로 들어오는 풍성한 햇별 속에서 스스로 튼튼해졌다. 금잔화에게는 햇빛이 더 많이 필요했었나 보다. 사람도 식물도 사랑하려면 그 대상을 제대로 알아야 하는 건 똑같구나 싶었다. 씩씩하게 BIS 금잔화의 BHO ''반드시 을 행복''이다. 24. 윗글의 내용과 같은 것을 고르십시오.", "내 책상 위에 둔 금잔화는 금방 말라 죽었다.", "나는 금잔화 화분에 BS 제대로 주지 못했다.", "나는 꽃집에서 금잔화가 피어 있는 화분을 abeh, @ 내가 금잔화 화분을 옮긴 곳은 햇별이 잘 들었다."]'::jsonb, 2, '나는 꽃집에서 금잔화가 피어 있는 화분을 abeh, @ 내가 금잔화 화분을 옮긴 곳은 햇별이 잘 들었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 75, '| 가수 진영, 3년 만의 콘서트에 구름 관중
D 가수 진영이 3년 만에 콘서트를 열자 수많은 관증이 몰렸다.
09 가수 진영이 3년 내에 다시 콘서트를 열기로 관종에게 약속했다.
08 가수 진영이 3년간 준비한 콘서트를 열었으나 관중의 호응이 적었다.
® 가수 진영이 3년 만에 하는 SAE 많은 BSS 모으려고 홍보했다.', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 76, '| 한국 탁구의 간판 김수미, Sa 국제 대회 금메달 Go|
0) 올해 국제 탁구 대회에서 한국 대표 김수미의 금메달 가능성이 높아졌다.
<) 한국 탁구계가 김수미를 내세워 올해 국제 대회의 금메달을 노리고 있다.
(8) 한국의 대표 탁구 선수 김수미가 올해 국제 대회에서 모두 금메달을 BH.
@) 한국 탁구 선수 김수미가 올해 국제 대회에서 금메달을 따고자 훈련 중이다.', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 77, '| 대출 금리 하락세, 부동산 시장 기지개
D 대출 금리가 떨어지면서 부동산 시장이 살아나기 시작했다.
<) 부동산 시장에 대한 규제가 대출 금리 하락에 영향을 미쳤다.
(8) 대출 금리가 하락했지만 부동산 시장의 거래는 줄어들고 있다.
® 부동산 시장을 활성화하려고 대출 금리 안정화 대책이 논의되고 있다.', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 78, '| 선글라스는 보통 햇빛이 강할 때 눈 건강을 위해 쓴다. 그런데 선글라스의
렌즈는 사용 기한이 있다. 선글라스의 렌즈에는 자외선 ALS 위한 Qe
막이 입혀져 있는데 열에 계속 노출되면 자외선 차단 기능이 점점 떨어지게
된다. 자외선 차단 기능이 약해진 선글라스로는 ES 보호하기 어려우므로
5년 정도 쓰고 나면 ( ) 것이 좋다.', NULL, NULL, NULL, '["렌즈를 바꿔 주는", "렌즈를 꼼꼼히 SE", "렌즈의 색을 BA 하는", "렌즈의 Be 막을 벗겨 내는"]'::jsonb, 2, '렌즈를 바꿔 주는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 79, '| AIA 구도는 전체적인 분위기를 살리는 중요한 요소이다. 보통 동적인
느낌을 주고 싶을 때는 대각선 구도를 쓰는데 도로나 폭포 등의 풍경 사진 등에
쓰여 생동감을 표현한다. 한편 전통적인 가족사진은 ( )
위해서 삼각형 구도를 가장 많이 활용한다. 이 구도는 연장자를 중심으로
가족 구성원이 옆이나 뒤에 배치되어 전체적으로 편안하고 균형 잡힌 분위기를
만들어 낸다.
® 동적인 효과를 살리기
@ 안정적인 LAS 주기
@ 풍경을 중앙에 배치하기
@) 긴장된 분위기를 연출하기', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 80, '| 풍부한 자원은 경제 성장의 필요조건이지 충분조건은 아니다. 풍부한 천연
자원을 갖추고 있음에도 ( ) 경우도 있다. 풍부한 자원에만
의존해 경제 성장의 중심 산업인 제조업이나 서비스업 등에 투자를 하지
않게 되는 것이다. 반면에 천연자원이 빈약해도 새로운 기술 개발이나
교육을 통해 생산 능력을 높이는 나라도 있다.', NULL, NULL, NULL, '["제조업에 의존하려는", "자원을 생산하지 못하는", "경제 WAL 이루지 못하는", "기술 개발에 무리하게 투자하는"]'::jsonb, 2, '경제 WAL 이루지 못하는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 81, '| _ 의사의 모습을 생각하면 우리는 보통 흰색 가운을 떠올리게 된다. 그런데
의사 가운이 처음부터 흰색이었던 것은 아니다. 중세 시대에는 성직자가
의사를 겸하는 경우가 많아 성직자용 검은색 가운을 입고 진료를 했다.
그런데 ALA LL 세균으로 오염된 얼룩이 잘 보이지 않았다. 이후 세균
감염의 위험성에 대한 인식이 높아지면서 ( ) 가운의 색이
흰색으로 바뀌었다.
0', NULL, NULL, NULL, '["엽색하기 편하게", "환자와 구분이 되도록", "오염이 쉽게 눈에 픽도록", "밝은 이미지를 줄 수 있게"]'::jsonb, 2, '오염이 쉽게 눈에 픽도록', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 82, '| 당뇨 환자들을 위해 고추 품종인 ''살리초''가 개발되었다. 고추는 보통
열매를 얻기 위해 재배하지만 살리초는 열매가 없고 잎을 먹는 품종이다.
일반 고추에 비해 WIS 낮추는 성분이 1배 이상 많이 함유돼 있어 당뇨병,
비만증 등 성인병의 예방과 치료에 이용될 수 있다. 또한 살리초에는 칼슴,
비타민 등 각종 영양 성분이 풍부하다. 병해충에도 강하고 생육 기간도
짧아서 농가의 고소득 작물로 주목받고 있다.', NULL, NULL, NULL, '["살리초는 해충에 취약하다는 단점이 있다.", "살리초의 열매는 크고 영양 성분이 풍부하다.", "AYRE 생육 기간이 길어 BIS 받지 못하고 있다.", "살리초의 잎에는 WHS 떨어뜨리는 성분이 들어 있다."]'::jsonb, 2, '살리초의 잎에는 WHS 떨어뜨리는 성분이 들어 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 83, '| _ 『임원경제지』는 조선 시대 서유구가 쓴 백과사전이다. 선비가 시골에서
살아가는 데 필요한 지식을 탐색한 것으로 농업, 건축, 의학 등 16개 분야를
정리했다. 서유구는 이 책을 쓸 때 조선의 생활상을 직접 관찰하고 여러
서적들을 참고했으며 거기에 자신의 논평을 첨부했다. 이 과정에서 인용한
책들을 밝혀 놓아 서지학적 가치도 크다. 총 52권의 책을 편찬했는데 개인이
완성했다고 보기 어려울 만큼 방대하고 전문적인 지식이 담겨 있다.', NULL, NULL, NULL, '["이 YL 각 분야의 전문가가 모여 만든 책이다.", "서유구는 집필하면서 참고한 LAS 이 책에 기록해 놓았다.", "서유구는 객관적인 BS 쓰기 위해 자신의 의견은 배제했다.", "이 책은 내용이 특정 분야에 한정되어 서지학적 가치는 크지 않다."]'::jsonb, 2, '서유구는 집필하면서 참고한 LAS 이 책에 기록해 놓았다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 84, '| _ 코알라는 유칼립투스라는 나못잎을 먹고 산다. 이 나못잎은 독성이 강해서
일반적인 동물들은 먹을 수 없다. 하지만 코알라는 유칼립두스의 Se
해독하는 효소가 있어서 다른 동물들과 경쟁할 필요 없이 유칼립두스
2S 충분히 먹을 수 있다. 다만 새끼 코알라는 SIS 분해하는 효소가
없어서 유칼립투스 잎 대신 어미의 배설물을 먹는다. 이를 먹다 보면 새끼
AWS] 몸속에도 유칼립투스의 독을 해독하는 효소가 생기게 된다.', NULL, NULL, NULL, '["다양한 동물들이 유칼립투스 잎을 차지하기 위해 경쟁한다.", "어미 코알라는 유칼립투스의 SYS 분해하는 BAS 가지고 있다.", "코알라는 태어난 직후부터 많은 양의 유칼립투스 URNS 먹는다.", "새끼 코알라는 유칼립투스의 독성 때문에 어미의 배설물을 먹지 않는다."]'::jsonb, 2, '어미 코알라는 유칼립투스의 SYS 분해하는 BAS 가지고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 85, '| _ 태양계에 존재하는 수많은 소행성에는 천문학적인 가치를 지닌 광물이
있는 것으로 예상된다. 그래서 많은 나라들이 이에 관심을 가지고 있다.
실제로 최근 몇몇 국가에서는 소행성에 있는 광물 시료를 채취하는 데
성공하기도 했다. 하지만 대부분의 나라들에서는 소행성 탐사가 아직 논의
단계에 머무르고 있다. 미래 자원을 확보하기 위해서 적극적으로 소행성
탐사에 대한 투자와 기술 개발에 나설 필요가 있다.
© 태양계에는 아직 발견되지 않은 소행성이 많이 존재한다.
@ 소행성에서 자원을 가져오는 것은 실현 가능성이 희박하다.
08 소행성 탐사를 성공시키기 위해 국제 협력을 확대해야 한다.
® 미래 자원 확보를 위해 소행성 탐사에 대한 LAS 기울여야 한다.', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 86, '| 경기 침체에 빠지면 사람들은 소비보다는 ASS 늘리려고 한다. 그런데
저축이 언제나 긍정적인 것만은 아니다. 소비가 SA 기업의 매출이 감소
해서 생신과 고용이 줄 수밖에 없고 결국 근로자들의 ASE 줄어들게 된다.
그러면 미래가 불확실해진 사람들이 더욱 소비를 줄여 전체 경기가 다시
침체에 빠지는 악순환이 되풀이된다. 개인 차원에서는 저축이 합리적인 행동
이지만 경제 전체적으로는 비합리적인 상황을 초래하게 되는 것이다.', NULL, NULL, NULL, '["불경기에는 비합리적인 AM 인해 근로자들의 저축이 줄어든다.", "경기가 침체하면 개인의 소득이 줄어들지 않도록 투자를 늘려야 한다.", "경제 상황을 고려해서 생산과 WSS 적절히 조절하는 것이 중요하다.", "경기 침체 시에는 저축이 국가 경제 전체에 부정적 영향을 줄 수 있다."]'::jsonb, 2, '경기 침체 시에는 저축이 국가 경제 전체에 부정적 영향을 줄 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 87, '| 참치 쿼터제는 참치의 무분별한 포획을 막기 위해 어획량을 국가별로
정해 놓은 제도이다. 한국은 참치 FIFO] 매우 적게 배정돼 있는데 이는
한국 연안에서는 참치가 거의 잡히지 않았기 때문이다. 최근 수온이 상승
함에 따라 한국 연안에 유입되는 참치가 금격히 늘어나고 있지만 쿼터제
때문에 그물에 걸린 참치를 대부분 바다에 버리고 있다. 쿼터제의 필요성은
인정하지만 국가별 개체 수 증감을 반영한 BEA 있는 조정이 필요하다.
® 국가별 상황에 따라 참치 쿼터제를 현실에 맞게 수정해야 한다.
© 참치의 무분별한 포획을 방지하기 위해 쿼터제를 도입해야 한다.
0 수온 상승으로부터 참치를 보호하기 위한 대책을 마련해야 한다.
® 참치의 유입량을 늘리기 위한 실질적인 연구가 이루어져야 한다.', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 88, '* [35~3', NULL, NULL, NULL, '["CSS 읽고 글의 주제로 가장 알맞은 것을 고르십시오. (각 2점) 38.| _ 기업들은 기술 혁신을 통해 고객에게 편의와 FAS 제공하려고 한다. 하지만 아무리 획기적인 혁신이라도 고객에게 낮설고 커다란 행동 변화를 요구한다면 외면당하기 쉽다. 예를 들어 초창기 전기 자동차는 전기로 오래 SAL 해야 하는 것이 낮설고 불편해서 큰 관심을 끌지 못했다. 반대로 전자 칠판과 전자 펜처럼 대단한 혁신은 아니지만 사용하는 방법이 고객 에게 익숙하고 간단해서 환영받는 경우도 있다.", "BAS 무리한 요구 때문에 기술 혁신에 어려움을 겪게 된다.", "혁신적인 기업은 고객들에게 신기술의 사용 방법을 잘 설명해 준다.", "기술 혁신에 실패한 기업은 자연스럽게 고객들의 외면을 받게 된다. @) 기술 혁신은 고객이 쉽게 받아들일 수 있을 때 성공할 가능성이 높다."]'::jsonb, 2, '기술 혁신에 실패한 기업은 자연스럽게 고객들의 외면을 받게 된다. @) 기술 혁신은 고객이 쉽게 받아들일 수 있을 때 성공할 가능성이 높다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 89, '* [35~38] CSS 읽고 글의 주제로 가장 알맞은 것을 고르십시오. (각 2점)
39.| 그런데 심판이 아무리 위치 선정을 잘해도 필연적으로 선수의 몸에 가려서
볼 수 없는 사각지대가 생긴다.
스포츠 경기를 진행할 때 득점이나 반칙 등의 WSS 심판에 의해서 이루어
진다. (^ 이 ) 이렇게 눈에 보이지 않는 곳에서 벌어진 상황에 대해서는
ABE 정확한 판단을 하기 어렵다. (©) 비디오 판독은 이런 스포츠
경기에서 초고속 카메라를 판정의 DAS 사용하는 기술이다. (< )
이처럼 비디오 BES 활용하면 심간이 판단하기 어려운 부분을 객완적으로
확인할 수 있어 Ago] 대한 신뢰도를 높일 수 있다 ( @ )
O@ One) 8) 9)', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 90, '| 그 증거로 지중해 전역에서 발견되고 있는 소금 퇴적층을 들 수 있다.
유럼과 아시아, 아프리카 대륙으로 둘러싸인 바다를 지중해라고 한다.
( @ ) 오늘날 지중해 연안은 기후가 온화하서 살기 좋은 곳으로 손꼽힌다.
( © ) 그런데 ASHE 오래전 사막이었던 적이 있었다 (2 )
이 소금 퇴적층은 바닷물이 증발되고 남은 소금이 쌓여 만들어진 것으로
지중해가 이전에는 사막이었음을 보여 준다. (^ < _ ) 사막이었던 지중해에
이후 큰 홍수가 발생하면서 다시 오늘날과 같은 바다가 되었다.
O@ Ox) 9) Oe', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 91, '| 이런 상소문들을 저자는 왕을 향한 깨우침의 죽비 소리로 비유하고 있다.
최근 역사학자 김경민 씨가 「응답하라, 조선』을 펴냈다 (GD) 이 책은
왕과 신하의 소통을 다루고 있어 사람들의 관심을 끈다. ( < ) 그 소통의
내용 중에서 특히 왕의 노여움을 무릅쓰고 Alo} 왕의 ALS 지적한
상소문을 다룬 부분이 주목받고 있다. ( ) Sale} 조선』은 눈치를
살피며 윗사람의 잘못을 모르는 체 넘기곤 하는 현대인들을 깨우는 죽비인
것이다 ( @ )
O@ Ox) Ox) @)', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 92, '민욱이 주말에 친구 HHS 초대해도 되느냐고 물었을 때, 미연은 말없이
한참 SS 들였다. 그녀는 그날 민욱과 함께 아파트의 발코니 벽을 페인트
칠할 계획이었다. (중략) 그들은 육 개월 전에 EAS) 아파트를 사서 이사
했다. 지은 지 이십 년도 SS 아파트였지만, 누구의 도움도 받지 않고
그들 스스로 이룬 일이었다. YAS 직접 발품을 팔아 수도부터 새시까지
새로 손을 보았다. 하지만 집수리는 대강 되었다고 해도, 미연이 생각해 =
대로 인테리어가 완성되려면 아직 부족했다.
“손님 초대는 좀 이르지 않아? 집 단장도 덜 SMEG”
“성재가 한국에 왔대.”
민욱이 무거운 목소리로 말했다. (중략)
민욱과 성재는 고등학교 동창이고, 그들을 통해 만난 미연과 연주도 십여
년이 넘는 인연이었다. 꽤나 가까운 사이였지만 성재가 사업 실패로 한국을
떠나면서 연락이 끊겼다. 미연은 자신이 연주의 이름을 오랫동안 잊고
있었다는 사실을 깨달았다. 더 이상 뭐라고 할 말이 없었다. (중략)
ERY 오전에 미연은 두 딸아이를 데리고 마트에 가서 고기와 채소를
Ath 누군가를 초대해 음식을 대접하는 것이 정말로 오랜만이었다.
42. 밑줄 A 부분에 나타난 ''미연''의 심정으로 가장 알맞은 것을 고르십시오.
< 후련하다 @ 불만스럽다
08 허전하다 © 자랑스럽다', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 93, '민욱이 주말에 친구 HHS 초대해도 되느냐고 물었을 때, 미연은 말없이
한참 SS 들였다. 그녀는 그날 민욱과 함께 아파트의 발코니 벽을 페인트
칠할 계획이었다. (중략) 그들은 육 개월 전에 EAS) 아파트를 사서 이사
했다. 지은 지 이십 년도 SS 아파트였지만, 누구의 도움도 받지 않고
그들 스스로 이룬 일이었다. YAS 직접 발품을 팔아 수도부터 새시까지
새로 손을 보았다. 하지만 집수리는 대강 되었다고 해도, 미연이 생각해 =
대로 인테리어가 완성되려면 아직 부족했다.
“손님 초대는 좀 이르지 않아? 집 단장도 덜 SMEG”
“성재가 한국에 왔대.”
민욱이 무거운 목소리로 말했다. (중략)
민욱과 성재는 고등학교 동창이고, 그들을 통해 만난 미연과 연주도 십여
년이 넘는 인연이었다. 꽤나 가까운 사이였지만 성재가 사업 실패로 한국을
떠나면서 연락이 끊겼다. 미연은 자신이 연주의 이름을 오랫동안 잊고
있었다는 사실을 깨달았다. 더 이상 뭐라고 할 말이 없었다. (중략)
ERY 오전에 미연은 두 딸아이를 데리고 마트에 가서 고기와 채소를
Ath 누군가를 초대해 음식을 대접하는 것이 정말로 오랜만이었다.
43. 윗글의 내용으로 알 수 있는 것을 고르십시오.
0) 미연은 민욱과 성재를 통해 ASS 알게 되었다.
<) USS 주변 EES 받아 EAS] 새 아파트를 Art.
® NAS 육 개월 전에 산 아파트로 이사 갈 계획이다.
® USS 인테리어를 완성한 후에 마트에 AS 보러 갔다.', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 94, '※ ([44~4', NULL, NULL, NULL, '["CSS 읽고 SS", "답하십시오. (각 2점) ''수로왕 AVL Qo] 알에서 탄생하는 여느 건국 신회와 유사하다. 고대에 아직 나라가 없던 낙동강 하류에 황금알 여섯 개가 하늘에서 내려왔다. 그중 맨 먼저 알을 깨고 나온 아이를 ''수로''라 하였고 하늘의 Eo] 따라 수로는 지상의 첫 번째 왕이 되었다. ( ) 다섯 아이 역시 각각 왕이 되었다. FEY ABH 이렇게 한꺼번에 여섯 개 알이 나타나 거기서 태어난 이가 모두 왕이 된다는 점에서 다른 건국 신화와 큰 차이가 있다. 당시 세워진 여섯 나라는 강력한 왕권 국가가 아니었다. 황금알은 하늘로부터 부여받은 절대적 권위를 상징하는데 수로가 알에서 최초로 탄생했다는 부분은 수로왕이 중심이 되어 여섯 나라를 하나의 강력한 국가 ''가야 로 통합하려 했다는 것을 말해 준다. 44. ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.", "알을 가지고 내려온 ® 기존의 YS 물리치고", "수로에 이어 알에서 태어난 @ 탄생을 축하하며 BA) 기뻐하던"]'::jsonb, 2, '알을 가지고 내려온 ® 기존의 YS 물리치고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 95, '※ ([44~4', NULL, NULL, NULL, '["CSS 읽고 SS", "답하십시오. (각 2점) ''수로왕 AVL Qo] 알에서 탄생하는 여느 건국 신회와 유사하다. 고대에 아직 나라가 없던 낙동강 하류에 황금알 여섯 개가 하늘에서 내려왔다. 그중 맨 먼저 알을 깨고 나온 아이를 ''수로''라 하였고 하늘의 Eo] 따라 수로는 지상의 첫 번째 왕이 되었다. ( ) 다섯 아이 역시 각각 왕이 되었다. FEY ABH 이렇게 한꺼번에 여섯 개 알이 나타나 거기서 태어난 이가 모두 왕이 된다는 점에서 다른 건국 신화와 큰 차이가 있다. 당시 세워진 여섯 나라는 강력한 왕권 국가가 아니었다. 황금알은 하늘로부터 부여받은 절대적 권위를 상징하는데 수로가 알에서 최초로 탄생했다는 부분은 수로왕이 중심이 되어 여섯 나라를 하나의 강력한 국가 ''가야 로 통합하려 했다는 것을 말해 준다. 45. 윗글의 주제로 가장 알맞은 것을 고르십시오.", "이 신화는 전형적인 건국 신화의 SYS 지니고 있다.", "이 신화는 낙동강 일대의 유용한 지리적 정보를 담고 있다. @ 이 신화는 고대의 문학 작품으로서 훌륭한 가치를 지니고 있다. @ 이 신화는 강력한 왕권 국가를 이루려고 한 통함 의식을 반영한다."]'::jsonb, 2, '이 신화는 낙동강 일대의 유용한 지리적 정보를 담고 있다. @ 이 신화는 고대의 문학 작품으로서 훌륭한 가치를 지니고 있다. @ 이 신화는 강력한 왕권 국가를 이루려고 한 통함 의식을 반영한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 96, '※ ([46~4', NULL, NULL, NULL, '["다음을 읽고 물음에 답하십시오. (각 2점) 주가 조작이나 공금 횡령 등의 경제 범죄는 사람에게 직접적인 상해를 가하는 흉악 범죄보다 범죄 정도가 낮다고 생각하기 쉽다. 그러나 경제 범죄의 수법이 날이 갈수록 다양해지고 지능화되어 사회에 미치는 충격과 피해가 막심하다. 최근 증권사 직원의 주가 조작으로 고객들이 천억 넘게 손해 본 사건만 해도 그렇다. 이러한 경제 범죄는 개인 손해를 넘어 국가 경제와도 직결될 수 있다. 따라서 이를 가벼이 여겨서는 안 되며 관대하게 처벌해서도 안 된다. 건전한 경제 AAS 확립하기 위해 경제 사범을 엄벌할 필요가 있다. ''한탕 크게 해 먹고 몸으로 때우면 된다''는 한탕주의가 만연 하지 않도록 처벌 수준을 더 높여야 한다. 지금까지 미진했던 부당 이익 환수도 앞으로 잘 이루어져 경제 범죄가 재발되지 않도록 해야 할 것이다. 46. 윗글에 나타난 필자의 태도로 기장 알맞은 것을 고르십시오.", "경제 범죄가 사회에 미치는 영향을 부정하고 있다.", "경제 사범에 대한 AVS 강화하도록 촉구하고 있다.", "경제 APIS] 처벌로 생길 결과에 대해 우려하고 있다. 2 경제 범죄의 다양한 FAS 객관적으로 분석하고 있다."]'::jsonb, 2, '경제 범죄가 사회에 미치는 영향을 부정하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 97, '※ ([46~4', NULL, NULL, NULL, '["다음을 읽고 물음에 답하십시오. (각 2점) 주가 조작이나 공금 횡령 등의 경제 범죄는 사람에게 직접적인 상해를 가하는 흉악 범죄보다 범죄 정도가 낮다고 생각하기 쉽다. 그러나 경제 범죄의 수법이 날이 갈수록 다양해지고 지능화되어 사회에 미치는 충격과 피해가 막심하다. 최근 증권사 직원의 주가 조작으로 고객들이 천억 넘게 손해 본 사건만 해도 그렇다. 이러한 경제 범죄는 개인 손해를 넘어 국가 경제와도 직결될 수 있다. 따라서 이를 가벼이 여겨서는 안 되며 관대하게 처벌해서도 안 된다. 건전한 경제 AAS 확립하기 위해 경제 사범을 엄벌할 필요가 있다. ''한탕 크게 해 먹고 몸으로 때우면 된다''는 한탕주의가 만연 하지 않도록 처벌 수준을 더 높여야 한다. 지금까지 미진했던 부당 이익 환수도 앞으로 잘 이루어져 경제 범죄가 재발되지 않도록 해야 할 것이다. 47. 윗글의 내용과 같은 것을 고르십시오.", "경제 VAS 생긴 부당 이익을 문제없이 잘 환수해 왔다.", "공금을 불법으로 SAL WAL 경제 범죄에 포함된다.", "Alo] 저지른 주가 조작 범죄는 국가 경제와 큰 관련이 없다. 2 경제 범죄 수법이 교묘해졌지만 사회에 미치는 SAS 크지 않다."]'::jsonb, 2, '경제 VAS 생긴 부당 이익을 문제없이 잘 환수해 왔다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 98, '예술인은 독창적인 문화를 창조하고 고유한 문화를 보존하는 동시에 예술
활동을 업으로 삼아 FS 내서 생활하는 사람이다. 그런데 많은 예술인이
기본 생활이 불가능한 적은 수입 탓에 예술 활동을 포기한다. 그 결과 예술인이
감소하며 고령화되는 현상이 나타나고 있다. 2011년에는 생활고로 한 작가가
사망하는 사건까지 일어났다. 이 사건이 계기가 되어 2012년부터 예술인의
권리 보호를 위해 ''예술인 복지법''이 시행되었다. 그러나 이는 예술 현장의
실상에 맞지 않아 많은 예술인이 여전히 ( ). 이런 상황에서
올해 예술 BES 증명하지 못해 지원을 못 받았던 예술인을 위해 예술인
복지법이 개정되었다. 개정안은 이런 예술인도 일반 직업인과 같이 권리를
보호받을 수 있는 대상임을 명확히 하고 있다. 또 예술인이 불리한 처우를
받지 않도록 세부 조치를 마련하는 등 예술인의 고용 안정을 위한 여러
내용을 담고 있다. 앞으로는 이를 바탕으로 유능한 예술인이 활동을 포기하지
않도록 해야 할 것이다.
48. 윗글을 쓴 목적으로 가장 알맞은 것을 고르십시오.', NULL, NULL, NULL, '["예술인의 자질에 대해 분석하려고", "예술 발전의 어려움을 토로하려고", "예술 작품의 창작 BSS 설명하려고", "예술인 생활 보장의 필요성을 강조하려고"]'::jsonb, 2, '예술인 생활 보장의 필요성을 강조하려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 99, '예술인은 독창적인 문화를 창조하고 고유한 문화를 보존하는 동시에 예술
활동을 업으로 삼아 FS 내서 생활하는 사람이다. 그런데 많은 예술인이
기본 생활이 불가능한 적은 수입 탓에 예술 활동을 포기한다. 그 결과 예술인이
감소하며 고령화되는 현상이 나타나고 있다. 2011년에는 생활고로 한 작가가
사망하는 사건까지 일어났다. 이 사건이 계기가 되어 2012년부터 예술인의
권리 보호를 위해 ''예술인 복지법''이 시행되었다. 그러나 이는 예술 현장의
실상에 맞지 않아 많은 예술인이 여전히 ( ). 이런 상황에서
올해 예술 BES 증명하지 못해 지원을 못 받았던 예술인을 위해 예술인
복지법이 개정되었다. 개정안은 이런 예술인도 일반 직업인과 같이 권리를
보호받을 수 있는 대상임을 명확히 하고 있다. 또 예술인이 불리한 처우를
받지 않도록 세부 조치를 마련하는 등 예술인의 고용 안정을 위한 여러
내용을 담고 있다. 앞으로는 이를 바탕으로 유능한 예술인이 활동을 포기하지
않도록 해야 할 것이다.
49.( )에 들어갈 말로 가장 알맞은 것을 고르십시오.', NULL, NULL, NULL, '["WAS 증요시해야 한다", "생계의 어려움을 겨고 있다", "한 번에 SES 모을 수 있다 _ 0", "창작에 관한 기밀을 지켜야 한다"]'::jsonb, 2, '생계의 어려움을 겨고 있다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 100, '예술인은 독창적인 문화를 창조하고 고유한 문화를 보존하는 동시에 예술
활동을 업으로 삼아 FS 내서 생활하는 사람이다. 그런데 많은 예술인이
기본 생활이 불가능한 적은 수입 탓에 예술 활동을 포기한다. 그 결과 예술인이
감소하며 고령화되는 현상이 나타나고 있다. 2011년에는 생활고로 한 작가가
사망하는 사건까지 일어났다. 이 사건이 계기가 되어 2012년부터 예술인의
권리 보호를 위해 ''예술인 복지법''이 시행되었다. 그러나 이는 예술 현장의
실상에 맞지 않아 많은 예술인이 여전히 ( ). 이런 상황에서
올해 예술 BES 증명하지 못해 지원을 못 받았던 예술인을 위해 예술인
복지법이 개정되었다. 개정안은 이런 예술인도 일반 직업인과 같이 권리를
보호받을 수 있는 대상임을 명확히 하고 있다. 또 예술인이 불리한 처우를
받지 않도록 세부 조치를 마련하는 등 예술인의 고용 안정을 위한 여러
내용을 담고 있다. 앞으로는 이를 바탕으로 유능한 예술인이 활동을 포기하지
않도록 해야 할 것이다.
50. 윗글의 내용과 같은 것을 고르십시오.
© 예술인 BAYS 한 번 신설된 후 개정된 적이 없다.
0 전국에서 예술 분야에 종사하는 사람들 수가 늘고 있다.
@ 올해부터 예술인은 WES 반드시 증명해야 AWS 받을 수 있다.
9) 2012년의 예술인 복지법은 WH] 실상을 반영하는 데 한계가 있었다.', NULL, NULL, NULL, '["①", "②", "③", "④"]'::jsonb, 2, '④', NULL);

COMMIT;
