-- Generated by scripts/generate_topik_64_sql.mjs
BEGIN;

INSERT INTO mock_test_bank (
  title, exam_type, test_number, description, total_questions, duration, listening_questions, reading_questions
)
SELECT
  'TOPIK II 64-р шалгалт',
  'TOPIK_II',
  64,
  '64-р албан ёсны TOPIK II шалгалт',
  100,
  130,
  50,
  50
WHERE NOT EXISTS (
  SELECT 1 FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64
);

UPDATE mock_test_bank
SET
  title = 'TOPIK II 64-р шалгалт',
  description = '64-р албан ёсны TOPIK II шалгалт',
  total_questions = 100,
  duration = 130,
  listening_questions = 50,
  reading_questions = 50,
  updated_at = NOW()
WHERE id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1);

DELETE FROM mock_test_questions WHERE mock_test_id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1);

INSERT INTO mock_test_questions (
  mock_test_id,
  section,
  question_number,
  question_text,
  question_image_url,
  audio_url,
  option_image_urls,
  options,
  question_score,
  correct_answer_text,
  explanation
) VALUES
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 1, '다음을 듣고 알맞은 그림을 고르십시오.

여자: 고객님, 어떤 문제가 있으세요?
남자: 노트북 화면이 안 나와서요.
여자: 네, 언제 구입하셨지요?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q1_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q1_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q1_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q1_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 2, '다음을 듣고 알맞은 그림을 고르십시오.

남자: 공을 잘 들고 앞쪽을 봐.
여자: 이렇게? 그다음에는 어떻게 해?
남자: 천천히 걸어가면서 공을 굴려 봐.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q2_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q2_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q2_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q2_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 3, '다음을 듣고 알맞은 그림을 고르십시오.

남자: 2015년 이후 영화관을 찾는 관객 수가 계속해서 감소하고 있습니다.
관객 수가 줄고 있는 이유로는 ''여가 활동이 다양해져서''가 가장
많았고, ''영화를 모바일로 보는 경우가 늘어서'', ''관람료가 올라서''가
그 뒤를 이었습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q3_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q3_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q3_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/listening/q3_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 4, '다음 대화를 잘 듣고 이어질 수 있는 말을 고르십시오.

여자: 저는 내일 모임에 못 갈 것 같아요.
남자: 왜요? 무슨 일이 있어요?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["모임 장소로 오세요.","내일은 갈 수 있어요.","고향에서 친구가 와서요.","못 만날까 봐 걱정했어요."]'::jsonb, 2, '고향에서 친구가 와서요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 5, '다음 대화를 잘 듣고 이어질 수 있는 말을 고르십시오.

남자: 약 좀 사 가지고 올게. 머리가 계속 아프네.
여자: 지금 이 시간에도 문을 연 약국이 있을까?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["아니, 머리는 괜찮아졌어.","응, 내가 약을 사다 줄게.","아니, 문을 안 열었더라고.","응, 늦게까지 하는 약국이 있어."]'::jsonb, 2, '응, 늦게까지 하는 약국이 있어.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 6, '다음 대화를 잘 듣고 이어질 수 있는 말을 고르십시오.

여자 : 토요일에 3층 연습실 사용할 수 있어?
남자: 아직 관리실에 얘기를 못 해서 잘 모르겠어.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["그럼 토요일에 보자.","그럼 내가 가서 물어볼게.","연습실은 3층으로 가면 돼.","주말에 연습이 없는 줄 알았어."]'::jsonb, 2, '그럼 내가 가서 물어볼게.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 7, '다음 대화를 잘 듣고 이어질 수 있는 말을 고르십시오.

남자: 공사 소음 때문에 일에 집중이 안 되네요.
여자: 맞아요. 먼지도 심하고요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["공사를 하면 깨끗해지겠어요.","공사는 내일부터 시작한대요.","공사를 해서 시끄러울 거예요.","공사가 빨리 끝났으면 좋겠어요."]'::jsonb, 2, '공사가 빨리 끝났으면 좋겠어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 8, '다음 대화를 잘 듣고 이어질 수 있는 말을 고르십시오.

여자: 첫 방송에 대한 시청자 의견은 어때요?
남자: 재미있다는 의견이 많았습니다. 그런데 음악이 장면에 안 어울린다는
의견도 있었습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["첫 방송이 정말 기대되네요.","시청자 의견을 못 들었어요.","장면들이 아름다웠다고 해요.","음악에 더 신경을 써야겠네요."]'::jsonb, 2, '음악에 더 신경을 써야겠네요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 9, '다음 대화를 잘 듣고 여자가 이어서 할 행동으로 알맞은 것을 고르십시오.

여자: 선물도 샀고 꽃도 준비했고, 케이크는 어떻게 됐지?
남자: 케이크는 민수가 사 온다고 했어.
여자: 그럼 난 생일 카드 좀 쓰고 있어야겠다.
남자: 그래. 난 민수 어디쯤 왔는지 전화해 볼게.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["꽃을 가져온다.","선물을 고른다.","생일 카드를 쓴다.","민수한테 전화한다."]'::jsonb, 2, '생일 카드를 쓴다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 10, '다음 대화를 잘 듣고 여자가 이어서 할 행동으로 알맞은 것을 고르십시오.

여자: 저, 오늘 두 시에 진료 예약했는데요. 김수미라고 합니다.
남자: 네, 예약 확인되셨고요. 검사 전에 옷을 갈아입으셔야 해요.
여자: 그래요? 어디로 가면 되지요?
남자: 오른쪽으로 가시면 탈의실이 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["검사 예약을 한다.","옷을 갈아입으러 간다.","진료 시간을 확인한다.","탈의실 위치를 물어본다."]'::jsonb, 2, '옷을 갈아입으러 간다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 11, '다음 대화를 잘 듣고 여자가 이어서 할 행동으로 알맞은 것을 고르십시오.

남자: 토마토 심은 날짜까지 붙였으니까 이제 다 끝났어.
여자: 토마토 심는 게 생각보다 간단하다.
남자: 그렇지? 이제 화분을 베란다로 옮겨 놓을 테니까 네가 물을 좀 줘.
여자: 응, 알겠어.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["화분에 물을 준다.","화분에 날짜를 붙인다.","화분에 토마토를 심는다.","화분을 베란다로 옮긴다."]'::jsonb, 2, '화분에 물을 준다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 12, '다음 대화를 잘 듣고 여자가 이어서 할 행동으로 알맞은 것을 고르십시오.

남자: 김수미 씨, 직원 연수 프로그램은 확정됐나요?
여자: 아직 특강해 주실 분을 못 구했는데요. 오늘 박민석 선생님께 연락
드려 보려고요.
남자: 그럼 좀 서둘러 주세요. 안 되면 다른 분을 찾아봐야 하니까요.
여자: 네, 바로 알아보겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["다른 강사를 찾아본다.","박 선생님에게 연락한다.","특강 자료를 정리한다.","연수 프로그램을 알아본다."]'::jsonb, 2, '박 선생님에게 연락한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 13, '다음을 듣고 내용과 일치하는 것을 고르십시오.

여자: 민수야, 너 작년에 심리학 개론 수업 들었지?
남자: 응. 진짜 좋았어. 너도 그 수업 들으려고?
여자: 수강 신청은 했는데 다른 학과 수업이라 걱정이 돼서.
남자: 그 수업, 내용도 재밌고 어렵지 않아서 괜찮을 거야.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["여자는 심리학과 학생이다.","여자는 수강 신청을 하지 못했다.","남자는 심리학 개론 수업에 만족했다.","남자는 여자와 심리학 개론 수업을 들었다."]'::jsonb, 2, '남자는 심리학 개론 수업에 만족했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 14, '다음을 듣고 내용과 일치하는 것을 고르십시오.

남자: 주민 여러분, 내일은 우리 아파트의 어울림 축제가 있는 날입니다.
놀이터 옆에 아이들을 위한 미니 수영장이 설치될 예정이고, 작년에
이어 올해도 야시장이 열립니다. 오후 세 시, 노래자랑 대회를 시작
으로 다양한 행사가 준비되어 있으니 많은 참여 바랍니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["노래자랑 대회는 오후에 한다.","어울림 축제는 저녁에 시작한다.","올해 처음으로 야시장이 열린다.","수영장은 놀이터 안에 설치됐다."]'::jsonb, 2, '노래자랑 대회는 오후에 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 15, '다음을 듣고 내용과 일치하는 것을 고르십시오.

여자: 오늘 오전 8시경 인주역에서 지하철 3호선 열차에 정전 사고가 발생
했습니다. 사고 열차가 10분간 멈추면서 출근길 시민들이 큰 불편을
겪었습니다. 이 열차는 지난주에도 정전 사고가 한 차례 있었는데요.
현재 운행을 중단하고 정밀 검사를 하고 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 열차는 현재 운행 중이다.","이 열차는 인주역에 들어오지 못했다.","이 열차는 지난주에도 정전 사고가 있었다.","이 열차의 정전 사고는 늦은 밤에 발생했다."]'::jsonb, 2, '이 열차는 지난주에도 정전 사고가 있었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 16, '다음을 듣고 내용과 일치하는 것을 고르십시오.

여자: 오랫동안 나무를 치료해 오셨는데요. 나무는 어떻게 치료를 하나요?
남자: 병든 나무의 증상을 살피고, 땅의 상태나 주변 나무들도 조사해요.
나무도 다른 식물들처럼 주변 환경에 민감하기 때문이죠. 병이 생긴
원인에 따라 주변 환경을 개선하거나 직접 나무에 약을 처방합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["병든 나무에는 직접 약을 처방하지 않는다.","남자는 나무 치료를 시작한 지 얼마 안 됐다.","남자는 나무 치료를 위해 땅의 상태를 조사한다.","나무는 다른 식물에 비해 환경의 영향을 덜 받는다."]'::jsonb, 2, '남자는 나무 치료를 위해 땅의 상태를 조사한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 17, '다음을 듣고 남자의 중심 생각을 고르십시오.

남자: 아무래도 요가 학원에 다녀야겠어. 혼자서 운동을 하니까 동작이
맞는지 모르겠고 효과도 없는 것 같아.
여자: 요즘은 인터넷 요가 영상도 많이 있던데, 그걸 보는 건 어때?
남자: 영상만으로는 안 될 것 같아. 내 동작이 틀려도 알 수 없잖아.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["운동을 제대로 배워서 하고 싶다.","인터넷의 운동 정보는 도움이 된다.","건강을 위해 꾸준히 운동을 해야 한다.","따라 하기 쉬운 요가 영상을 선택해야 한다."]'::jsonb, 2, '운동을 제대로 배워서 하고 싶다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 18, '다음을 듣고 남자의 중심 생각을 고르십시오.

남자: 수미야, 왜 아무 말도 안 해? 너도 어디 가고 싶은지 말을 해.
여자: 난 어디든 상관없어. 그냥 여러 사람이 원하는 곳으로 해.
남자: 모두가 만족할 수 있는 결정을 하려면 네 생각도 정확하게 말해
줘야 돼.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["갈등이 생기면 빨리 해결해야 한다.","자신의 생각을 분명하게 말하면 좋겠다.","상대방이 원하는 것을 먼저 하는 게 좋다.","상대방의 입장을 이해하려면 대화가 필요하다."]'::jsonb, 2, '자신의 생각을 분명하게 말하면 좋겠다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 19, '다음을 듣고 남자의 중심 생각을 고르십시오.

여자: 이거 조금 전에 받은 명함인데요. 디자인이 참 특이하죠?
남자: 그렇네요. 그림이 있는 것도 인상적이고요.
여자: 그런데 명함이라고 하기에는 정보가 좀 부족한 것 같지 않아요?
남자: 디자인 덕분에 이렇게 한 번 더 보게 되니까 전 좋은 것 같아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 명함은 디자인이 인상적이어서 좋다.","이 명함은 디자인에 더 신경을 써야 한다.","이 명함은 정보를 충분히 넣을 필요가 있다.","이 명함은 명함을 준 사람에 대해 알기 쉽다."]'::jsonb, 2, '이 명함은 디자인이 인상적이어서 좋다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 20, '다음을 듣고 남자의 중심 생각을 고르십시오.

여자: 기업 행사를 기획할 때는 어떤 부분에 신경을 써야 하나요?
남자: 행사의 목적이 무엇인지 잘 파악해야 합니다. 신제품 홍보를 위한
행사는 제품의 이미지에 맞게 분위기를 연출해야 하고요. 송년회같이
직원들을 위한 행사는 친목을 위한 다양한 프로그램이 필요합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["기업 행사는 분위기 연출이 가장 어렵다.","기업 행사는 행사의 목적을 고려해야 한다.","기업 행사는 프로그램이 다양할수록 좋다.","기업 행사는 직원들이 만족할 수 있어야 한다."]'::jsonb, 2, '기업 행사는 행사의 목적을 고려해야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 21, '남자의 중심 생각으로 알맞은 것을 고르십시오.

남자: 최근 조사 자료를 보면 여행객들이 호텔을 선택할 때 가장 많이 참고
하는 게 이용 후기라고 해요.
여자: 맞아요. 우리도 후기 관리에 더 신경을 써야 할 것 같아요. 우리
호텔은 고객 만족도는 높은 데 비해 이용 후기는 적은 편이잖아요.
남자: 그래서 고객들에게 후기 작성에 대해 적극적으로 알려야 할 것
같아요. 후기를 많이 남길 수 있도록 하는 이벤트도 해 보고요.
여자: 좋네요. 그럼 어떤 이벤트가 좋을지 한번 생각해 봐요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["여행객들의 성향을 조사해야 한다.","고객 만족도를 높이는 것이 우선이다.","이용 후기를 늘릴 수 있도록 해야 한다.","후기 분석을 적극적으로 할 필요가 있다."]'::jsonb, 2, '이용 후기를 늘릴 수 있도록 해야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 22, '들은 내용으로 맞는 것을 고르십시오.

남자: 최근 조사 자료를 보면 여행객들이 호텔을 선택할 때 가장 많이 참고
하는 게 이용 후기라고 해요.
여자: 맞아요. 우리도 후기 관리에 더 신경을 써야 할 것 같아요. 우리
호텔은 고객 만족도는 높은 데 비해 이용 후기는 적은 편이잖아요.
남자: 그래서 고객들에게 후기 작성에 대해 적극적으로 알려야 할 것
같아요. 후기를 많이 남길 수 있도록 하는 이벤트도 해 보고요.
여자: 좋네요. 그럼 어떤 이벤트가 좋을지 한번 생각해 봐요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 호텔에서는 후기 작성 이벤트를 하고 있다.","남자는 호텔과 관련된 자료를 조사할 예정이다.","이 호텔을 이용한 고객들은 후기를 많이 남겼다.","여자가 일하는 호텔은 고객 만족도가 높은 편이다."]'::jsonb, 2, '여자가 일하는 호텔은 고객 만족도가 높은 편이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 23, '여자가 무엇을 하고 있는지 고르십시오.

여자: 여보세요. 제가 운전면허증을 잃어버려서 다시 발급을 받고 싶은데요.
어떻게 하면 되나요?
남자: 운전면허 시험장으로 오시면 당일에 받을 수 있습니다. 오실 때
신분증을 꼭 챙겨 오셔야 하고요.
여자: 인터넷으로는 신청이 안 되나요? 면허 시험장이 너무 멀어서요.
남자: 인터넷으로도 가능합니다. 신청하실 때 가까운 경찰서를 지정해서
면허증을 받으시면 돼요. 그런데 시간은 두 주 정도 걸립니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["면허증 재발급 방법을 문의하고 있다.","면허증 재발급 기간을 확인하고 있다.","면허 시험장의 위치를 알아보고 있다.","면허증 발급을 위한 서류를 요청하고 있다."]'::jsonb, 2, '면허증 재발급 방법을 문의하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 24, '들은 내용으로 맞는 것을 고르십시오.

여자: 여보세요. 제가 운전면허증을 잃어버려서 다시 발급을 받고 싶은데요.
어떻게 하면 되나요?
남자: 운전면허 시험장으로 오시면 당일에 받을 수 있습니다. 오실 때
신분증을 꼭 챙겨 오셔야 하고요.
여자: 인터넷으로는 신청이 안 되나요? 면허 시험장이 너무 멀어서요.
남자: 인터넷으로도 가능합니다. 신청하실 때 가까운 경찰서를 지정해서
면허증을 받으시면 돼요. 그런데 시간은 두 주 정도 걸립니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["경찰서에서도 면허증을 받을 수 있다.","여자는 인터넷으로 신청서를 제출했다.","여자는 면허 시험장에서 가까운 곳에 있다.","인터넷을 이용하면 당일에 면허증 발급이 가능하다."]'::jsonb, 2, '경찰서에서도 면허증을 받을 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 25, '남자의 중심 생각으로 알맞은 것을 고르십시오.

여자: 오늘은 소방복을 재활용한 가방을 만들어 화제가 된 대학생들을
만나러 왔습니다. 어떻게 이런 일을 하게 되셨습니까?
남자 : 소방관들이 시민을 위해 얼마나 힘든 환경에서 일하고 있는지를
알리고 싶었어요. 그래서 작년부터 저희의 전공을 살려 버려진 소방
복을 재활용해 가방을 만들게 되었습니다. 가방의 소재가 특이하다
보니 자연스럽게 사람들의 관심을 모을 수 있었고 판매까지 하게
되었습니다. 현재는 가방을 판매한 수익금을 소방관의 활동을 알리는
데에 사용하고 있습니다. 저희의 작은 노력이 소방관의 어려움을
한 번 더 떠올리는 계기가 되었으면 좋겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["소방관의 근무 환경을 개선해야 한다.","사람들이 소방관에 대해 관심을 가지면 좋겠다.","사람들은 소방관의 희생정신을 본받아야 한다.","소방관의 안전을 보장하기 위한 대책이 필요하다."]'::jsonb, 2, '사람들이 소방관에 대해 관심을 가지면 좋겠다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 26, '들은 내용으로 맞는 것을 고르십시오.

여자: 오늘은 소방복을 재활용한 가방을 만들어 화제가 된 대학생들을
만나러 왔습니다. 어떻게 이런 일을 하게 되셨습니까?
남자 : 소방관들이 시민을 위해 얼마나 힘든 환경에서 일하고 있는지를
알리고 싶었어요. 그래서 작년부터 저희의 전공을 살려 버려진 소방
복을 재활용해 가방을 만들게 되었습니다. 가방의 소재가 특이하다
보니 자연스럽게 사람들의 관심을 모을 수 있었고 판매까지 하게
되었습니다. 현재는 가방을 판매한 수익금을 소방관의 활동을 알리는
데에 사용하고 있습니다. 저희의 작은 노력이 소방관의 어려움을
한 번 더 떠올리는 계기가 되었으면 좋겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["남자는 소방관으로 일하고 있다.","이 가방은 사람들에게 판매되지 않는다.","이 가방은 소방복을 재활용해 만든 것이다.","남자가 만든 가방은 아직 알려지지 않았다."]'::jsonb, 2, '이 가방은 소방복을 재활용해 만든 것이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 27, '남자가 여자에게 말하는 의도를 고르십시오.

남자: 이번에 김 과장님도 육아 휴직을 신청했대요. 요즘 우리 회사 남자
직원들 중에 육아 휴직을 신청하는 사람들이 점점 많아지고 있어요.
여자: 그러게요. 제도가 바뀌면서 휴직 기간 동안 월급도 주고 경력 인정도
되니까 예전보다 신청에 대한 부담이 적어진 거겠죠.
남자: 제 생각엔 남성 육아를 긍정적으로 보는 시각이 많아진 게 큰 이유인
것 같아요. 정부나 회사에서 남성 육아를 권장하기도 하고요.
여자: 하긴 요즘 분위기가 많이 달라진 것 같긴 해요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["남성 육아의 필요성을 일깨우기 위해","남성 육아를 위한 제도를 설명하기 위해","남성 육아의 문제점에 대해 지적하기 위해","남성 육아에 대한 인식 변화를 말하기 위해"]'::jsonb, 2, '남성 육아에 대한 인식 변화를 말하기 위해', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 28, '들은 내용으로 맞는 것을 고르십시오.

남자: 이번에 김 과장님도 육아 휴직을 신청했대요. 요즘 우리 회사 남자
직원들 중에 육아 휴직을 신청하는 사람들이 점점 많아지고 있어요.
여자: 그러게요. 제도가 바뀌면서 휴직 기간 동안 월급도 주고 경력 인정도
되니까 예전보다 신청에 대한 부담이 적어진 거겠죠.
남자: 제 생각엔 남성 육아를 긍정적으로 보는 시각이 많아진 게 큰 이유인
것 같아요. 정부나 회사에서 남성 육아를 권장하기도 하고요.
여자: 하긴 요즘 분위기가 많이 달라진 것 같긴 해요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["남자의 회사에는 육아 휴직 신청자가 없다.","육아 휴직을 해도 경력을 인정받을 수 있다.","육아 휴직 기간에는 월급이 지급되지 않는다.","정부에서는 육아 휴직 제도의 시행을 준비하고 있다."]'::jsonb, 2, '육아 휴직을 해도 경력을 인정받을 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 29, '여자는 누구인지 맞는 것을 고르십시오.

남자: 사장님께서 만든 전자책 구독 서비스의 인기 비결이 뭐라고 생각
하세요?
여자: 독서를 위한 다양한 서비스를 제공한다는 점이겠죠. 우선 매달 이용료를
내면 수만 권의 책을 얼마든지 읽을 수 있고요. 어려운 책은 전문가의
해설을 들으면서 읽거나 요약본으로 볼 수도 있어요. 모든 책에 음성
지원이 가능해서 이동 중에도 내용을 들을 수 있습니다.
남자: 최근에는 책의 내용을 만화나 동영상 등으로 소개하는 기능도 추가
하셨다고요.
여자: 네. 더 즐겁게 독서할 수 있는 여러 방법을 계속 고민 중이에요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["전자책을 조사하는 사람","전자책을 골라 주는 사람","전자책 구독 서비스에 가입한 사람","전자책 구독 서비스를 개발한 사람"]'::jsonb, 2, '전자책 구독 서비스를 개발한 사람', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 30, '들은 내용으로 맞는 것을 고르십시오.

남자: 사장님께서 만든 전자책 구독 서비스의 인기 비결이 뭐라고 생각
하세요?
여자: 독서를 위한 다양한 서비스를 제공한다는 점이겠죠. 우선 매달 이용료를
내면 수만 권의 책을 얼마든지 읽을 수 있고요. 어려운 책은 전문가의
해설을 들으면서 읽거나 요약본으로 볼 수도 있어요. 모든 책에 음성
지원이 가능해서 이동 중에도 내용을 들을 수 있습니다.
남자: 최근에는 책의 내용을 만화나 동영상 등으로 소개하는 기능도 추가
하셨다고요.
여자: 네. 더 즐겁게 독서할 수 있는 여러 방법을 계속 고민 중이에요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 서비스는 무료로 이용이 가능하다.","이 서비스는 아직 이용자가 많지 않다.","이 서비스는 책에 대한 해설도 제공한다.","이 서비스는 동영상 기능을 추가할 예정이다."]'::jsonb, 2, '이 서비스는 책에 대한 해설도 제공한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 31, '남자의 생각으로 알맞은 것을 고르십시오.

여자: 재학생을 대상으로 한 창업 지원 사업은 사전 교육을 강화하는 방향
으로 가야 한다고 생각합니다.
남자: 사전 교육과 함께 창업 지원금을 늘려서 더 많은 학생들이 실제로
창업을 해 보게 하는 건 어떨까요?
여자: 지금 상황에서 창업을 해 보게 하는 건 좀 이르지 않을까요? 교육이
부족하면 창업 과정에서 어려움이 많을 겁니다.
남자: 직접 부딪혀 봐야 배울 수 있는 것도 있잖아요. 그게 진정한 의미의
창업 교육인 것 같아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["창업 사전 교육을 강화해야 한다.","학생들이 창업을 직접 해 보게 해야 한다.","학생들에게 창업 지원 사업을 홍보해야 한다.","창업 지원 사업의 시행 기간을 연장해야 한다."]'::jsonb, 2, '학생들이 창업을 직접 해 보게 해야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 32, '남자의 태도로 알맞은 것을 고르십시오.

여자: 재학생을 대상으로 한 창업 지원 사업은 사전 교육을 강화하는 방향
으로 가야 한다고 생각합니다.
남자: 사전 교육과 함께 창업 지원금을 늘려서 더 많은 학생들이 실제로
창업을 해 보게 하는 건 어떨까요?
여자: 지금 상황에서 창업을 해 보게 하는 건 좀 이르지 않을까요? 교육이
부족하면 창업 과정에서 어려움이 많을 겁니다.
남자: 직접 부딪혀 봐야 배울 수 있는 것도 있잖아요. 그게 진정한 의미의
창업 교육인 것 같아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["사업의 효과를 회의적으로 바라보고 있다.","사례를 들어 상대방의 주장을 반박하고 있다.","상황을 분석하면서 발생할 문제를 염려하고 있다.","상대의 의견을 일부 인정하며 다른 주장을 하고 있다."]'::jsonb, 2, '상대의 의견을 일부 인정하며 다른 주장을 하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 33, '무엇에 대한 내용인지 맞는 것을 고르십시오.

여자: 비행기가 착륙할 때 바퀴와 지면의 마찰로 인해 엄청난 열이 발생
합니다. 그 온도가 워낙 높아 공기를 주입한 타이어에서는 공기에
포함된 산소가 자칫 폭발을 유도할 위험이 있습니다. 그래서 자동차
타이어와 달리 비행기 타이어에는 산소가 혼합되지 않은 질소만을
주입합니다. 타이어 표면의 무늬도 마찰열과 관계가 있는데요. 자동차
타이어에는 복잡한 무늬를 넣어 미끄러짐을 방지하지만 비행기
타이어에는 단순한 세로 줄무늬를 사용하여 지면과의 마찰을 줄이고
착륙 시 발생하는 열을 최소화해 줍니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["질소의 활용 방법","질소의 생성 원리","비행기 타이어의 특징","비행기 타이어의 종류"]'::jsonb, 2, '비행기 타이어의 특징', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 34, '들은 내용으로 맞는 것을 고르십시오.

여자: 비행기가 착륙할 때 바퀴와 지면의 마찰로 인해 엄청난 열이 발생
합니다. 그 온도가 워낙 높아 공기를 주입한 타이어에서는 공기에
포함된 산소가 자칫 폭발을 유도할 위험이 있습니다. 그래서 자동차
타이어와 달리 비행기 타이어에는 산소가 혼합되지 않은 질소만을
주입합니다. 타이어 표면의 무늬도 마찰열과 관계가 있는데요. 자동차
타이어에는 복잡한 무늬를 넣어 미끄러짐을 방지하지만 비행기
타이어에는 단순한 세로 줄무늬를 사용하여 지면과의 마찰을 줄이고
착륙 시 발생하는 열을 최소화해 줍니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["질소는 자동차 타이어에 주로 사용된다.","비행기 타이어에는 복잡한 무늬를 새긴다.","단순한 무늬의 타이어는 잘 미끄러지지 않는다.","질소만 주입한 타이어는 폭발 위험이 줄어든다."]'::jsonb, 2, '질소만 주입한 타이어는 폭발 위험이 줄어든다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 35, '남자는 무엇을 하고 있는지 고르십시오.

남자: 아역 배우로 영화 인생을 시작해서 78세의 나이로 눈을 감기까지,
김민수 선배님의 삶은 오직 영화만을 위한 것이었습니다. 선배님은
배우로서 백여 편의 영화에 출연하며 특유의 개성 넘치는 연기로
우리를 울고 웃게 했습니다. 53세에는 감독으로서 첫 작품을 발표하고,
이후 3편의 영화를 더 남겼습니다. 마지막으로 연출한 작품으로 국제
영화제에서 감독상을 수상하기도 했지요. 뿐만 아니라 영화 박물관의
대표로서 한국 영화의 역사를 기록하는 일에도 힘을 써 온, 누구보다
영화를 사랑하는 분이셨습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["선배의 업적을 소개하고 있다.","선배의 영화를 홍보하고 있다.","선배가 만든 작품을 설명하고 있다.","선배에 대한 지지를 부탁하고 있다."]'::jsonb, 2, '선배의 업적을 소개하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 36, '들은 내용으로 맞는 것을 고르십시오.

남자: 아역 배우로 영화 인생을 시작해서 78세의 나이로 눈을 감기까지,
김민수 선배님의 삶은 오직 영화만을 위한 것이었습니다. 선배님은
배우로서 백여 편의 영화에 출연하며 특유의 개성 넘치는 연기로
우리를 울고 웃게 했습니다. 53세에는 감독으로서 첫 작품을 발표하고,
이후 3편의 영화를 더 남겼습니다. 마지막으로 연출한 작품으로 국제
영화제에서 감독상을 수상하기도 했지요. 뿐만 아니라 영화 박물관의
대표로서 한국 영화의 역사를 기록하는 일에도 힘을 써 온, 누구보다
영화를 사랑하는 분이셨습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["김민수는 배우이자 감독으로 활약했다.","김민수는 늦은 나이에 배우로 데뷔했다.","김민수는 백여 편이 넘는 영화를 연출했다.","김민수는 국제 영화제에서 상을 받지 못했다."]'::jsonb, 2, '김민수는 배우이자 감독으로 활약했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 37, '여자의 중심 생각으로 알맞은 것을 고르십시오.

남자: 충치뿐 아니라 잇몸병으로 고생하는 젊은 분들이 상당히 많네요.
여자 : 네. 그 수가 전체 잇몸병 환자의 3분의 1을 차지할 정도니까요. 2, 30대
환자는 최근 5년 사이에 약 60%나 증가했습니다. 젊은 분들은 잇몸
병을 대수롭지 않게 여기는 경향이 있는데요. 손상된 잇몸은 원래대로
회복되지 않습니다. 게다가 잇몸병의 원인이 되는 세균이 온몸을
돌아다니며 다른 신체 기관에 악영향을 끼치기도 하고요. 심각한
경우에 이 세균이 심장병이나 치매를 유발할 수도 있어요. 건강할
때부터 잇몸을 잘 관리하는 것이 좋습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["잇몸병의 원인을 명확하게 밝혀야 한다.","젊을 때부터 잇몸 관리에 신경을 써야 한다.","치매 예방을 위해서 잇몸 관리가 중요하다.","잇몸병에 대한 잘못된 정보를 바로잡아야 한다."]'::jsonb, 2, '젊을 때부터 잇몸 관리에 신경을 써야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 38, '들은 내용과 일치하는 것을 고르십시오.

남자: 충치뿐 아니라 잇몸병으로 고생하는 젊은 분들이 상당히 많네요.
여자 : 네. 그 수가 전체 잇몸병 환자의 3분의 1을 차지할 정도니까요. 2, 30대
환자는 최근 5년 사이에 약 60%나 증가했습니다. 젊은 분들은 잇몸
병을 대수롭지 않게 여기는 경향이 있는데요. 손상된 잇몸은 원래대로
회복되지 않습니다. 게다가 잇몸병의 원인이 되는 세균이 온몸을
돌아다니며 다른 신체 기관에 악영향을 끼치기도 하고요. 심각한
경우에 이 세균이 심장병이나 치매를 유발할 수도 있어요. 건강할
때부터 잇몸을 잘 관리하는 것이 좋습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["잇몸은 손상되더라도 빠르게 회복된다.","잇몸병 환자의 절반 이상이 젊은 사람들이다.","젊은 층의 잇몸병 환자가 줄고 있는 추세이다.","잇몸병을 일으키는 세균은 다른 질환도 유발할 수 있다."]'::jsonb, 2, '잇몸병을 일으키는 세균은 다른 질환도 유발할 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 39, '이 담화 앞의 내용으로 알맞은 것을 고르십시오.

여자: 국외로 유출된 문화재가 이렇게 많은데, 어떤 방법으로 이런 문화재
들을 다시 본국으로 가져올 수 있을까요?
남자: 관련된 국제 협약이 1970년에 마련되었고, 1990년대 후반부터 문화재
환수에 대한 관심이 높아지면서 국가 간 논의와 공조가 활발해졌습
니다. 문화재 환수에는 정부 간 대여나 기증 등의 방식이 있는데요.
기증을 통한 영구적 환수가 바람직하겠지만 나라마다 문화재 보호에
관한 법이 서로 달라서 이것이 쉽지는 않습니다. 현재는 대여하는
방식으로 일시적 환수가 이루어지는 경우가 많습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["민간 주도로 문화재 환수가 이루어지고 있다.","해외에 있는 문화재를 대여해서 전시하고 있다.","환수하지 못하고 해외에 남아 있는 문화재가 많다.","문화재 환수를 위해 다른 나라와 협정을 체결했다."]'::jsonb, 2, '환수하지 못하고 해외에 남아 있는 문화재가 많다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 40, '들은 내용과 일치하는 것을 고르십시오.

여자: 국외로 유출된 문화재가 이렇게 많은데, 어떤 방법으로 이런 문화재
들을 다시 본국으로 가져올 수 있을까요?
남자: 관련된 국제 협약이 1970년에 마련되었고, 1990년대 후반부터 문화재
환수에 대한 관심이 높아지면서 국가 간 논의와 공조가 활발해졌습
니다. 문화재 환수에는 정부 간 대여나 기증 등의 방식이 있는데요.
기증을 통한 영구적 환수가 바람직하겠지만 나라마다 문화재 보호에
관한 법이 서로 달라서 이것이 쉽지는 않습니다. 현재는 대여하는
방식으로 일시적 환수가 이루어지는 경우가 많습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["각국의 법이 달라 문화재의 영구적 환수가 어렵다.","1970년대부터 문화재 환수가 활발해지기 시작했다.","문화재 환수는 주로 기증하는 방식으로 이루어진다.","문화재 환수와 관련된 국제 협약은 존재하지 않는다."]'::jsonb, 2, '각국의 법이 달라 문화재의 영구적 환수가 어렵다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 41, '이 강연의 중심 내용으로 맞는 것을 고르십시오.

여자: 과학자들은 오랜 논의를 거쳐 ''감칠맛''을 다섯 번째 미각으로 인정
했습니다. ''감칠맛''은 음식을 더 맛있게 느끼게 해 식욕을 당기게
합니다. 이제 과학자들은 여섯 번째 미각에 관심을 쏟고 있는데요.
여러 맛들이 언급되고 있지만 ''깊은맛''이 유력한 후보로 거론되고
있습니다. ''깊은맛''은 식재료를 오래 끓이거나 숙성, 발효시키는
과정에서 우러나는 맛인데요. 그 자체로 맛을 가지고 있지는 않지만
다른 맛들과 결합해 음식의 풍미를 높여 줍니다. 콩을 발효해 만든
된장이나 간장을 기본양념으로 하는 한식에는 ''깊은맛''을 맛볼 수
있는 음식이 많습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["감칠맛에 대한 연구가 새로이 시작되었다.","새로운 미각으로 깊은맛이 주목을 받고 있다.","한식의 조리 과정에서는 발효가 가장 중요하다.","음식의 풍미를 높이는 다양한 방법이 개발되었다."]'::jsonb, 2, '새로운 미각으로 깊은맛이 주목을 받고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 42, '들은 내용과 일치하는 것을 고르십시오.

여자: 과학자들은 오랜 논의를 거쳐 ''감칠맛''을 다섯 번째 미각으로 인정
했습니다. ''감칠맛''은 음식을 더 맛있게 느끼게 해 식욕을 당기게
합니다. 이제 과학자들은 여섯 번째 미각에 관심을 쏟고 있는데요.
여러 맛들이 언급되고 있지만 ''깊은맛''이 유력한 후보로 거론되고
있습니다. ''깊은맛''은 식재료를 오래 끓이거나 숙성, 발효시키는
과정에서 우러나는 맛인데요. 그 자체로 맛을 가지고 있지는 않지만
다른 맛들과 결합해 음식의 풍미를 높여 줍니다. 콩을 발효해 만든
된장이나 간장을 기본양념으로 하는 한식에는 ''깊은맛''을 맛볼 수
있는 음식이 많습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["감칠맛은 다른 맛과 결합해 풍미를 높인다.","감칠맛은 미각으로 인정을 받지 못하고 있다.","깊은맛은 식욕을 당기게 해 주는 특징이 있다.","깊은맛은 식재료를 오래 끓여서 낼 수 있는 맛이다."]'::jsonb, 2, '깊은맛은 식재료를 오래 끓여서 낼 수 있는 맛이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 43, '이 이야기의 중심 내용으로 맞는 것을 고르십시오.

남자: 새끼 상어가 꼬물꼬물 헤엄을 치는 이 작은 공간은 어미 황갈색수
염상어의 자궁 속이다. 새끼 황갈색수염상어는 인간과 마찬가지로
이곳에서 약 10개월을 보낸다. 그런데 영양분을 공급받아야 할 탯줄이
보이지 않는다. 어떻게 영양분을 섭취하는 걸까. 어미 상어는 수정이
되지 않은 수십 개의 무정란을 자궁 속에 가지고 있다. 탯줄이 없어
움직임이 자유로운 새끼 상어는 이 알들을 찾아다니며 먹는다. 어미
상어 배 속에서부터 헤엄치는 법과 먹이 찾는 법을 함께 익히고 있는
셈이다. 세상을 살아갈 만반의 준비를 모두 마친 후 마침내 새끼
상어는 자궁 밖으로 나온다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["황갈색수염상어가 해양 생태계를 변화시키고 있다.","황갈색수염상어의 서식 공간이 점점 좁아지고 있다.","황갈색수염상어의 자궁은 인간의 자궁과 형태가 유사하다.","황갈색수염상어의 새끼는 자궁 속에서 세상에 나올 준비를 한다."]'::jsonb, 2, '황갈색수염상어의 새끼는 자궁 속에서 세상에 나올 준비를 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 44, '새끼 상어가 자궁 속에서 무정란을 먹는 이유로 맞는 것을 고르십시오.

남자: 새끼 상어가 꼬물꼬물 헤엄을 치는 이 작은 공간은 어미 황갈색수
염상어의 자궁 속이다. 새끼 황갈색수염상어는 인간과 마찬가지로
이곳에서 약 10개월을 보낸다. 그런데 영양분을 공급받아야 할 탯줄이
보이지 않는다. 어떻게 영양분을 섭취하는 걸까. 어미 상어는 수정이
되지 않은 수십 개의 무정란을 자궁 속에 가지고 있다. 탯줄이 없어
움직임이 자유로운 새끼 상어는 이 알들을 찾아다니며 먹는다. 어미
상어 배 속에서부터 헤엄치는 법과 먹이 찾는 법을 함께 익히고 있는
셈이다. 세상을 살아갈 만반의 준비를 모두 마친 후 마침내 새끼
상어는 자궁 밖으로 나온다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["공간을 넓히기 위해서","영양분을 얻기 위해서","수분을 배출하기 위해서","움직임을 줄이기 위해서"]'::jsonb, 2, '영양분을 얻기 위해서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 45, '들은 내용과 일치하는 것을 고르십시오.

여자: 이 사진 속의 악기는 여러분이 잘 알고 있는 색소폰입니다. 색소폰은
다른 클래식 악기들에 비해 늦은 시기인 19세기에 유럽에서 발명됐
는데요. 당시 음악계에서 별로 환영을 받지 못했습니다. 음악계를
주도했던 오케스트라는 이미 악기 편성이 확립돼 있었고, 다른 악기
들과 조화를 이뤄 연주하기에 색소폰의 음색이 너무 튀었기 때문이죠.
색소폰이 인기를 얻기 시작한 건 20세기 들어 불기 시작한 재즈 열풍
덕분이었는데요. 흔들리듯 불안하게 들리는 색소폰의 음색이 자유로운
분위기의 재즈와 잘 맞아떨어진 겁니다. 관능적이고 호소력 짙은
소리가 독특한 음색으로 인정받게 된 것이죠.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["섹소폰은 다른 악기와의 합주에 적합했다.","섹소폰은 19세기부터 활발하게 사용되었다.","섹소폰은 재즈 덕분에 인기를 얻기 시작했다.","섹소폰의 음색은 편안하고 안정된 느낌을 준다."]'::jsonb, 2, '섹소폰은 재즈 덕분에 인기를 얻기 시작했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 46, '여자가 말하는 방식으로 가장 알맞은 것을 고르십시오.

여자: 이 사진 속의 악기는 여러분이 잘 알고 있는 색소폰입니다. 색소폰은
다른 클래식 악기들에 비해 늦은 시기인 19세기에 유럽에서 발명됐
는데요. 당시 음악계에서 별로 환영을 받지 못했습니다. 음악계를
주도했던 오케스트라는 이미 악기 편성이 확립돼 있었고, 다른 악기
들과 조화를 이뤄 연주하기에 색소폰의 음색이 너무 튀었기 때문이죠.
색소폰이 인기를 얻기 시작한 건 20세기 들어 불기 시작한 재즈 열풍
덕분이었는데요. 흔들리듯 불안하게 들리는 색소폰의 음색이 자유로운
분위기의 재즈와 잘 맞아떨어진 겁니다. 관능적이고 호소력 짙은
소리가 독특한 음색으로 인정받게 된 것이죠.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["색소폰의 위상 변화를 설명하고 있다.","색소폰의 연주 방법을 비교하고 있다.","색소폰의 발명 과정을 요약하고 있다.","색소폰의 세부 형태를 묘사하고 있다."]'::jsonb, 2, '색소폰의 위상 변화를 설명하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 47, '들은 내용과 일치하는 것을 고르십시오.

여자: 국가지점번호라....... 저는 좀 생소한데요. 이미 시행 중인 제도라고요?
남자: 네, 국가지점번호 제도는 조난이 발생했을 때 그 위치를 정확하게
알 수 있도록 지역마다 번호를 부여하고 표지판을 설치하는 것입니다.
이 제도는 2013년부터 신속한 구조를 목적으로 시행이 되었는데요.
아직까지도 표지판이 설치되지 않은 지역이 많고, 잘 알려지지도
않았습니다. 이는 실제 수행을 담당해야 할 지방자치단체들이 업무의
책임을 분명히 하지 않고, 예산 부족을 핑계로 설치를 미루고 있기
때문인데요. 국민들의 안전과도 밀접한 관계가 있는 만큼 시행을
위한 각 지방자치단체들의 적극적인 노력이 있어야 하겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 제도는 곧 시행될 예정이다.","이 제도는 신속한 구조를 위해 마련되었다.","이 제도는 국민 대상 홍보가 잘 이루어졌다.","이 제도는 예산 지원이 원활하게 진행되고 있다."]'::jsonb, 2, '이 제도는 신속한 구조를 위해 마련되었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 48, '남자의 태도로 가장 알맞은 것을 고르십시오.

여자: 국가지점번호라....... 저는 좀 생소한데요. 이미 시행 중인 제도라고요?
남자: 네, 국가지점번호 제도는 조난이 발생했을 때 그 위치를 정확하게
알 수 있도록 지역마다 번호를 부여하고 표지판을 설치하는 것입니다.
이 제도는 2013년부터 신속한 구조를 목적으로 시행이 되었는데요.
아직까지도 표지판이 설치되지 않은 지역이 많고, 잘 알려지지도
않았습니다. 이는 실제 수행을 담당해야 할 지방자치단체들이 업무의
책임을 분명히 하지 않고, 예산 부족을 핑계로 설치를 미루고 있기
때문인데요. 국민들의 안전과도 밀접한 관계가 있는 만큼 시행을
위한 각 지방자치단체들의 적극적인 노력이 있어야 하겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["제도에 대한 평가를 유보하고 있다.","제도의 긍정적인 효과를 기대하고 있다.","제도 시행을 위한 국민의 협조를 당부하고 있다.","제도 시행의 문제를 지적하며 시정을 촉구하고 있다."]'::jsonb, 2, '제도 시행의 문제를 지적하며 시정을 촉구하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 49, '들은 내용과 일치하는 것을 고르십시오.

여자: 이것은 조선 후기 왕들의 일기인 ''일성록''입니다. 하루의 반성문이란
뜻을 가진 이 책은 왕의 소소한 일상에서부터 국정 업무 전반을 왕의
시점으로 기록한 것인데요. 당시의 왕들은 ''일성록''을 신하들이 볼
수 있게 하여 국정 업무에 참고하게 했습니다. 이 일기에는 백성들의
상소와 처리 과정은 물론 그에 대한 왕의 심경까지 기록되어 있고,
18세기부터 20세기에 걸친 세계정세 변화와 동서양의 사회 문화적
교류 양상까지도 상세히 적혀 있습니다. ''일성록''은 단순한 일기를
넘어 한국뿐만 아니라 세계 역사에도 매우 중요한 사료로 인정받고
있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 책은 왕의 업무 내용을 담고 있다.","이 책은 신하들에게 공개되지 않았다.","이 책은 백성의 관점에서 작성되었다.","이 책은 조선 시대 이전에 기록되었다."]'::jsonb, 2, '이 책은 왕의 업무 내용을 담고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'listening', 50, '여자의 태도로 가장 알맞은 것을 고르십시오.

여자: 이것은 조선 후기 왕들의 일기인 ''일성록''입니다. 하루의 반성문이란
뜻을 가진 이 책은 왕의 소소한 일상에서부터 국정 업무 전반을 왕의
시점으로 기록한 것인데요. 당시의 왕들은 ''일성록''을 신하들이 볼
수 있게 하여 국정 업무에 참고하게 했습니다. 이 일기에는 백성들의
상소와 처리 과정은 물론 그에 대한 왕의 심경까지 기록되어 있고,
18세기부터 20세기에 걸친 세계정세 변화와 동서양의 사회 문화적
교류 양상까지도 상세히 적혀 있습니다. ''일성록''은 단순한 일기를
넘어 한국뿐만 아니라 세계 역사에도 매우 중요한 사료로 인정받고
있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/audio/64-TOPIK-II-Listening-Audio-File.mp3', NULL, '["기록물의 가치를 높이 평가하고 있다.","기록물의 활용 방안을 강구하고 있다.","기록물에 대한 맹신을 경계하고 있다.","기록물의 훼손 가능성을 우려하고 있다."]'::jsonb, 2, '기록물의 가치를 높이 평가하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 1, '( ........................ )에 들어갈 가장 알맞은 것을 고르십시오. (각 2점)

나는 주말에는 보통 영화를( ........................ ) 운동을 한다.', NULL, NULL, NULL, '["보지만","보거나","보려고","보더니"]'::jsonb, 2, '보거나', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 2, '( ........................ )에 들어갈 가장 알맞은 것을 고르십시오. (각 2점)

동생이 점점 아버지를( ........................ ).', NULL, NULL, NULL, '["닮아 간다","닮기도 한다","닮았나 보다","닮은 적이 없다"]'::jsonb, 2, '닮아 간다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 3, '다음 밑줄 친 부분과 의미가 비슷한 것을 고르십시오.

정부는 일자리를 <span class=''underline''>늘리고자</span> 새로운 정책을 수립했다.', NULL, NULL, NULL, '["늘리자마자","늘리더라도","늘리는 대신","늘리기 위해"]'::jsonb, 2, '늘리기 위해', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 4, '다음 밑줄 친 부분과 의미가 비슷한 것을 고르십시오.

태어난 지 얼마 안 되어 서울로 왔으니 서울이 <span class=''underline''>고향인 셈이다</span>.', NULL, NULL, NULL, '["고향일 뿐이다","고향이면 좋겠다","고향일 리가 없다","고향이나 마찬가지이다"]'::jsonb, 2, '고향이나 마찬가지이다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 5, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/reading/q5.png', NULL, NULL, '["에어컨","청소기","냉장고","세탁기"]'::jsonb, 2, '에어컨', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 6, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/reading/q6.png', NULL, NULL, '["병원","은행","여행사","체육관"]'::jsonb, 2, '은행', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 7, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/reading/q7.png', NULL, NULL, '["건강 관리","화재 예방","이웃 사랑","환경 보호"]'::jsonb, 2, '환경 보호', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 8, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/reading/q8.png', NULL, NULL, '["이용 안내","구입 문의","사용 순서","교환 방법"]'::jsonb, 2, '이용 안내', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 9, '다음 글의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/reading/q9.png', NULL, NULL, '["이 대회는 이번에 처음으로 열린다.","이 대회에는 누구나 참가할 수 있다.","이 대회에 참가하려면 돈을 내야 한다.","이 대회의 출발 장소는 인주기념관이다."]'::jsonb, 2, '이 대회에는 누구나 참가할 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 10, '다음 글 또는 그래프의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-64/reading/q10.png', NULL, NULL, '["1위 순위의 직업이 바뀌었다.","공무원은 순위의 변화가 없었다.","군인이 새롭게 5위 안에 들었다.","간호사는 4위로 순위가 떨어졌다."]'::jsonb, 2, '군인이 새롭게 5위 안에 들었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 11, '다음 글의 내용과 같은 것을 고르십시오.

지난 24일에 ''제7회 소비자 선정 최고 브랜드 대상'' 시상식이 인주신문사 대강당에서 개최됐다. 이 상은 소비자의 온라인 투표로 수상 브랜드가 선정되어 의미가 크다. 지난해와 같이 100개 브랜드가 상을 받았는데 올해는 처음으로 친환경 화장품 브랜드 두 개가 포함되었다.', NULL, NULL, NULL, '["소비자가 수상 브랜드를 선정했다.","기업들이 직접 온라인 투표에 참여했다.","지난해보다 더 많은 브랜드가 선정됐다.","친환경 화장품 브랜드는 상을 못 받았다."]'::jsonb, 2, '소비자가 수상 브랜드를 선정했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 12, '다음 글의 내용과 같은 것을 고르십시오.

최근 한 나라에서 4,400년 전에 만들어진 무덤이 발견됐다. 이 무덤의 주인은 당시 왕으로 밝혀졌으며 무덤 벽에는 고대 문자와 다양한 색의 그림이 가득했다. 이 무덤은 오랜 시간이 지났지만 색이 거의 그대로 보존 되어 있어 역사적 가치가 높다고 전문가들은 전했다. 무덤의 일부는 일반인 에게도 곧 공개될 예정이다.', NULL, NULL, NULL, '["무덤의 주인이 누구인지 찾고 있다.","무덤 안을 구경하는 사람들이 많아졌다.","무덤 안의 그림은 색의 상태가 좋은 편이다.","무덤 바닥에서 다양한 문자와 그림이 발견됐다."]'::jsonb, 2, '무덤 안의 그림은 색의 상태가 좋은 편이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 13, '다음을 순서대로 맞게 배열한 것을 고르십시오.

(가) 회사의 1층 로비를 외부인에게 개방하는 회사가 많아졌다.
(나) 사람들은 작품을 감상하고 커피를 마시면서 시간을 보낸다.
(다) 미술관과 카페를 만들어 사람들이 와서 즐길 수 있게 한 것이다.
(라) 이 공간을 이용하는 사람이 늘면서 회사의 이미지도 좋아지고 있다.', NULL, NULL, NULL, '["(가)-(다)-(나)-(라)","(나)-(라)-(다)-(가)","(다)-(나)-(라)-(가)","(라)-(나)-(가)-(다)"]'::jsonb, 2, '(가)-(다)-(나)-(라)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 14, '다음을 순서대로 맞게 배열한 것을 고르십시오.

(가) 차에서 내려 앞차의 주인에게 사과하고 사정을 설명했다.
(나) 앞차 주인은 큰 사고가 아니니 괜찮다며 그냥 가라고 했다.
(다) 친절한 배려 덕분에 딸은 무사히 병원에 도착해 치료를 받았다.
(라) 아픈 딸을 병원으로 급하게 데려가다가 앞차와 부딪쳐서 사고를 냈다.', NULL, NULL, NULL, '["(나)-(가)-(다)-(라)","(나)-(가)-(라)-(다)","(라)-(가)-(나)-(다)","(라)-(가)-(다)-(나)"]'::jsonb, 2, '(라)-(가)-(나)-(다)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 15, '다음을 순서대로 맞게 배열한 것을 고르십시오.

(가) 선택에 대한 부담으로 구매를 망설이다가 포기하기도 한다.
(나) 선택에 대한 고객의 부담을 줄여 구매를 유도하려는 것이다.
(다) 그래서 마트에서는 품목별로 몇 가지의 제품만 매장에 진열한다.
(라) 소비자는 선택의 폭이 넓을수록 물건을 고를 때 어려움을 겪는다.', NULL, NULL, NULL, '["(나)-(가)-(라)-(다)","(나)-(라)-(가)-(다)","(라)-(가)-(다)-(나)","(라)-(다)-(가)-(나)"]'::jsonb, 2, '(라)-(가)-(다)-(나)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 16, '( ........................ )에 들어갈 내용으로 가장 알맞은 것을 고르십시오.

상담을 통해 책을 추천해 주는 서점이 있어 화제가 되고 있다. 서점 주인은 손님과 오랜 시간 대화를 나눈 후( ........................ ) 책을 추천해 준다. 상처 받은 사람에게는 위로가 되는 책을, 자신감이 부족한 사람에게는 용기를 주는 책을 추천하는 방식으로 서비스를 제공한다.', NULL, NULL, NULL, '["내용이 재미있는","지식을 전달하는","사람들이 많이 읽는","손님의 상황에 맞는"]'::jsonb, 2, '손님의 상황에 맞는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 17, '( ........................ )에 들어갈 내용으로 가장 알맞은 것을 고르십시오.

샌드위치나 샐러드 등은 오래 보관할 수 없어 신선할 때 팔아야 한다. 이런 식품을 영업 마감 시간을 앞두고 사람들에게 할인된 가격으로 판매 하는 서비스가 큰 호응을 얻고 있다. 음식점은 남은 음식을 팔아 수익을 얻을 수 있고, 소비자는 ( ........................ ) 이용자들의 만족도가 높다.', NULL, NULL, NULL, '["자원을 아낄 수 있어서","식품을 저렴하게 살 수 있어서","요리법을 배울 수 있기 때문에","음식을 선택할 수 있기 때문에"]'::jsonb, 2, '식품을 저렴하게 살 수 있어서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 18, '( ........................ )에 들어갈 내용으로 가장 알맞은 것을 고르십시오.

뮤지컬은 보통 한 역할에 여러 명의 배우들이 출연한다. 배우에 따라 연기나 분위기가 다르기 때문에 같은 작품이라도 색다른 느낌을 받을 수 있다. 그래서 뮤지컬 팬들은( ........................ ) 작품을 즐기기 위해 공연을 반복해서 관람한다.', NULL, NULL, NULL, '["입장료를 할인해 주는","공연장에서 인기가 있는","유행하는 노래가 나오는","각 배우들의 개성이 담긴"]'::jsonb, 2, '각 배우들의 개성이 담긴', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 19, '( ........................ )에 들어갈 알맞은 것을 고르십시오.

해파리는 몸의 95%가 물로 구성되어 있어 열량이 낮다. 그래서 해파리를 먹고 사는 동물이 거의 없다고 알려져 있었다. 하지만 새나 펭귄, 뱀장어 등 많은 동물들에게 해파리는 좋은 먹잇감이다. 해파리에는 비타민이나 콜라겐 같은 영양 성분이 있기 때문이다. ( ........................ ) 해파리는 바다 어디에나 있고 도망치지 않아 사냥하기 쉽기 때문이다.', NULL, NULL, NULL, '["과연","만약","게다가","이처럼"]'::jsonb, 2, '게다가', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 20, '위 글의 내용과 같은 것을 고르십시오.

해파리는 몸의 95%가 물로 구성되어 있어 열량이 낮다. 그래서 해파리를 먹고 사는 동물이 거의 없다고 알려져 있었다. 하지만 새나 펭귄, 뱀장어 등 많은 동물들에게 해파리는 좋은 먹잇감이다. 해파리에는 비타민이나 콜라겐 같은 영양 성분이 있기 때문이다. ( ........................ ) 해파리는 바다 어디에나 있고 도망치지 않아 사냥하기 쉽기 때문이다.', NULL, NULL, NULL, '["해파리는 바다 생태계에 피해를 준다.","해파리는 잡기 어려운 먹이 자원이다.","해파리는 여러 동물의 먹이가 되고 있다.","해파리는 대부분 콜라겐으로 이루어져 있다."]'::jsonb, 2, '해파리는 여러 동물의 먹이가 되고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 21, '( ........................ )에 들어갈 알맞은 것을 고르십시오.

내비게이션은 목적지까지 길을 안내해 주는 기기이다. 내비게이션이 없이 낯선 곳에 갔다가 길을 못 찾아 ( ........................ ) 본 적이 있는 사람이라면 내비게이션이 얼마나 편리한지 느꼈을 것이다. 그러나 우리의 뇌는 스스로 정보를 찾았을 때 그 정보를 오래 기억하는 특성이 있다. 따라서 지나치게 디지털 기기에만 의존하다 보면 정보를 찾고 기억하는 능력이 점점 줄어들어 결국 그 능력을 사용할 수 없게 될지도 모른다.', NULL, NULL, NULL, '["앞뒤를 재어","진땀을 흘려","발목을 잡아","귀를 기울여"]'::jsonb, 2, '진땀을 흘려', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 22, '위 글의 중심 생각을 고르십시오.

내비게이션은 목적지까지 길을 안내해 주는 기기이다. 내비게이션이 없이 낯선 곳에 갔다가 길을 못 찾아 ( ........................ ) 본 적이 있는 사람이라면 내비게이션이 얼마나 편리한지 느꼈을 것이다. 그러나 우리의 뇌는 스스로 정보를 찾았을 때 그 정보를 오래 기억하는 특성이 있다. 따라서 지나치게 디지털 기기에만 의존하다 보면 정보를 찾고 기억하는 능력이 점점 줄어들어 결국 그 능력을 사용할 수 없게 될지도 모른다.', NULL, NULL, NULL, '["디지털 기기는 편리한 생활을 위해 필요하다.","운전자에게 내비게이션은 활용도가 매우 높다.","스스로 정보를 찾고 기억하려는 노력을 해야 한다.","내비게이션을 잘 활용하면 기억력 향상에 도움이 된다."]'::jsonb, 2, '스스로 정보를 찾고 기억하려는 노력을 해야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 23, '밑줄 친 부분에 나타난 ''나''의 심정으로 알맞은 것을 고르십시오.

놀이공원 매표소에서 아르바이트를 했다. 아르바이트가 처음이라 실수를 하지 않으려고 늘 긴장하면서 일을 했다. 어느 날, 놀러 온 한 가족에게 인원수만큼 표를 줬다. 그런데 그 가족을 보내고 나서 이용권 한 장의 값이 더 결제된 것을 알아차렸다. 바로 카드사로 전화해 고객의 전화번호를 물었지만 상담원은 알려 줄 수 없다고 했다. 하지만 내 연락처를 고객에게 전달해 주겠다고 했다. 일을 하는 내내 일이 손에 잡히지 않았다. 퇴근 시간 무렵 드디어 그 가족에게서 전화가 왔다. 내가 한 실수에 <span class=''underline''>화를 낼지도 모른다는 생각에</span> 떨리는 목소리로 상황을 설명하자 그 가족은 “놀이 기구를 타고 노느라 문자 메시지가 온 줄 몰랐어요. 많이 기다렸겠어요.”라고 하며 따뜻하게 말해 주었다.', NULL, NULL, NULL, '["걱정스럽다","불만스럽다","후회스럽다","당황스럽다"]'::jsonb, 2, '걱정스럽다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 24, '위 글의 내용과 같은 것을 고르십시오.

놀이공원 매표소에서 아르바이트를 했다. 아르바이트가 처음이라 실수를 하지 않으려고 늘 긴장하면서 일을 했다. 어느 날, 놀러 온 한 가족에게 인원수만큼 표를 줬다. 그런데 그 가족을 보내고 나서 이용권 한 장의 값이 더 결제된 것을 알아차렸다. 바로 카드사로 전화해 고객의 전화번호를 물었지만 상담원은 알려 줄 수 없다고 했다. 하지만 내 연락처를 고객에게 전달해 주겠다고 했다. 일을 하는 내내 일이 손에 잡히지 않았다. 퇴근 시간 무렵 드디어 그 가족에게서 전화가 왔다. 내가 한 실수에 <span class=''underline''>화를 낼지도 모른다는 생각에</span> 떨리는 목소리로 상황을 설명하자 그 가족은 “놀이 기구를 타고 노느라 문자 메시지가 온 줄 몰랐어요. 많이 기다렸겠어요.”라고 하며 따뜻하게 말해 주었다.', NULL, NULL, NULL, '["그 가족은 나에게 화를 냈다.","카드 회사는 그 가족에게 연락을 했다.","나는 그 가족에게 직접 전화를 걸었다.","나는 그 가족을 찾아다니느라 일을 못 했다."]'::jsonb, 2, '카드 회사는 그 가족에게 연락을 했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 25, '다음 신문 기사의 제목을 가장 잘 설명한 것을 고르십시오.

관광버스 추락, 안전벨트로 승객 전원 목숨 건져', NULL, NULL, NULL, '["관광버스가 추락했지만 승객들이 안전벨트 덕분에 모두 살았다.","관광버스 추락 사고 이후 안전벨트를 하는 승객이 더 많아졌다.","관광버스가 추락하자 일부 승객이 안전벨트를 풀고 탈출하였다.","관광버스가 추락하면서 안전벨트를 한 일부 승객이 크게 다쳤다."]'::jsonb, 2, '관광버스가 추락했지만 승객들이 안전벨트 덕분에 모두 살았다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 26, '다음 신문 기사의 제목을 가장 잘 설명한 것을 고르십시오.

침묵 깬 김민수 의원, 대통령 선거 출마설 부인', NULL, NULL, NULL, '["김 의원이 대통령 선거에 나가느냐는 질문에 계속 답하지 않고 있다.","김 의원이 마음을 바꾸어 대통령 선거에 나가겠다고 최종 발표하였다.","김 의원이 대통령 선거에 나간다고 선언하자 사람들이 열렬히 환영했다.","김 의원이 대통령 선거에 나간다는 것이 사실이 아니라고 입장을 밝혔다."]'::jsonb, 2, '김 의원이 대통령 선거에 나간다는 것이 사실이 아니라고 입장을 밝혔다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 27, '다음 신문 기사의 제목을 가장 잘 설명한 것을 고르십시오.

민간 우주선 무사 귀환, 우주여행 시대 ''성큼''', NULL, NULL, NULL, '["사람들의 응원 속에 민간 우주선이 긴 우주여행을 마치고 돌아왔다.","사람들은 민간 우주선이 우주여행에서 무사히 돌아오기를 기대했다.","민간 우주선이 무사히 돌아오면서 우주여행의 가능성이 더욱 높아졌다.","민간 우주선이 돌아오지 않자 우주여행에 대한 우려의 목소리가 커졌다."]'::jsonb, 2, '민간 우주선이 무사히 돌아오면서 우주여행의 가능성이 더욱 높아졌다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 28, '( ........................ )에 들어갈 내용으로 가장 알맞은 것을 고르십시오.

새해에 세운 목표를 효과적으로 이루려면 한 주 단위로 계획을 세우는 것이 좋다. 주마다 계획을 세우면( ........................ ) 때문이다. ''건강한 식습관 기르기''라는 새해 결심이 한 주 단위가 되면 ''라면 안 먹기'', ''채소 챙겨 먹기''처럼 구체적인 계획으로 바뀐다. 이렇게 하면 작은 목표를 달성 하는 횟수가 늘어 한 해의 목표에 가까워진다.', NULL, NULL, NULL, '["한 해의 목표를 확인하기","계획을 세우는 데 집중하기","자신의 능력을 보여 줄 수 있기","실천 가능한 계획을 세울 수 있기"]'::jsonb, 2, '실천 가능한 계획을 세울 수 있기', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 29, '( ........................ )에 들어갈 내용으로 가장 알맞은 것을 고르십시오.

무지개는 빛이 공기 중의 물방울을 통과할 때 굴절되어 나타나는 현상이다. 그래서 비가 그친 직후 해가 뜰 때 무지개가 잘 생긴다. 이때 ( ........................ ) 않으면 무지개가 만들어지기 어렵다. 공기에 먼지 등의 오염 물질이 섞이면 물방울들이 먼지 주위로 모여 빛이 통과하는 것을 막기 때문이다.', NULL, NULL, NULL, '["해가 뜨지","비가 그치지","빛이 약하지","공기가 깨끗하지"]'::jsonb, 2, '공기가 깨끗하지', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 30, '( ........................ )에 들어갈 내용으로 가장 알맞은 것을 고르십시오.

취재 경계선은 취재가 과열되어 발생할 수 있는 불상사를 예방하기 위해 설정한 것이다. 수백 명의 취재진이 화제의 인물에게 몰려들 경우 사고가 발생해 취재를 망칠 수 있다. 그래서 선을 그어 놓고 그 바깥에서 취재하자는 합의를 본 것이다. 비록 법으로 정해져 있지 않지만 언론계가 이 선을 지키려고 노력하는 것은 ( ........................ ) 순간 원활한 보도가 어려워진다는 것을 누구보다 잘 알고 있기 때문이다.', NULL, NULL, NULL, '["취재 정보를 공유하는","취재 경계선이 무너지는","취재 내용을 잘못 해석하는","취재 경계선이 새로 설정되는"]'::jsonb, 2, '취재 경계선이 무너지는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 31, '( ........................ )에 들어갈 내용으로 가장 알맞은 것을 고르십시오.

병원의 규모에 따라 개인이 부담해야 하는 약값을 달리하는 제도가 생겼다. 감기와 같이 비교적 가벼운 병에 걸렸을 때 종합병원에서 진료를 받으면( ........................ ) 만든 것이다. 같은 약을 동네 의원에서 받은 처방전으로 사게 되면 약값이 더 적게 나온다. 이 제도를 통해 환자들이 진료에 대한 신뢰 때문에 종합병원으로만 몰리는 현상을 줄일 수 있을 것으로 예상된다.', NULL, NULL, NULL, '["환자가 약값을 조금 더 내게","개인이 약값을 비교할 수 있게","병원에서 병원비를 올리지 못하게","병원비의 일부를 병원에서 지원하게"]'::jsonb, 2, '환자가 약값을 조금 더 내게', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 32, '다음을 읽고 내용이 같은 것을 고르십시오.

나비 박사 석주명은 나비의 종류를 분류하고 이름을 지어 준 생물학자 이다. 1931년부터 나비를 연구한 그는 한국의 나비가 총 844종이라는 당시의 분류를 248종으로 수정하였다. 날개 무늬나 모양이 조금만 달라도 다른 종이라고 판단한 기존의 분류가 틀렸음을 배추흰나비 16만여 마리의 무늬를 비교해서 밝혔다. 또한 그때까지 한자어나 외래어로 명명된 나비에 ''떠들썩 팔랑나비''와 같은 고유어 이름을 지어 주는 데 앞장섰다.', NULL, NULL, NULL, '["석주명은 한국의 나비를 총 844종으로 분류하였다.","석주명은 나비 이름을 고유어로 바꾸려고 노력하였다.","석주명은 자신의 배추흰나비 연구에 문제가 있음을 알았다.","석주명은 나비의 날개 모양이 다르면 종이 달라짐을 밝혔다."]'::jsonb, 2, '석주명은 나비 이름을 고유어로 바꾸려고 노력하였다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 33, '다음을 읽고 내용이 같은 것을 고르십시오.

저축의 방식을 가로 저축과 세로 저축으로 나눠 비유하여 설명할 수 있다. 차량 구입이나 주택 마련과 같이 특정 목적을 위해 한 통장에 집중하여 저축하는 것이 세로 저축이다. 반면 장기적으로 다양한 목적에 따라 자금을 여러 통장에 분산하여 저축하는 것을 가로 저축이라고 한다. 단기적으로 빨리 목돈을 만들고 싶다면 세로 저축을, 은퇴 후의 생활까지 고려한다면 가로 저축을 선택하는 것이 좋다.', NULL, NULL, NULL, '["노후 준비에는 세로 저축이 유리하다.","세로 저축보다 가로 저축을 하는 것이 더 좋다.","저축의 목적이 다양하면 가로 저축이 유용하다.","가로 저축은 단기적인 계획이 있을 때 효율적이다."]'::jsonb, 2, '저축의 목적이 다양하면 가로 저축이 유용하다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 34, '다음을 읽고 내용이 같은 것을 고르십시오.

''책가도''는 책장과 책을 중심으로 하여 각종 문방구 등을 그린 그림이다. 학문을 중요시하는 왕의 바람과 출세를 원하는 양반의 마음이 더해져 책가도는 궁중과 사대부를 중심으로 발전하였다. 19세기에는 상인과 농민 계층으로도 확산되면서 그 형식도 자유로워졌다. 그림에서 책장 대신 작은 탁자가 활용되기도 하고 일상 용품이 함께 그려지기도 했다.', NULL, NULL, NULL, '["왕은 책가도에 대해 부정적 인식이 강했다.","점차 다양한 계층에서 책가도를 즐기게 되었다.","초기의 책가도에는 일상 용품이 주로 그려졌다.","책가도는 왕의 바람으로 그림의 형식이 바뀌었다."]'::jsonb, 2, '점차 다양한 계층에서 책가도를 즐기게 되었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 35, '다음 글의 주제로 가장 알맞은 것을 고르십시오.

문화재 복원 작업은 복원된 부분이 자연스러워야 하고 그 과정에서 문화재가 추가로 손상되지 않아야 한다. 이 때문에 정확한 측정으로 복원할 부분을 원래 모습과 동일하게 만들어 내는 것은 복원의 성공을 결정하는 중요한 요건이다. 최근 3D 스캐너와 프린터가 등장하여 이러한 요건을 충족할 수 있게 되면서 정밀하고 안전한 문화재 복원이 가능해졌다.', NULL, NULL, NULL, '["첨단 장비 덕분에 문화재 복원이 수월해졌다.","문화재는 손상 예방을 위한 사전 관리가 중요하다.","복원 환경 탓에 원본이 변형되는 경우가 많아지고 있다.","복원 기술자를 대상으로 한 3D 장치 사용 교육이 필요하다."]'::jsonb, 2, '첨단 장비 덕분에 문화재 복원이 수월해졌다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 36, '다음 글의 주제로 가장 알맞은 것을 고르십시오.

아기는 주변 사물을 손으로 더듬고 만지면서 지각 능력을 발달시킨다. 그런데 이렇게 능동적인 경험뿐만 아니라 사람, 햇빛, 바람 등에 의한 접촉도 주요한 촉각 경험이 된다. 그중 주변 인물과의 피부 접촉은 사랑, 유대감, 신뢰감 등 유아의 정서 발달과 사회성 발달에 매우 중요하다. 연구에 따르면 아기가 태어난 후 몇 년 사이에 이루어진 피부 접촉은 정서 발달에 필수적인 호르몬 분비를 촉진할 뿐만 아니라 지능 발달에도 영향을 미친다고 한다.', NULL, NULL, NULL, '["인간은 촉각을 통해 주변 사물을 이해한다.","정서 발달과 지능 발달은 상관관계가 높다.","촉각 경험의 중요성에 대한 연구가 필요하다.","유아의 발달을 위해서는 피부 접촉이 중요하다."]'::jsonb, 2, '유아의 발달을 위해서는 피부 접촉이 중요하다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 37, '다음 글의 주제로 가장 알맞은 것을 고르십시오.

나무에 붙어 자라는 버섯을 보면 나무로부터 양분을 받으며 별다른 노력 없이 살아간다고 생각하기 쉽다. 하지만 버섯은 나무에게 없어서는 안 될 중요한 존재이다. 나무들은 위기 상황이 발생해도 자리를 옮겨 이를 알릴 수 없기 때문에 뿌리로 소통하며 위험에 대비한다. 이때 뿌리가 짧아 서로 닿지 않는 나무들 사이에서는 실처럼 뻗은 버섯 균사체가 메시지 전달을 대신한다. 그래서 학자들은 버섯 균류를 ''숲의 통신망''이라고 부른다.', NULL, NULL, NULL, '["버섯은 다른 식물이 있어야 자랄 수 있다.","나무의 뿌리가 숲에서 하는 기능은 다양하다.","버섯은 숲에서 나무들의 정보 교환을 돕는 역할을 한다.","나무의 생활환경에 대한 학자들의 관심이 높아지고 있다."]'::jsonb, 2, '버섯은 숲에서 나무들의 정보 교환을 돕는 역할을 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 38, '다음 글의 주제로 가장 알맞은 것을 고르십시오.

음주 운전으로 인명 피해를 낸 사람에 대한 처벌 강화 법안이 국회에서 통과되었다. 하지만 새 법안은 원래 안건보다 처벌의 강도를 낮춘 것이라는 점에서 반쪽짜리 법안에 불과하다. 이 법안에 따르면 여전히 음주 운전 가해자의 처벌이 미뤄지거나 일정 기간이 지난 후 효력이 없어질 수도 있다. 이는 음주 운전에 대한 경각심을 높이고 재발 위험성을 낮추려던 본래의 취지에는 맞지 않는 것이다.', NULL, NULL, NULL, '["법안이 가진 본래의 취지를 널리 알려야 한다.","피해 정도에 따라 처벌의 수위를 조절해야 한다.","새 법안의 통과가 더 이상 미루어져서는 안 된다.","새 법안은 실질적 효과를 거두는 데 미흡한 점이 있다."]'::jsonb, 2, '새 법안은 실질적 효과를 거두는 데 미흡한 점이 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 39, '주어진 문장이 들어갈 곳으로 가장 알맞은 곳을 고르십시오.

주어진 문장: 그래서 백성들이 구하기 힘든 매우 귀하고 값비싼 재료로 만들어졌다.

왕관은 과거 지배 계층이 착용했던 대표적인 장신구이다. ( ㉠ ) 장식도 화려하게 더해져 그것을 쓴 왕의 지위를 더욱 돋보이게 했다.( ㉡ ) 오늘날 왕관이 가졌던 힘과 지위의 의미는 약화되었으나 고귀한 이미지는 남아 여러 디자인에서 발견된다.( ㉢ ) 아름다움이 강조되어야 할 신부의 머리 장식이나 여러 액세서리에 왕관이 활용되고 있는 것이다.( ㉣ )', NULL, NULL, NULL, '["㉠","㉡","㉢","㉣"]'::jsonb, 2, '㉠', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 40, '주어진 문장이 들어갈 곳으로 가장 알맞은 곳을 고르십시오.

주어진 문장: 그들은 못생기고 혐오감을 준다는 이유만으로 외면당한 동물들을 대중에게 알리는 활동을 한다.

멸종 위기에 처한 동물을 보호하려는 노력이 계속되고 있으나 주된 연구와 지원이 몇몇 동물에 쏠리고 있어 문제가 되고 있다. ( ㉠ ) 한 조사에 따르면 동물 보호 기금의 모금 액수도 북극곰, 판다같이 인기 있는 동물들 에게 편중되었다고 한다. ( ㉡ ) 이런 가운데 그간 관심을 받지 못했던 동물들을 보호하기 위한 단체가 등장했다. ( ㉢ ) 이러한 노력은 동물 보호를 위한 마음에도 편견이 깃들어 있었음을 일깨우고 있다. ( ㉣ )', NULL, NULL, NULL, '["㉠","㉡","㉢","㉣"]'::jsonb, 2, '㉢', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 41, '주어진 문장이 들어갈 곳으로 가장 알맞은 곳을 고르십시오.

주어진 문장: 일곱 편의 단편에는 오해와 잘못으로 멀어진 사람들에 대한 이야기가 담겨 있다.

''젊은 작가상''을 수상한 최은영이 두 번째 소설집 『내게 무해한 사람』을 펴냈다. ( ㉠ ) 2년여에 걸쳐 여러 지면에 발표했던 작품들을 한 권에 모은 것이다. ( ㉡ ) 그들처럼 누군가에 대한 배반, 원치 않았던 이별 등 매듭짓지 못한 일들을 다시 떠올린다는 것은 괴로운 과정일 것이다. ( ㉢ ) 그러나 작가는 이미 지나간 시간에 대해 후회할 필요는 없으며 상처도 힘이 될 수 있다는 메시지로 독자의 마음을 움직인다. ( ㉣ )', NULL, NULL, NULL, '["㉠","㉡","㉢","㉣"]'::jsonb, 2, '㉡', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 42, '밑줄 친 부분에 나타난 ''소희''의 심정으로 알맞은 것을 고르십시오.

그때 소희네는 이사를 앞두고 있었는데 엄마는 그렇게 집을 나가 돌아 오지 않았다. 작별 인사는커녕 아무 신호도 낌새도 없이 사라졌다. (중략) 엄마가 집 나가고 열흘쯤 지났을 땐가, 소희가 텔레비전을 보고 있는데 본희가 현관에서 신을 신으며 잠깐 나갔다 오겠다고 했다. "잠깐 어디?" "친구네.” “친구 누구?" 소희가 눈을 맞추려 했지만 본희는 돌아보지 않았다. "늦으면 친구네서 자고 올지도 몰라. 기다리지 말고 자." 돌아서 나가는 본희가 멘 가방이 이상하게 커 보여 소희는 자리에서 벌떡 일어났다. 가만히 서 있다가 갑자기 현관문을 열고 맨발로 뛰어나가 계단을 올라가는 본희 뒷모습에 대고 외쳤다. "언니야, 올 거지?" 본희는 멈춰 섰지만 돌아보지 않았다. <span class=''underline''>소희는 묻고 또 물었다.</span> (중략) 한참 있다가, 몇 년은 지난 거 같은데 몇 시간쯤밖에 안 지난 한밤중에 언니가 문자를 했다. 소희는 언니가 올 때까지 휴대 전화를 손에 꼭 쥐고 문자를 보고 또 보았다. 그러지 않으면 문자가 감쪽같이 날아갈 것 같았다. 삼겹살 사가지고 가께, 라면 끓여먹지 말고 기다려.', NULL, NULL, NULL, '["불안하다","흡족하다","실망스럽다","감격스럽다"]'::jsonb, 2, '불안하다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 43, '위 글의 내용과 같은 것을 고르십시오.

그때 소희네는 이사를 앞두고 있었는데 엄마는 그렇게 집을 나가 돌아 오지 않았다. 작별 인사는커녕 아무 신호도 낌새도 없이 사라졌다. (중략) 엄마가 집 나가고 열흘쯤 지났을 땐가, 소희가 텔레비전을 보고 있는데 본희가 현관에서 신을 신으며 잠깐 나갔다 오겠다고 했다. "잠깐 어디?" "친구네.” “친구 누구?" 소희가 눈을 맞추려 했지만 본희는 돌아보지 않았다. "늦으면 친구네서 자고 올지도 몰라. 기다리지 말고 자." 돌아서 나가는 본희가 멘 가방이 이상하게 커 보여 소희는 자리에서 벌떡 일어났다. 가만히 서 있다가 갑자기 현관문을 열고 맨발로 뛰어나가 계단을 올라가는 본희 뒷모습에 대고 외쳤다. "언니야, 올 거지?" 본희는 멈춰 섰지만 돌아보지 않았다. <span class=''underline''>소희는 묻고 또 물었다.</span> (중략) 한참 있다가, 몇 년은 지난 거 같은데 몇 시간쯤밖에 안 지난 한밤중에 언니가 문자를 했다. 소희는 언니가 올 때까지 휴대 전화를 손에 꼭 쥐고 문자를 보고 또 보았다. 그러지 않으면 문자가 감쪽같이 날아갈 것 같았다. 삼겹살 사가지고 가께, 라면 끓여먹지 말고 기다려.', NULL, NULL, NULL, '["본희는 밤늦게 소희에게 연락을 줬다.","엄마는 이사하는 날에 집으로 돌아왔다.","본희는 소희를 데리고 친구 집에 놀러 갔다.","소희는 엄마를 기다리며 휴대 전화를 놓지 못했다."]'::jsonb, 2, '본희는 밤늦게 소희에게 연락을 줬다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 44, '( ........................ )에 들어갈 내용으로 가장 알맞은 것을 고르십시오.

성대하고 까다로운 제사 준비 탓에 유교 예법을 비판하는 사람들이 많다. 하지만 현재 우리가 지키고 있는 예법은 ( ........................ ) 잘못된 예법이 전해져 온 것이다. 유교 전문가들은 제사든 차례든 조상을 공경하는 마음과 자손들의 화목이 중요하다고 말한다. 선조들은 제사를 드릴 때 좋은 음식을 많이 준비하는 것보다 그 음식을 준비하는 마음과 정성을 중시했던 것이다. 유서 깊은 집안에서는 이러한 제사의 본질을 제대로 이해하여 상차림은 간소하게 하되 집안사람들이 모두 모여 함께 제사를 드리는 경우가 많다. 형식보다 정성이 중요하다는 유교의 가르침을 지키고 있는 것이다.', NULL, NULL, NULL, '["상차림이 간소화된","후손들의 바람이 반영된","유교의 본뜻을 살리지 못한","현실에 맞게 축소되지 않은"]'::jsonb, 2, '현실에 맞게 축소되지 않은', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 45, '위 글의 주제로 알맞은 것을 고르십시오.

성대하고 까다로운 제사 준비 탓에 유교 예법을 비판하는 사람들이 많다. 하지만 현재 우리가 지키고 있는 예법은 ( ........................ ) 잘못된 예법이 전해져 온 것이다. 유교 전문가들은 제사든 차례든 조상을 공경하는 마음과 자손들의 화목이 중요하다고 말한다. 선조들은 제사를 드릴 때 좋은 음식을 많이 준비하는 것보다 그 음식을 준비하는 마음과 정성을 중시했던 것이다. 유서 깊은 집안에서는 이러한 제사의 본질을 제대로 이해하여 상차림은 간소하게 하되 집안사람들이 모두 모여 함께 제사를 드리는 경우가 많다. 형식보다 정성이 중요하다는 유교의 가르침을 지키고 있는 것이다.', NULL, NULL, NULL, '["조상을 모시는 제사상 차림은 점차 간소화되고 있다.","유교 문화는 후손들에 의해 유동적으로 변화되고 있다.","명절에 제사를 드리는 전통은 예법에 맞게 유지되고 있다.","유교 예법에서 중요한 것은 정성을 다해 예를 갖추는 것이다."]'::jsonb, 2, '명절에 제사를 드리는 전통은 예법에 맞게 유지되고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 46, '위 글에서 <보기>의 글이 들어가기에 가장 알맞은 곳을 고르십시오。

주어진 문장: 이와 같은 시장 형태가 전체 소비 시장에 미치는 영향력은 아직 미미하다.

1인 미디어 시대가 되면서 개인 방송을 이용한 새로운 시장 형태가 등장해 주목받고 있다. 이 시장은 SNS를 통해 제품이 유통되고 판매된다는 특징이 있다. ( ㉠ ) 대표적인 판매 방식은 1인 미디어 운영자가 방송 중에 특정 물건을 의도적으로 노출하여 구매를 유도하는 것이다. 이때 관심이 생긴 시청자는 그 운영자에게서 물건을 산다. ( ㉡ ) SNS 계정만 있으면 누구든지 판매를 시작할 수 있으며 제품 홍보부터 구매까지 모든 과정이 SNS상에서 이루어진다. ( ㉢ ) 덕분에 초기 사업 비용이 거의 들지 않는다는 장점이 있다. ( ㉣ ) 하지만 개별 사업자의 수가 무한 하게 늘 수 있기 때문에 향후 경제 변화를 이끌 핵심 시장으로의 성장이 예상된다.<br><br><strong><i>[Sentence to Insert: 이와 같은 시장 형태가 전체 소비 시장에 미치는 영향력은 아직 미미하다.]</i></strong>', NULL, NULL, NULL, '["㉠","㉡","㉢","㉣"]'::jsonb, 2, '㉣', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 47, '위 글의 내용과 같은 것을 고르십시오.

1인 미디어 시대가 되면서 개인 방송을 이용한 새로운 시장 형태가 등장해 주목받고 있다. 이 시장은 SNS를 통해 제품이 유통되고 판매된다는 특징이 있다. ( ㉠ ) 대표적인 판매 방식은 1인 미디어 운영자가 방송 중에 특정 물건을 의도적으로 노출하여 구매를 유도하는 것이다. 이때 관심이 생긴 시청자는 그 운영자에게서 물건을 산다. ( ㉡ ) SNS 계정만 있으면 누구든지 판매를 시작할 수 있으며 제품 홍보부터 구매까지 모든 과정이 SNS상에서 이루어진다. ( ㉢ ) 덕분에 초기 사업 비용이 거의 들지 않는다는 장점이 있다. ( ㉣ ) 하지만 개별 사업자의 수가 무한 하게 늘 수 있기 때문에 향후 경제 변화를 이끌 핵심 시장으로의 성장이 예상된다.<br><br><strong><i>[Sentence to Insert: 이와 같은 시장 형태가 전체 소비 시장에 미치는 영향력은 아직 미미하다.]</i></strong>', NULL, NULL, NULL, '["1인 미디어 운영자는 이 시장의 운영에 참여할 수 없다.","이 시장의 운영자들은 시장 경제에 부정적인 영향을 미친다.","1인 미디어 시청자는 방송을 보다가 제품을 구매할 수 있다.","이 시장을 처음 시작할 때는 충분한 자본 투자가 필수적이다."]'::jsonb, 2, '1인 미디어 시청자는 방송을 보다가 제품을 구매할 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 48, '위 글을 쓴 목적으로 알맞은 것을 고르십시오.

올해 ''자치경찰제''가 전국으로 확대될 예정이다. 자치경찰제는 지방자치 단체가 경찰의 운영 및 관리를 담당하도록 하는 제도를 말한다. <span class=''underline''>이 제도가 실시되면 경찰이 지역 주민의 삶에 밀착돼 지역 특성에 맞는 다양한 서비 스를 주민들에게 제공할 수 있을 것으로 보인다.</span> 그러나 제도적 취약점과 예측되는 부작용이 있을 수 있다. 무엇보다 현장에서의 혼선이 예상된다. 제도에 따르면 자치경찰은 교통사고나 가정 폭력 조사 등 생활 안전 부분을 담당하고 국가 보안이나 전국 단위의 수사는 지금처럼 국가경찰이 맡는다. 이처럼 경찰 조직이 이중 구조일 때 어려움을 겪는 것은 국민이 될 수 있다. 영역 구분이 애매한 사건이 발생하면 자치경찰과 국가경찰이 함께 출동 하거나 사건을 서로 떠넘기다가 신속하고 치밀한 대응이 이뤄지지 않을 수 있기 때문이다. ( ........................ ) 치안의 질이 떨어진다면 새 제도의 시행 의의가 퇴색될 수 있을 것이다.', NULL, NULL, NULL, '["제도 확대 시행의 의의를 강조하기 위해서","제도 시행의 구체적 방안을 제시하기 위해서","제도의 취지와 주민 요구의 차이를 설명하기 위해서","제도 시행 후 생길 수 있는 문제를 지적하기 위해서"]'::jsonb, 2, '제도 시행 후 생길 수 있는 문제를 지적하기 위해서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 49, '( ........................ )에 들어갈 내용으로 가장 알맞은 것을 고르십시오.

올해 ''자치경찰제''가 전국으로 확대될 예정이다. 자치경찰제는 지방자치 단체가 경찰의 운영 및 관리를 담당하도록 하는 제도를 말한다. <span class=''underline''>이 제도가 실시되면 경찰이 지역 주민의 삶에 밀착돼 지역 특성에 맞는 다양한 서비 스를 주민들에게 제공할 수 있을 것으로 보인다.</span> 그러나 제도적 취약점과 예측되는 부작용이 있을 수 있다. 무엇보다 현장에서의 혼선이 예상된다. 제도에 따르면 자치경찰은 교통사고나 가정 폭력 조사 등 생활 안전 부분을 담당하고 국가 보안이나 전국 단위의 수사는 지금처럼 국가경찰이 맡는다. 이처럼 경찰 조직이 이중 구조일 때 어려움을 겪는 것은 국민이 될 수 있다. 영역 구분이 애매한 사건이 발생하면 자치경찰과 국가경찰이 함께 출동 하거나 사건을 서로 떠넘기다가 신속하고 치밀한 대응이 이뤄지지 않을 수 있기 때문이다. ( ........................ ) 치안의 질이 떨어진다면 새 제도의 시행 의의가 퇴색될 수 있을 것이다.', NULL, NULL, NULL, '["경찰들의 업무 과다로","업무의 충돌과 혼선으로","자치경찰의 배치 감소로","제도의 단계적 시행으로"]'::jsonb, 2, '업무의 충돌과 혼선으로', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 64 ORDER BY created_at DESC LIMIT 1), 'reading', 50, '밑줄 친 부분에 나타난 필자의 태도로 알맞은 것을 고르십시오.

이처럼 경찰 조직이 이중 구조일 때 어려움을 겪는 것은 국민이 될 수 있다.', NULL, NULL, NULL, '["자치경찰과 지역 주민의 관계 변화에 대해 예상하고 있다.","자치경찰제가 주민에게 미칠 긍정적 영향을 기대하고 있다.","자치경찰제가 제공해야 할 서비스의 조건을 강조하고 있다.","지역 친화적 서비스가 특정 지역에 쏠릴 것을 우려하고 있다."]'::jsonb, 2, '자치경찰제가 주민에게 미칠 긍정적 영향을 기대하고 있다.', NULL);

COMMIT;
