-- Generated by scripts/generate_topik_91_sql.mjs
BEGIN;

INSERT INTO mock_test_bank (
  title, exam_type, test_number, description, total_questions, duration, listening_questions, reading_questions
)
SELECT
  'TOPIK II 91-р шалгалт',
  'TOPIK_II',
  91,
  '91-р албан ёсны TOPIK II шалгалт',
  100,
  130,
  50,
  50
WHERE NOT EXISTS (
  SELECT 1 FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91
);

UPDATE mock_test_bank
SET
  title = 'TOPIK II 91-р шалгалт',
  description = '91-р албан ёсны TOPIK II шалгалт',
  total_questions = 100,
  duration = 130,
  listening_questions = 50,
  reading_questions = 50,
  updated_at = NOW()
WHERE id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1);

DELETE FROM mock_test_questions WHERE mock_test_id = (SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1);

INSERT INTO mock_test_questions (
  mock_test_id,
  section,
  question_number,
  question_text,
  question_image_url,
  audio_url,
  option_image_urls,
  options,
  question_score,
  correct_answer_text,
  explanation
) VALUES
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 1, '다음을 듣고 가장 알맞은 그림 또는 그래프를 고르십시오.

여자: 손님, 마음에 드는 넥타이 있으세요?
남자: 제일 오른쪽에 있는 줄무늬 넥타이가 괜찮아 보이네요.
여자: 그럼 이걸로 꺼내서 보여 드릴까요?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q1_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q1_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q1_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q1_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 2, '②', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 2, '다음을 듣고 가장 알맞은 그림 또는 그래프를 고르십시오.

남자: 음, 이 사과 정말 달고 맛있네요.
여자: 그러네요. 하나 더 깎을까요?
남자: 네, 좋아요. 수미 씨는 먹고 있어요. 제가 할게요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q2_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q2_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q2_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q2_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 2, '①', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 3, '다음을 듣고 가장 알맞은 그림 또는 그래프를 고르십시오.

남자: 최근 한 조사에 따르면 성인 독서율이 계속 감소하고 있는 것으로 나타났습니다. 독서를 하지 않는 이유로는 ''일 때문에 시간이 없어서'' 라는 응답이 가장 많았고, ''책 대신 다른 매체를 이용해서'', ''책 읽는 습관이 안 들어서''가 그 뒤를 이었습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', '["https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q3_option_1.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q3_option_2.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q3_option_3.png","https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/listening/q3_option_4.png"]'::jsonb, '["①","②","③","④"]'::jsonb, 2, '③', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 4, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.

남자: 어제 요가 학원에 왜 안 나왔어?
여자: 할머니 생신이라 부모님하고 할머니 댁에 갔다 왔어.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["그래? 안 나와서 걱정했어.","무슨 학원에 다니고 있어?","그래? 할머니 댁에 언제 가?","부모님과 함께 가기로 했거든."]'::jsonb, 2, '그래? 안 나와서 걱정했어.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 5, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.

여자 : 우리가 둘러본 가게들 중에 어느 가게의 소파가 괜찮았어요?
남자: 저는 처음에 갔던 가게의 소파들이 제일 나은 것 같아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["그럼 거기로 다시 가 볼까요?","아직 한 곳밖에 안 가 봤는데요.","그럼 이 소파를 사는 게 어때요?","집 근처에 있는 소파 가게에서 샀어요."]'::jsonb, 2, '그럼 거기로 다시 가 볼까요?', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 6, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.

남자: 수미야, 오늘 면접 있지? 면접 잘 봐.
여자: 어쩌지? 벌써부터 너무 떨려서 아무 생각이 안 나.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["면접 날짜를 다시 확인하고 알려 줘.","준비 많이 했으니까 잘할 수 있을 거야.","면접 보기 전인데 안 떨린다니 대단하다.","생각하지 못한 질문을 받아서 정말 놀랐겠네."]'::jsonb, 2, '준비 많이 했으니까 잘할 수 있을 거야.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 7, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.

남자: 이 드라마 처음 보는데 내용도 좋고 대사도 재미있네요.
여자: 그렇죠? 이 드라마 쓴 작가의 작품들은 다 재미있어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["맞아요. 이전 작품은 내용이 별로였어요.","그래요? 이 드라마 다 보면 다른 작품도 봐야겠어요.","맞아요. 이 드라마는 몇 번을 다시 봐도 재미있네요.","그래요? 이 작가가 처음으로 쓴 작품인 줄 몰랐어요."]'::jsonb, 2, '그래요? 이 드라마 다 보면 다른 작품도 봐야겠어요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 8, '다음을 듣고 이어질 수 있는 말로 가장 알맞은 것을 고르십시오.

여자: 손님, 운동화에 얼룩이 많네요. 생긴 지 꽤 오래된 거 같은데요.
남자: 네. 제가 집에서 해 봤는데 안 지워지더라고요. 깨끗하게 될까요?', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["얼룩이 잘 지워진 것 같아요.","운동화를 깨끗하게 신으셨네요.","해 봐야 알겠지만 최대한 없애 볼게요.","집에 돌아가서 다시 한번 지워 보려고요."]'::jsonb, 2, '해 봐야 알겠지만 최대한 없애 볼게요.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 9, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.

여자: 기차 탈 때까지 시간이 좀 남았네.
남자: 그러네. 저 카페에서 커피 한잔 마시자.
여자: 응. 난 기차에서 먹을 김밥 좀 사서 갈 테니까 먼저 들어가 있어.
남자: 알았어. 카페에 앉아 있을게.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["김밥을 산다.","기차를 탄다.","자리에 앉는다.","카페로 들어간다."]'::jsonb, 2, '김밥을 산다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 10, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.

여자: 자동차 수리하러 왔는데요. 김수미로 예약했어요.
남자: 네. 차 열쇠 주시고 고객 대기실에서 잠깐 기다려 주세요.
여자: 열쇠는 차 안에 두었어요. 대기실은 이쪽으로 가면 되나요?
남자: 네. 자동차 상태 확인하고 말씀드리겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["고객 대기실로 간다.","남자에게 열쇠를 준다.","차의 상태를 확인한다.","차를 수리하려고 예약한다."]'::jsonb, 2, '고객 대기실로 간다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 11, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.

남자: 수미 씨, 미술 연필은 골랐어요. 더 살게 있어요?
여자: 물감을 사야 하는데 찾는 게 안 보이네요.
남자: 제품 이름 알려 줘요. 직원한테 그 제품이 있는지 물어볼게요.
여자: 아니에요. 제가 물어보고 올 테니까 민수 씨는 여기에서 기다려요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["물감을 찾아본다.","미술 연필을 고른다.","직원에게 물어본다.","남자에게 제품 이름을 말한다."]'::jsonb, 2, '직원에게 물어본다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 12, '다음을 듣고 여자가 이어서 할 행동으로 가장 알맞은 것을 고르십시오.

여자: 무대 점검 끝났습니다. 이제 무대 연습 진행할까요?
남자: 네. 지금 무대 앞으로 공연팀들을 데리고 와 줄래요? 연습 전에 진행 순서 설명하게요.
여자: 알겠습니다. 촬영팀한테 연습 시작할 거라고 연락할까요?
남자: 그건 제가 할게요. 얼른 다녀오세요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["촬영팀에게 연락한다.","진행 순서를 설명한다.","공연 무대를 점검한다.","공연팀을 데리러 간다."]'::jsonb, 2, '공연팀을 데리러 간다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 13, '다음을 듣고 들은 내용과 같은 것을 고르십시오.

여자: 와, 10년 만에 와 보니까 여기 많이 변했다.
남자: 응. 내가 알던 곳이 아닌 것 같아. 길도 넓어지고 가게도 많아지고.
여자: 그러네. 어, 그런데 저기 인주서점은 아직도 그대로 있어.
남자: 정말이네. 우리 대학 다닐 때 전공 책 사러 자주 갔었잖아.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["길이 예전에 비해 좁아졌다.","여자는 이곳에 처음 와 봤다.","남자는 인주서점에 간 적이 없다.","인주서점은 지금까지 같은 자리에 있다."]'::jsonb, 2, '인주서점은 지금까지 같은 자리에 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 14, '다음을 듣고 들은 내용과 같은 것을 고르십시오.

여자: (딩동댕) 안내 말씀드립니다. 고객 센터에서 빨간색 지갑을 보관하고 있습니다. 지갑은 조금 전에 1층 구두 매장에서 발견되었습니다. 잠시 후 여덟 시에 백화점이 문을 닫으니 지갑을 분실하신 고객님께서는 그 전에 5층에 있는 고객 센터로 와 주시기 바랍니다. (댕동딩)', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["분실물은 구두 매장에 있었다.","오후 8시에 지갑이 발견되었다.","고객 센터는 구두 매장 옆에 있다.","지갑을 잃어버린 사람은 1층으로 가면 된다."]'::jsonb, 2, '분실물은 구두 매장에 있었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 15, '다음을 듣고 들은 내용과 같은 것을 고르십시오.

남자: 오늘 새벽 네 시경, 인주 앞바다에서 낚싯배가 바위에 부딪치는 사고가 발생했습니다. 배에 타고 있던 사람들은 경찰에 의해 모두 구조되었고 다행히 다친 사람은 없었습니다. 현재 경찰은 배에 타고 있던 사람들을 상대로 정확한 사고 원인을 파악하고 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 사고는 어젯밤에 발생했다.","이 사고로 인해 사람들이 크게 다쳤다.","경찰은 사고 원인에 대해 조사하고 있다.","낚싯배가 다른 배와 충돌하는 사고가 났다."]'::jsonb, 2, '경찰은 사고 원인에 대해 조사하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 16, '다음을 듣고 들은 내용과 같은 것을 고르십시오.

남자: 동물보건사라는 직업을 모르는 분들이 많은데요. 어떤 일을 하시나요?
여자: 저는 동물 병원에서 아픈 동물을 돌보는 일을 하는데요. 동물의 상태도 살피고 수의사의 처방에 따라 약도 줍니다. 또 수의사가 진찰을 하거나 수술할 때 옆에서 돕는 일도 하죠. 그리고 보호자가 동물을 집에서 돌볼 때 주의할 사항을 알려 드리기도 합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["여자는 수술 과정에 참여한다.","여자는 보호자의 집에서 동물을 돌본다.","여자의 직업은 사람들에게 잘 알려져 있다.","동물의 상태를 관찰하는 일은 여자의 업무가 아니다."]'::jsonb, 2, '여자는 수술 과정에 참여한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 17, '다음을 듣고 남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

남자: 피곤한데 오늘 저녁은 밖에서 먹고 들어가요.
여자: 그냥 집에 가서 먹어요. 식사 준비하는 데 얼마 안 걸리잖아요.
남자: 피곤해서 집에 갈 힘도 없어요. 이럴 땐 그냥 밖에서 사 먹어요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["저녁 식사를 미리 준비해 두어야 한다.","음식을 한꺼번에 많이 먹지 않는 것이 좋다.","건강을 위해서 식사를 규칙적으로 해야 한다.","피곤할 때는 저녁을 밖에서 사 먹는 것이 좋다."]'::jsonb, 2, '피곤할 때는 저녁을 밖에서 사 먹는 것이 좋다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 18, '다음을 듣고 남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

남자: 민수가 여자 친구랑 헤어져서 힘든가 봐. 우리 만나서 위로해 주자.
여자: 정말? 근데 그럴 때는 혼자 있게 해 주는 게 좋지 않을까?
남자: 지금이 바로 우리가 같이 있어 줘야 할 때지. 그것만으로도 큰 힘이 될 거야.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["친구가 힘들 때는 옆에 있어 줘야 한다.","여러 사람과 잘 지내기 위해 노력할 필요가 있다.","다른 사람과 함께 있을 때는 말을 조심해야 한다.","친구와 문제가 생겼을 때는 빨리 해결하는 것이 좋다."]'::jsonb, 2, '친구가 힘들 때는 옆에 있어 줘야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 19, '다음을 듣고 남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

여자: 오늘 여행 일정이 많아서 서둘러야 해요. 먼저 박물관에 갔다가 미술관에 가요. 그다음에 근처 유적지 둘러보고 연극 보러 가면 돼요.
남자: 일정이 너무 많아요. 전 좀 여유롭게 여행하고 싶어요.
여자: 모처럼 여행 왔는데 뭐든 많이 하면 좋잖아요.
남자: 그래도 시간을 갖고 천천히 보면 좋겠어요. 일정을 좀 줄이죠.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["여행은 여유롭게 하는 것이 좋다.","여행을 자주 가는 것은 좋지 않다.","여행에서 다양한 경험을 해 봐야 한다.","여행에 필요한 예산을 정해 놓을 필요가 있다."]'::jsonb, 2, '여행은 여유롭게 하는 것이 좋다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 20, '다음을 듣고 남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

여자: 감독님은 광고를 만들 때 어떤 부분에 신경을 쓰시나요?
남자: 대부분의 광고는 제품의 장점을 드러내는 데 집중하는데요. 저는 호기심을 자극하는 것에 중점을 둡니다. 그러기 위해 사람들이 지금 보고 있는 게 무엇을 광고하는 것인지 끝까지 봐야 알 수 있도록 숨기는 거죠. 이렇게 대중의 궁금증을 유발하는 겁니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["광고를 짧게 만드는 것이 효과적이다.","광고는 대중의 호기심을 자극해야 한다.","광고는 제품의 정보를 사실대로 전달해야 한다.","광고는 보는 사람이 쉽게 이해할 수 있어야 한다."]'::jsonb, 2, '광고는 대중의 호기심을 자극해야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 21, '남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

여자: 부장님, 회의 때 사용할 발표 자료는 복사해서 회의실에 갖다 놓았습니다. 참고할 다른 자료도 복사할까요?
남자: 그건 참석자들에게 미리 이메일로 보내죠. 회의 때마다 낭비되는 종이가 너무 많은 것 같아요.
여자: 네, 바로 보내겠습니다. 지난번 회의처럼 대형 화면을 사용하실 거지요?
남자: 네. 그리고 앞으로는 발표 자료도 필요한 경우에만 복사하죠. 어차피 회의는 화면을 보면서 하는데 굳이 종이를 사용할 필요 없잖아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["회의 내용을 빠짐없이 기록해야 한다.","회의 때 낭비되는 종이를 줄이는 것이 좋다.","회의실을 지금보다 더 큰 장소로 바꿔야 한다.","발표 자료는 알아보기 쉽게 만드는 것이 좋다."]'::jsonb, 2, '회의 때 낭비되는 종이를 줄이는 것이 좋다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 22, '들은 내용과 같은 것을 고르십시오.

여자: 부장님, 회의 때 사용할 발표 자료는 복사해서 회의실에 갖다 놓았습니다. 참고할 다른 자료도 복사할까요?
남자: 그건 참석자들에게 미리 이메일로 보내죠. 회의 때마다 낭비되는 종이가 너무 많은 것 같아요.
여자: 네, 바로 보내겠습니다. 지난번 회의처럼 대형 화면을 사용하실 거지요?
남자: 네. 그리고 앞으로는 발표 자료도 필요한 경우에만 복사하죠. 어차피 회의는 화면을 보면서 하는데 굳이 종이를 사용할 필요 없잖아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이번 회의는 발표 자료 없이 진행된다.","여자는 회의에서 쓸 자료를 복사할 예정이다.","남자는 회의 때 대형 화면을 사용한 적이 있다.","여자는 참석자들에게 참고할 자료를 이미 이메일로 보내 놓았다."]'::jsonb, 2, '남자는 회의 때 대형 화면을 사용한 적이 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 23, '남자가 무엇을 하고 있는지 고르십시오.

남자: 카페에서 케이크 보관용으로 사용할 냉장고를 찾고 있는데요. 사용 기간이 얼마 안 된 중고 냉장고 있을까요?
여자: 손님들이 케이크를 보고 살 수 있게 유리문이 달린 걸 찾으시는 거지요?
남자: 아니요. 그건 이미 설치돼 있어요. 주방에서 쓸 거라서 안이 안 보여도 돼요. 케이크를 많이 넣을 수 있게 사이즈가 컸으면 좋겠어요.
여자: 이거 어떠세요? 저희 가게에 어제 들어온 제품인데요. 크기도 크고 6개월 정도 사용한 거라서 깨끗하고 좋아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["가게의 위치를 확인하고 있다.","가게 운영에 대해 조언을 구하고 있다.","구매할 물건의 사용 방법을 물어보고 있다.","원하는 조건의 물건이 있는지 알아보고 있다."]'::jsonb, 2, '원하는 조건의 물건이 있는지 알아보고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 24, '들은 내용과 같은 것을 고르십시오.

남자: 카페에서 케이크 보관용으로 사용할 냉장고를 찾고 있는데요. 사용 기간이 얼마 안 된 중고 냉장고 있을까요?
여자: 손님들이 케이크를 보고 살 수 있게 유리문이 달린 걸 찾으시는 거지요?
남자: 아니요. 그건 이미 설치돼 있어요. 주방에서 쓸 거라서 안이 안 보여도 돼요. 케이크를 많이 넣을 수 있게 사이즈가 컸으면 좋겠어요.
여자: 이거 어떠세요? 저희 가게에 어제 들어온 제품인데요. 크기도 크고 6개월 정도 사용한 거라서 깨끗하고 좋아요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["여자의 가게에는 크기가 큰 냉장고가 없다.","남자는 카페에서 케이크를 팔지 않기로 했다.","남자의 카페에는 유리문이 달린 냉장고가 있다.","여자의 가게에서는 새로 나온 제품만 판매한다."]'::jsonb, 2, '남자의 카페에는 유리문이 달린 냉장고가 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 25, '남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

여자: 올해로 3주년을 맞은 해바라기 축제에 정말 많은 분들이 찾아오고 있는데요. 어떻게 이렇게 성공할 수 있었나요?
남자: 마을의 장점을 살린 것이 좋은 결과로 이어졌다고 생각합니다. 우리 마을의 넓고 아름다운 해바라기 들판은 오래전부터 마을의 자랑이었는데요. 이런 특색을 활용해서 축제를 기획한 것이 관광객의 발길을 이끌었죠. 축제 기간에 특산품도 파는데요. 특히 해바라기 씨로 만든 기름이 관광객들에게 인기가 좋습니다. 앞으로도 우리 마을이 가진 것을 잘 활용해서 이 축제를 더욱 발전시키려고 합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["마을 축제에 대한 주민들의 관심이 필요하다.","마을의 특징을 활용한 것이 축제의 성공 비결이다.","축제에서 판매할 기념품을 새로 제작하는 것이 좋다.","축제를 기획할 때 성공 사례를 충분히 검토해야 한다."]'::jsonb, 2, '마을의 특징을 활용한 것이 축제의 성공 비결이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 26, '들은 내용과 같은 것을 고르십시오.

여자: 올해로 3주년을 맞은 해바라기 축제에 정말 많은 분들이 찾아오고 있는데요. 어떻게 이렇게 성공할 수 있었나요?
남자: 마을의 장점을 살린 것이 좋은 결과로 이어졌다고 생각합니다. 우리 마을의 넓고 아름다운 해바라기 들판은 오래전부터 마을의 자랑이었는데요. 이런 특색을 활용해서 축제를 기획한 것이 관광객의 발길을 이끌었죠. 축제 기간에 특산품도 파는데요. 특히 해바라기 씨로 만든 기름이 관광객들에게 인기가 좋습니다. 앞으로도 우리 마을이 가진 것을 잘 활용해서 이 축제를 더욱 발전시키려고 합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 마을을 아는 사람이 거의 없다.","이 마을에서 축제가 올해 처음으로 열렸다.","이 마을의 해바라기 들판은 최근에 만들어졌다.","이 마을의 특산품이 관광객에게 좋은 반응을 얻었다."]'::jsonb, 2, '이 마을의 특산품이 관광객에게 좋은 반응을 얻었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 27, '남자가 말하는 의도로 알맞은 것을 고르십시오.

남자: 인주제과에서 새로 나온 과자 말이야. 맛있다고 해서 한번 먹어 보고 싶은데 살 수가 없네. 여기저기 다 품절이래.
여자: 뉴스에서 들었는데 평소보다 네 시간이나 더 작업해서 생산량을 두 배나 늘렸대. 그런데도 수요가 많아서 구하기 힘든 거래.
남자: 그래도 이렇게까지 사기 어려운 게 말이 돼? 과자를 사려고 하는 사람이 많으면 생산 시설을 더 늘리면 되잖아.
여자: 그런 결정은 쉽지 않지. 그랬다가 과자의 인기가 식으면 비용을 들여 만든 시설이 쓸모없어지잖아. 그럼 회사의 손해가 클걸.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 과자의 맛이 달라진 것을 지적하려고","이 과자를 생산하게 된 이유를 알려 주려고","이 과자의 생산이 중단될 것이라는 소식을 전하려고","이 과자를 구하기 어려운 것에 대한 불만을 말하려고"]'::jsonb, 2, '이 과자를 구하기 어려운 것에 대한 불만을 말하려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 28, '들은 내용과 같은 것을 고르십시오.

남자: 인주제과에서 새로 나온 과자 말이야. 맛있다고 해서 한번 먹어 보고 싶은데 살 수가 없네. 여기저기 다 품절이래.
여자: 뉴스에서 들었는데 평소보다 네 시간이나 더 작업해서 생산량을 두 배나 늘렸대. 그런데도 수요가 많아서 구하기 힘든 거래.
남자: 그래도 이렇게까지 사기 어려운 게 말이 돼? 과자를 사려고 하는 사람이 많으면 생산 시설을 더 늘리면 되잖아.
여자: 그런 결정은 쉽지 않지. 그랬다가 과자의 인기가 식으면 비용을 들여 만든 시설이 쓸모없어지잖아. 그럼 회사의 손해가 클걸.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 회사는 작업 시간을 늘렸다.","남자는 이 과자를 구입한 적이 있다.","이 과자는 사람들의 관심을 끌지 못했다.","여자는 남자에게 이 과자에 대해 처음 들었다."]'::jsonb, 2, '이 회사는 작업 시간을 늘렸다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 29, '남자가 누구인지 고르십시오.

여자: 지금 하시는 일이 보통의 라디오 방송과 준비 과정이 다르다고요?
남자: 네. 저는 매일 오전 여섯 시부터 오후 두 시까지, 30분마다 교통 정보를 안내하고 있는데요. 도로에 설치된 여러 대의 CCTV와 시민들이 보낸 문자를 보고 교통 상황을 분석해 시민들에게 전달합니다.
여자: 방송 중에도 도로 상황은 수시로 달라질 텐데요. 방송 내용을 미리 준비하기가 어려울 것 같습니다.
남자: 네. 미리 원고를 작성하기는 하지만 실시간 교통 상황을 보며 원고에 없는 내용을 전달할 때가 많습니다. 그래서 긴장을 늦출 수 없죠.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["도로를 정비하는 사람","교통 상황을 촬영하는 사람","도로에 CCTV를 설치하는 사람","방송에서 교통 상황을 알려 주는 사람"]'::jsonb, 2, '방송에서 교통 상황을 알려 주는 사람', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 30, '들은 내용과 같은 것을 고르십시오.

여자: 지금 하시는 일이 보통의 라디오 방송과 준비 과정이 다르다고요?
남자: 네. 저는 매일 오전 여섯 시부터 오후 두 시까지, 30분마다 교통 정보를 안내하고 있는데요. 도로에 설치된 여러 대의 CCTV와 시민들이 보낸 문자를 보고 교통 상황을 분석해 시민들에게 전달합니다.
여자: 방송 중에도 도로 상황은 수시로 달라질 텐데요. 방송 내용을 미리 준비하기가 어려울 것 같습니다.
남자: 네. 미리 원고를 작성하기는 하지만 실시간 교통 상황을 보며 원고에 없는 내용을 전달할 때가 많습니다. 그래서 긴장을 늦출 수 없죠.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["남자는 매일 오후에 근무를 시작한다.","남자는 이 일을 할 때 긴장하지 않는다.","남자는 CCTV를 분석하는 일을 하지 않는다.","남자의 일에는 시민들이 보낸 문자를 보는 것이 포함된다."]'::jsonb, 2, '남자의 일에는 시민들이 보낸 문자를 보는 것이 포함된다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 31, '남자의 중심 생각으로 가장 알맞은 것을 고르십시오.

여자: 우리 지역에 생활 폐기물 처리 시설이 설치되는 것이 확정되면 시설의 안전성 문제로 주민들의 반발이 거셀 텐데요.
남자: 지속적으로 주민 설명회를 열어 시설의 안전성에 대해 충분히 설명하고 이미 안전성이 확인된 인주시의 사례를 적극적으로 알리면 우려하는 부분은 곧 해결될 겁니다.
여자: 그래도 우리 지역에는 안 된다는 인식을 바꾸기는 어려울 겁니다.
남자: 지역 광고도 하고 수영장 같은 여가 시설이 보상으로 제공된다는 사실도 대대적으로 알리면 주민들의 인식도 분명히 바뀔 겁니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["시설을 다른 지역으로 옮겨서 설치해야 한다.","시설의 설치 효과에 대한 명확한 검증이 필요하다.","시설 설치에 대한 반대는 홍보를 통해 해결할 수 있다.","시설의 설치 사실을 주민들에게 바로 알리지 않는 것이 좋다."]'::jsonb, 2, '시설 설치에 대한 반대는 홍보를 통해 해결할 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 32, '남자의 태도로 가장 알맞은 것을 고르십시오.

여자: 우리 지역에 생활 폐기물 처리 시설이 설치되는 것이 확정되면 시설의 안전성 문제로 주민들의 반발이 거셀 텐데요.
남자: 지속적으로 주민 설명회를 열어 시설의 안전성에 대해 충분히 설명하고 이미 안전성이 확인된 인주시의 사례를 적극적으로 알리면 우려하는 부분은 곧 해결될 겁니다.
여자: 그래도 우리 지역에는 안 된다는 인식을 바꾸기는 어려울 겁니다.
남자: 지역 광고도 하고 수영장 같은 여가 시설이 보상으로 제공된다는 사실도 대대적으로 알리면 주민들의 인식도 분명히 바뀔 겁니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["앞으로 일어날 문제에 대해 걱정하고 있다.","자신의 의견대로 될 것임을 확신하고 있다.","상대방에게 객관적인 근거를 요구하고 있다.","상황이 심각해진 것에 대한 책임을 묻고 있다."]'::jsonb, 2, '자신의 의견대로 될 것임을 확신하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 33, '무엇에 대한 내용인지 알맞은 것을 고르십시오.

여자: 한 연구팀이 노화로 인해 인지 기능이 떨어지는 것을 막는 데 음악 활동이 도움이 될 거라는 가설을 세우고 실험을 진행했습니다. 연구팀은 음악을 전문적으로 배운 적이 없는 노인들을 대상으로 6개월간 실험했는데요. 이 기간에 한 집단은 피아노를 배우게 했고, 다른 집단은 음악 활동을 못 하게 통제했습니다. 그 결과 음악 활동을 통제한 집단은 인지 기능의 저하가 진행된 데 비해 피아노를 배운 집단은 인지 기능이 떨어지지 않았습니다. 연구팀의 예상대로 음악 활동이 인지 기능의 저하를 막는 데 긍정적으로 작용한 거죠.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["음악을 감상하는 올바른 방법","음악적 재능이 발달하는 결정적 시기","노인을 대상으로 하는 연구에서 주의할 점","음악 활동이 노인의 인지 기능에 미치는 영향"]'::jsonb, 2, '음악 활동이 노인의 인지 기능에 미치는 영향', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 34, '들은 내용과 같은 것을 고르십시오.

여자: 한 연구팀이 노화로 인해 인지 기능이 떨어지는 것을 막는 데 음악 활동이 도움이 될 거라는 가설을 세우고 실험을 진행했습니다. 연구팀은 음악을 전문적으로 배운 적이 없는 노인들을 대상으로 6개월간 실험했는데요. 이 기간에 한 집단은 피아노를 배우게 했고, 다른 집단은 음악 활동을 못 하게 통제했습니다. 그 결과 음악 활동을 통제한 집단은 인지 기능의 저하가 진행된 데 비해 피아노를 배운 집단은 인지 기능이 떨어지지 않았습니다. 연구팀의 예상대로 음악 활동이 인지 기능의 저하를 막는 데 긍정적으로 작용한 거죠.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 연구를 위한 실험은 1년 동안 진행됐다.","이 실험의 결과는 연구팀의 예상과 같았다.","이 실험에서 두 집단은 동일한 결과를 보였다.","이 실험은 음악을 전공한 사람들을 대상으로 했다."]'::jsonb, 2, '이 실험의 결과는 연구팀의 예상과 같았다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 35, '남자가 무엇을 하고 있는지 고르십시오.

남자: 오늘은 우리 박물관에 전시되어 있는 한 통의 편지가 국가 보물로 지정된 뜻깊은 날입니다. 이 편지는 조선 초기 한 군인이 아내에게 보낸 것인데요. 가족을 잘 보살펴 달라는 당부와 입을 옷을 몇 벌 보내 달라고 부탁하는 내용이 한글로 쓰여 있습니다. 평범한 사람이 쓴 일상적인 내용의 편지지만 학술적, 역사적 가치는 매우 큽니다. 조선 초기에 사용된 호칭과 높임말 같은 언어생활을 비롯해 당시 사람들의 생활상과 복식 문화 등을 알 수 있기 때문입니다. 앞으로 이 편지가 다양한 연구에 활용되길 기대합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 편지가 가지는 가치와 의의를 알리고 있다.","이 편지의 보존 상태에 대해 아쉬움을 표하고 있다.","이 편지가 발견된 장소와 발굴 과정을 보고하고 있다.","이 편지를 연구하는 데 도움을 준 사람들에게 감사하고 있다."]'::jsonb, 2, '이 편지가 가지는 가치와 의의를 알리고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 36, '들은 내용과 같은 것을 고르십시오.

남자: 오늘은 우리 박물관에 전시되어 있는 한 통의 편지가 국가 보물로 지정된 뜻깊은 날입니다. 이 편지는 조선 초기 한 군인이 아내에게 보낸 것인데요. 가족을 잘 보살펴 달라는 당부와 입을 옷을 몇 벌 보내 달라고 부탁하는 내용이 한글로 쓰여 있습니다. 평범한 사람이 쓴 일상적인 내용의 편지지만 학술적, 역사적 가치는 매우 큽니다. 조선 초기에 사용된 호칭과 높임말 같은 언어생활을 비롯해 당시 사람들의 생활상과 복식 문화 등을 알 수 있기 때문입니다. 앞으로 이 편지가 다양한 연구에 활용되길 기대합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 편지는 곧 박물관에 전시될 것이다.","이 편지는 군인인 남편이 아내에게 쓴 것이다.","이 편지가 어느 시대의 것인지 밝혀지지 않았다.","이 편지를 보물로 지정하기 위한 논의가 진행 중이다."]'::jsonb, 2, '이 편지는 군인인 남편이 아내에게 쓴 것이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 37, '여자의 중심 생각으로 가장 알맞은 것을 고르십시오.

남자: 교수님, 한국의 산에는 30년 이상 된 오래된 나무가 많다고 하는데요. 어떻게 관리되어야 할까요?
여자: 네, 그런 나무가 72%나 되는데요. 그러다 보니 나무의 고령화로 인해 산림의 탄소 흡수량과 저장량이 줄어들고 있는 상황입니다. 나무가 30년 이상 되면 탄소를 흡수하고 저장하는 능력이 현저히 떨어지기 때문이죠. 그래서 오래된 나무를 베어 내고 어린나무를 심는 방식의 산림 순환 경영을 도입해 관리해야 합니다. 산림 순환 경영을 도입하면 목재 활용 면에서도 유용한데요. 한국은 목재 수입 비중이 상당히 높은데 산림을 순환시키면 목재 수입량을 크게 줄일 수 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["목재를 수출하기 위한 경로를 확보해야 한다.","산림 순환 경영을 통해 좋은 효과를 얻을 수 있다.","좋은 목재를 얻을 수 있는 나무를 심는 것이 좋다.","산림 순환 경영이 정착될 때까지 시간이 필요하다."]'::jsonb, 2, '산림 순환 경영을 통해 좋은 효과를 얻을 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 38, '들은 내용과 같은 것을 고르십시오.

남자: 교수님, 한국의 산에는 30년 이상 된 오래된 나무가 많다고 하는데요. 어떻게 관리되어야 할까요?
여자: 네, 그런 나무가 72%나 되는데요. 그러다 보니 나무의 고령화로 인해 산림의 탄소 흡수량과 저장량이 줄어들고 있는 상황입니다. 나무가 30년 이상 되면 탄소를 흡수하고 저장하는 능력이 현저히 떨어지기 때문이죠. 그래서 오래된 나무를 베어 내고 어린나무를 심는 방식의 산림 순환 경영을 도입해 관리해야 합니다. 산림 순환 경영을 도입하면 목재 활용 면에서도 유용한데요. 한국은 목재 수입 비중이 상당히 높은데 산림을 순환시키면 목재 수입량을 크게 줄일 수 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["한국은 목재 수입 비중이 낮은 편이다.","한국은 산림 순환 경영을 시행하고 있다.","나무가 30년 이상 되면 탄소 흡수 능력이 떨어진다.","한국의 산에는 심은 지 얼마 안 된 어린나무가 많다."]'::jsonb, 2, '나무가 30년 이상 되면 탄소 흡수 능력이 떨어진다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 39, '이 대화 전의 내용으로 가장 알맞은 것을 고르십시오.

여자: 박사님, 대기권에서 그런 위험한 사고가 발생했었군요. 앞으로 인공위성이 더 많아지면 이로 인한 사고도 늘어날 텐데요.
남자: 네. 앞으로 더 많은 인공위성이 쏘아 올려지면 앞서 말씀드린 것과 같은 폭발 사고는 더 많아질 겁니다. 충돌 사고, 전파 방해 같은 사고도 일어날 수 있고요. 이런 걸 대비해 오래전에 만들어 놓은 우주 조약이 있긴 한데요. 문제는 내용이 구체적이지 않고 꼭 지켜야 한다는 강제성이 없다는 거죠. 앞으로 발생할 수 있는 여러 문제를 해결하기 위해서라도 우주 조약을 현실에 맞게 개정하고 보완해야 합니다. 나아가서는 법적 효력을 갖는 국제 우주법을 제정해야 하고요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["인공위성을 관측하는 신기술이 개발되었다.","대기권에서 인공위성이 폭발하는 사고가 있었다.","우주 조약을 개정하기 위해 여러 나라 사람들이 모였다.","우주 탐사를 위한 인력을 양성하는 것은 쉬운 일이 아니다."]'::jsonb, 2, '대기권에서 인공위성이 폭발하는 사고가 있었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 40, '들은 내용과 같은 것을 고르십시오.

여자: 박사님, 대기권에서 그런 위험한 사고가 발생했었군요. 앞으로 인공위성이 더 많아지면 이로 인한 사고도 늘어날 텐데요.
남자: 네. 앞으로 더 많은 인공위성이 쏘아 올려지면 앞서 말씀드린 것과 같은 폭발 사고는 더 많아질 겁니다. 충돌 사고, 전파 방해 같은 사고도 일어날 수 있고요. 이런 걸 대비해 오래전에 만들어 놓은 우주 조약이 있긴 한데요. 문제는 내용이 구체적이지 않고 꼭 지켜야 한다는 강제성이 없다는 거죠. 앞으로 발생할 수 있는 여러 문제를 해결하기 위해서라도 우주 조약을 현실에 맞게 개정하고 보완해야 합니다. 나아가서는 법적 효력을 갖는 국제 우주법을 제정해야 하고요.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["얼마 전에 국제 우주법이 제정되었다.","우주 조약은 구체적인 내용으로 구성되어 있다.","우주 조약은 강제적인 효력을 가지고 있지 않다.","인공위성으로 인한 전파 방해 문제는 일어나지 않을 것이다."]'::jsonb, 2, '우주 조약은 강제적인 효력을 가지고 있지 않다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 41, '이 강연의 중심 내용으로 가장 알맞은 것을 고르십시오.

여자: 제조업체들이 서비스업을 병행하며 사업 영역을 확장해 나가고 있습니다. 즉, 고객에게 직접 서비스를 제공하면서 변화를 도모하고 있는 건데요. 선박 엔진을 생산하는 한 업체를 예로 들어 볼까요? 조선업계 경기가 살아나면서 엔진 판매가 활발해졌는데요. 이 업체는 엔진 판매와 함께 엔진 상태를 실시간으로 점검해 주는 서비스 사업도 하고 있습니다. 서비스 시스템 구축에 많은 비용이 들어갔지만 이 서비스가 부품 판매와 수리 작업으로 이어져 안정적인 수입원이 되고 있죠. 이러한 방식을 통해 제조업이 한 단계 진화하고 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["제품의 품질은 부품의 질에 의해 결정된다.","제조업은 일자리 창출에 크게 기여하고 있다.","제품에 대한 고객의 의견을 반영하는 것이 중요하다.","제조업은 사업 영역 확장을 통해 발전을 도모하고 있다."]'::jsonb, 2, '제조업은 사업 영역 확장을 통해 발전을 도모하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 42, '들은 내용과 같은 것을 고르십시오.

여자: 제조업체들이 서비스업을 병행하며 사업 영역을 확장해 나가고 있습니다. 즉, 고객에게 직접 서비스를 제공하면서 변화를 도모하고 있는 건데요. 선박 엔진을 생산하는 한 업체를 예로 들어 볼까요? 조선업계 경기가 살아나면서 엔진 판매가 활발해졌는데요. 이 업체는 엔진 판매와 함께 엔진 상태를 실시간으로 점검해 주는 서비스 사업도 하고 있습니다. 서비스 시스템 구축에 많은 비용이 들어갔지만 이 서비스가 부품 판매와 수리 작업으로 이어져 안정적인 수입원이 되고 있죠. 이러한 방식을 통해 제조업이 한 단계 진화하고 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 업체는 엔진 판매에 어려움을 겪고 있다.","조선업이 경제적으로 힘든 상황에 놓여 있다.","이 업체는 안정적인 수입을 얻지 못하고 있다.","이 업체는 실시간 엔진 점검 서비스 시스템을 마련했다."]'::jsonb, 2, '이 업체는 실시간 엔진 점검 서비스 시스템을 마련했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 43, '무엇에 대한 내용인지 알맞은 것을 고르십시오.

남자: 서울 도심 한가운데, 다른 세상 같은 공간이 존재한다. 조선의 역대 왕과 왕비의 제사를 모시는 종묘의 정전이다. 낮은 담장을 지나 정전을 정면으로 마주한 순간 크기와 위엄에 압도된다. 그중 단연 눈에 띄는 것은 지붕이다. 가로길이만 101미터다. 수평선처럼 일직선으로 길게 뻗은 지붕은 마치 바닥까지 덮을 듯 아래로 내려와 있다. 좌우가 완벽하게 대칭을 이룬 모습에 감탄이 절로 나온다. 지붕 아래엔 화려한 색깔 하나 없는 단아한 기둥들이 절묘한 균형을 이루며 줄지어 서 있다. 이렇듯 종묘 정전은 제사를 드리는 엄숙한 곳답게 절제된 아름다움으로 신성하고 장엄한 분위기를 자아낸다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["종묘 정전의 건축미","종묘 정전의 건립 과정","종묘 정전의 관리 방법","종묘 정전의 현대적 기능"]'::jsonb, 2, '종묘 정전의 건축미', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 44, '종묘 정전에 대한 설명으로 맞는 것을 고르십시오.

남자: 서울 도심 한가운데, 다른 세상 같은 공간이 존재한다. 조선의 역대 왕과 왕비의 제사를 모시는 종묘의 정전이다. 낮은 담장을 지나 정전을 정면으로 마주한 순간 크기와 위엄에 압도된다. 그중 단연 눈에 띄는 것은 지붕이다. 가로길이만 101미터다. 수평선처럼 일직선으로 길게 뻗은 지붕은 마치 바닥까지 덮을 듯 아래로 내려와 있다. 좌우가 완벽하게 대칭을 이룬 모습에 감탄이 절로 나온다. 지붕 아래엔 화려한 색깔 하나 없는 단아한 기둥들이 절묘한 균형을 이루며 줄지어 서 있다. 이렇듯 종묘 정전은 제사를 드리는 엄숙한 곳답게 절제된 아름다움으로 신성하고 장엄한 분위기를 자아낸다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["지붕이 곡선 형태로 휘어 있다.","기둥에 화려한 색이 사용되었다.","도심에서 멀리 떨어진 곳에 있다.","왕과 왕비의 제사를 지내는 공간이다."]'::jsonb, 2, '왕과 왕비의 제사를 지내는 공간이다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 45, '들은 내용과 같은 것을 고르십시오.

여자: 여기 오른쪽 아랫배, 대장이 시작되는 부분에 주머니처럼 생긴 기관이 맹장인데요. 이 맹장 끝에 꼬리처럼 붙어 있는 게 충수입니다. 충수는 소화 과정에 전혀 관여하지 않고 걸핏하면 염증을 일으켜 쓸모없는 기관으로 여겨졌습니다. 그래서 충수에 염증이 생기면 제거해 버렸죠. 그런데 충수가 면역 기능을 강화하는 데 기여한다는 사실이 밝혀졌습니다. 충수가 장내 미생물을 비축해 두는 창고 역할을 한다는 것이죠. 대장에 탈이 나면 충수에 담겨 있는 유산균 같은 미생물들이 대장으로 이동해 회복을 돕습니다. 그래서 최근에 충수염이 생겼을 때 충수를 보존하며 치료하는 방법이 연구되고 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["충수에는 염증이 잘 생기지 않는다.","충수는 소화가 잘되도록 돕는 일을 한다.","충수에는 유익한 미생물이 서식하고 있다.","충수를 제거하는 수술이 최근에 가능해졌다."]'::jsonb, 2, '충수에는 유익한 미생물이 서식하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 46, '여자가 말하는 방식으로 알맞은 것을 고르십시오.

여자: 여기 오른쪽 아랫배, 대장이 시작되는 부분에 주머니처럼 생긴 기관이 맹장인데요. 이 맹장 끝에 꼬리처럼 붙어 있는 게 충수입니다. 충수는 소화 과정에 전혀 관여하지 않고 걸핏하면 염증을 일으켜 쓸모없는 기관으로 여겨졌습니다. 그래서 충수에 염증이 생기면 제거해 버렸죠. 그런데 충수가 면역 기능을 강화하는 데 기여한다는 사실이 밝혀졌습니다. 충수가 장내 미생물을 비축해 두는 창고 역할을 한다는 것이죠. 대장에 탈이 나면 충수에 담겨 있는 유산균 같은 미생물들이 대장으로 이동해 회복을 돕습니다. 그래서 최근에 충수염이 생겼을 때 충수를 보존하며 치료하는 방법이 연구되고 있습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["유사한 사례들을 묶어 비교 분석하고 있다.","대상이 가진 문제의 주요 원인을 유추하고 있다.","대상의 역할에 대해 밝혀진 사실을 설명하고 있다.","다양한 연구를 바탕으로 자신만의 기준을 제시하고 있다."]'::jsonb, 2, '대상의 역할에 대해 밝혀진 사실을 설명하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 47, '들은 내용과 같은 것을 고르십시오.

여자: 수익이 줄면서 부족해진 영업 비용을 메우려고 불가피하게 빚을 내는 소상공인이 늘고 있습니다. 어떤 대책이 필요할까요?
남자: 경영에 어려움을 겪는 소상공인에게는 금융 지원이 시급합니다. 이때 중요한 건 그들이 처한 상황에 따라 지원 방식이 달라야 한다는 겁니다. 가령 대출 의존도가 높은 사업체는 이자율을 낮추거나 대출금을 나눠 갚는 식으로 채무를 조정해 줘야 합니다. 또 매출액이 적은 사업체는 영업 비용을 줄일 수 있도록 인건비나 임대료 등의 고정 비용을 지원하는 게 효과적이고요. 이처럼 경영난을 해소하는 데 실질적인 도움이 되는 지원책이 하루빨리 마련되면 좋겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["인건비와 임대료는 고정 비용에 포함되지 않는다.","소상공인의 경영난은 일률적 방식으로 해결할 수 있다.","대출 의존도가 높은 경우 채무를 조정해 주면 안 된다.","영업 비용 때문에 빚을 지는 소상공인이 많아지고 있다."]'::jsonb, 2, '영업 비용 때문에 빚을 지는 소상공인이 많아지고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 48, '남자의 태도로 알맞은 것을 고르십시오.

여자: 수익이 줄면서 부족해진 영업 비용을 메우려고 불가피하게 빚을 내는 소상공인이 늘고 있습니다. 어떤 대책이 필요할까요?
남자: 경영에 어려움을 겪는 소상공인에게는 금융 지원이 시급합니다. 이때 중요한 건 그들이 처한 상황에 따라 지원 방식이 달라야 한다는 겁니다. 가령 대출 의존도가 높은 사업체는 이자율을 낮추거나 대출금을 나눠 갚는 식으로 채무를 조정해 줘야 합니다. 또 매출액이 적은 사업체는 영업 비용을 줄일 수 있도록 인건비나 임대료 등의 고정 비용을 지원하는 게 효과적이고요. 이처럼 경영난을 해소하는 데 실질적인 도움이 되는 지원책이 하루빨리 마련되면 좋겠습니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["소상공업계의 태도 변화를 기대하고 있다.","경제 위기 극복을 위한 소상공인의 노력에 감탄하고 있다.","소상공인에 대한 실효성 있는 지원 방안을 제안하고 있다.","소상공업의 활성화가 가져올 경제적 효과를 낙관하고 있다."]'::jsonb, 2, '소상공인에 대한 실효성 있는 지원 방안을 제안하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 49, '들은 내용과 같은 것을 고르십시오.

남자: 한 철학자는 행위의 결과와는 무관하게 인간이 지켜야 할 도덕적 의무만을 기준으로 도덕성을 판단해야 한다고 주장했는데요. 보편적 견해와 달리 동정심과 같은 행위자의 감정은 배제한 거죠. 예를 들어 연민의 감정에 이끌려 채권자에게 갚아야 할 돈으로 경제적 어려움에 빠진 이웃을 도와주는 것은 도덕적으로 정당한 행위가 아니라는 겁니다. 이 철학자의 기준에 따르면 도움을 청하는 사람을 외면하고 출근 시간을 지켜 회사에 간 사람이 도덕적으로 선한 사람이 됩니다. 물론 이 철학자의 견해는 인간의 감정을 고려하지 않았다는 점에서 이견이 있을 순 있지만 어느 한 면만을 보고 누군가의 도덕성을 판단하는 걸 자제해야 한다는 점을 다시 생각하게 합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["이 철학자는 도덕성에 대해 일반적인 견해를 따르고 있다.","이 철학자는 도덕성을 평가하는 기준에서 감정을 배제했다.","이 철학자에 따르면 출근 시간을 지키는 것은 도덕적 의무가 아니다.","이 철학자에 따르면 어떤 상황에서도 다른 사람을 돕는 것이 최우선이다."]'::jsonb, 2, '이 철학자는 도덕성을 평가하는 기준에서 감정을 배제했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'listening', 50, '남자의 태도로 알맞은 것을 고르십시오.

남자: 한 철학자는 행위의 결과와는 무관하게 인간이 지켜야 할 도덕적 의무만을 기준으로 도덕성을 판단해야 한다고 주장했는데요. 보편적 견해와 달리 동정심과 같은 행위자의 감정은 배제한 거죠. 예를 들어 연민의 감정에 이끌려 채권자에게 갚아야 할 돈으로 경제적 어려움에 빠진 이웃을 도와주는 것은 도덕적으로 정당한 행위가 아니라는 겁니다. 이 철학자의 기준에 따르면 도움을 청하는 사람을 외면하고 출근 시간을 지켜 회사에 간 사람이 도덕적으로 선한 사람이 됩니다. 물론 이 철학자의 견해는 인간의 감정을 고려하지 않았다는 점에서 이견이 있을 순 있지만 어느 한 면만을 보고 누군가의 도덕성을 판단하는 걸 자제해야 한다는 점을 다시 생각하게 합니다.', NULL, 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/audio/91-TOPIK-II-Listening-Audio-File.mp3', NULL, '["도덕적 행위의 당위성을 강조하고 있다.","도덕적 행위의 가치를 과대평가하고 있다.","도덕성에 대한 섣부른 판단을 경계하고 있다.","도덕성에 대한 연구의 필요성을 제기하고 있다."]'::jsonb, 2, '도덕성에 대한 섣부른 판단을 경계하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 1, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오. (각 2점)

나는 오래전에 설악산을( ........................ ).', NULL, NULL, NULL, '["등산하고 싶다","등산해도 된다","등산할 것 같다","등산한 적이 있다"]'::jsonb, 2, '등산한 적이 있다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 2, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오. (각 2점)

새집으로( ........................ ) 가구를 새로 샀다.', NULL, NULL, NULL, '["이사한 지","이사하거든","이사하려면","이사하고 나서"]'::jsonb, 2, '이사하고 나서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 3, '밑줄 친 부분과 의미가 가장 비슷한 것을 고르십시오.

어려운 이웃을 <span class=''underline''>돕고자</span> 매년 봉사 활동에 참여하고 있다.', NULL, NULL, NULL, '["돕기 위해서","돕는 대신에","돕기 무섭게","돕는 바람에"]'::jsonb, 2, '돕기 위해서', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 4, '밑줄 친 부분과 의미가 가장 비슷한 것을 고르십시오.

지난 3년 동안 영화를 한 편 봤으니 거의 안 <span class=''underline''>본 셈이다</span>.', NULL, NULL, NULL, '["본 척했다","보기 나름이다","볼 수밖에 없었다","본 거나 마찬가지이다"]'::jsonb, 2, '본 거나 마찬가지이다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 5, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q5.png', NULL, NULL, '["비누","칫솔","안경","수건"]'::jsonb, 2, '칫솔', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 6, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q6.png', NULL, NULL, '["은행","서점","유치원","우체국"]'::jsonb, 2, '유치원', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 7, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q7.png', NULL, NULL, '["건강 관리","안전 운전","전화 예절","절약 습관"]'::jsonb, 2, '건강 관리', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 8, '다음은 무엇에 대한 글인지 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q8.png', NULL, NULL, '["관람 규칙","제품 소개","사용 방법","예약 문의"]'::jsonb, 2, '관람 규칙', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 9, '다음 글의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q9.png', NULL, NULL, '["성인과 학생의 버스 요금이 같다.","이 버스는 별빛공원에서 출발한다.","매일 오전에 이 버스를 탈 수 있다.","이 버스를 타려면 미리 신청해야 한다."]'::jsonb, 2, '이 버스를 타려면 미리 신청해야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 10, '다음 글 또는 그래프의 내용과 같은 것을 고르십시오.', 'https://ywtxdfwntobzegrlyplw.supabase.co/storage/v1/object/public/mock%20test%20files/topik-ii-91/reading/q10.png', NULL, NULL, '["자가용으로 출퇴근한다고 응답한 직장인들의 비율이 줄었다.","걸어서 출퇴근하는 직장인은 2012년보다 2022년이 더 적었다.","2022년에는 지하철을 타고 출퇴근하는 직장인이 가장 많았다.","2012년에 직장인들은 출퇴근할 때 버스를 제일 많이 이용했다."]'::jsonb, 2, '걸어서 출퇴근하는 직장인은 2012년보다 2022년이 더 적었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 11, '다음 글의 내용과 같은 것을 고르십시오.

인주시가 작년에 이어 올해도 10월 한 달간 ''찾아가는 자전거 수리 센터''를 운영한다. 평일에는 여러 지역을 직접 방문해 고쳐 주고 주말에는 인주공원에서 수리 서비스를 제공한다. 전문 수리 기사가 자전거를 무료로 고쳐 주고 부품 교체가 필요한 경우에는 저렴한 가격으로 바꿔 준다. 시는 시민들의 자전거 타기 생활화를 위해 이 수리 센터를 운영하는 것이라고 밝혔다.', NULL, NULL, NULL, '["이 서비스는 일 년 내내 운영된다.","올해 처음으로 이 센터가 운영되기 시작했다.","주말에는 인주공원에서 수리를 받을 수 있다.","이 수리 센터에서는 무료로 부품을 교체해 준다."]'::jsonb, 2, '주말에는 인주공원에서 수리를 받을 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 12, '다음 글의 내용과 같은 것을 고르십시오.

피자 가게를 운영하는 김민수 씨의 사연이 잔잔한 감동을 주고 있다. 최근 김 씨는 피자를 배달하러 가다가 오토바이가 빗길에 미끄러지는 사고를 당했다. 다행히 사람이 다치는 피해는 없었지만 피자가 망가져서 배달에 문제가 생겼다. 배달이 늦어지는 것에 대해 김 씨가 고객에게 연락하자 고객은 "천천히 오셔도 돼요. 몸은 괜찮나요?"라며 따뜻한 말부터 전했다고 한다.', NULL, NULL, NULL, '["고객은 주문한 피자를 취소하겠다고 말했다.","사고가 생겨서 배달 중이던 피자가 망가졌다.","오토바이가 빗길에 미끄러져서 김 씨가 다쳤다.","김 씨는 피자를 시킨 고객에게 연락하다 사고가 났다."]'::jsonb, 2, '사고가 생겨서 배달 중이던 피자가 망가졌다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 13, '다음을 순서에 맞게 배열한 것을 고르십시오.

(가) 짧게는 하루, 길게는 한 달 정도 반짝 운영하는 임시 매장이다.
(나) 사람이 붐비는 장소에서 짧은 기간 동안 운영하는 매장이 유행이다.
(다) 기업은 이 임시 매장을 이용해 주로 특정 제품을 팔거나 홍보를 한다.
(라) 또 기업 이미지를 친숙하게 만들기 위해 재미있는 행사를 열기도 한다.', NULL, NULL, NULL, '["(가) - (다) - (라) - (나)","(나) - (가) - (다) - (라)","(가) - (라) - (나) - (다)","(나) - (라) - (다) - (가)"]'::jsonb, 2, '(나) - (가) - (다) - (라)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 14, '다음을 순서에 맞게 배열한 것을 고르십시오.

(가) 그런데 전화를 끊고 뒤늦게 미안한 마음이 들었다.
(나) 친구는 나의 합격 소식을 듣고 자신의 일처럼 기뻐했다.
(다) 얼마 전 나는 회사 합격 소식을 듣고 친한 친구에게 전화했다.
(라) 아직 취업 못 한 친구를 내가 배려하지 못했다는 생각 때문이었다.', NULL, NULL, NULL, '["(나) - (다) - (라) - (가)","(나) - (라) - (가) - (다)","(다) - (나) - (가) - (라)","(다) - (나) - (라) - (가)"]'::jsonb, 2, '(다) - (나) - (가) - (라)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 15, '다음을 순서에 맞게 배열한 것을 고르십시오.

(가) 빵이나 고기를 구울 때 갈색으로 바뀌는 것이 그 예이다.
(나) 갈색으로 바뀌면서 빵이나 고기의 맛도 더 깊어지고 풍부해진다.
(다) 식품에 들어 있는 당과 단백질이 열을 만나면 색깔이 바뀌게 된다.
(라) 만약 열이 너무 가해져서 검게 타게 되면 그런 맛을 낼 수가 없다.', NULL, NULL, NULL, '["(가) - (나) - (라) - (다)","(다) - (가) - (나) - (라)","(가) - (다) - (라) - (나)","(다) - (라) - (나) - (가)"]'::jsonb, 2, '(다) - (가) - (나) - (라)', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 16, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

타조는 멀리서 적이 다가와도 머리를 모래에 파묻고 있다. 그래서 위험이나 위기를 모르는 척 피하는 사람을 타조에 비유하곤 한다. 그런데 사실 타조는 ( ........................ ) 위해 이런 행동을 한다. 시각보다 청각이 발달한 타조는 땅에서 울리는 발소리를 듣고 적이 오는지를 파악하려는 것이다.', NULL, NULL, NULL, '["적의 움직임을 알기","먹이를 빨리 구하기","머리를 깨끗이 씻기","다른 타조를 공격하기"]'::jsonb, 2, '적의 움직임을 알기', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 17, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

섬유 유연제는 섬유에 막을 씌워 옷감을 부드럽게 하고 향기도 남긴다. 그래서 세탁할 때 유연제를 넣는 사람들이 많다. 그런데 수건처럼 물기를 빠르게 흡수해야 하는 소재에는 유연제를 넣는 것이 좋은 것만은 아니다. 유연제가 만든 막이 오히려 섬유의( ........................ ) 때문이다.', NULL, NULL, NULL, '["향기를 없애기","색깔을 변형시키기","흡수력을 떨어뜨리기","촉감을 거칠게 만들기"]'::jsonb, 2, '흡수력을 떨어뜨리기', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 18, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

디지털 기기에 대한 의존도가 높아지면서 사람들이 무언가 직접 기억해야 할 일은 줄었다. 그래서 이전보다( ........................ ) 생각할 수 있다. 그런데 뇌를 사용하는 방식이 이전과 달라졌을 뿐 사용량이 줄어든 것이 아니다. 과거에는 단순히 정보를 기억하는 데 뇌를 썼다면 이제는 과거보다 압도적으로 많아진 정보를 처리하는 데 사용하고 있는 것이다.', NULL, NULL, NULL, '["뇌를 덜 사용한다고","기억력이 좋아졌다고","저장해야 할 정보가 많다고","디지털 기기를 많이 쓴다고"]'::jsonb, 2, '뇌를 덜 사용한다고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 19, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

매서운 남극의 겨울, 황제펭귄들은 겹겹이 붙어 서로의 체온으로 추위를 견딘다. 무리 전체가 돌면서 바깥쪽과 안쪽에 있는 펭귄들이 계속 서로의 위치를 바꾼다. 안에서 몸을 데운 펭귄은 밖으로 나가고 밖에서 추위에 떨던 펭귄은 안으로 들어오는 것이다. ( ........................ ) 그 움직임은 아주 느리지만 쉬지 않고 이루어져 한 마리의 펭귄이 줄곧 찬바람을 맞고 서 있는 일이 없다. 그렇게 쉼 없이 둥글게 돌면서 펭귄들은 다 함께 살아남는다.', NULL, NULL, NULL, '["혹시","또는","비록","만약"]'::jsonb, 2, '비록', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 20, '윗글의 주제로 가장 알맞은 것을 고르십시오.

매서운 남극의 겨울, 황제펭귄들은 겹겹이 붙어 서로의 체온으로 추위를 견딘다. 무리 전체가 돌면서 바깥쪽과 안쪽에 있는 펭귄들이 계속 서로의 위치를 바꾼다. 안에서 몸을 데운 펭귄은 밖으로 나가고 밖에서 추위에 떨던 펭귄은 안으로 들어오는 것이다. ( ........................ ) 그 움직임은 아주 느리지만 쉬지 않고 이루어져 한 마리의 펭귄이 줄곧 찬바람을 맞고 서 있는 일이 없다. 그렇게 쉼 없이 둥글게 돌면서 펭귄들은 다 함께 살아남는다.', NULL, NULL, NULL, '["황제펭귄은 서로 도우면서 추위에 맞서 생존해 왔다.","황제펭귄은 둥글게 돌면서 날씨에 대한 정보를 알린다.","황제펭귄은 추위에서 살아남기 위해 움직임이 느려졌다.","황제펭귄은 무리 생활을 통해 경쟁에서 이기는 법을 배운다."]'::jsonb, 2, '황제펭귄은 서로 도우면서 추위에 맞서 생존해 왔다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 21, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

최근 미술 전시회 수요가 증가하면서 돈벌이에 급급한 전시회가 늘고 있다. 일부 전시 관계자들이 전시 포스터 등 홍보 자료에 복제품 전시임을 밝히지 않고 입장료 수입만을 챙기는 것이다. 전시장을 찾아와서야 이런 사실을 알게 된 관람객들은 불만을 쏟아 내고 있다. 전문가들은 이런 전시 행태가 미술계 발전의 ( ........................ ) 수 있다고 우려한다. 전시회에 실망한 사람들이 미술에 대한 관심을 아예 끊을 수 있기 때문이다.', NULL, NULL, NULL, '["입맛에 맞을","가슴을 울릴","발목을 잡을","손을 맞잡을"]'::jsonb, 2, '발목을 잡을', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 22, '윗글의 내용과 같은 것을 고르십시오.

최근 미술 전시회 수요가 증가하면서 돈벌이에 급급한 전시회가 늘고 있다. 일부 전시 관계자들이 전시 포스터 등 홍보 자료에 복제품 전시임을 밝히지 않고 입장료 수입만을 챙기는 것이다. 전시장을 찾아와서야 이런 사실을 알게 된 관람객들은 불만을 쏟아 내고 있다. 전문가들은 이런 전시 행태가 미술계 발전의 ( ........................ ) 수 있다고 우려한다. 전시회에 실망한 사람들이 미술에 대한 관심을 아예 끊을 수 있기 때문이다.', NULL, NULL, NULL, '["복제품 전시회는 입장료를 받지 않는다.","최근 미술 전시회를 찾는 사람들이 많지 않다.","전시회에서 복제품을 전시하는 일이 점점 줄고 있다.","복제품 전시회인지 모르고 전시회를 방문한 관람객들이 있다."]'::jsonb, 2, '복제품 전시회인지 모르고 전시회를 방문한 관람객들이 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 23, '밑줄 친 부분에 나타난 ''나''의 심정으로 가장 알맞은 것을 고르십시오.

꽃집을 지나다가 꽃말에 이끌려 금잔화 꽃씨를 샀다. 화분에 심어 사무실의 내 책상 위에 두었더니 어느 날 싹이 텄다. 때맞춰 물도 주며 나는 수시로 들여다보았다. 신기했다. 작고 여린 싹은 눈에 띄게 쑥쑥 자랐다. 그런데 내가 상상한 모습이 아니었다. <span class=''underline''>도대체 여기서 어떻게 꽃이 핀다는 건지.</span> 무순처럼 길쭉하게 위로만 자라는 것이었다. 하루는 출근해 보니 금잔화가 쓰러져 있었다. 그럼 그렇지. 내가 무슨 식물을 키우나. 그날 나는 화분을 창가로 옮겨 놓았다. 죽을 것 같은 모습을 눈앞에서 보고 싶지 않았다. 그런데 어느 날부턴가 점점 줄기가 굵어지더니 잎도 제법 풍성해지기 시작했다. 어느 날에는 꽃망울도 올라와 있었다. 금잔화는 창문으로 들어오는 풍성한 햇볕 속에서 스스로 튼튼해졌다. 금잔화에게는 햇빛이 더 많이 필요했었나 보다. 사람도 식물도 사랑하려면 그 대상을 제대로 알아야 하는 건 똑같구나 싶었다. 씩씩하게 꽃피운 금잔화의 꽃말은 ''반드시 올 행복''이다.', NULL, NULL, NULL, '["의심스럽다","고통스럽다","조심스럽다","부담스럽다"]'::jsonb, 2, '의심스럽다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 24, '윗글의 내용과 같은 것을 고르십시오.

꽃집을 지나다가 꽃말에 이끌려 금잔화 꽃씨를 샀다. 화분에 심어 사무실의 내 책상 위에 두었더니 어느 날 싹이 텄다. 때맞춰 물도 주며 나는 수시로 들여다보았다. 신기했다. 작고 여린 싹은 눈에 띄게 쑥쑥 자랐다. 그런데 내가 상상한 모습이 아니었다. <span class=''underline''>도대체 여기서 어떻게 꽃이 핀다는 건지.</span> 무순처럼 길쭉하게 위로만 자라는 것이었다. 하루는 출근해 보니 금잔화가 쓰러져 있었다. 그럼 그렇지. 내가 무슨 식물을 키우나. 그날 나는 화분을 창가로 옮겨 놓았다. 죽을 것 같은 모습을 눈앞에서 보고 싶지 않았다. 그런데 어느 날부턴가 점점 줄기가 굵어지더니 잎도 제법 풍성해지기 시작했다. 어느 날에는 꽃망울도 올라와 있었다. 금잔화는 창문으로 들어오는 풍성한 햇볕 속에서 스스로 튼튼해졌다. 금잔화에게는 햇빛이 더 많이 필요했었나 보다. 사람도 식물도 사랑하려면 그 대상을 제대로 알아야 하는 건 똑같구나 싶었다. 씩씩하게 꽃피운 금잔화의 꽃말은 ''반드시 올 행복''이다.', NULL, NULL, NULL, '["내 책상 위에 둔 금잔화는 금방 말라 죽었다.","나는 금잔화 화분에 물을 제대로 주지 못했다.","나는 꽃집에서 금잔화가 피어 있는 화분을 샀다.","내가 금잔화 화분을 옮긴 곳은 햇볕이 잘 들었다."]'::jsonb, 2, '내가 금잔화 화분을 옮긴 곳은 햇볕이 잘 들었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 25, '다음 신문 기사의 제목을 가장 잘 설명한 것을 고르십시오.

가수 진영, 3년 만의 콘서트에 구름 관중', NULL, NULL, NULL, '["가수 진영이 3년 만에 콘서트를 열자 수많은 관중이 몰렸다.","가수 진영이 3년 내에 다시 콘서트를 열기로 관중에게 약속했다.","가수 진영이 3년간 준비한 콘서트를 열었으나 관중의 호응이 적었다.","가수 진영이 3년 만에 하는 콘서트에 많은 관중을 모으려고 홍보했다."]'::jsonb, 2, '가수 진영이 3년 만에 콘서트를 열자 수많은 관중이 몰렸다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 26, '다음 신문 기사의 제목을 가장 잘 설명한 것을 고르십시오.

한국 탁구의 간판 김수미, 올해 국제 대회 금메달 싹쓸이', NULL, NULL, NULL, '["올해 국제 탁구 대회에서 한국 대표 김수미의 금메달 가능성이 높아졌다.","한국 탁구계가 김수미를 내세워 올해 국제 대회의 금메달을 노리고 있다.","한국의 대표 탁구 선수 김수미가 올해 국제 대회에서 모두 금메달을 땄다.","한국 탁구 선수 김수미가 올해 국제 대회에서 금메달을 따고자 훈련 중이다."]'::jsonb, 2, '한국의 대표 탁구 선수 김수미가 올해 국제 대회에서 모두 금메달을 땄다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 27, '다음 신문 기사의 제목을 가장 잘 설명한 것을 고르십시오.

대출 금리 하락세, 부동산 시장 기지개', NULL, NULL, NULL, '["대출 금리가 떨어지면서 부동산 시장이 살아나기 시작했다.","부동산 시장에 대한 규제가 대출 금리 하락에 영향을 미쳤다.","대출 금리가 하락했지만 부동산 시장의 거래는 줄어들고 있다.","부동산 시장을 활성화하려고 대출 금리 안정화 대책이 논의되고 있다."]'::jsonb, 2, '대출 금리가 떨어지면서 부동산 시장이 살아나기 시작했다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 28, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

선글라스는 보통 햇빛이 강할 때 눈 건강을 위해 쓴다. 그런데 선글라스의 렌즈는 사용 기한이 있다. 선글라스의 렌즈에는 자외선 차단을 위한 엷은 막이 입혀져 있는데 열에 계속 노출되면 자외선 차단 기능이 점점 떨어지게 된다. 자외선 차단 기능이 약해진 선글라스로는 눈을 보호하기 어려우므로 5년 정도 쓰고 나면( ........................ ) 것이 좋다.', NULL, NULL, NULL, '["렌즈를 바꿔 주는","렌즈를 꼼꼼히 잘 닦는","렌즈의 색을 어둡게 하는","렌즈의 엷은 막을 벗겨 내는"]'::jsonb, 2, '렌즈를 바꿔 주는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 29, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

사진에서 구도는 전체적인 분위기를 살리는 중요한 요소이다. 보통 동적인 느낌을 주고 싶을 때는 대각선 구도를 쓰는데 도로나 폭포 등의 풍경 사진 등에 쓰여 생동감을 표현한다. 한편 전통적인 가족사진은( ........................ ) 위해서 삼각형 구도를 가장 많이 활용한다. 이 구도는 연장자를 중심으로 가족 구성원이 옆이나 뒤에 배치되어 전체적으로 편안하고 균형 잡힌 분위기를 만들어 낸다.', NULL, NULL, NULL, '["동적인 효과를 살리기","안정적인 느낌을 주기","풍경을 중앙에 배치하기","긴장된 분위기를 연출하기"]'::jsonb, 2, '안정적인 느낌을 주기', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 30, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

풍부한 자원은 경제 성장의 필요조건이지 충분조건은 아니다. 풍부한 천연 자원을 갖추고 있음에도( ........................ ) 경우도 있다. 풍부한 자원에만 의존해 경제 성장의 중심 산업인 제조업이나 서비스업 등에 투자를 하지 않게 되는 것이다. 반면에 천연자원이 빈약해도 새로운 기술 개발이나 교육을 통해 생산 능력을 높이는 나라도 있다.', NULL, NULL, NULL, '["제조업에 의존하려는","자원을 생산하지 못하는","경제 발전을 이루지 못하는","기술 개발에 무리하게 투자하는"]'::jsonb, 2, '경제 발전을 이루지 못하는', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 31, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

의사의 모습을 생각하면 우리는 보통 흰색 가운을 떠올리게 된다. 그런데 의사 가운이 처음부터 흰색이었던 것은 아니다. 중세 시대에는 성직자가 의사를 겸하는 경우가 많아 성직자용 검은색 가운을 입고 진료를 했다. 그런데 검은색 옷은 세균으로 오염된 얼룩이 잘 보이지 않았다. 이후 세균 감염의 위험성에 대한 인식이 높아지면서( ........................ ) 가운의 색이 흰색으로 바뀌었다.', NULL, NULL, NULL, '["염색하기 편하게","환자와 구분이 되도록","오염이 쉽게 눈에 띄도록","밝은 이미지를 줄 수 있게"]'::jsonb, 2, '오염이 쉽게 눈에 띄도록', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 32, '다음을 읽고 글의 내용과 같은 것을 고르십시오.

당뇨 환자들을 위해 고추 품종인 ''살리초''가 개발되었다. 고추는 보통 열매를 얻기 위해 재배하지만 살리초는 열매가 없고 잎을 먹는 품종이다. 일반 고추에 비해 혈당을 낮추는 성분이 10배 이상 많이 함유돼 있어 당뇨병, 비만증 등 성인병의 예방과 치료에 이용될 수 있다. 또한 살리초에는 칼슘, 비타민 등 각종 영양 성분이 풍부하다. 병해충에도 강하고 생육 기간도 짧아서 농가의 고소득 작물로 주목받고 있다.', NULL, NULL, NULL, '["살리초는 해충에 취약하다는 단점이 있다.","살리초의 열매는 크고 영양 성분이 풍부하다.","살리초는 생육 기간이 길어 관심을 받지 못하고 있다.","살리초의 잎에는 혈당을 떨어뜨리는 성분이 들어 있다."]'::jsonb, 2, '살리초의 잎에는 혈당을 떨어뜨리는 성분이 들어 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 33, '다음을 읽고 글의 내용과 같은 것을 고르십시오.

「임원경제지』는 조선 시대 서유구가 쓴 백과사전이다. 선비가 시골에서 살아가는 데 필요한 지식을 탐색한 것으로 농업, 건축, 의학 등 16개 분야를 정리했다. 서유구는 이 책을 쓸 때 조선의 생활상을 직접 관찰하고 여러 서적들을 참고했으며 거기에 자신의 논평을 첨부했다. 이 과정에서 인용한 책들을 밝혀 놓아 서지학적 가치도 크다. 총 52권의 책을 편찬했는데 개인이 완성했다고 보기 어려울 만큼 방대하고 전문적인 지식이 담겨 있다.', NULL, NULL, NULL, '["이 책은 각 분야의 전문가가 모여 만든 책이다.","서유구는 집필하면서 참고한 문헌을 이 책에 기록해 놓았다.","서유구는 객관적인 책을 쓰기 위해 자신의 의견은 배제했다.","이 책은 내용이 특정 분야에 한정되어 서지학적 가치는 크지 않다."]'::jsonb, 2, '서유구는 집필하면서 참고한 문헌을 이 책에 기록해 놓았다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 34, '다음을 읽고 글의 내용과 같은 것을 고르십시오.

코알라는 유칼립투스라는 나뭇잎을 먹고 산다. 이 나뭇잎은 독성이 강해서 일반적인 동물들은 먹을 수 없다. 하지만 코알라는 유칼립투스의 독을 해독하는 효소가 있어서 다른 동물들과 경쟁할 필요 없이 유칼립투스 잎을 충분히 먹을 수 있다. 다만 새끼 코알라는 독성을 분해하는 효소가 없어서 유칼립투스 잎 대신 어미의 배설물을 먹는다. 이를 먹다 보면 새끼 코알라의 몸속에도 유칼립투스의 독을 해독하는 효소가 생기게 된다.', NULL, NULL, NULL, '["다양한 동물들이 유칼립투스 잎을 차지하기 위해 경쟁한다.","어미 코알라는 유칼립투스의 독성을 분해하는 효소를 가지고 있다.","코알라는 태어난 직후부터 많은 양의 유칼립투스 나뭇잎을 먹는다.","새끼 코알라는 유칼립투스의 독성 때문에 어미의 배설물을 먹지 않는다."]'::jsonb, 2, '어미 코알라는 유칼립투스의 독성을 분해하는 효소를 가지고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 35, '다음을 읽고 글의 주제로 가장 알맞은 것을 고르십시오.

태양계에 존재하는 수많은 소행성에는 천문학적인 가치를 지닌 광물이 있는 것으로 예상된다. 그래서 많은 나라들이 이에 관심을 가지고 있다. 실제로 최근 몇몇 국가에서는 소행성에 있는 광물 시료를 채취하는 데 성공하기도 했다. 하지만 대부분의 나라들에서는 소행성 탐사가 아직 논의 단계에 머무르고 있다. 미래 자원을 확보하기 위해서 적극적으로 소행성 탐사에 대한 투자와 기술 개발에 나설 필요가 있다.', NULL, NULL, NULL, '["태양계에는 아직 발견되지 않은 소행성이 많이 존재한다.","소행성에서 자원을 가져오는 것은 실현 가능성이 희박하다.","소행성 탐사를 성공시키기 위해 국제 협력을 확대해야 한다.","미래 자원 확보를 위해 소행성 탐사에 대한 노력을 기울여야 한다."]'::jsonb, 2, '미래 자원 확보를 위해 소행성 탐사에 대한 노력을 기울여야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 36, '다음을 읽고 글의 주제로 가장 알맞은 것을 고르십시오.

경기 침체에 빠지면 사람들은 소비보다는 저축을 늘리려고 한다. 그런데 저축이 언제나 긍정적인 것만은 아니다. 소비가 줄면 기업의 매출이 감소 해서 생산과 고용이 줄 수밖에 없고 결국 근로자들의 소득도 줄어들게 된다. 그러면 미래가 불확실해진 사람들이 더욱 소비를 줄여 전체 경기가 다시 침체에 빠지는 악순환이 되풀이된다. 개인 차원에서는 저축이 합리적인 행동 이지만 경제 전체적으로는 비합리적인 상황을 초래하게 되는 것이다.', NULL, NULL, NULL, '["불경기에는 비합리적인 소비로 인해 근로자들의 저축이 줄어든다.","경기가 침체하면 개인의 소득이 줄어들지 않도록 투자를 늘려야 한다.","경제 상황을 고려해서 생산과 고용을 적절히 조절하는 것이 중요하다.","경기 침체 시에는 저축이 국가 경제 전체에 부정적 영향을 줄 수 있다."]'::jsonb, 2, '경기 침체 시에는 저축이 국가 경제 전체에 부정적 영향을 줄 수 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 37, '다음을 읽고 글의 주제로 가장 알맞은 것을 고르십시오.

참치 쿼터제는 참치의 무분별한 포획을 막기 위해 어획량을 국가별로 정해 놓은 제도이다. 한국은 참치 어획량이 매우 적게 배정돼 있는데 이는 한국 연안에서는 참치가 거의 잡히지 않았기 때문이다. 최근 수온이 상승 함에 따라 한국 연안에 유입되는 참치가 급격히 늘어나고 있지만 쿼터제 때문에 그물에 걸린 참치를 대부분 바다에 버리고 있다. 쿼터제의 필요성은 인정하지만 국가별 개체 수 증감을 반영한 융통성 있는 조정이 필요하다.', NULL, NULL, NULL, '["국가별 상황에 따라 참치 쿼터제를 현실에 맞게 수정해야 한다.","참치의 무분별한 포획을 방지하기 위해 쿼터제를 도입해야 한다.","수온 상승으로부터 참치를 보호하기 위한 대책을 마련해야 한다.","참치의 유입량을 늘리기 위한 실질적인 연구가 이루어져야 한다."]'::jsonb, 2, '국가별 상황에 따라 참치 쿼터제를 현실에 맞게 수정해야 한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 38, '다음을 읽고 글의 주제로 가장 알맞은 것을 고르십시오.

기업들은 기술 혁신을 통해 고객에게 편의와 혜택을 제공하려고 한다. 하지만 아무리 획기적인 혁신이라도 고객에게 낯설고 커다란 행동 변화를 요구한다면 외면당하기 쉽다. 예를 들어 초창기 전기 자동차는 전기로 오래 충전을 해야 하는 것이 낯설고 불편해서 큰 관심을 끌지 못했다. 반대로 전자 칠판과 전자 펜처럼 대단한 혁신은 아니지만 사용하는 방법이 고객 에게 익숙하고 간단해서 환영받는 경우도 있다.', NULL, NULL, NULL, '["고객들의 무리한 요구 때문에 기술 혁신에 어려움을 겪게 된다.","혁신적인 기업은 고객들에게 신기술의 사용 방법을 잘 설명해 준다.","기술 혁신에 실패한 기업은 자연스럽게 고객들의 외면을 받게 된다.","기술 혁신은 고객이 쉽게 받아들일 수 있을 때 성공할 가능성이 높다."]'::jsonb, 2, '기술 혁신은 고객이 쉽게 받아들일 수 있을 때 성공할 가능성이 높다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 39, '주어진 문장이 들어갈 곳으로 가장 알맞은 것을 고르십시오.

주어진 문장: 그런데 심판이 아무리 위치 선정을 잘해도 필연적으로 선수의 몸에 가려서 볼 수 없는 사각지대가 생긴다.

스포츠 경기를 진행할 때 득점이나 반칙 등의 판정은 심판에 의해서 이루어 진다.( ㉠ ) 이렇게 눈에 보이지 않는 곳에서 벌어진 상황에 대해서는 심판도 정확한 판단을 하기 어렵다. ( ㉡ ) 비디오 판독은 이런 스포츠 경기에서 초고속 카메라를 판정의 근거로 사용하는 기술이다. ( ㉢ ) 이처럼 비디오 판독을 활용하면 심판이 판단하기 어려운 부분을 객관적으로 확인할 수 있어 판정에 대한 신뢰도를 높일 수 있다. ( ㉣ )', NULL, NULL, NULL, '["㉠","㉡","㉢","㉣"]'::jsonb, 2, '㉠', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 40, '주어진 문장이 들어갈 곳으로 가장 알맞은 것을 고르십시오.

주어진 문장: 그 증거로 지중해 전역에서 발견되고 있는 소금 퇴적층을 들 수 있다.

유럽과 아시아, 아프리카 대륙으로 둘러싸인 바다를 지중해라고 한다.( ㉠ ) 오늘날 지중해 연안은 기후가 온화해서 살기 좋은 곳으로 손꼽힌다.( ㉡ ) 그런데 지중해는 오래전 사막이었던 적이 있었다. ( ㉢ ) 이 소금 퇴적층은 바닷물이 증발되고 남은 소금이 쌓여 만들어진 것으로 지중해가 이전에는 사막이었음을 보여 준다. ( ㉣ ) 사막이었던 지중해에 이후 큰 홍수가 발생하면서 다시 오늘날과 같은 바다가 되었다.', NULL, NULL, NULL, '["㉠","㉡","㉢","㉣"]'::jsonb, 2, '㉢', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 41, '주어진 문장이 들어갈 곳으로 가장 알맞은 것을 고르십시오.

주어진 문장: 이런 상소문들을 저자는 왕을 향한 깨우침의 죽비 소리로 비유하고 있다.

최근 역사학자 김경민 씨가 『응답하라, 조선』을 펴냈다.( ㉠ ) 이 책은 왕과 신하의 소통을 다루고 있어 사람들의 관심을 끈다. ( ㉡ ) 그 소통의 내용 중에서 특히 왕의 노여움을 무릅쓰고 신하가 왕의 잘못을 지적한 상소문을 다룬 부분이 주목받고 있다. ( ㉢ ) 『응답하라, 조선』은 눈치를 살피며 윗사람의 잘못을 모르는 체 넘기곤 하는 현대인들을 깨우는 죽비인 것이다.( ㉣ )', NULL, NULL, NULL, '["㉠","㉡","㉢","㉣"]'::jsonb, 2, '㉢', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 42, '밑줄 친 부분에 나타난 ''미연''의 심정으로 가장 알맞은 것을 고르십시오.

민욱이 주말에 친구 부부를 초대해도 되느냐고 물었을 때, 미연은 말없이 한참 뜸을 들였다. 그녀는 그날 민욱과 함께 아파트의 발코니 벽을 페인트 칠할 계획이었다. (중략) 그들은 육 개월 전에 도시의 아파트를 사서 이사 했다. 지은 지 이십 년도 더 된 낡은 아파트였지만, 누구의 도움도 받지 않고 그들 스스로 이룬 일이었다. 미연은 직접 발품을 팔아 수도부터 새시까지 새로 손을 보았다. 하지만 집수리는 대강 되었다고 해도, 미연이 생각해 둔 대로 인테리어가 완성되려면 아직 부족했다.<br><br>“<span class=''underline''>손님 초대는 좀 이르지 않아? 집 단장도 덜 되었는데......</span>”<br><br>"성재가 한국에 왔대"<br><br>민욱이 무거운 목소리로 말했다. (중략) 미연은 자신이 연주의 이름을 오랫동안 잊고 있었다는 사실을 깨달았다. 더 이상 뭐라고 할 말이 없었다. (중략) 토요일 오전에 미연은 두 딸아이를 데리고 마트에 가서 고기와 채소를 샀다. 누군가를 초대해 음식을 대접하는 것이 정말로 오랜만이었다.', NULL, NULL, NULL, '["후련하다","불만스럽다","허전하다","자랑스럽다"]'::jsonb, 2, '불만스럽다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 43, '윗글의 내용으로 알 수 있는 것을 고르십시오.

민욱이 주말에 친구 부부를 초대해도 되느냐고 물었을 때, 미연은 말없이 한참 뜸을 들였다. 그녀는 그날 민욱과 함께 아파트의 발코니 벽을 페인트 칠할 계획이었다. (중략) 그들은 육 개월 전에 도시의 아파트를 사서 이사 했다. 지은 지 이십 년도 더 된 낡은 아파트였지만, 누구의 도움도 받지 않고 그들 스스로 이룬 일이었다. 미연은 직접 발품을 팔아 수도부터 새시까지 새로 손을 보았다. 하지만 집수리는 대강 되었다고 해도, 미연이 생각해 둔 대로 인테리어가 완성되려면 아직 부족했다.<br><br>“<span class=''underline''>손님 초대는 좀 이르지 않아? 집 단장도 덜 되었는데......</span>”<br><br>"성재가 한국에 왔대"<br><br>민욱이 무거운 목소리로 말했다. (중략) 미연은 자신이 연주의 이름을 오랫동안 잊고 있었다는 사실을 깨달았다. 더 이상 뭐라고 할 말이 없었다. (중략) 토요일 오전에 미연은 두 딸아이를 데리고 마트에 가서 고기와 채소를 샀다. 누군가를 초대해 음식을 대접하는 것이 정말로 오랜만이었다.', NULL, NULL, NULL, '["미연은 민욱과 성재를 통해 연주를 알게 되었다.","민욱은 주변 도움을 받아 도시의 새 아파트를 샀다.","미연은 육 개월 전에 산 아파트로 이사 갈 계획이다.","민욱은 인테리어를 완성한 후에 마트에 장을 보러 갔다."]'::jsonb, 2, '미연은 민욱과 성재를 통해 연주를 알게 되었다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 44, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

''수로왕 신화''는 왕이 알에서 탄생하는 여느 건국 신화와 유사하다. 고대에 아직 나라가 없던 낙동강 하류에 황금알 여섯 개가 하늘에서 내려왔다. 그중 맨 먼저 알을 깨고 나온 아이를 ''수로''라 하였고 하늘의 뜻에 따라 수로는 지상의 첫 번째 왕이 되었다. ( ........................ ) 다섯 아이 역시 각각 왕이 되었다. 수로왕 신화는 이렇게 한꺼번에 여섯 개 알이 나타나 거기서 태어난 이가 모두 왕이 된다는 점에서 다른 건국 신화와 큰 차이가 있다. 당시 세워진 여섯 나라는 강력한 왕권 국가가 아니었다. 황금알은 하늘로부터 부여받은 절대적 권위를 상징하는데 수로가 알에서 최초로 탄생했다는 부분은 수로왕이 중심이 되어 여섯 나라를 하나의 강력한 국가 ''가야''로 통합하려 했다는 것을 말해 준다.', NULL, NULL, NULL, '["알을 가지고 내려온","기존의 왕을 물리치고","수로에 이어 알에서 태어난","탄생을 축하하며 몹시 기뻐하던"]'::jsonb, 2, '수로에 이어 알에서 태어난', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 45, '윗글의 주제로 가장 알맞은 것을 고르십시오.

''수로왕 신화''는 왕이 알에서 탄생하는 여느 건국 신화와 유사하다. 고대에 아직 나라가 없던 낙동강 하류에 황금알 여섯 개가 하늘에서 내려왔다. 그중 맨 먼저 알을 깨고 나온 아이를 ''수로''라 하였고 하늘의 뜻에 따라 수로는 지상의 첫 번째 왕이 되었다. ( ........................ ) 다섯 아이 역시 각각 왕이 되었다. 수로왕 신화는 이렇게 한꺼번에 여섯 개 알이 나타나 거기서 태어난 이가 모두 왕이 된다는 점에서 다른 건국 신화와 큰 차이가 있다. 당시 세워진 여섯 나라는 강력한 왕권 국가가 아니었다. 황금알은 하늘로부터 부여받은 절대적 권위를 상징하는데 수로가 알에서 최초로 탄생했다는 부분은 수로왕이 중심이 되어 여섯 나라를 하나의 강력한 국가 ''가야''로 통합하려 했다는 것을 말해 준다.', NULL, NULL, NULL, '["이 신화는 전형적인 건국 신화의 특성을 지니고 있다.","이 신화는 낙동강 일대의 유용한 지리적 정보를 담고 있다.","이 신화는 고대의 문학 작품으로서 훌륭한 가치를 지니고 있다.","이 신화는 강력한 왕권 국가를 이루려고 한 통합 의식을 반영한다."]'::jsonb, 2, '이 신화는 강력한 왕권 국가를 이루려고 한 통합 의식을 반영한다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 46, '윗글에 나타난 필자의 태도로 가장 알맞은 것을 고르십시오.

주가 조작이나 공금 횡령 등의 경제 범죄는 사람에게 직접적인 상해를 가하는 흉악 범죄보다 범죄 정도가 낮다고 생각하기 쉽다. 그러나 경제 범죄의 수법이 날이 갈수록 다양해지고 지능화되어 사회에 미치는 충격과 피해가 막심하다. 최근 증권사 직원의 주가 조작으로 고객들이 천억 넘게 손해 본 사건만 해도 그렇다. 이러한 경제 범죄는 개인 손해를 넘어 국가 경제와도 직결될 수 있다. 따라서 이를 가벼이 여겨서는 안 되며 관대하게 처벌해서도 안 된다. 건전한 경제 질서를 확립하기 위해 경제 사범을 엄벌할 필요가 있다. ''한탕 크게 해 먹고 몸으로 때우면 된다''는 한탕주의가 만연 하지 않도록 처벌 수준을 더 높여야 한다. 지금까지 미진했던 부당 이익 환수도 앞으로 잘 이루어져 경제 범죄가 재발되지 않도록 해야 할 것이다.', NULL, NULL, NULL, '["경제 범죄가 사회에 미치는 영향을 부정하고 있다.","경제 사범에 대한 처벌을 강화하도록 촉구하고 있다.","경제 사범의 처벌로 생길 결과에 대해 우려하고 있다.","경제 범죄의 다양한 수법을 객관적으로 분석하고 있다."]'::jsonb, 2, '경제 사범에 대한 처벌을 강화하도록 촉구하고 있다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 47, '윗글의 내용과 같은 것을 고르십시오.

주가 조작이나 공금 횡령 등의 경제 범죄는 사람에게 직접적인 상해를 가하는 흉악 범죄보다 범죄 정도가 낮다고 생각하기 쉽다. 그러나 경제 범죄의 수법이 날이 갈수록 다양해지고 지능화되어 사회에 미치는 충격과 피해가 막심하다. 최근 증권사 직원의 주가 조작으로 고객들이 천억 넘게 손해 본 사건만 해도 그렇다. 이러한 경제 범죄는 개인 손해를 넘어 국가 경제와도 직결될 수 있다. 따라서 이를 가벼이 여겨서는 안 되며 관대하게 처벌해서도 안 된다. 건전한 경제 질서를 확립하기 위해 경제 사범을 엄벌할 필요가 있다. ''한탕 크게 해 먹고 몸으로 때우면 된다''는 한탕주의가 만연 하지 않도록 처벌 수준을 더 높여야 한다. 지금까지 미진했던 부당 이익 환수도 앞으로 잘 이루어져 경제 범죄가 재발되지 않도록 해야 할 것이다.', NULL, NULL, NULL, '["경제 범죄로 생긴 부당 이익을 문제없이 잘 환수해 왔다.","공금을 불법으로 가로채는 범죄는 경제 범죄에 포함된다.","개인이 저지른 주가 조작 범죄는 국가 경제와 큰 관련이 없다.","경제 범죄 수법이 교묘해졌지만 사회에 미치는 충격은 크지 않다."]'::jsonb, 2, '공금을 불법으로 가로채는 범죄는 경제 범죄에 포함된다.', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 48, '윗글을 쓴 목적으로 가장 알맞은 것을 고르십시오.

예술인은 독창적인 문화를 창조하고 고유한 문화를 보존하는 동시에 예술 활동을 업으로 삼아 수익을 내서 생활하는 사람이다. 그런데 많은 예술인이 기본 생활이 불가능한 적은 수입 탓에 예술 활동을 포기한다. 그 결과 예술인이 감소하며 고령화되는 현상이 나타나고 있다. 2011년에는 생활고로 한 작가가 사망하는 사건까지 일어났다. 이 사건이 계기가 되어 2012년부터 예술인의 권리 보호를 위해 ''예술인 복지법''이 시행되었다. 그러나 이는 예술 현장의 실상에 맞지 않아 많은 예술인이 여전히 ( ........................ ). 이런 상황에서 올해 예술 활동을 증명하지 못해 지원을 못 받았던 예술인을 위해 예술인 복지법이 개정되었다. 개정안은 이런 예술인도 일반 직업인과 같이 권리를 보호받을 수 있는 대상임을 명확히 하고 있다. 또 예술인이 불리한 처우를 받지 않도록 세부 조치를 마련하는 등 예술인의 고용 안정을 위한 여러 내용을 담고 있다. 앞으로는 이를 바탕으로 유능한 예술인이 활동을 포기하지 않도록 해야 할 것이다.', NULL, NULL, NULL, '["예술인의 자질에 대해 분석하려고","예술 발전의 어려움을 토로하려고","예술 작품의 창작 활동을 설명하려고","예술인 생활 보장의 필요성을 강조하려고"]'::jsonb, 2, '예술인 생활 보장의 필요성을 강조하려고', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 49, '( ........................ )에 들어갈 말로 가장 알맞은 것을 고르십시오.

예술인은 독창적인 문화를 창조하고 고유한 문화를 보존하는 동시에 예술 활동을 업으로 삼아 수익을 내서 생활하는 사람이다. 그런데 많은 예술인이 기본 생활이 불가능한 적은 수입 탓에 예술 활동을 포기한다. 그 결과 예술인이 감소하며 고령화되는 현상이 나타나고 있다. 2011년에는 생활고로 한 작가가 사망하는 사건까지 일어났다. 이 사건이 계기가 되어 2012년부터 예술인의 권리 보호를 위해 ''예술인 복지법''이 시행되었다. 그러나 이는 예술 현장의 실상에 맞지 않아 많은 예술인이 여전히 ( ........................ ). 이런 상황에서 올해 예술 활동을 증명하지 못해 지원을 못 받았던 예술인을 위해 예술인 복지법이 개정되었다. 개정안은 이런 예술인도 일반 직업인과 같이 권리를 보호받을 수 있는 대상임을 명확히 하고 있다. 또 예술인이 불리한 처우를 받지 않도록 세부 조치를 마련하는 등 예술인의 고용 안정을 위한 여러 내용을 담고 있다. 앞으로는 이를 바탕으로 유능한 예술인이 활동을 포기하지 않도록 해야 할 것이다.', NULL, NULL, NULL, '["안전을 중요시해야 한다","생계의 어려움을 겪고 있다","한 번에 큰돈을 모을 수 있다","창작에 관한 기밀을 지켜야 한다"]'::jsonb, 2, '생계의 어려움을 겪고 있다', NULL),
  ((SELECT id FROM mock_test_bank WHERE exam_type = 'TOPIK_II' AND test_number = 91 ORDER BY created_at DESC LIMIT 1), 'reading', 50, '윗글의 내용과 같은 것을 고르십시오.

예술인은 독창적인 문화를 창조하고 고유한 문화를 보존하는 동시에 예술 활동을 업으로 삼아 수익을 내서 생활하는 사람이다. 그런데 많은 예술인이 기본 생활이 불가능한 적은 수입 탓에 예술 활동을 포기한다. 그 결과 예술인이 감소하며 고령화되는 현상이 나타나고 있다. 2011년에는 생활고로 한 작가가 사망하는 사건까지 일어났다. 이 사건이 계기가 되어 2012년부터 예술인의 권리 보호를 위해 ''예술인 복지법''이 시행되었다. 그러나 이는 예술 현장의 실상에 맞지 않아 많은 예술인이 여전히 ( ........................ ). 이런 상황에서 올해 예술 활동을 증명하지 못해 지원을 못 받았던 예술인을 위해 예술인 복지법이 개정되었다. 개정안은 이런 예술인도 일반 직업인과 같이 권리를 보호받을 수 있는 대상임을 명확히 하고 있다. 또 예술인이 불리한 처우를 받지 않도록 세부 조치를 마련하는 등 예술인의 고용 안정을 위한 여러 내용을 담고 있다. 앞으로는 이를 바탕으로 유능한 예술인이 활동을 포기하지 않도록 해야 할 것이다.', NULL, NULL, NULL, '["예술인 복지법은 한 번 신설된 후 개정된 적이 없다.","전국에서 예술 분야에 종사하는 사람들 수가 늘고 있다.","올해부터 예술인은 활동을 반드시 증명해야 지원을 받을 수 있다.","2012년의 예술인 복지법은 현장의 실상을 반영하는 데 한계가 있었다."]'::jsonb, 2, '2012년의 예술인 복지법은 현장의 실상을 반영하는 데 한계가 있었다.', NULL);

COMMIT;
